### ISSUE TITLE
Fix RPM dependencies for el7 distribution, by changing .spec files.

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5000]
Guidelines to accomplish this task are published on

http://wiki.nethserver.org/doku.php?id=developer:nethserver_7_kickstart

----
Original issue http://dev.nethserver.org/issues/3145

**Comment by DavidePrincipi** [comment]
Updated comps file NethServer/comps@c936f23e54

**Comment by gsanchietti** [comment]
All packages should be fixed.
