### ISSUE TITLE
install 'file-server' using gui software center.

### ISSUE THREAD

**Issue by fasttech** [NethServer/dev#5003]
Error message post install;

Task completed with errors
S10nethserver-directory-conf #15 (exit status 28416)
S11nethserver-directory-dit-setup #16 (exit status 2304)
S97nethserver-samba-sam-conf #60 (exit status 256)
Adjust service smb #53 (exit status 1)
restart service smb failed!
Adjust service smb #75 (exit status 1)
failed
S04user-create-unix #78 (exit status 256)
S20nethserver-directory-organization-modify #79 (exit status 256)
S25nethserver-directory-user-modify #82 (exit status 256)
S04user-create-unix #87 (exit status 256)
S20nethserver-directory-organization-modify #88 (exit status 256)
S25nethserver-directory-user-modify #91 (exit status 256)
S04group-create-unix #96 (exit status 256)
S20group-modify-unix #97 (exit status 256)

**Comment by DavidePrincipi** [comment]
I can't reproduce the problem with ``nethserver-samba-1.5.4-1.2.g66cac90.ns7.noarch``. Did you start from a clean installation? What are the steps to reproduce the bug?
