### ISSUE TITLE
ldap errors post 'file-server' install from gui software center.

### ISSUE THREAD

**Issue by fasttech** [NethServer/dev#5004]
Dec 22 17:48:12 localhost systemd: Starting OpenLDAP Server Daemon...
Dec 22 17:48:12 localhost esmith::event[11020]: Cannot connect LDAP server at /etc/e-smith/events/nethserver-directory-update/S10nethserver-directory-conf line 48.
Dec 22 17:48:12 localhost esmith::event[11020]: Action: /etc/e-smith/events/nethserver-directory-update/S10nethserver-directory-conf FAILED: 111 [0.204992]
Dec 22 17:48:12 localhost systemd: Started OpenLDAP Server Daemon.
Dec 22 17:48:12 localhost esmith::event[11020]: Added LDIF /etc/openldap/schema/cosine.ldif schema
Dec 22 17:48:12 localhost esmith::event[11020]: Added LDIF /etc/openldap/schema/nis.ldif schema
Dec 22 17:48:12 localhost esmith::event[11020]: Added LDIF /etc/openldap/schema/inetorgperson.ldif schema
Dec 22 17:48:12 localhost esmith::event[11020]: LDAP_UNWILLING_TO_PERFORM no global superior knowledge at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 122.
Dec 22 17:48:12 localhost esmith::event[11020]: Error modifying `dc=directory,dc=nh`: 53 LDAP_UNWILLING_TO_PERFORM at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 124.
Dec 22 17:48:12 localhost esmith::event[11020]: LDAP_UNWILLING_TO_PERFORM no global superior knowledge at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 122.
Dec 22 17:48:12 localhost esmith::event[11020]: Error modifying `ou=People,dc=directory,dc=nh`: 53 LDAP_UNWILLING_TO_PERFORM at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 124.
Dec 22 17:48:12 localhost esmith::event[11020]: LDAP_UNWILLING_TO_PERFORM no global superior knowledge at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 122.
Dec 22 17:48:12 localhost esmith::event[11020]: Error modifying `ou=Groups,dc=directory,dc=nh`: 53 LDAP_UNWILLING_TO_PERFORM at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 124.
Dec 22 17:48:12 localhost esmith::event[11020]: LDAP_UNWILLING_TO_PERFORM no global superior knowledge at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 122.
Dec 22 17:48:12 localhost esmith::event[11020]: Error modifying `uid=nsstest,ou=People,dc=directory,dc=nh`: 53 LDAP_UNWILLING_TO_PERFORM at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 124.
Dec 22 17:48:12 localhost esmith::event[11020]: LDAP_UNWILLING_TO_PERFORM no global superior knowledge at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 122.
Dec 22 17:48:12 localhost esmith::event[11020]: Error modifying `cn=nsstest,ou=Groups,dc=directory,dc=nh`: 53 LDAP_UNWILLING_TO_PERFORM at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 124.
Dec 22 17:48:12 localhost esmith::event[11020]: LDAP_UNWILLING_TO_PERFORM no global superior knowledge at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 122.
Dec 22 17:48:12 localhost esmith::event[11020]: Error modifying `uid=locals,ou=People,dc=directory,dc=nh`: 53 LDAP_UNWILLING_TO_PERFORM at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 124.
Dec 22 17:48:12 localhost esmith::event[11020]: LDAP_UNWILLING_TO_PERFORM no global superior knowledge at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 122.
Dec 22 17:48:12 localhost esmith::event[11020]: Error modifying `cn=locals,ou=Groups,dc=directory,dc=nh`: 53 LDAP_UNWILLING_TO_PERFORM at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 124.
Dec 22 17:48:12 localhost esmith::event[11020]: LDAP_UNWILLING_TO_PERFORM no global superior knowledge at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 133.
Dec 22 17:48:12 localhost esmith::event[11020]: error merging  at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 133.
Dec 22 17:48:12 localhost esmith::event[11020]: LDAP_UNWILLING_TO_PERFORM no global superior knowledge at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 134.
Dec 22 17:48:12 localhost esmith::event[11020]: error merging  at /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup line 134.
Dec 22 17:48:12 localhost esmith::event[11020]: Action: /etc/e-smith/events/nethserver-directory-update/S11nethserver-directory-dit-setup FAILED: 9 [0.185004]
Dec 22 17:48:12 localhost esmith::event[11020]: Action: /etc/e-smith/events/nethserver-directory-update/S50nethserver-directory-password-policy SUCCESS [0.055556]
Dec 22 17:48:12 localhost systemd: Reloading.

**Comment by DavidePrincipi** [comment]
I can't reproduce the problem with ``nethserver-directory-2.3.0-1.9.g7c0a11e.ns7.noarch``. Did you start from a clean installation? What are the steps to reproduce the bug?
