### ISSUE TITLE
gui log viewer unknown font or characters post 'file-server' install

### ISSUE THREAD

**Issue by fasttech** [NethServer/dev#5005]
/var/log/samba/cores/winbindd/core

s;�@��������qtP����p��otP��Yv������������X�����0������P������������5219 �X���������������X�������X�����otP���qtP��.�y�������������otP��ȁ��55@����otP��ȁ���@����0����@����P�������������	`����0������������������P����5219F����`����_����`���q55�֫��[W����������`���ණ��(����`���`��������k�������������k�����K����15219�P���� `����`׫��p�^�����P���	��������������@�����������������������������otP��胎�55@����otP��胎��@����otP��胎��`���`����^���k���������	�����p�������� �����������������������������W�����55`����`���P����H����`V�����`���`��������k�������������k�����K����15219�P���� `���1`׫��&W�����`����`���P����(����0&������y�� ����`����y�� $���������$������p��`����6sc������4:05.852 �p���f��� �p����X���f����l��� $���������$������p��`����6sc��������y���f��� �p���f����#���P����'N���0����P�����f�������f����f��� �p����X���f���������x��� 0�����Ї����ܼ��1E���f���0���� �p��@{��� �p����0����(�c��pi���̍B��@u����f����f��� �p�����31�@u����f����f�����B���f���P������B��@u��������*����@u����u����f���@u����u���Td���0r����h����s���VY����}����s���p���o��� �����h���.A����z����p��� �����U���.�h���� X��0W����H����z���pk����h���0W���0[����h��� ����� X��.�l����I����l���Њ���Њ�����p����8�������� �p��@������������@�����8�������Ϫ���l���Rb���qtq���P�����D2���O2�������yVm�s;����� ����]2��`T2���O2��k���31� �p���Ϫ����������������� ����y��X#���`����P����W��]2�������O2�� ���|�����y�����2�� $���`S���Ϫ��v����[v���pu���0���31�������Ϫ�� �p���Ϫ�������|�������������Ϫ��#����E������� �p��k���	,�2����2��`�����ê���Ϫ��k�2��0q���`������q���Pg���pu�������7�2��pu��� �p��������2��Ҫ��Ҫ�� �p������������C	�������BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBҪ���+���������������BBBBBBBB03SERVER77�
���31�� ���`������� �2��U�����Ԫ���Ԫ��pu����Ҫ�� �2��$�2��pu��� w�������������.�2������|�����p�������Pg���pu�������������7�2��pu����q����������2���q��� �p���q���������)������������+�����%��� �s������������S�����������F�̼��������������l����D����������ii����.����nn9���������I����t0����������������p���.V���蚞t0��������.V��9ca.VK�>!/a�����Ҽ��vt0���������0����������������,����c�������������������ȿ���տ���!�������d@����8	����	t0���
I����忎��Y����9���31�hLtMO�x86_64/usr/sbin/winbinddLANG=en_US.UTF-8PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/binNOTIFY_SOCKET=/run/systemd/notifyKRB5CCNAME=FILE:/run/samba/krb5cc_sambaSAMBAOPTIONS=SMBDOPTIONS=NMBDOPTIONS=WINBINDOPTIONS=/usr/sbin/winbinddELF>p�����@�@8@p�����p�������hhp�����hp�������p�����p�����<<P�tdTTp�����Tp�����,,

**Comment by DavidePrincipi** [comment]
Fun! The samba core file is dumped under ``/var/log``. This issue is not related to 7, it will be tracked here:

http://dev.nethserver.org/issues/3334
