### ISSUE TITLE
nethserver-httpd configuration errors

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5009]
Package
nethserver-httpd-2.4.0-1.3.gc38287d.ns7.noarch

Symptom
The ``nethserver-httpd-update`` event is not triggered. If it is triggered manually an Apache configuration error occurs. In ``/var/log/messages``

    Jan 15 14:37:38 vm5 httpd: httpd: Syntax error on line 28 of /etc/httpd/conf/httpd.conf: Cannot load modules/mod_authn_alias.so into server: /etc/httpd/modules/mod_authn_alias.so: cannot open shared object file: No such file or directory

Expected results 
Apache must be up and running after ``nethserver-httpd-update`` event

More informations:
http://www.nethserver.org/go7/result.html#ruleresult-idp7335504

**Comment by DavidePrincipi** [comment]
In nethserver-base/7.2.1511
nethserver-httpd-2.5.1-1.3.g43f3554.ns7.noarch.rpm

This package requires further testing, to validate the solution

**Comment by gsanchietti** [comment]
New configuration should work correctly.
