### ISSUE TITLE
nethserver-adagios v7 errors

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5015]
Installed ``nethserver-adagios-1.0.3-1.4.ga4f16be.ns7.noarch.rpm``, nagios service fails to start

First error

    qh: Failed to init socket '/var/log/nagios/rw/nagios.qh'. bind() failed: No such file or directory
    Error: Failed to initialize query handler. Aborting

The ``/var/log/nagios/rw`` directory is missing. If I create it manually and ``nagios`` ownership,

    Error: Could not load module '/usr/lib64/mk-livestatus/livestatus.o' -> /usr/lib64/mk-livestatus/livestatus.o: undefined symbol: last_command_check
    Error: Failed to load module '/usr/lib64/mk-livestatus/livestatus.o'.
    Error: Module '/usr/lib64/nagios/brokers/npcdmod.o' is using an old or unspecified version of the event broker API.  Module will be unloaded.
    Error: Failed to load module '/usr/lib64/nagios/brokers/npcdmod.o'.

Probably Nagios 4 and packages from ``ok-testing`` repo are not compatible. Upstream discussion on https://github.com/opinkerfi/adagios/issues/585

**Comment by nrauso** [comment]
It works!

**Comment by nrauso** [comment]
Good news!
There's a tutorial for the installation on v7, it works flawlessly:

https://github.com/opinkerfi/adagios/wiki/Naemon-and-Adagios-Install-Guide

**Comment by gsanchietti** [comment]
Since the linked tutorial is for naemon and not nagios, we don't know even if nethserver-adagios can work with the new configuration.
We need further investigation, so this is a full new feature.

**Comment by DavidePrincipi** [comment]
We could open a new feature in the future.
