### ISSUE TITLE
VPN L2TP/IPsec

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5018]
AFAIK, NethServer 6 L2TP VPNs implementation has a limitation: it can't work with both windows or iOS clients, i.e. two different server setups are needed and they can't live together.

I'd like to change l2TP in NethServer 7 to overcome this limitation.
Meanwhile, we can ship working IPsec tunnels simply removing one line from a configuration file.

**Comment by DavidePrincipi** [comment]
Refs NethServer/nethserver-ipsec#3

**Comment by DavidePrincipi** [comment]
http://packages.nethesis.it/nethserver/7.2.1511/base/x86_64/Packages/nethserver-ipsec-1.1.4-1.4.g74f79ba.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
RSA authentication with l2tp still have problems.

http://packages.nethserver.org/nethserver/7.2.1511/base/x86_64/Packages/nethserver-ipsec-1.1.4-1.14.g4dd8472.ns7.noarch.rpm
