### ISSUE TITLE
nethserver-config-network fails to reconfigure NIC at boot

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5019]
Symptom
After replacing a NIC, the boot process hangs

Expected behaviour
If NIC is replaced, ``nethserver-config-network``, run by the ``rc.local`` template at boot must ask to reassign the old interface name.

**Comment by gsanchietti** [comment]
Package:
http://packages.nethserver.org/nethserver/7.2.1511/base/x86_64/Packages/nethserver-base-2.9.5-1.41.g3ce9e22.ns7.noarch.rpm

* Removed hwaddr property from configuration scripts and web interface
* Network reconfiguration:
  * if a new interface changes MAC address, but not the name, no modification is done
  * if there is a non-existent green interface and only one new unassigned interface, the system will swap the configuration to new interface
* if there is a  non-existent green interface and two or more unassigned interfaces, the system will create a new _brdef_ bridge configured with the old green address and containing all the free interfaces

**Comment by gsanchietti** [comment]
Current implement prevent the creation of new interface from the web interface.

**Comment by gsanchietti** [comment]
This should be fixed in: nethserver-base-2.9.5-1.44.ged6bd96.ns7.noarch.rpm
