### ISSUE TITLE
Replace Fetchmail with getmail

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5021]
Fetchmail is software is old and doesn't work correctly with many ISP.
Substitute Fetchmail with the much more promising Getmail (http://pyropus.ca/software/getmail/).

The new package should be able to read existing Fetchmail configuration.

**Comment by gsanchietti** [comment]
Getmail uses spamc and clamdscan to check messages for SPAM and virus.

The package needs:
* a clamd instance: we can use the one configured form amavis
* a spamd instance: a new package must be built

Steps:
* move spamd implementation from nethserver-p3scan to nethserver-spamd new package
* nethserver-p3scan package must require nethserver-spamd and nethserver-mail-filter
* nethserver-getmail package must require nethserver-spamd and nethserver-mail-filter

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-spamd-0.0.1-1.ns7.noarch.rpm
* nethserver-getmail-0.0.1-1.2.g04a39e3.ns7.noarch.rpm
* nethserver-p3scan-1.1.0-1.1.gdb17cac.ns7.noarch.rpm

*Test case 1*
* On a clean machine, install nethserver-p3scan
* Check nethserver-spamd is installed and spamd is running

*Test case 2*
* On a clean machine, install nethserver-getmail
* Configure a POP3 account
* Check the mail is delivered
* Repeat the test using POP3s, IMAP and IMAPs accounts

**Comment by dz00te** [comment]
Test Case 1: NO
clean and fully updated ns7b1:
yum --enablerepo=nethserver-testing install nethserver-p3scan
```
[...]
--> Finished Dependency Resolution
Error: clamav-data-empty conflicts with clamav-data-0.99.2-1.el7.noarch
Error: clamav-data conflicts with clamav-data-empty-0.99.2-1.el7.noarch
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Test Case 1 bis: OK
clean and fully updated ns7b1 
+ from software center: openldap, MailServer, Roundcube. 1 user configured
installation ok
spamd is running


Test Case 2: OK with errors in log
yum --enablerepo=nethserver-testing install nethserver-getmail

```
Jul 31 22:11:08 ns7b1f2 yum[1761]: Installed: 1:perl-Error-0.17020-2.el7.noarch
Jul 31 22:11:46 ns7b1f2 unbound-checkconf: unbound-checkconf: no errors in /etc/unbound/unbound.conf
Jul 31 22:12:03 ns7b1f2 esmith::event[2687]: ERROR in /etc/e-smith/templates//etc/cron.d/getmail/10base: Program fragment delivered error <<Can't open getmail db at /etc/e-smith/templates//etc/cron.d/getmail/10base line 4.>> at template line 1
Jul 31 22:12:03 ns7b1f2 esmith::event[2687]: ERROR: Template processing failed for //etc/cron.d/getmail: 1 fragment generated errors
Jul 31 22:12:03 ns7b1f2 esmith::event[2687]: [WARNING] expansion of /etc/cron.d/getmail failed
Jul 31 22:12:03 ns7b1f2 esmith::event[2687]: Action: /etc/e-smith/events/actions/generic_template_expand FAILED: 1 [0.229722]
Jul 31 22:12:03 ns7b1f2 esmith::event[2687]: Action: /etc/e-smith/events/nethserver-getmail-update/S20nethserver-getmail-conf FAILED: 2 [0.046792]
Jul 31 22:12:03 ns7b1f2 esmith::event[2687]: Event: nethserver-getmail-update FAILED
```
configured 1 POP3s account with ssl, mail OK

I still have to do more tests but for now great work tnx!

**Comment by gsanchietti** [comment]
The following packages should fix all reported problems:
* nethserver-getmail-0.0.1-1.4.g235fbb9.ns7.noarch.rpm
* p3scan-2.3.2-4.ns7.x86_64.rpm
* nethserver-spamd-0.0.1-1.ns7.noarch.rpm

**Comment by dz00te** [comment]
Test Case 1: OK
clean and fully updated ns7b1:
yum --enablerepo=nethserver-testing install nethserver-p3scan

install ok, nethserver-spamd installed and spamassassin running


Test Case 2: OK with POP3s
clean and fully updated ns7b1:
yum --enablerepo=nethserver-testing install nethserver-getmail

install ok, no errors in log
installed from software center:
Account provider: OpenLDAP
Roundcube web mail
created a user

note: remote mail server is a NS6.8

getmail from POP3S: OK (spamd seems to work ), with no delete

still need some time to test it better and with POP3/IMAP/IMAPs and options

**Comment by filippocarletti** [comment]
I've successfully tested nethserver-getmail with a single account.
I've a few remarks:

1. drop privileges when running filters (user amavis it's already ok)
2. don't pass big messages to spam check (spam is always small)
3. don't add the Delivered-To: unknown header
4. add bayes_ignore as suggested in getmail faq

**Comment by filippocarletti** [comment]
nethserver-getmail compared to smtp delivery has a couple of limitations:
1. high scored spam can't be discarded
2. if spam or virus checks fail, the email is delivered unscanned

**Comment by filippocarletti** [comment]
When debugging getmail, I added a noisy option:
message_log_verbose = true
Maybe we could add a _Debug_ option to the interface to enable verbose logging.

**Comment by gsanchietti** [comment]
New package in nethserver-testing:
* nethserver-getmail-0.0.1-1.12.g2448b34.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
The updated package created a getmail configuration which mimicked all my manual modifications

**Comment by gsanchietti** [comment]
Released:
* nethserver-getmail-1.0.0-1.ns7.noarch.rpm

Also added to Software Center as "POP3 connector (nethserver-pop3connector)"

**Comment by gsanchietti** [comment]
Also released:
- nethserver-spamd-1.0.0-1.ns7.noarch
- nethserver-p3scan-1.1.1-1.ns7.noarch.rpm
