### ISSUE TITLE
Let's Encrypt support

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5023]
Let's Encrypt automatically generates and renews SSL certificates (see: https://letsencrypt.org/).

Prerequisites:
- the server must be reachable from outside at port 80
- the server must have at least one public domain name associated to its own public IP (technically a DNS record A or a CNAME)

The system should support Let's Encrypt to generate certificates for the following domains:
- server FQDN
- server alias used as web root inside shared folders (ibays)
- custom domain names

**Comment by DavidePrincipi** [comment]
* http://packages.nethserver.org/nethserver/7.2.1511/base/x86_64/Packages/nethserver-base-3.0.0-1.ns7.noarch.rpm
* http://packages.nethserver.org/nethserver/7.2.1511/base/x86_64/Packages/nethserver-letsencrypt-1.1.0-1.ns7.noarch.rpm
