### ISSUE TITLE
SOGo junkmail folder

### ISSUE THREAD

**Issue by markVnl** [NethServer/dev#5024]
In sogo v3 SOGoJunkFolderName is not mandatory.
I added this to my custom 05general_preferences template

  `  $S{SOGoJunkFolderName} = ($dovecot{SpamFolder} || "Junk");`

**Comment by gsanchietti** [comment]
It seems a reasonable default to me.

Would you like to try opening a pull request?

**Comment by markVnl** [comment]
Done;

just succeed in opening my first pull request.

**Comment by gsanchietti** [comment]
Great shot!

RPM rebuilt in nethserver-testing:
nethserver-sogo-1.5.5-1.8.g22f60f6.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released in updates: nethserver-sogo-1.5.6-1.9.g840558d.ns7.noarch.rpm

Ported also to NS 6.7: http://dev.nethserver.org/issues/3343
