### ISSUE TITLE
SOGO v3 sending mail from web-UI fails sometimes

### ISSUE THREAD

**Issue by markVnl** [NethServer/dev#5025]
I can confirm the send buton fails sometimes, symptoms:
- Sent button does fail.
- Only local receipts are accepted.

It's quirky, sometime it just works. Can't remember having this with v2.
I tied so far:
-one mail domain = server domain
-one mail domain <> server domain
-two mail domains (one = server doamin) in diferent order

in the sogo log : 
`sogod [2929]: <0x0x7ff6529e0720[SOGoCache]> an error occurred when caching value for key `

this indicates memcached can't be reached http://wiki.sogo.nu/CommonProblems
tried in sogod.plist:
```
<key>SOGoMemcachedHost</key>
<string>127.0.0.1</string>
```

Note i did a lot of testing: dav access, thunderbird integrator, ActiveSync etc. etc. so should probably set up an vanilla system to investigate, running out of time so this could take a while...

**Comment by markVnl** [comment]
Sorry, has nothing to do with SOGo, its caused by faulty DNS settings:

from mail log:
`neth transfer/smtpd[23861]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname;`

smtp port 587 requires a good DNS record 
That why it worked using a real (www) domain and not on a fake (unkown by DNS) domain.
a dns ponter to this "fake" domain or "server alias soves it.

**Comment by gsanchietti** [comment]
I guess we can close the issue.

Do you think we should add a note on this inside the manual?

**Comment by markVnl** [comment]
you can close it

A hint in the manual would be nice, "we use port 587 so check DNS settings" 

If i continue to see memcached troubles i'll raise a new isseu (it has nothing to do with this)
