### ISSUE TITLE
SOGo 3: use sogo.conf

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5028]
New upstream release (SOGo 3) moved the configuration to a standard file: `/etc/sogo/sogo.conf`.

Change current implementation by switching from GNUStep database to configuration file.

See pull request: NethServer/nethserver-sogo#4

**Comment by gsanchietti** [comment]
* Merged pull request
* Removed existing gnustep configuration
* Template fragments cleanup

**Comment by gsanchietti** [comment]
Ready for test:
http://packages.nethserver.org/nethserver/7.2.1511/testing/x86_64/Packages/nethserver-sogo-1.5.6-1.19.g3caebf8.ns7.noarch.rpm

**Comment by markVnl** [comment]
Had brief look at the nethserver-sogo testing package
(nethserver-sogo-1.5.6-1.19.g3caebf8.ns7.noarch.rpm)

sogo.conf (still) has to be expanded manually, no big deal as it is for testing;  
Or summit a quick fix by adding sogo.conf to  
/etc/e-smith/events/nethserver-sogo-update/templates2expand/etc/sogo/   ?

I’ll guess eventually you want a nethserver-sogo-setup script containing some error handling...

**Comment by gsanchietti** [comment]
Ready for test:
http://packages.nethserver.org/nethserver/7.2.1511/testing/x86_64/Packages/nethserver-sogo-1.5.6-1.19.g3caebf8.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Tested, it seems work flawlessly.

New package: nethserver-sogo-1.5.6-1.23.g9498db3.ns7.noarch.rpm
