### ISSUE TITLE
Guacamole Package [$5]

### ISSUE THREAD

**Issue by alefattorini** [NethServer/dev#5030]
Implement nethserver-guacamole RPM package, following Adam's howto
http://community.nethserver.org/t/guacamole-package/2030/27?u=alefattorini

http://guac-dev.org/
It's a very handy opensource replacement for the RDP gateway that used to come with Microsoft SBS servers before SBS was deemed to be no more: Remote Web Workplace.
##

**Comment by gsanchietti** [comment]
No one stepped in to create a new package.
Feel free to reopen this issue when an implementation is ready.
