### ISSUE TITLE
Base: hostname not changed

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5033]
When setting a new hostname from web interface, the hostname is not reflected in the underlying running system.

See @markVnl patch from #5029: 
```
[root@nethso actions]# diff interface-config-hostname-old interface-config-hostname
17c17
< /bin/hostname ${system_name:-localhost}.${domain_name:-localdomain}
---
> /bin/hostnamectl set-hostname  ${system_name:-localhost}.${domain_name:-localdomain}
```

**Comment by DavidePrincipi** [comment]
Changed nethserver-lib, nethserver-base and nethserver-ntp to read hostname and timezone values directly from the system. The configuration DB is backward compatible: SystemName and DomainName keys read their values from DBus and hostname system call directly.
