### ISSUE TITLE
Nethserver- Moodle package [$15]

### ISSUE THREAD

**Issue by robbosch** [NethServer/dev#5037]
There are quite some users in the community with an educational background. In an attempt to get some specialized applications integrated in NS, it would be great to start with moodle. Http://www.moodle.org
Moodle is a webbased elearning application wich is very feature rich, including system social media features, student score history an ofcourse serving e learning objects.
Goal is to have moodle installed with SSO support from NS user accounts.
##

**Comment by gsanchietti** [comment]
Sorry, but no one stepped in to create a new package.
Feel free to reopen this issue when an implementation is ready.

If anyone interested, you can find a great howto here: http://community.nethserver.org/t/install-moodle-on-ns7/5029

IMO, @robbosch can collect the bounty for the howto.

**Comment by robbosch** [comment]
Uhm, @areguera did a great job already on creating a moodle package.... It still is in testing I think and it needs some modification on using the NS account provider(s)...

**Comment by gsanchietti** [comment]
Sorry, I missed it, thank you for reporting here!

If a new packages comes out, we can reopen the issue.
