### ISSUE TITLE
nethserver-delegated-panel

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5038]
nethserver-delegated-panel is a software to grant access permissions to the server-manager for groups or users.

You can define precisely who is granted and for what.

http://community.nethserver.org/t/nethserver-delegated-panel/1937

what is needed to do
- allow dashboard for simple users
- templatize the json authorisation file

When it's ready and stable the package will be moved into the NethForge

**Comment by gsanchietti** [comment]
A lot of excellent work as been done and packages are available inside @stephdl repository.

Feel free to reopen the issue if you want to move the package inside the NethForge.
