### ISSUE TITLE
UrBackup package

### ISSUE THREAD

**Issue by alefattorini** [NethServer/dev#5039]
UrBackup is an easy to setup open source client/server backup system, that through a combination of image and file backups accomplishes both data safety and a fast restoration time. 

Implement nethserver-urbackup RPM package

More info here:

http://community.nethserver.org/t/nethserver-urbackup-need-testers/3272
http://community.nethserver.org/t/nethserver-as-a-backup-station/2962/11
**When it's ready and stable the package will be moved into the NethForge** @stephdl 
##

**Comment by gsanchietti** [comment]
@stephdl already implemented such feature and he prefers to keep the work on its own repository.

See https://wiki.nethserver.org/doku.php?id=urbackup
