### ISSUE TITLE
No feedback when configuring samba4 DC 

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5042]
Step to reproduce:

* install Account provider: Samba Active Directory
* go to domain controller configuration interface, set an ip address and create bridge option
* click on START DC

Now I can see on /var/log/messages that nethserver-dc-save event is in progress, but nothing happens on the interface

It used to work, it's an intermittent bug or something has been broken during development

**Comment by DavidePrincipi** [comment]
I reproduced this issue by clicking on the TODO link. If I click on the "User and groups" menu entry the problem is not reproducible.

**Comment by DavidePrincipi** [comment]
http://packages.nethserver.org/nethserver/7.2.1511/base/x86_64/Packages/nethserver-dc-1.0.0-1.ns7.x86_64.rpm
