### ISSUE TITLE
Prop "user" in proxy settings isn't saved

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5043]
in page proxy settings, user prop isn't saved. Proxy key is configured with host, port and pass, but not user because of a wrong property name

Package:
nethserver-base-3.0.0

**Comment by Stell0** [comment]
nethserver-base-3.0.0-1.2.g0c6ef0f.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
*VERIFIED*

The ``user`` prop is set correctly with the modified package.

**Comment by DavidePrincipi** [comment]
http://packages.nethesis.it/nethserver/7.2.1511/updates/x86_64/Packages/nethserver-base-3.0.1-1.ns7.noarch.rpm
