### ISSUE TITLE
Software center: warning after removing any module

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5044]
Anytime the user try to uninstall an a module from the Software Center, the web interface displays the following error:
```
Resolving RPM dependencies
The install/update may have failed due to metadata caching issues. Please clean the cache by clicking the button below and retry the install/update operation.
[CLEAR YUM CACHE]
```
*Affected package*: nethserver-base-3.0.0-

*Steps to reproduce*

* Open the Software Center page
* Install a new module
* Remove the installed module

*Expected behavior*
* The module should be removed without errors

*Actual behavior*
* The web interface always displays the above error

Reference: http://community.nethserver.org/t/ns7b1-software-center-warning-after-removing-any-module/3849

**Comment by gsanchietti** [comment]
In testing repo: nethserver-yum-1.4.0-1.1.g438025c.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-yum-1.4.1-1.ns7.noarch.rpm
