### ISSUE TITLE
Blank checkbox on "Network services" page

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5045]
The "Network services" edit page displays an empty checkbox for each unconfigured ethernet interface.

*Affected package*
nethserver-base-3.0.0-1

*Steps to reproduce*
* Configure a machine with 2 interfaces
* Leave a ethernet interface unconfigured 

*Expected behavior*
* The edit page inside "Network services" section must display green and red zones

*Actual behavior*
* The edit page inside "Network services" section displays an empty checkbox

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-base-3.0.1-1.4.g4e6d47c.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-updates:
nethserver-base-3.0.2-1.ns7.noarch.rpm
