### ISSUE TITLE
nethserver-phonehome proxy configuration

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5046]
nethserver-phonehome 1.2.0 uses its own proxy configuration file instead of global proxy configuration.

Change the nethserver-phonehome configuration to read the proxy configuration from the global proxy settings, as other services like yum.

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-phonehome-1.2.0-1.3.g8f62348.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Reverted commit d09ba77effc4989ae1a0ba6826bd601166bcf492: the script already protects special chars for user name and password.

In nethserver testing:
nethserver-phonehome-1.2.0-1.4.g01b1fed.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-updates:
nethserver-phonehome-1.2.1-1.ns7.noarch.rpm
