### ISSUE TITLE
nethserver-dc backup fails if launched by cron or from interface

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5047]
nethserver-dc-1.0.0: when backup is launched from interface or by cron, it fails. It's a race condition and after first backup fails, seem that others don't.
step to reproduce: launch configuration backup from interface or wait for cron to launch it and check in /var/log/messages that it fails

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.0.0-1.2.g831604e.ns7.x86_64.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-dc-1.0.1-1.ns7.x86_64.rpm
