### ISSUE TITLE
collectd - monitor only locally connected ups

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5049]
Port the commits from NS6.

See: http://dev.nethserver.org/issues/3413

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-nut-1.2.1-1.2.ge5a4e50.ns7.noarch.rpm

_Test case 1_
Install the updated package but not collectd-nut
Enable the UPS
Check the collectd plugin is not enabled

_Test case 2_
Install the updated package and collectd-nut
Enable the UPS
Check the collectd plugin is enabled

_Test case 3_
Install the updated package and collectd-nut
Disable the UPS (or put it on slave mode)
Check the collectd plugin is not enabled

**Comment by Stell0** [comment]
In nethserver-updates:
nethserver-nut-1.2.1-1.ns7.noarch.rpm
