### ISSUE TITLE
First install of roundcube gives template error

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5053]
The error:
`Jul 14 17:21:11 ns7b1 esmith::event[9125]: expanding /etc/roundcubemail/config.inc.php
Jul 14 17:21:11 ns7b1 esmith::event[9125]: ERROR in /etc/e-smith/templates//etc/roundcubemail/config.inc.php/50ADDRESSBOOK_SETTINGS: Program fragment delivered error <<Can't call method "host" without a package or object reference at /usr/share/perl5/vendor_perl/NethServer/SSSD.pm line 150.>> at template line 31`

I was a fresh beta1 where I was installing both nethserver-dc and roundcube in the same software center transaction.

**Comment by gsanchietti** [comment]
The template didn't correctly handle the expansion in case of sssd wasn't configured.
But please remind that roundecubemail must be reconfigured after the installation of any user provider: `signal-event nethserver-roundecubemail-update`.

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-roundcubemail-1.2.0-1.1.ga995f2c.ns7.noarch.rpm

*Test case*
* Update nethserver-sssd: see #5051 
* Install nethserver-roundecubemail

**Comment by filippocarletti** [comment]
After I updated nethserver-sssd I installed roundcube via software center: no errors displayed and the reload green button appeared.
No errors in messages.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-roundcubemail-1.2.1-1.ns7.noarch.rpm
