### ISSUE TITLE
Apache config error with smbaudit

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5054]
After installing ``nethserver-smbaudit`` I found some log lines like the following:

```
Jul 14 18:29:16 ns7b1 httpd: [Thu Jul 14 18:29:16.841477 2016] [alias:warn] [pid 15379] AH00671: The Alias directive in /etc/httpd/conf.d/welcome.conf at line 29 will probably never match because it overlaps an earlier Alias.
```

Workaround: remove ``/etc/httpd/conf.d/smbaudit.conf`` 

See [smbaudit.conf template](https://github.com/NethServer/nethserver-samba-audit/blob/e08151794c57c63aa57d7d452d247a6ffd29418e/root/etc/e-smith/templates/etc/httpd/conf.d/smbaudit.conf/10base#L2)

**Comment by gsanchietti** [comment]
The bug should be related to #5057
