### ISSUE TITLE
Dashboard: display Gateway field inside Interfaces tab

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5056]
The Dashboard doesn't correctly display the gateway.
Try to move the gateway field inside the the Interfaces tabs, if not possible, remove the gateway and eventually display all static routes.

Reference: http://community.nethserver.org/t/dashboard-not-populating-the-gateway/3872

**Comment by gsanchietti** [comment]
Modifications:
* removed gateway from Network tile
* if set, the gateway is displayed inside the interfaces tab

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-base-3.0.2-1.4.gda6c12f.ns7.noarch.rpm

*Test case 1*
* Configure a system with only one green interface
* Check the gateway is correctly displayed under the Interfaces tab

*Test case 2*
* Configure a system with a green and a red interface in DHCP
* Check the gateway is correctly displayed under the Interfaces tab for the green interface (even if the gateway is not used)
* Check the gateway is NOT displayed under the Interfaces tab for the red interface

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-base-3.0.3-1.ns7.noarch.rpm
