### ISSUE TITLE
Undefined subroutine &esmith::util::genRandomHash

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5057]
Many modules uses the library function _genRandomHash_ which has been removed during a code cleanup.

Re-add the missing function.

Affected packages:
* nethserver-ligthsquid
* nethserver-cgp

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-lib-2.2.0-1.1.g9ab3030.ns7.noarch.rpm

*Test case 1*
* Install nethserver-cgp
* Access nethserver-cgp from the web interface: "Graphs"

*Test case 2*
* Install nethserver-lightsquid
* Access nethserver-ligthsquid from the web interface: "Web proxy stats"

*Test case 3*
* On a machine with nethserver-cgp or nethserver-lightsquid already installed, update nethserver-lib
* Execute:
```
signal-event nethserver-cgp-update
signal-event nethserver-ligthsquid-update
```

**Comment by filippocarletti** [comment]
Test 3:
1. lightsquid - I see this error whatever language I select:
Nethgui:
    404 - Language not found
    1377519247

2. cgp - I see:
Not Found
The requested URL /1e441e51b86bb8f805e136fc346b5545b4ea62c8/host.php was not found on this server.

**Comment by filippocarletti** [comment]
Oops, restarting httpd-admin both errors went away.
In messages I read:
Jul 18 14:18:50 ns7b1 systemd: Started Delayed graceful restart of httpd-admin.

Test case 1 and 2: ok

**Comment by Stell0** [comment]
In nethserver-updates: nethserver-lib-2.2.1-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
The package was missing , just uploaded.
