### ISSUE TITLE
sope49-gdl1-mysql: wrong GPG key

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5058]
SOGo installation from the NethForge raises this bug:

> Transaction Summary
> Install 1 Package
> 
> Total download size: 36 k
> Installed size: 138 k
> Is this ok [y/d/N]: y
> Downloading packages:
> warning: /var/cache/yum/x86_64/7/nethforge/packages/sope49-gdl1-mysql-4.9-20160305_1664.el7.1.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 2bdaabff: NOKEY
> Public key for sope49-gdl1-mysql-4.9-20160305_1664.el7.1.x86_64.rpm is not installed
> sope49-gdl1-mysql-4.9-20160305_1664.el7.1.x86_64.rpm http://community.nethserver.org/t/try-out-nethserver-7-beta1/3901/10 | 36 kB 00:00:00
> 
>
>Public key for sope49-gdl1-mysql-4.9-20160305_1664.el7.1.x86_64.rpm is not installed

Workaround:
```yum --nogpgcheck install nethserver-sogo```

Reference: http://community.nethserver.org/t/try-out-nethserver-7-beta1/3901/11?u=giacomo

**Comment by gsanchietti** [comment]
All sogo packages have been resigned.

*Test case*
* In NethForge.repo disable _mirrorlist_ and use this as _baseurl_ "http://packages.nethserver.org/nethserver/$releasever/nethforge/$basearch/"
* Install the package:
```
yum clean all
yum install nethserver-sogo
```

When all the mirrors will be in synch (tomorrow), modifications to NethForge.repo will not be necessary anymore.

**Comment by dz00te** [comment]
*System and  Package Version installed*
VM KVM - Clean install of Nethserver 7b1 fully updated
Package Installed: MailServer, OpenLDAP

*Install Updated Package*
installed from Software Center without modifying NethForge.repo

*Test Results after update*
Installed and running without problems

**Comment by gsanchietti** [comment]
Everything is already released.
