### ISSUE TITLE
Self-signed certificate doesn't save changes

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5059]
Self-signed certificate: does not save changes for Country code, CommonName, State, Locality (takes it from Organization Contacts) and Email address fields (as reported by @netbix and @GG_jr)

Also edit Server certificate's inline help shows an error:

> Docutils System Messages
> System Message: ERROR/3 (/dev/stdin, line 46); backlink
> Undefined substitution referenced: "product".

http://community.nethserver.org/t/try-out-nethserver-7-beta1/3901/33

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-base-3.0.2-1.5.g76d45bc.ns7.noarch.rpm

*Test case 1*
* Try to edit the self-signed certificate
* Wait a little bit and reload the page: the browser should force you to accept the new certificate
* Check certificate details using browser tools

*Test case 2*
* Open the inline help inside the "Server certificate" page
* Check there is no error at the bottom of the help page

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-base-3.0.3-1.ns7.noarch.rpm
