### ISSUE TITLE
Move "DNS servers"  inline documentation  to Network page.

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5060]
The "DNS servers" page has been moved inside the Network page but the inline help has not have been moved.

Reference:
*  http://community.nethserver.org/t/try-out-nethserver-7-beta1/3901/33
* http://community.nethserver.org/t/try-out-nethserver-7-beta1/3901/32

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-hosts-1.2.0-1.1.g25ae6e4.ns7.noarch.rpm
* nethserver-base-3.0.2-1.1.g923456f.ns7.noarch.rpm

*Test case*
* The 'DNS servers' section should not be present inside the inline help of DNS page
* The 'DNS servers' section should be present inside the inline help of Network page

**Comment by Stell0** [comment]
In nethserver-updates:
· nethserver-hosts-1.2.1-1.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-base-3.0.3-1.ns7.noarch.rpm
