### ISSUE TITLE
Web UI: missing labels

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5061]
Following untraslated labels are used on hover on menu titles:

- Applications_Description
- Services_Description
- Dhcp_Descrition
- RestoreData_Description
- Ntopng_Description
- MailQuota_Description
- Ejabber_Description

Reference: http://community.nethserver.org/t/try-out-nethserver-7-beta1/3901/41

**Comment by gsanchietti** [comment]
All listed string have been fixed.
Packages will be rebuilt later.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.1-1.ns7.noarch.rpm
