### ISSUE TITLE
ntopng service unable to start

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5063]
When starting ntpng this is the error:

> Starting ntopng: /usr/bin/ntopng: error while loading shared libraries: libzmq.so.4: cannot open shared object file: No such file or directory

Workaround:
`ln -s /usr/lib64/libzmq.so.5 /usr/lib64/libzmq.so.4`

Upstream  ntop/ntopng#issues/450

If possible, update to latest release: 2.4.0

Reference: http://community.nethserver.org/t/try-out-nethserver-7-beta1/3901/5?u=giacomo

It is an upstream_bug.
P.S. ntopng shows there is a new version:

**Comment by gsanchietti** [comment]
The bug seems fixed with latest ntopng release.

In nethserver-testing:
* ntopng-2.5.160718-1335.x86_64.rpm
* pfring-6.5.0-730.x86_64.rpm
* pfring-dkms-6.5.0-730.noarch.rpm

*Test case*
* Install the release from testing repository
* Enable ntopng from the server manager
* Check ntopng is running

**Comment by dz00te** [comment]
*System and  Package Version installed*
VM KVM - Clean install of NethServer 7b1 fully updated

*Install Updated Package*
`yum --enablerepo=nethserver-testing install ntopng-data-2.4.160712-1303.noarch ntopng-2.4.160712-1303.x86_64 pfring-6.4.1-718.x86_64 pfring-dkms-6.4.1-718.noarch nethserver-ntopng.noarch `

*Test Results after update*
Installed, enabled and running without problems

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-ntopng-1.4.1-1.ns7.noarch.rpm
ntopng-2.4.160712-1303.x86_64.rpm
ntopng-data-2.4.160712-1303.noarch.rpm
pfring-6.4.1-718.x86_64.rpm
pfring-dkms-6.4.1-718.noarch.rpm
