### ISSUE TITLE
Asterisk 13

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5065]
Asterisk 13 (LTS) should install into the system with all needed dependencies.
Check the daemon correctly starts and stops using systemd commands.

RPMs available from FreePBX distro:
- pjproject-2.4.5-1.9.sng.x86_64.rpm
- libresample-0.1.3-17.2.sng.x86_64.rpm
- asterisk13-voicemail-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-alsa-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-odbc-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-core-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-sqlite3-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-snmp-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-ogg-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-speex-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-addons-ooh323-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-pgsql-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-addons-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-addons-mysql-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-curl-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-devel-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-flite-2.2.1.3-3_3118e6a.sng7.x86_64.rpm
- asterisk13-voicemail-odbcstorage-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-doc-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-resample-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-dahdi-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-voicemail-imapstorage-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-tds-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-configs-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-addons-bluetooth-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-addons-core-13.9.1-1.17.sng.x86_64.rpm

Sangoma repository:

```
# This is the standard Sangoma Yum Repository

[sng-base]
name=Sangoma-$releasever - Base
mirrorlist=http://mirrorlist.pbx.ws/?release=$releasever&arch=$basearch&repo=os&dist=$dist
#baseurl=http:/package1.sangoma.net/sng7/$releasever/os/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Sangoma-7

[sng-updates]
name=Sangoma-$releasever - Updates
mirrorlist=http://mirrorlist.pbx.ws/?release=$releasever&arch=$basearch&repo=updates&dist=$dist
#baseurl=http://package1.sangoma.net/sng7/$releasever/updates/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Sangoma-7

[sng-extras]
name=Sangoma-$releasever - Extras
mirrorlist=http://mirrorlist.pbx.ws/?release=$releasever&arch=$basearch&repo=extras&dist=$dist
#baseurl=http://package1.sangoma.net/sng7/$releasever/extras/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Sangoma-7

[sng-pkgs]
name=Sangoma-$releasever - Sangoma Open Source Packages
mirrorlist=http://mirrorlist.pbx.ws/?release=$releasever&arch=$basearch&repo=sng7&dist=$dist
#baseurl=http://package1.sangoma.net/sng7/$releasever/sng7/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Sangoma-7

[sng-epel]
name=Sangoma-$releasever - Sangoma Epel mirror
mirrorlist=http://mirrorlist.pbx.ws/?release=$releasever&arch=$basearch&repo=epel&dist=$dist
#baseurl=http://package1.sangoma.net/sng7/$releasever/epel/$basearch/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
```
##

**Comment by gsanchietti** [comment]
Packages have already been pushed to testing repository.

**Comment by dz00te** [comment]
wow!
missing package
--> Finished Dependency Resolution
Error: Package: asterisk13-13.9.1-1.17.sng.x86_64 (nethserver-testing)
           Requires: asterisk-sounds-core-en-ulaw

**Comment by gsanchietti** [comment]
Added also 
- asterisk-sounds-core-en-ulaw

**Comment by alepolidori** [comment]
The installation requires "asterisk" user and group

```
...
warning: user asterisk does not exist - using root
warning: group asterisk does not exist - using root
...
```

**Comment by dz00te** [comment]
for now, installed using:
```adduser asterisk -M -c "Asterisk User```
```yum --nogpgcheck --enablerepo=nethserver-testing install asterisk13```
because:
```Package asterisk13-voicemail-13.9.1-1.17.sng.x86_64.rpm is not signed```

**Comment by alepolidori** [comment]
Now it should install also without "--nogpgcheck".
Could you confirm it ?

**Comment by dz00te** [comment]
yes it works tnx

**Comment by xrobau** [comment]
The asterisk13-core RPM creates the asterisk user if it doesn't exist:

```
%pre core
useradd -r -M -s /bin/bash -d /home/asterisk asterisk 2> /dev/null || :
```

The -sounds rpms *assume* (but don't insist) that asterisk is installed before them, which is why you're seeing that warning. When we install the RPMs, we manually install the sound files after the asterisk files, to avoid that.

**Comment by Stell0** [comment]
Thanks @xrobau 
We are using RPMs for CentOS 7, and Asterisk RPMs seems good (we are going to give a better feedback in the future, as soon as we'll start to have an usable environment)
We are also working on FreePBX (14) to have it on NethServer, but we'd like to have a different approach on it's RPM, as wrote here http://community.freepbx.org/t/freepbx-rpm-and-installation-script/36031.
Now I'm working on it and I'll have an example soon to show you.

**Comment by alepolidori** [comment]
It can be tested installing nethserver-freepbx package as explained [here.](http://community.nethserver.org/t/asterisk-13-and-freepbx-14-on-nethserver-7/4003/9?u=edoardo_spadoni)

**Comment by Stell0** [comment]
Missing features to add before testing: 

- [ ] Server manager web interface for ports

· Add a server manager interface for managing PBX ports 

- [ ] DAHDI kernel modules

· make sure that dahdi modules are installed and loaded
· Verify that kernel updates are correctly managed

- [ ] Asterisk modules

· check if there is any missing and useful asterisk module in Sangoma build 

- [ ] G729 

· check if there is any open g729 rpm and if is allowed to use it by license 

- [ ] Open pjsip port as done for chan_sip

**Comment by alepolidori** [comment]
DAHDI kernel modules are not automatically loaded.
Kernel update is not managed. Updating it, dahdi modules are not re-compiled.
Putting dahdi modules into "/usr/lib/modules/`uname -r`/extra/" fix the re-compilation.

**Comment by gsanchietti** [comment]
Listed asterisk modules are available installing following packages:
* asterisk13-addons-mysql
* asterisk13-speex
* asterisk13-resample
* asterisk13-voicemail-odbcstorage

**Comment by gsanchietti** [comment]
There is no available rpm for g729, still you can find pre-compiled binaries at http://asterisk.hosting.lv/. Choose between binaries for Asterisk 13, but this should work almost on every x86_64 machine:
http://asterisk.hosting.lv/bin/codec_g729-ast130-gcc4-glibc-x86_64-pentium4.so

Install steps:
```
cd /usr/lib64/asterisk/modules/
http://asterisk.hosting.lv/bin/codec_g729-ast130-gcc4-glibc-x86_64-pentium4.so
systemctl restart asterisk
```

Check the module is loaded:
```
 asterisk -rx "core show codecs" | grep g729
```

**Comment by xrobau** [comment]
If you guys start distributing g729, you're potentially exposing yourself to legal liability. 

Extremely not recommended, go speak to a lawyer before you do that.

Opinion: Also, this isn't 2004. People should be using g722, not g729.  Stop empowering people to have bad audio quality.

**Comment by gsanchietti** [comment]
@xrobau  we don't have any plans to distribute the g729 codec, as you can see there is no spec RPM on our github repositories.

But since many users still use the codec, I did some tests and added a note which will be part of the official manual. We can't distribute the codec, but probably we can also build a little script to easy the life of our users.

**Comment by Stell0** [comment]
Test case: install nethserver-freepbx and
- Verify that you can open IAX, WebRTC and WebSocket external ports from NethServer GUI -> PBX access
- check that pjsip port (5160) is open as chan_sip

**Comment by gsanchietti** [comment]
In nethserver-testing:
- wanpipe-7.0.20-3.10.0.327.36.1.el7.dahdi.2.11.1.16.sng7.x86_64.rpm
- kmod-dahdi-linux-2.11.1-3.10.0_327.36.1.el7.24.sng7.x86_64.rpm-
- dahdi-firmware-te820-1.76-1.3.sng.noarch.rpm
- dahdi-firmware-te436-10017-1.3.sng.noarch.rpm
- dahdi-firmware-vpmoct032-1.12.0-1.3.sng.noarch.rpm
- dahdi-firmware-te435-e0019-1.3.sng.noarch.rpm
- dahdi-firmware-te134-780017-1.3.sng.noarch.rpm
- dahdi-firmware-te133-780019-1.3.sng.noarch.rpm
- dahdi-firmware-tc400m-MR6.12-1.3.sng.noarch.rpm
- dahdi-firmware-oct6126-128-01.07.04-1.3.sng.noarch.rpm
- dahdi-firmware-oct6114-256-1.05.01-1.3.sng.noarch.rpm
- dahdi-firmware-oct6114-128-1.05.01-1.3.sng.noarch.rpm
- dahdi-firmware-oct6114-064-1.05.01-1.3.sng.noarch.rpm
- dahdi-firmware-oct6114-032-1.07.01-1.3.sng.noarch.rpm
- dahdi-firmware-hx8-2.06-1.3.sng.noarch.rpm
- dahdi-firmware-a8b-1f001e-1.3.sng.noarch.rpm
- dahdi-firmware-a8a-1d0017-1.3.sng.noarch.rpm
- dahdi-firmware-a4b-d001e-1.3.sng.noarch.rpm
- dahdi-firmware-a4a-a0017-1.3.sng.noarch.rpm
- dahdi-firmware-2.9.3-1.3.sng.noarch.rpm
- libwat-2.1.0-1.2.sng.x86_64.rpm
- libtonezone-2.11.1-1.17.sng.x86_64.rpm
- libss7-2.0.0-1.2.sng.x86_64.rpm
- libpri-1.4.15-13.7.sng.x86_64.rpm
- libopenr2-1.3.4-1.6.sng.x86_64.rpm
- dahdi-tools-2.11.1-1.17.sng.x86_64.rpm
- dahdi-linux-2.11.1-1.17.sng.x86_64.rpm
- asterisk13-voicemail-odbcstorage-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-voicemail-imapstorage-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-voicemail-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-tds-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-sqlite3-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-speex-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-snmp-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-resample-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-ogg-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-pgsql-13.9.1-1.17.sng.x86_64.rpm
- asterisk-sounds-core-en-ulaw-1.5-1.8.noarch.rpm
- asterisk13-odbc-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-flite-2.2.1.3-3_3118e6a.sng7.x86_64.rpm
- asterisk13-doc-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-devel-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-dahdi-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-curl-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-core-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-configs-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-alsa-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-addons-ooh323-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-addons-mysql-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-addons-core-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-addons-bluetooth-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-addons-13.9.1-1.17.sng.x86_64.rpm
- asterisk13-13.9.1-1.17.sng.x86_64.rpm
- pjproject-2.4.5-1.9.sng.x86_64.rpm
- libresample-0.1.3-17.2.sng.x86_64.rpm

**Comment by gsanchietti** [comment]
All upstream RPMs are good, release the packages when #5074 is done:
https://github.com/NethServer/nethserver-freepbx/blob/master/README.rst
