### ISSUE TITLE
VPS: can't access public services 

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5068]
*Steps to reproduce*

* Install on a VPS with a public IP
* All services with public access are not accessible

*Expected behaviour*

Server manager and ssh must be accessible from remote hosts.

Output of ``iptables -nvL net2fw``

```
Chain net2fw (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  103 12822 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8 /* Ping */
    7   377 Drop       all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    7   377 LOG        all  --  *      *       0.0.0.0/0            0.0.0.0/0            LOG flags 0 level 6 prefix "Shorewall:net2fw:DROP:"
    7   377 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0    
```

Extract from firewall.log:
```
Jul 19 15:40:47 srv1 kernel: Shorewall:net2fw:DROP:IN=ens3 OUT= MAC=00:16:3e:1a:10:19:a0:36:9f:30:bd:e4:08:00 SRC=93.57.48.68 DST=185.116.239.201 LEN=60 TOS=0
x00 PREC=0x00 TTL=52 ID=27337 DF PROTO=TCP SPT=50814 DPT=22 WINDOW=29200 RES=0x00 SYN URGP=0 
```

Packages:
nethserver-firewall-base-3.0.0-1.ns7.noarch

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-firewall-base-3.0.0-1.2.gbb485c8.ns7.noarch.rpm
* nethserver-firewall-base-ui-3.0.0-1.2.gbb485c8.ns7.noarch.rpm

*Test case*
* Check the bug is not reproducible
* Make sure net2fw chain contains rules for sshd and httpd-admin

**Comment by DavidePrincipi** [comment]
*VERIFIED*

After upgrading to the modified version the net2fw chain lists the required services.

**Comment by Stell0** [comment]
In nethserver-updates:
nethserver-firewall-base-3.0.1-1.ns7.noarch.rpm
nethserver-firewall-base-ui-3.0.1-1.ns7.noarch.rpm
