### ISSUE TITLE
Host domain initialization failure

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5069]
At some point during the network startup, ``dhclient`` seems to change the hostname to "localhost." (no domain part). This is a problem for "system-init" that fails to detect the "DomainName" key value properly.

Symptom:
* after unattended install dnsmasq is dead
* any name resolution fails

Steps to reproduce:
* single NIC machine, DHCP server on LAN
* nethserver-7 beta1 ISO,
* unattended installation
* first boot

Additional info:
The First configuration wizard procedure sets the hostname and domain again and restart dnsmasq. The problem is solved.

journalctl:
<pre>
Jul 20 15:53:25 localhost.localdomain network[641]: Bringing up loopback interface:  [  OK  ]
Jul 20 15:53:25 localhost.localdomain network[641]: Bringing up interface eth0:
Jul 20 15:53:25 localhost.localdomain dhclient[812]: DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 8 (xid=0x4af9ce20)
Jul 20 15:53:25 localhost.localdomain dhclient[812]: DHCPREQUEST on eth0 to 255.255.255.255 port 67 (xid=0x4af9ce20)
Jul 20 15:53:25 localhost.localdomain dhclient[812]: DHCPOFFER from 192.168.5.253
Jul 20 15:53:25 localhost.localdomain dhclient[812]: DHCPACK from 192.168.5.253 (xid=0x4af9ce20)
Jul 20 15:53:27 localhost.localdomain NET[861]: /usr/sbin/dhclient-script : updated /etc/resolv.conf
Jul 20 15:53:27 localhost dhclient[812]: bound to 192.168.5.41 -- renewal in 32591 seconds.
Jul 20 15:53:27 localhost network[641]: Determining IP information for eth0... done.
Jul 20 15:53:27 localhost NET[920]: /etc/sysconfig/network-scripts/ifup-post : updated /etc/resolv.conf
Jul 20 15:53:27 localhost network[641]: [  OK  ]
Jul 20 15:53:27 localhost systemd[1]: Started LSB: Bring up/down networking.
Jul 20 15:53:27 localhost systemd[1]: Reached target Network.
Jul 20 15:53:27 localhost systemd[1]: Starting Network.
Jul 20 15:53:27 localhost systemd[1]: Started OpenSSH server daemon.
Jul 20 15:53:27 localhost systemd[1]: Starting OpenSSH server daemon...
Jul 20 15:53:27 localhost systemd[1]: Starting Dynamic System Tuning Daemon...
Jul 20 15:53:27 localhost systemd[1]: Starting Postfix Mail Transport Agent...
Jul 20 15:53:27 localhost systemd[1]: Reached target Network is Online.
Jul 20 15:53:27 localhost systemd[1]: Starting Network is Online.
Jul 20 15:53:27 localhost systemd[1]: Starting Initialize NethServer configuration...
Jul 20 15:53:27 localhost sshd[944]: Server listening on 0.0.0.0 port 22.
Jul 20 15:53:27 localhost sshd[944]: Server listening on :: port 22.
Jul 20 15:53:28 localhost esmith::event[947]: Event: system-init
</pre>

See also:
http://community.nethserver.org/t/dnsmasq-dead-after-ns7-unattended-installation/3951

**Comment by gsanchietti** [comment]
We can workaround the dnsmasq problem by properly initializing the DomainName inside `dnsmasq.conf` template.

**Comment by gsanchietti** [comment]
In nethserver-testing
* nethserver-dnsmasq-1.6.0-1.2.g4154f9c.ns7.noarch.rpm

*Test case*
* On a clean machine with DHCP on green, install nethserver-dnsmasq from testing repository
* Dnsmasq must be running

**Comment by gsanchietti** [comment]
Released:
* nethserver-dnsmasq-1.6.1-1.ns7.noarch.rpm
