### ISSUE TITLE
Blank checkbox on FirewallRules/EditService page

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5070]
This is the same issue of NethServer/dev#5045, but applied to ``Firewall rules > Edit service`` page.

Probably a similar fix could be applied, too!

**Comment by gsanchietti** [comment]
Applied the same fix from the referenced bug.

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-firewall-base-3.0.1-1.1.g09b12ab.ns7.noarch.rpm
* nethserver-firewall-base-ui-3.0.1-1.1.g09b12ab.ns7.noarch.rpm

*Test case*
* Check the bug is not reproducible

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
* nethserver-firewall-base-3.0.2-1.ns7.noarch.rpm
* nethserver-firewall-base-ui-3.0.2-1.ns7.noarch.rpm
