### ISSUE TITLE
sssd-save event: reconfigure all packages

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5071]
All packages accessing the user database must be reconfigured when SSSD configuration changes.

_Example_
* Installation of nethserver-ejabberd
* Installation of nethserver-dc
* Ejabberd must be reconfigured to access nethserver-directory

The SSSD save event should call `system-adjust` action at the end.

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-sssd-1.0.1-1.1.g408fc79.ns7.noarch.rpm

*Test case*
* Install nethserver-sssd from testing repository
* Install nethserver-ejabberd
* Install nethserver-dc and create a user
* Check the user can login into ejabberd

**Comment by alepolidori** [comment]
Ok it works.

RPMs used:

```
nethserver-sssd-1.0.1-1.2.g29bdc92.ns7.noarch (testing)
nethserver-ejabberd-1.1.1-1.ns7.noarch (updates)
nethserver-dc-1.0.2-1.ns7.x86_64 (updates)
```

I've created 2 users and both can login to ejabberd and communicate.

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
* nethserver-sssd-1.0.2-1.ns7.noarch.rpm
