### ISSUE TITLE
nethserver-directory: execute nethserver-sssd-save event

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5072]
The nethserver-directory installation modifies the existing SSSD configuration, thus it should execute the `nethserver-sssd-save` at the end of `nethserver-directory-update` event.

Since he `nethserver-sssd-save` event executes all update events of installed package, it should be executed only after the first installation of nethserver-directory package to avoid loops.
See: #5071

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-directory-3.0.0-1.1.gee9e432.ns7.noarch.rpm

*Test case*
* Install nethserver-sssd from testing repository
* Install nethserver-ejabberd
* Install nethserver-directory and create a user
* Check the user can login into ejabberd

**Comment by gsanchietti** [comment]
New package in nethserver-testing:
* nethserver-directory-3.0.0-1.3.ga1c7b1b.ns7.noarch.rpm

Thanks to @alepolidori  for finding out this silly commit!

**Comment by alepolidori** [comment]
Ok: it works.

RPMs installed:

```
nethserver-sssd-1.0.1-1.2.g29bdc92.ns7.noarch
nethserver-ejabberd-1.1.1-1.ns7.noarch
nethserver-directory-3.0.0-1.3.ga1c7b1b.ns7.noarch
```

I've created 2 user and they can login into ejabberd and can communicate

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
* nethserver-directory-3.0.1-1.ns7.noarch.rpm
