### ISSUE TITLE
FreePBX 14

### ISSUE THREAD

**Issue by pinkra** [NethServer/dev#5074]
FreePBX 14 is a web interface that controls and manages Asterisk (https://www.freepbx.org).

Implement nethserver-freepbx rpm and freepbx rpm (starting from the one Sangoma has built for its distribution on https://www.freepbx.org/downloads/freepbx-distro/).

More info here:
- https://www.freepbx.org
- http://community.nethserver.org/t/asterisk-13-and-freepbx-14-on-nethserver-7
##

**Comment by edospadoni** [comment]
Some news on community: http://community.nethserver.org/t/asterisk-13-and-freepbx-14-on-nethserver-7/4003/9?u=edoardo_spadoni

**Comment by Stell0** [comment]
Missing features to add before testing: 

- [ ] backup 

· add to backup audio files and recording
· make sure that everything needed by freepbx is in backup.
· check what is saved by backup freepbx module

- [ ] User integration

FreePBX user module can get users from it's DB or from AD
· Write documentation for using AD as user source
· ask freepbx community if there is any will to add generic ldap, and maybe develop it and push to fpbx

- [ ] Test webrtc 

- [ ] Module repository

· Check how to create a module repository and configure it on freepbx

- [ ] Test rpm update 

· test rpm update when additional modules are installed
· test rpm update when core and framework installed are newer than those in rpm

**Comment by Stell0** [comment]
Test case: install nethserver-freepbx and
- Test backup / restore
- test user integration from ldap and AD

 - [Official FreePBX AD integration link](http://wiki.freepbx.org/display/FPG/How+to+Authenticate+User+Manager+via+Microsoft+Active+Directory)

- test WebRTC
 [Setting up WebRTC on FreePBX](http://wiki.freepbx.org/display/FPG/WebRTC+Phone-UCP#WebRTCPhone-UCP-EnablingWebRTCPhoneforauser)

 After the installation of Certificate Manager and WebRTC modules there is a valid self-signed certificate that can be use for WebRTC.
 Known bugs:
  - WebRTC under Chrome is not allowed in HTTP
  - WebRTC in UCP module on FreepBX not works as expected. [Ref](http://community.freepbx.org/t/webrtc-phone-with-https/26698/9)

- test redirect from http to https 

- create two extensios and make sure they can call each other

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-freepbx-0.0.1-1.58.gd4b7a54.ns7.noarch.rpm
- freepbx-14.0-2.11.g296debe.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Split FPM configuration into a new rpm.

In nethserver-testing:
- nethserver-rh-php56-php-fpm-0.0.1-1.2.g73acebd.ns7.noarch.rpm
- nethserver-freepbx-0.0.1-1.82.g5b12ec9.ns7.noarch.rpm
- freepbx-14.0-2.15.gf380335.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-freepbx-0.0.1-1.85.g5e19dcc.ns7.noarch.rpm

**Comment by Stell0** [comment]
Test case:
* Opern RTP ports if SIPS or WebRTC are enabled from interface (add it only once on shorewall config)
  * open all PBX ports from NethServer interface -> PBX Access -> External Access
  * verifywith  iptables -nL that ports 10000:20000, 4569, 5036, 8089, 5061,5038 are open and that they are listed only once per network 

* Access list to FreePBX interface from NethServer web UI
  * verify that access from red interfaces are forbidden
  * verify that is possible to allow access from a network using NethServer interface -> PBX Access -> Web interface access
_note:_ there is a known NethGUI glitch in table visualization, first row isn't displayed correctly

Add asterisk manager port 5038 to Asterisk ports

**Comment by gsanchietti** [comment]
Released **92** packages in nethserver-updates:

- libsrtp15-devel-1.5.4-3.ns7.x86_64.rpm
- libsrtp15-1.5.4-3.ns7.x86_64.rpm
- libsrtp15-debuginfo-1.5.4-3.ns7.x86_64.rpm
- libresample-0.1.3-20.ns7.x86_64.rpm
- libresample-debuginfo-0.1.3-20.ns7.x86_64.rpm
- libresample-devel-0.1.3-20.ns7.x86_64.rpm
- libpri-devel-1.4.15-13.ns7.x86_64.rpm
- libpri-1.4.15-13.ns7.x86_64.rpm
- libpri-debuginfo-1.4.15-13.ns7.x86_64.rpm
- libss7-debuginfo-2.0.0-1.ns7.x86_64.rpm
- libss7-2.0.0-1.ns7.x86_64.rpm
- libss7-devel-2.0.0-1.ns7.x86_64.rpm
- mISDNuser-2.0.19-1.2.ns7.x86_64.rpm
- mISDNuser-debuginfo-2.0.19-1.2.ns7.x86_64.rpm
- mISDNuser-devel-2.0.19-1.2.ns7.x86_64.rpm
- pjproject-2.5.5-2.ns7.x86_64.rpm
- pjproject-devel-2.5.5-2.ns7.x86_64.rpm
- pjproject-debuginfo-2.5.5-2.ns7.x86_64.rpm
- sofia-sip-1.12.11-1.ns7.x86_64.rpm
- sofia-sip-debuginfo-1.12.11-1.ns7.x86_64.rpm
- libwat-2.1.0-1.2.sng.x86_64.rpm
- kmod-dahdi-linux-2.11.1-3.10.0_514.el7.ns7.x86_64.rpm
- dahdi-linux-kmod-debuginfo-2.11.1-3.10.0_514.el7.ns7.x86_64.rpm
- dahdi-firmware-3.0.0-1.ns7.noarch.rpm
- dahdi-linux-debuginfo-2.11.1-1.ns7.x86_64.rpm
- dahdi-linux-2.11.1-1.ns7.x86_64.rpm
- dahdi-linux-devel-2.11.1-1.ns7.x86_64.rpm
- dahdi-tools-libs-2.11.1-1.ns7.x86_64.rpm
- dahdi-tools-2.11.1-1.ns7.x86_64.rpm
- dahdi-tools-devel-2.11.1-1.ns7.x86_64.rpm
- libtonezone-devel-2.11.1-1.ns7.x86_64.rpm
- dahdi-tools-doc-2.11.1-1.ns7.x86_64.rpm
- dahdi-tools-debuginfo-2.11.1-1.ns7.x86_64.rpm
- libtonezone-2.11.1-1.ns7.x86_64.rpm
- libopenr2-1.3.3-1.ns7.x86_64.rpm
- libopenr2-devel-1.3.3-1.ns7.x86_64.rpm
- libopenr2-doc-1.3.3-1.ns7.x86_64.rpm
- libopenr2-debuginfo-1.3.3-1.ns7.x86_64.rpm
- asterisk-sounds-core-ja-wideband-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-en-alaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-en_AU-ulaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-es-alaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-it-ulaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-en_GB-wideband-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-en_AU-alaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-ja-alaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-es-ulaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-en-wideband-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-it-alaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-en_GB-ulaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-ja-ulaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-en-ulaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-fr-wideband-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-en_AU-wideband-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-es-wideband-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-fr-ulaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-en_GB-alaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-it-wideband-1.5-2.ns7.noarch.rpm
- asterisk-sounds-core-fr-alaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-extra-en-ulaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-extra-en-alaw-1.5-2.ns7.noarch.rpm
- asterisk-sounds-extra-en-wideband-1.5-2.ns7.noarch.rpm
- asterisk13-odbc-13.17.0-2.ns7.x86_64.rpm
- asterisk13-voicemail-odbcstorage-13.17.0-2.ns7.x86_64.rpm
- asterisk13-addons-13.17.0-2.ns7.x86_64.rpm
- asterisk13-voicemail-imapstorage-13.17.0-2.ns7.x86_64.rpm
- asterisk13-snmp-13.17.0-2.ns7.x86_64.rpm
- asterisk13-devel-13.17.0-2.ns7.x86_64.rpm
- asterisk13-curl-13.17.0-2.ns7.x86_64.rpm
- asterisk13-dahdi-13.17.0-2.ns7.x86_64.rpm
- asterisk13-addons-core-13.17.0-2.ns7.x86_64.rpm
- asterisk13-voicemail-13.17.0-2.ns7.x86_64.rpm
- asterisk13-speex-13.17.0-2.ns7.x86_64.rpm
- asterisk13-debuginfo-13.17.0-2.ns7.x86_64.rpm
- asterisk13-resample-13.17.0-2.ns7.x86_64.rpm
- asterisk13-addons-ooh323-13.17.0-2.ns7.x86_64.rpm
- asterisk13-ogg-13.17.0-2.ns7.x86_64.rpm
- asterisk13-sqlite3-13.17.0-2.ns7.x86_64.rpm
- asterisk13-alsa-13.17.0-2.ns7.x86_64.rpm
- asterisk13-configs-13.17.0-2.ns7.x86_64.rpm
- asterisk13-addons-mysql-13.17.0-2.ns7.x86_64.rpm
- asterisk13-addons-bluetooth-13.17.0-2.ns7.x86_64.rpm
- asterisk13-pgsql-13.17.0-2.ns7.x86_64.rpm
- asterisk13-13.17.0-2.ns7.x86_64.rpm
- asterisk13-core-13.17.0-2.ns7.x86_64.rpm
- asterisk13-tds-13.17.0-2.ns7.x86_64.rpm
- asterisk13-doc-13.17.0-2.ns7.x86_64.rpm
- freepbx-14.0-5.ns7.noarch.rpm
- nethserver-freepbx-14.0.0-1.ns7.noarch.rpm
- janus-gateway-debuginfo-0.2.3-5.ns7.x86_64.rpm
- janus-gateway-0.2.3-5.ns7.x86_64.rpm
- nethserver-janus-1.0.0-1.ns7.noarch.rpm
