### ISSUE TITLE
Missing Roundcube disclaimer

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5075]
Steps to reproduce

* Install nethserver-roundcubemail-1.2.1-1.ns7
* Activate a disclaimer text for a domain
* Send out messages
* The messages do not contain the disclaimer text

Discussion, workaround, solution on
http://community.nethserver.org/t/append-legal-note-to-mails-not-working/3934

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-roundcubemail-1.2.1-1.1.g66b3d07.ns7.noarch.rpm

*Test case*
* Check the bug is not reproducible

**Comment by alepolidori** [comment]
The bug is still present: the disclaimer is not added.
The message does not pass through amavis:

```
Aug  4 16:53:14 ns7beta1-1 postfix/smtpd[24609]: connect from localhost[127.0.0.1]
Aug  4 16:53:14 ns7beta1-1 postfix/smtpd[24609]: 26F03C1B5661: client=localhost[127.0.0.1]
Aug  4 16:53:14 ns7beta1-1 postfix/cleanup[24611]: 26F03C1B5661: message-id=<f9dd8003a69854ab2306d23063670559@alep.it>
Aug  4 16:53:14 ns7beta1-1 postfix/qmgr[9515]: 26F03C1B5661: from=<user1@alep.it>, size=550, nrcpt=1 (queue active)
Aug  4 16:53:14 ns7beta1-1 postfix/smtpd[24609]: disconnect from localhost[127.0.0.1]
Aug  4 16:53:17 ns7beta1-1 postfix/smtp[24612]: 26F03C1B5661: to=<davide.principi@nethesis.it>, relay=nethservice.nethesis.it[192.168.5.252]:25, delay=3.7, delays=0.07/0.01/0/3.6, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as B23848C0760)
Aug  4 16:53:17 ns7beta1-1 postfix/qmgr[9515]: 26F03C1B5661: removed
```

**Comment by DavidePrincipi** [comment]
@alepolidori, you could workaround this new bug (#5080) by installing nethserver-mail-filter. Please wait until #5080 is ready for testing.

**Comment by DavidePrincipi** [comment]
Now #5080 is on testing, please repeat the QA phase with its modified mail-common package.

**Comment by gsanchietti** [comment]
Bug #5080 tested with Roundcube mail client: all tests passed.

**Comment by gsanchietti** [comment]
Released:

- nethserver-roundcubemail-1.2.2-1.ns7.noarch.rpm
