### ISSUE TITLE
Nextcloud: trusted domains not updated on IP change

### ISSUE THREAD

**Issue by alepolidori** [NethServer/dev#5076]
**RPMs:**

```
nethserver-nextcloud-1.0.0-1.ns7.noarch
nextcloud-9.0.53-2.ns7.noarch
```

**Description**
The change of IP address does not update `trusted_domains` into `/var/www/html/nextcloud/config/config.php`

**Problem**
Login to `https://<NEW_IP>/nextcloud` does not work

**Steps to reproduce**
1. install nethserver-nextcloud
2. change IP
3. `trusted_domains` key into the `/var/www/html/nextcloud/config/config.php` file still has old IP

**Note:** changing of fqdn (without `nethserver-dc` or `nethserver-directory` installed) fix the data.

**Comment by alepolidori** [comment]
Created PR https://github.com/NethServer/nethserver-nextcloud/pull/2

**Comment by alepolidori** [comment]
New package in nethserver-testing:
- nethserver-nextcloud-1.0.0-1.2.g69d1745.ns7.noarch.rpm

Test case:
- Install nethserver-nextcloud from testing repository
- Change IP address of the server
- Verify that "trusted_domains" key into /var/www/html/nextcloud/config/config.php file contains the new IP address

**Comment by gsanchietti** [comment]
The trusted domains variable is correctly updated after ip change.

**Comment by gsanchietti** [comment]
Released:

- nethserver-nextcloud-1.0.1-1.ns7.noarch.rpm
