### ISSUE TITLE
Bandwidthd

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5077]
Ntopng has some limitations: only few hours of history are available, large amounts of disk space are allocated.

Bandwidthd1 is an old network monitoring tool, which is no longer maintained but it's widely adopted among many UTM linux distributions.

The package should:

- [x]  compile bandwidthd with SQLite support, to overcome its memory usage limitations
- [x]  integrate bandwidthd inside the server manager

Reference: http://community.nethserver.org/t/bandwidthd-for-nethserver-7/4071

Other tasks:

 - [x] list in Software center (update comps)

**Comment by DavidePrincipi** [comment]
- [ ] update comps

**Comment by DavidePrincipi** [comment]
In nethserver-testing:

-	nethserver-bandwidthd-0.0.1-1.9.g47cb750.ns7.noarch.rpm	
-	bandwidthd-debuginfo-2.0.1-33.18.gfd98c1a.ns7.x86_64.rpm	
-	bandwidthd-2.0.1-33.18.gfd98c1a.ns7.x86_64.rpm

**Comment by alepolidori** [comment]
From the server manager I can see Report -> Bandwith usage
I can see:
- the total send/received traffic
- the same for each specific host
- a table containing traffic data with protocol details

I can filter the results by interval data, by the number of results and by subnet filter.

Ok: it works.

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
* bandwidthd-2.0.1-34.ns7.x86_64.rpm
* nethserver-bandwidthd-1.0.0-1.ns7.noarch.rpm

Group on Software Center is named "Simplified bandwidth monitor (nethserver-bandwidthd)"

**Comment by filippocarletti** [comment]
I would have called it "Simple bandwidth monitor" :-)

**Comment by gsanchietti** [comment]
Done!
