### ISSUE TITLE
Advanced static routes

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5079]
Improve actual configuration of static routes:

- [x] implement static routes with specific selection of device and metric
- [x] implement special static routes to force a default gateway
- [x] add a new web interface for improved static routes
- [x] migrate existing db format to a the new one

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-base-3.0.4-1.9.g5c789af.ns7.noarch.rpm

*Test case 1*
- Configure at least one static route
- Install the update, check the static route has been migrated to the new format
- Modify the static route
- Verify the static route has been set using `ip ro` command

*Test case 2*
- Install the update
- Remove the gateway from the green interface
- Configure a static route using *default* as key
- Check the route is configured as default gateway

**Comment by DavidePrincipi** [comment]
* When migrating an existing route, why not set ``Any`` unconditionally on ``Device`` prop?
* On update, in /var/log/messages, avoid the following WARNING:<pre>
WARNING in /etc/e-smith/db/routes/migrate//issue5079: Use of uninitialized value $esmith::__TEMPLATE__::5::rand in concatenation (.) or string at /etc/e-smith/db/routes/
migrate//issue5079 line 45.
</pre>
The migrate fragment should return an empty string [on the last line](https://github.com/NethServer/nethserver-base/pull/47/files#diff-7f80703e2e003c00b017d7c5c22b235eR48).
* the ``default`` record is ignored if a gateway is set on green or if the gateway is the system itself (in  other words with a red interface). Would be great if UI warns about it!

**Comment by gsanchietti** [comment]
- Migrated routes should reflect the old configuration (routes must be placed to route-<interface> file)
- We could add a yellow todo in the Web UI if a ``default`` record is set,  anyway the admin needs to dig into the command line to fully understand the routing table

**Comment by gsanchietti** [comment]
New package with fix on migration fragment:

- nethserver-base-3.0.4-1.10.gfa9279d.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
- nethserver-httpd-admin-2.0.1-1.ns7.noarch.rpm
- nethserver-base-3.0.5-1.ns7.noarch.rpm
