### ISSUE TITLE
Mail disclaimer is not added

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5080]
Steps to reproduce

* install nethserver-mail-common
* configure a domain with disclaimer
* SMTP connect on localhost port 587 and send a message, sender from configured domain

The disclaimer is not added.

See also #5075

**Comment by DavidePrincipi** [comment]
Opened PRs

* NethServer/nethserver-mail-common#11, 
* NethServer/nethserver-mail-filter#5.

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
* nethserver-mail-common-1.6.1-1.1.g13db333.ns7.noarch.rpm
* nethserver-mail-filter-1.4.1-1.4.g607b1a9.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
The mail is correctly delivered in all cases.

**Comment by gsanchietti** [comment]
Released:
- nethserver-mail-common-1.6.2-1.ns7.noarch.rpm
- nethserver-mail-filter-1.4.2-1.ns7.noarch.rpm
