### ISSUE TITLE
Package install after restore log noise

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5081]
After restoring a system, I found a lot of lines like the following in /var/log/messages:
```
Aug  9 18:38:00 nethsecurity7 esmith::event[9668]: No package is available.
Aug  9 18:38:00 nethsecurity7 esmith::event[9668]: No package not available.
Aug  9 18:38:00 nethsecurity7 esmith::event[9668]: No package owned available.
Aug  9 18:38:00 nethsecurity7 esmith::event[9668]: No package by available.
```
The package-list file in the backup contained:
```
file /etc/e-smith/events/actions is not owned by any package
file /etc/e-smith/events/backup-restore-duc-index is not owned by any package
file /etc/e-smith/events/certificate-update is not owned by any package
```

The find command used in the nethserver-backup-config-list-packages action seems to no longer be appropriated for v7.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-backup-config-1.5.0-1.1.ga6c8d62.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducible
- Create the package list and check it contains only a list of valid nethserver packages:
```
/etc/e-smith/events/actions/nethserver-backup-config-list-packages
cat /var/lib/nethserver/backup/package-list
```

**Comment by gsanchietti** [comment]
Released:
nethserver-backup-config-1.5.1-1.ns7.noarch.rpm
