### ISSUE TITLE
nethserver-letsencrypt: apache acl for 2.4

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5082]
/etc/e-smith/templates/httpd/vhost-default/30letsencrypt contains apache 2.2 syntax:
```
 #
 # 30letsencrypt
 #
 Alias "/.well-known/acme-challenge/" "/var/www/html/.well-known/acme-challenge/"
 <Directory "/var/www/html/.well-known/acme-challenge/">
    Order allow,deny
    Allow from all
    Options -Indexes -FollowSymLinks
    AllowOverride None
 </Directory>
```
Following the upgrade docs (http://httpd.apache.org/docs/current/upgrading.html) we should drop Order and Allow lines and replace them with **Require all granted**.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-letsencrypt-1.1.0-1.1.ge8401e0.ns7.noarch.rpm

*Test case*
* Create a test file:
```
echo test > /var/www/html/.well-known/acme-challenge/test
```
* Check the file is accessible from a http client:
```
/var/www/html/.well-known/acme-challenge/
```

**Comment by gsanchietti** [comment]
Released:
nethserver-letsencrypt-1.1.1-1.ns7.noarch.rpm
