### ISSUE TITLE
nethserver-squidclamav: reload action not supported by c-icap

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5083]
On every configuration change on the web filter page a red error box appears signalling that the c-icap service has not been restarted.
I think I've tracked the problem to the reload action that is not supported by the systemd unit.
It's used in
```
[root@nethsecurity7 ~]# cat /etc/e-smith/events/nethserver-squidguard-save/services2adjust/c-icap
reload
```
The c-icap daemon supports reload, we could try to improve the systemd unit file with
`echo -n "reconfigure" > /var/run/c-icap/c-icap.ctl`

Alternatively, we could use restart instead of reload.

Relevant log lines:
```
Aug 19 15:06:20 nethsecurity7 esmith::event[32033]: Failed to reload c-icap.service: Job type reload is not applicable for unit c-icap.service.
Aug 19 15:06:20 nethsecurity7 esmith::event[32033]: [WARNING] reload service c-icap failed!
Aug 19 15:06:21 nethsecurity7 esmith::event[32033]: Action: /etc/e-smith/events/actions/adjust-services FAILED: 1 [1.087656]
Aug 19 15:06:21 nethsecurity7 esmith::event[32033]: Event: nethserver-squidguard-save FAILED

```

**Comment by gsanchietti** [comment]
Accordingly to official systemd doc, we can't implement the reload command by writing to c-icap socket.
From https://www.freedesktop.org/software/systemd/man/systemd.service.html inside ExecReload section:

> It is strongly recommended to set ExecReload= to a command that not only triggers a configuration reload of the daemon, but also synchronously waits for it to complete.

**Comment by gsanchietti** [comment]
In nethserver-testing:

- nethserver-squidclamav-1.3.0-1.1.gead2a60.ns7.noarch.rpm

*Test case*

- Check the bug is not reproducible: c-icap must be restarted on nethserver-squidguard-save event

**Comment by gsanchietti** [comment]
Released:
nethserver-squidclamav-1.3.1-1.ns7.noarch.rpm
