### ISSUE TITLE
USB install error

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5085]
I installed NethServer 7 on a single disk system using an usb key as source media. I used the unattended option.
During install sda was the usb key and sdb the disk. Early during the install the following messages appeared on screen:

```
[  OK  ] Mounted Configuration File System.
[   13.654506] scsi 0:0:0:0: alua: not attached
[   14.413295] dracut-initqueue[562]: mount: /dev/sda is write-protected, mounting read-only
[   14.467801] dracut-initqueue[562]: gzip: stdout: Broken pipe
[  OK  ] Started dracut initqueue hook.

storage configuration failed: The following problem occurred on line 2 of the kickstart file:


Disk "sda" in part command is not partitioned.

================================================================================
================================================================================
Installation

 1) [x] Language settings                 2) [x] Timezone settings
        (English (United States))                (UTC timezone)
 3) [x] Installation source               4) [x] Software selection
        (Local media)                            (Custom software selected)
 5) [!] Installation Destination          6) [x] Kdump
        (No disks selected)                      (Kdump is enabled)
 7) [ ] Network configuration             8) [ ] User creation
        (Not connected)                          (No user will be created)
Not enough space in file systems for the current software selection. An additional 2861.02 MiB is needed.
  Please make your choice from above ['q' to quit | 'b' to begin installation |
  'r' to refresh]: 
[anaconda] 1:main* 2:shell  3:log  4:storage-lo> Switch tab: Alt+Tab | Help: F1 

```

I proceeded hitting 5 and configuring the disk to be used by NethServer. The install completed successfully.
Line 2 of the kickstart file doesn't seem relevant:
https://github.com/NethServer/nethserver-createiso/blob/master/src/lib/ks/unattended

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-createiso-1.4.0-1.3.g38e5a08.ns7.noarch.rpm

*Test case*
- Create a ISO with the new nethserver-createiso rpm
- Copy the ISO on a USB stick using dd
- Try to install from USB to a machine 
- Try also the same machine with 1, 2 or 3 disks

**Comment by filippocarletti** [comment]
I did an unattended install on a single disk system using an usb key: installation has proceeded without errors. Note: it was the same system where I saw the error reported above.

**Comment by filippocarletti** [comment]
Two more tests just completed:
1. unattended cdrom install on two disk system: RAID1 created
2. unattended cdrom install on two disk system with disks=sda boot optino: system installed on sda, sdb left untouched

**Comment by filippocarletti** [comment]
One more test:
3 disks system, unattended install: sda and sdb used in a RAID1 set, sdc left untouched.

**Comment by gsanchietti** [comment]
Released:
 -nethserver-createiso-1.4.1-1.ns7.noarch.rpm
