### ISSUE TITLE
Port forward from VLAN red

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5087]
Creating a port forward, VLAN reds are not listed in the WAN IP (red interface) section.
It's impossible to limit a port forward to a VLAN interface.

See: http://dev.nethserver.org/issues/3418

**Comment by gsanchietti** [comment]
In nethserver-testing:

- nethserver-firewall-base-2.10.6-1.2.gb2d39ec.ns7.noarch.rpm
- nethserver-firewall-base-ui-2.10.6-1.2.gb2d39ec.ns7.noarch.rpm

*Test case*

- Check the bug is not reproducible

**Comment by DavidePrincipi** [comment]
The fix was backported to ns6
http://dev.nethserver.org/issues/3418

**Comment by gsanchietti** [comment]
Released:
- nethserver-firewall-base-3.0.3-1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.0.3-1.ns7.noarch.rpm
