### ISSUE TITLE
Apache vhost-default template expansion

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5088]
Apache mod_rewrite directives, like ``RewriteRule``, specified in the server global scope are not inherited by VirtualHost scopes.

One of the purposes of the ``vhost-default`` template in ns6 was working around this limitation by always defining a default virtual host (``nethserver.d/00default..vhost``) and its configuration entirely.

In ns7, with the attempt of producing a more upstream compliant configuration, we could expand ``vhost-default`` template at the global scope level

- [x] Clean up old ns6 Apache configuration template and actions
- [x] Include ``vhost-default`` template from ``nethserver.conf``, at global scope level
- [x] Include ``vhost-default`` template from ``nethserver-virtualhosts`` default virtualhost configuration

**Comment by DavidePrincipi** [comment]
**TEST CASE**

upgrade ``nethserver-httpd`` package

* server-manager redirect: ``http://<IP>/server-manager/`` redirects to ``https://<IP>:980/``
* Let's Encrypt challenge ``touch /var/www/html/.well-known/acme-challenge/test`` then access ``http://<IP>/.well-known/acme-challenge/test``

install ``nethserver-virtualhosts`` package

* repeat the tests above
* define a virtual host, ``vh1.example.com`` and add it to your local /etc/hosts file

install ``nethserver-webtop4`` package

* ``http://<IP>/webtop`` redirects to ``https://<IP>/webtop/``
* ``http://vh1.example.com/webtop`` redirects to ``https://vh1.example.com/webtop/``

In nethserver-testing/7.2.1511:

* nethserver-webtop4-1.3.1-1.3.g3eb3050.ns7.noarch.rpm
* nethserver-httpd-3.0.0-1.5.g58edb2e.ns7.noarch.rpm
* nethserver-httpd-proxypass-3.0.0-1.5.g58edb2e.ns7.noarch.rpm
* nethserver-virtualhosts-1.0.0-1.2.g5c995a2.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Let's try with another small refactor:

- [ ] replace special `vhost-default` template with a real one which expands to  `/etc/conf.d/default-virtualthost.inc`
- [ ] `nethserver.conf ` will include `default-virtualthost.inc`
- [ ] `virtualhosts.conf` will include `default-virtualthost.inc`
- [ ] `default-virtualthost.inc` will include the old `vhost-default` template for backward-compatibility

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-httpd-admin-2.0.1-1.3.g1d6564e.ns7.noarch.rpm
- nethserver-virtualhosts-1.0.0-1.3.g2d9a8f1.ns7.noarch.rpm
- nethserver-httpd-3.0.0-1.8.g0218e86.ns7.noarch.rpm
- nethserver-httpd-proxypass-3.0.0-1.8.g0218e86.ns7.noarch.rpm
- nethserver-roundcubemail-1.2.2-1.1.g3a34a24.ns7.noarch.rpm
- nethserver-webtop4-1.3.1-1.6.gfb11e7c.ns7.noarch.rpm
- nethserver-nextcloud-1.0.1-1.3.g61fafdc.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:

- nethserver-httpd-3.0.0-1.9.g7d4fed0.ns7.noarch.rpm
- nethserver-httpd-proxypass-3.0.0-1.9.g7d4fed0.ns7.noarch.rpm
- nethserver-virtualhosts-1.0.0-1.5.g3878715.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
- nethserver-httpd-3.1.0-1.ns7.noarch.rpm
- nethserver-httpd-proxypass-3.1.0-1.ns7.noarch.rpm
- nethserver-virtualhosts-1.0.1-1.ns7.noarch.rpm
- nethserver-httpd-admin-2.0.2-1.ns7.noarch.rpm
- nethserver-roundcubemail-1.2.3-1.ns7.noarch.rpm
- nethserver-webtop4-1.3.2-1.ns7.noarch.rpm
