### ISSUE TITLE
Default centos-release-scl  package

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5089]
Add it to nethserver-iso YUM group.

PHP from SCL is required by PBX packages. The repository is compatible with others and can stay  enabled safely.

**Comment by DavidePrincipi** [comment]
Updated nethserver-groups.xml

**Comment by DavidePrincipi** [comment]
By default the repository is disabled! We must enable ``centos-sclo-rh`` and ``centos-sclo-sclo`` on

- [ ] ``nethserver-install`` script
- [ ] ``system-init`` event

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-release-7-0.2.1.gd4deade.ns7.noarch.rpm
-  nethserver-base-3.0.6-1.8.ga74db5d.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Passed tests:
- installation on a clean CentOS, after install available repos are:
> base/7/x86_64
> centos-sclo-rh/x86_64
> centos-sclo-sclo/x86_64
> epel/x86_64
> extras/7/x86_64
> nethforge/7/x86_64
> nethserver-base/7/x86_64
> nethserver-updates/7/x86_64
> updates/7/x86_64

- `yum grouplist -v` from command lines displays groups from all enabled repositories
- software center displays only groups from nethforge and nethserver-base
- software center displays groups also from extra repositories added to `/etc/nethserver/pkginfo.conf`

**Comment by gsanchietti** [comment]
Tested also with a custom ISO built with nethserver-testing enabled.

**Comment by gsanchietti** [comment]
Released:
- nethserver-base-3.0.7-1.ns7.noarch.rpm
- nethserver-release-7-0.3.ns7.noarch.rpm
