### ISSUE TITLE
Could not connect my Samba home share

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5090]
The following command fails:

```
    $ smbclient  '//192.168.122.5/second.user@dpnet.nethesis.it' -U second.user%Nethesis,1234 -W DPNET
Domain=[DPNET] OS=[Windows 6.1] Server=[Samba 4.2.10]
tree connect failed: NT_STATUS_BAD_NETWORK_NAME
```

``second.user``'s home is:

```
   $ getent passwd second.user@dpnet.nethesis.it
second.user@dpnet.nethesis.it:*:495001105:495000513:second.user:/var/lib/nethserver/home/second.user:/bin/bash
```

In ``/var/log/messages``:

```
Aug 26 12:10:10 vm5 smbd[14924]:  canonicalize_connect_path failed for service second.user@dpnet.nethesis.it, path /var/lib/nethserver/home/second.user@dpnet.nethesis.it
```

Workarounds:

1. change the home path to be what Samba expects (by appending the @domain suffix), or
2. change smb.conf to read the home path from the passwd DB itself: use ``%H`` on ``path`` directive under ``[homes]`` section.

According to [SAMBA-HOME] when a share name is unknown, Samba checks if it corresponds to a Unix user name.

   [SAMBA-HOME]: https://www.samba.org/samba/docs/using_samba/ch06.html#samba2-CHP-6-SECT-2.2

See also http://community.nethserver.org/t/missing-samba-home-directory/4191

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-samba-2.0.0-1.1.g649b2e8.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-samba-2.0.0-1.2.g9f318f7.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Tested with previously created user and with a new one:

```
smbclient  '//127.0.0.1/mario@neth.eu' -U mario%Nethesis,1234
```

**Comment by gsanchietti** [comment]
Released:
nethserver-samba-2.0.1-1.ns7.noarch.rpm
