### ISSUE TITLE
shorewall error on divert rules from firewall

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5091]
Creating a firewall rule to divert traffic originating from the firewall itself results in the following error, applying changes:
```
Configuring shorewall #24 (exit status 1)
 ERROR: Rules with SOURCE $FW must use the OUTPUT chain /etc/shorewall/mangle (line 34)
```
Rules are created like this:
`MARK(0x20000):P $FW     -       tcp     2222`

The ':P'  forces the us of the PREROUTING chain which is the default (see shorewall-mangle).

Omitting the ':P' the error goes away and the rules works as expected.

Possible patch:
```
--- /etc/e-smith/templates/etc/shorewall/mangle/40providers	2016-07-21 12:01:39.000000000 +0200
+++ /etc/e-smith/templates-custom/etc/shorewall/mangle/40providers	2016-08-26 15:12:34.545735160 +0200
@@ -66,7 +66,7 @@
         foreach (@src_addr) {
             my $comment = "\n#\n# FORCE traffic [$src_ori -> $dst_ori] to $provider_key \n#\n";
             my $lines = "?COMMENT $provider_key\n";
-            $lines .= "MARK(".$mask."):P\t".$_."\t".$dst_addr;
+            $lines .= "MARK(".$mask.")\t".$_."\t".$dst_addr;
             if ($service eq 'any' || $service eq '') {
                 next if ($_ eq '-' && ($dst_addr eq '-' || $dst_addr eq '')); # skip rules where dst, src and service are empty
                 $OUT .= $comment.$lines."\n";

```

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-firewall-base-3.0.3-1.1.gb67f007.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.0.3-1.1.gb67f007.ns7.noarch.rpm

*Test case 1*
- Create a divert rule using an host in a LAN as a source
- Check the rule correctly works

*Test case 1*
- Create a divert rule using the firewall as a source
- Check the rule correctly works

**Comment by filippocarletti** [comment]
MARK(0x20000)   $FW     -       tcp     2222
MARK(0x10000)   192.168.5.5     -       tcp     2222

**Comment by gsanchietti** [comment]
Released:
- nethserver-firewall-base-3.0.4-1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.0.4-1.ns7.noarch.rpm
