### ISSUE TITLE
Let's Encrypt: generated certificate is invalid

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5092]
Let's Encrypt certificate generated from the web interface is invalid.
During the validation step, the web interface generates a test certificate which isn't replaced by the valid one.

*Steps to reproduce*
* Install a clean machine
* Make sure all Let's Encrypt prerequsites are met
* Open the "Server certificates" page and select "Request Let's Encrypt certificate"
* Generate a new certificate 

*Actual behavior*
* Under the Issuer field, the displayed value is "Fake LE Intermediate X1"

*Expected behavior*
The Issuer must be "Let's Encrypt, CN=Let's Encrypt Authority X3"

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-base-3.0.6-1.1.g7dc8c8d.ns7.noarch.rpm
- nethserver-letsencrypt-1.1.1-1.1.gd201d7a.ns7.noarch.rpm

*Test case 1*
- Check the bug is not reproducibile

*Test case 2*
- After test case 1, add an extra domain to the Let's Encrypt certificate
- Check the certificate contains both domains:
```
openssl x509  -text -noout -in /etc/letsencrypt/live/<fqdn>/cert.pem | grep DNS
```

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-base-3.0.6-1.4.g71c7421.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
- nethserver-letsencrypt-1.1.2-1.ns7.noarch.rpm
- nethserver-base-3.0.7-1.ns7.noarch.rpm
