### ISSUE TITLE
Internationalized domain names (IDN) in UI

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5093]
By now the UI does not validate IDN character sequences on host and domain names. We could add IDN support by fixing the host and domain validator logic.

> IDN is standardized https://tools.ietf.org/html/rfc3490 with ACE prefix (xn--).
>  And from year 2009 allowed and now widely used for example in EU TLD http://www.mpo.cz/dokument66986.html1
> Without repaired bug "add IDN domain record" in to user interface is not usable in Europe. I mean the unusable for general users. 
> IT technician can use a configuration files, but then litle becomes meaningless use NethServer.

Thanks to delusion for having reported this:
http://community.nethserver.org/t/idn-broken-in-ui/2128/3

----
Originally opened on ns6 http://dev.nethserver.org/issues/3318

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-httpd-admin-2.0.1-1.1.g744d0c4.ns7.noarch.rpm

**Comment by dz00te** [comment]
*System and  Package Version installed*
VM KVM - Clean install of Nethserver 7b1 fully updated

*Install Updated Package*
yum --enablerepo=nethserver-testing install nethserver-httpd-admin-2.0.1-1.1.g744d0c4.ns7.noarch

*Test Results after update*
The host name validator now correctly allows consecutive "-" (minus) signs

**Comment by gsanchietti** [comment]
Released:
- nethserver-httpd-admin-2.0.2-1.ns7.noarch.rpm
