### ISSUE TITLE
Missing i18n labels

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5094]
As @jgjimenez reported on ns6, 

- [x] the table views are missing some language labels. DataTables supports i18n, we should configure it. <br><img src="http://dev.nethserver.org/attachments/download/328/path4217-3.png">
- [x] the Traffic Shaping page header cannot be translated <br><img src="http://community.nethserver.org/uploads/db8506/original/1X/f084428bc51926feaf716b6b0e6bc46a00538d14.png">
- [x] the Backup data dashboard panel does not translate the word "START" 
- [x] the Multi Wan dashboard panel does not translate the word "UP" <img src="http://community.nethserver.org/uploads/db8506/original/1X/a420ae5021e4df481f78ca35b431f5cabd6562c3.png">
 

Original request on ns6: http://dev.nethserver.org/issues/3203
Community: http://community.nethserver.org/t/add-new-words-in-transifex/1092

**Comment by DavidePrincipi** [comment]
QA note:
new labels are just defined and still untraslated

In nethserver-testing:
- nethserver-firewall-base-ui-3.0.3-1.3.gbcc0014.ns7.noarch.rpm
- nethserver-firewall-base-3.0.3-1.3.gbcc0014.ns7.noarch.rpm
- nethserver-httpd-admin-2.0.1-1.1.g744d0c4.ns7.noarch.rpm
- nethserver-backup-data-1.2.0-1.1.g7cc0bc0.ns7.noarch.rpm
- nethserver-lang-en-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-it-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-de-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-el-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-es-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-fr-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-hu-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-nl-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-ru-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-pt-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-tr-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-sv-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-cs-1.1.2-1.3.gc965eb9.ns7.noarch.rpm
- nethserver-lang-sr-1.1.2-1.3.gc965eb9.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
- nethserver-firewall-base-3.0.4-1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.0.4-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:

- nethserver-lang-cs-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-de-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-el-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-en-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-es-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-fr-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-hu-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-it-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-nl-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-pt-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-ru-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-sr-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-sv-1.1.3-1.ns7.noarch.rpm
- nethserver-lang-tr-1.1.3-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:

- nethserver-backup-data-1.2.1-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
- nethserver-httpd-admin-2.0.2-1.ns7.noarch.rpm
