### ISSUE TITLE
Nextcloud: upgrade to version 10

### ISSUE THREAD

**Issue by alepolidori** [NethServer/dev#5096]
New server release is available: 10.0.0.
Some new features:
- control workflow
- monitoring
- two Factor Authentication
- user interface enhancements

More information: https://nextcloud.com/secure-monitor-and-control-your-data-with-nextcloud-10-get-it-now/

**Comment by alepolidori** [comment]
PR submitted to nextcloud/server-packages: https://github.com/nextcloud/server-packages/pull/3

**Comment by alepolidori** [comment]
In nethserver-testing:

nextcloud-10.0.0-1.ns7.noarch.rpm
nethserver-nextcloud-1.0.1-1.2.g806d372.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Please, verify it using nethserver-httpd packages from #5088

**Comment by gsanchietti** [comment]
Tests passed within a clean installation and an updated one.

**Comment by gsanchietti** [comment]
Released:
- nextcloud-10.0.0-1.ns7.noarch.rpm
- nethserver-nextcloud-1.0.2-1.ns7.noarch.rpm
