### ISSUE TITLE
UI stale after joining a remote account provider

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5097]
**Steps to reproduce**

* Select "Users and Groups" page
* Configure AD or OpenLDAP provider
* Press "Bind" button

_The event runs but at the end the UI does not give any feedback_

**Expected behavior**
After a successful join/bind operation the UI reloads automatically ``/Account`` and shows the list of users from the domain.

**Component**
nethserver-sssd-1.0.2-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.2-1.3.gf9dec98.ns7.noarch.rpm

**Comment by dz00te** [comment]
*System and  Package Version installed*
VM KVM - Clean install of Nethserver 7b1 fully updated

*Install Updated Package*
yum --enablerepo=nethserver-testing install nethserver-sssd-1.0.2-1.3.gf9dec98.ns7.noarch

*Test Results after update*
tested with openldap
now after bind is correctly reloaded the Accounts page.
(still missing the test on AD)

note: just one doubt... on the help page to configure ldap:
Server URIto configure an external LDAP provider insert ldap URI like ldap://192.168.1.10:389
but it seems to accept only the ip address

**Comment by gsanchietti** [comment]
*System and  Package Version installed*
VM KVM - Clean install of Nethserver 7b1 fully updated

*Install Updated Package*
yum --enablerepo=nethserver-testing install nethserver-sssd-1.0.2-1.3.gf9dec98.ns7.noarch

*Test Results after update*
tested with AD
now after bind is correctly reloaded the Accounts page.

Also fixed LDAP field label and inline help accordignly to @dz00te note (thanks!).

**Comment by gsanchietti** [comment]
Released:
- nethserver-sssd-1.0.3-1.ns7.noarch.rpm
