### ISSUE TITLE
collectd graphs reset every night

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5098]
Collectd Graphs are always almost empty, i.e. they start around 3am.
Steps to reproduce:
1. click on Graphs
2. look at the graphs: they have 0 values before around 3am

The problem comes from an aggressive cleanup script supposed to delete old unused rrd data.
rrd files are written every two minutes:
`CacheTimeout 120`

**Comment by gsanchietti** [comment]
This is the bugged script:
https://github.com/NethServer/nethserver-collectd/blob/master/root/etc/cron.daily/collectd_cleanup

I'd like to remove it completely and eventually add some logic to CGP to hide old graphs.

**Comment by filippocarletti** [comment]
I'd prefer not to keep stale data on the disk.
We lived with the script for almost two years without problems.
The fix is super easy (already tested):
`find /var/lib/collectd/ -type f -mmin +10 -delete`
We could even keep stale files for some days.

**Comment by DavidePrincipi** [comment]
That script is potentially harmful. If collectd is not running (for any reason) it would erase all rrd files!

If the problem is what we see on CGP, we should try to fix CGP without destroying our databases!

**Comment by filippocarletti** [comment]
The problems I remember were:
1. changing ping hosts
2. df plugin collecting temporary mounts (i.e. /mnt/backup)
3. hardware no longer present (eth board, usb disks,...)

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-collectd-2.0.1-1.2.gef6ffcf.ns7.noarch.rpm

*Test case*

- Check the bug is not reproducible
  - Execute /etc/cron.daily/collectd_cleanup
  - Check the script delete only files not modified in last 24 hours

**Comment by DavidePrincipi** [comment]
Verified on ns6
http://dev.nethserver.org/issues/3423

**Comment by gsanchietti** [comment]
Released:
- nethserver-collectd-3.0.0-1.ns7.noarch.rpm

Bump version to 3.0.0 to avoid conflicts with NS 6
