### ISSUE TITLE
 DC join failed, realmd cannot join this realm

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5099]
**Steps to reproduce**

* Install Samba AD provider
* Set DC IP address and start it

This error is not always reproducible! In the log files I see the evidence of a race condition between realmd and samba startup process.

The join succeeds on a second attempt.

From ``/var/log/messages``

<pre>
[...]
Sep  2 08:40:53 myt esmith::event[2441]: Action: /etc/e-smith/events/nethserver-dc-save/S95nethserver-dc-waitstart SUCCESS [20.590579]
Sep  2 08:40:53 myt /sbin/e-smith/db[4386]: /var/lib/nethserver/db/configuration: OLD sssd=service|AdDns||LdapURI||Provider|none|status|disabled
Sep  2 08:40:53 myt /sbin/e-smith/db[4386]: /var/lib/nethserver/db/configuration: NEW sssd=service|AdDns|192.168.5.44|LdapURI||Provider|none|status|disabled
Sep  2 08:40:53 myt /sbin/e-smith/db[4386]: /var/lib/nethserver/db/configuration: OLD sssd=service|AdDns|192.168.5.44|LdapURI||Provider|none|status|disabled
Sep  2 08:40:53 myt /sbin/e-smith/db[4386]: /var/lib/nethserver/db/configuration: NEW sssd=service|AdDns|192.168.5.44|LdapURI||Provider|ad|status|disabled
Sep  2 08:40:53 myt /sbin/e-smith/db[4386]: /var/lib/nethserver/db/configuration: OLD sssd=service|AdDns|192.168.5.44|LdapURI||Provider|ad|status|disabled
Sep  2 08:40:53 myt /sbin/e-smith/db[4386]: /var/lib/nethserver/db/configuration: NEW sssd=service|AdDns|192.168.5.44|LdapURI||Provider|ad|status|enabled
Sep  2 08:40:54 myt dnsmasq[4277]: exiting on receipt of SIGTERM
Sep  2 08:40:54 myt systemd: Stopping DNS caching server....
Sep  2 08:40:54 myt systemd: Started DNS caching server..
Sep  2 08:40:54 myt systemd: Starting DNS caching server....
Sep  2 08:40:54 myt dnsmasq[4392]: started, version 2.66 cachesize 4000
Sep  2 08:40:54 myt dnsmasq[4392]: compile time options: IPv6 GNU-getopt DBus no-i18n IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth
Sep  2 08:40:54 myt dnsmasq-tftp[4392]: TFTP root is /var/lib/tftpboot
Sep  2 08:40:54 myt dnsmasq[4392]: using nameserver 192.168.5.44#53 for domain neth.eu
Sep  2 08:40:54 myt dnsmasq[4392]: using nameserver 8.8.8.8#53
Sep  2 08:40:54 myt dnsmasq[4392]: read /etc/hosts - 2 addresses
[...]
Sep  2 08:40:58 myt realmd: * Resolving: _ldap._tcp.neth.eu
Sep  2 08:40:58 myt realmd: * Performing LDAP DSE lookup on: 192.168.5.44
Sep  2 08:40:58 myt realmd: ! Can't contact LDAP server
Sep  2 08:40:58 myt esmith::event[2441]: realm: Cannot join this realm
Sep  2 08:40:58 myt esmith::event[2441]: [ERROR] DC join failed
Sep  2 08:40:58 myt esmith::event[2441]: Action: /etc/e-smith/events/nethserver-dc-save/S96nethserver-dc-join FAILED: 1 [5.347659]
Sep  2 08:41:00 myt esmith::event[2441]: Minimum password age changed!
Sep  2 08:41:00 myt esmith::event[2441]: Maximum password age changed!
Sep  2 08:41:00 myt esmith::event[2441]: All changes applied successfully!
Sep  2 08:41:02 myt esmith::event[2441]: Action: /etc/e-smith/events/nethserver-dc-save/S97nethserver-dc-password-policy SUCCESS [4.287287]
Sep  2 08:41:02 myt esmith::event[2441]: Event: nethserver-dc-save FAILED
</pre>

From ``journalctl -M nsdc``

<pre>
Sep 02 08:40:34 nsdc-myt.neth.eu samba-tool[24]: Setting up secrets.ldb
Sep 02 08:40:34 nsdc-myt.neth.eu samba-tool[24]: Setting up the registry
Sep 02 08:40:41 nsdc-myt.neth.eu samba-tool[24]: Setting up the privileges database
Sep 02 08:40:41 nsdc-myt.neth.eu samba-tool[24]: Setting up idmap db
Sep 02 08:40:41 nsdc-myt.neth.eu samba-tool[24]: Setting up SAM db
Sep 02 08:40:42 nsdc-myt.neth.eu samba-tool[24]: Setting up sam.ldb partitions and settings
Sep 02 08:40:42 nsdc-myt.neth.eu samba-tool[24]: Setting up sam.ldb rootDSE
Sep 02 08:40:42 nsdc-myt.neth.eu samba-tool[24]: Pre-loading the Samba 4 and AD schema
Sep 02 08:40:42 nsdc-myt.neth.eu samba-tool[24]: Adding DomainDN: DC=neth,DC=eu
Sep 02 08:40:42 nsdc-myt.neth.eu samba-tool[24]: Adding configuration container
Sep 02 08:40:42 nsdc-myt.neth.eu samba-tool[24]: Setting up sam.ldb schema
Sep 02 08:40:44 nsdc-myt.neth.eu samba-tool[24]: Setting up sam.ldb configuration data
Sep 02 08:40:44 nsdc-myt.neth.eu samba-tool[24]: Setting up display specifiers
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Modifying display specifiers
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Adding users container
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Modifying users container
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Adding computers container
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Modifying computers container
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Setting up sam.ldb data
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Setting up well known security principals
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Setting up sam.ldb users and groups
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Setting up self join
Sep 02 08:40:48 nsdc-myt.neth.eu samba-tool[24]: Adding DNS accounts
Sep 02 08:40:48 nsdc-myt.neth.eu samba-tool[24]: Creating CN=MicrosoftDNS,CN=System,DC=neth,DC=eu
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Setting up well known security principals
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Setting up sam.ldb users and groups
Sep 02 08:40:46 nsdc-myt.neth.eu samba-tool[24]: Setting up self join
Sep 02 08:40:48 nsdc-myt.neth.eu samba-tool[24]: Adding DNS accounts
Sep 02 08:40:48 nsdc-myt.neth.eu samba-tool[24]: Creating CN=MicrosoftDNS,CN=System,DC=neth,DC=eu
Sep 02 08:40:49 nsdc-myt.neth.eu samba-tool[24]: Creating DomainDnsZones and ForestDnsZones partitions
Sep 02 08:40:49 nsdc-myt.neth.eu systemd[1]: Started /bin/bash.
Sep 02 08:40:49 nsdc-myt.neth.eu systemd[1]: Starting /bin/bash...
Sep 02 08:40:50 nsdc-myt.neth.eu samba-tool[24]: Populating DomainDnsZones and ForestDnsZones partitions
Sep 02 08:40:51 nsdc-myt.neth.eu samba-tool[24]: Setting up sam.ldb rootDSE marking as synchronized
Sep 02 08:40:51 nsdc-myt.neth.eu samba-tool[24]: Fixing provision GUIDs
Sep 02 08:40:52 nsdc-myt.neth.eu samba-tool[24]: A Kerberos configuration suitable for Samba 4 has been generated at /var/lib/samba/private/krb5.conf
Sep 02 08:40:52 nsdc-myt.neth.eu samba-tool[24]: Once the above files are installed, your Samba4 server will be ready to use
Sep 02 08:40:52 nsdc-myt.neth.eu samba-tool[24]: Server Role:           active directory domain controller
Sep 02 08:40:52 nsdc-myt.neth.eu samba-tool[24]: Hostname:              nsdc-myt
Sep 02 08:40:52 nsdc-myt.neth.eu samba-tool[24]: NetBIOS Domain:        NETH
Sep 02 08:40:52 nsdc-myt.neth.eu samba-tool[24]: DNS Domain:            neth.eu
Sep 02 08:40:52 nsdc-myt.neth.eu samba-tool[24]: DOMAIN SID:            S-1-5-21-2748494373-3664257659-1870189200
Sep 02 08:40:52 nsdc-myt.neth.eu cp[35]: '/var/lib/samba/private/krb5.conf' -> '/etc/krb5.conf'
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Started Domain controller provisioning.
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Started Samba domain controller daemon.
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Starting Samba domain controller daemon...
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Reached target Multi-User System.
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Starting Multi-User System.
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Reached target Graphical Interface.
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Starting Graphical Interface.
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Started Stop Read-Ahead Data Collection 10s After Completed Startup.
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Starting Update UTMP about System Runlevel Changes...
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Started Update UTMP about System Runlevel Changes.
Sep 02 08:40:52 nsdc-myt.neth.eu systemd[1]: Startup finished in 19.866s.
Sep 02 08:40:52 nsdc-myt.neth.eu samba[37]: samba version 4.4.5 started.
Sep 02 08:40:52 nsdc-myt.neth.eu samba[37]: Copyright Andrew Tridgell and the Samba Team 1992-2016
Sep 02 08:40:52 nsdc-myt.neth.eu samba[37]: samba: using 'standard' process model
Sep 02 08:40:52 nsdc-myt.neth.eu samba[37]: Attempting to autogenerate TLS self-signed keys for https for hostname 'NSDC-MYT.neth.eu'
Sep 02 08:40:52 nsdc-myt.neth.eu winbindd[53]: [2016/09/02 08:40:52.900503,  0] ../source3/winbindd/winbindd_cache.c:3245(initialize_winbindd_cache)
Sep 02 08:40:52 nsdc-myt.neth.eu winbindd[53]:   initialize_winbindd_cache: clearing cache and re-creating with version number 2
Sep 02 08:40:54 nsdc-myt.neth.eu winbindd[53]: [2016/09/02 08:40:54.515566,  0] ../lib/util/become_daemon.c:124(daemon_ready)
Sep 02 08:40:54 nsdc-myt.neth.eu winbindd[53]:   STATUS=daemon 'winbindd' finished starting up and ready to serve connections
Sep 02 08:40:57 nsdc-myt.neth.eu samba[37]: TLS self-signed keys generated OK
Sep 02 08:40:58 nsdc-myt.neth.eu systemd[1]: Started /usr/bin/samba-tool domain passwordsettings set --min-pwd-age=0 --max-pwd-age=0.
Sep 02 08:40:58 nsdc-myt.neth.eu systemd[1]: Starting /usr/bin/samba-tool domain passwordsettings set --min-pwd-age=0 --max-pwd-age=0...
Sep 02 08:40:59 nsdc-myt.neth.eu smbd[42]: [2016/09/02 08:40:59.942122,  0] ../lib/util/become_daemon.c:124(daemon_ready)
Sep 02 08:40:59 nsdc-myt.neth.eu smbd[42]:   STATUS=daemon 'smbd' finished starting up and ready to serve connections
Sep 02 08:41:00 nsdc-myt.neth.eu systemd[1]: Started /usr/bin/samba-tool domain passwordsettings show.
Sep 02 08:41:00 nsdc-myt.neth.eu systemd[1]: Starting /usr/bin/samba-tool domain passwordsettings show...
</pre>

Realmd gives up at 08:40:58, whilst samba declares itself ready to serve connections at 08:40:59.

**Components**
nethserver-sssd-1.0.2-1.3.gf9dec98.ns7.noarch
nethserver-dc-1.0.2-1.ns7.x86_64

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.0.2-1.3.g09d9ae7.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
The dc is correctly installed.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-dc-1.0.3-1.ns7.x86_64.rpm
