### ISSUE TITLE
nDPI support: deep packet inspection

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5102]
Add support for nDPI to current Shorewall implementation.
The software is composed by
- a kernel modules for LT kernel from elrepo (kernel-lt-4.4)
- an iptables module which adds a special `ndpi` target

See: https://github.com/NethServer/xt_ndpi-kmod

NethServer module will be split in the following parts:

- [x] Kernel and modules requirements, after the installation the kernel-lt package will be the default kernel
- [x] Support for the new ndpi target in firewall library
- [x] Shorewall configuration for nDPI modules autoload
- [x] Extension of "Firewall rules" page to allow the creation of new rules
- [x] show a "todo" alert if the running kernel did not load xt_ndpi
- [x] smart DPI protocol icons in UI
- [x] forbid DPI protocol on route rules

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-ndpi-0.0.1-1.7.ge4785fd.ns7.noarch.rpm
- kmod-xt_ndpi-0.0-1.ns7.x86_64
- kernel-lt-4.4.19-1.el7.elrepo.x86_64

*Test case 1: installation*
- Install nethserver-ndpi
- Reboot the machine
- Check the elrepo kernel is loaded: `uname -r`

   > 4.4.19-1.el7.elrepo.x86_64
- Check ndpi modules is loaded: `lsmod | grep xt_ndpi | head -n1`

   > xt_ndpi               491520  58

*Test 2*
- Open the "Firewall rules" page
- Create a rule which block a protocol  (eg. facebook) using DPI
- Check the traffic is blocked

*Test 3*
- Configure a machine with at least 2 providers
- Create a rule which divert a protocol to a specific provider using DPI
- Check the traffic is routed to the specific provider

**Comment by dz00te** [comment]
Testing on a VM-KVM

> Test case 1: installation
>Install nethserver-ndpi
>Reboot the machine
>Check the elrepo kernel is loaded: uname -r
ok

>Check ndpi modules is loaded: lsmod | grep xt_ndpi | head -n1
>xt_ndpi 491520 58
module not loaded, but installed (in /lib/modules/4.4.19-1.el7.elrepo.x86_64/extra/xt_ndpi/xt_ndpi.ko)

**Comment by gsanchietti** [comment]
@dz00te  can you also try with this commands?

-  `grep ndpi /etc/shorewall/modules `
    Expected output:

    > loadmodule xt_ndpi

- `grep ndpi /etc/shorewall/shorewall.conf`
   Expected output:

   > MODULESDIR=+extra/xt_ndpi

**Comment by dz00te** [comment]
> grep ndpi /etc/shorewall/modules

```
# grep ndpi /etc/shorewall/modules
grep: /etc/shorewall/modules: No such file or directory
```

> grep ndpi /etc/shorewall/shorewall.conf

```
# grep ndpi /etc/shorewall/shorewall.conf
MODULESDIR=+extra/xt_ndpi
```

**Comment by gsanchietti** [comment]
I forgot to mention you should install latest firewall-base packages from testing repo. I just updated the comment with the test cases.

**Comment by gsanchietti** [comment]
Updated firewall rpms:
- nethserver-firewall-base-3.0.4-1.11.gce6bd99.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.0.4-1.11.gce6bd99.ns7.noarch.rpm

**Comment by dz00te** [comment]
Test case 1: installation
install ok, nothing relevant in logs
```
# uname -r
4.4.19-1.el7.elrepo.x86_64

```
```
# lsmod | grep xt_ndpi | head -n1
xt_ndpi               491520  0

```

Test 2
• Open the "Firewall rules" page
• Create a rule which block a protocol (eg. facebook) using DPI
• Check the traffic is blocked

uuuuuuu i can block facebook and apple :)

note: while selecting the service protocol for the new rule maybe a search is not enough... i mean it would be nice to have the opportunities to navigate thru the 221 result to know which protocol we can block... 

Test 3
i didn't have 2 providers....
probably i can simulate it but i need some time...

**Comment by gsanchietti** [comment]
Updated firewall packages with all icons (thanks to @AleRossini):
- nethserver-firewall-base-3.0.4-1.13.g0109cd1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.0.4-1.13.g0109cd1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
- kmod-xt_ndpi-1.0.0-1.ns7.x86_64.rpm
- nethserver-ndpi-1.0.0-1.ns7.noarch.rpm
- nethserver-firewall-base-3.1.0-1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.0-1.ns7.noarch.rpm
