### ISSUE TITLE
Failure on empty group creation

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5105]
**Steps to reproduce**
- Create a group with no members at all

In ``/var/log/messages``:

<pre>
Sep 12 15:31:56 vm5 esmith::event[6752]: Event: group-create mygroup1
Sep 12 15:31:56 vm5 esmith::event[6752]: Added group mygroup1
Sep 12 15:31:57 vm5 esmith::event[6752]: ERROR(exception): Failed to add members "" to group "mygroup1" - Unable to find "". Operation cancelled.
Sep 12 15:31:57 vm5 esmith::event[6752]:  File "/usr/lib64/python2.7/site-packages/samba/netcmd/group.py", line 227, in run
Sep 12 15:31:57 vm5 esmith::event[6752]:    add_members_operation=True)
Sep 12 15:31:57 vm5 esmith::event[6752]:  File "/usr/lib64/python2.7/site-packages/samba/samdb.py", line 274, in add_remove_group_members
Sep 12 15:31:57 vm5 esmith::event[6752]:    raise Exception('Unable to find "%s". Operation cancelled.' % member)
Sep 12 15:31:57 vm5 esmith::event[6752]: [ERROR] Failed to add members to group mygroup1
Sep 12 15:31:57 vm5 esmith::event[6752]: Action: /etc/e-smith/events/group-create/S40nethserver-dc-group-create FAILED: 3 [1.141383]
Sep 12 15:31:57 vm5 esmith::event[6752]: Action: /etc/e-smith/events/group-create/S90nethserver-sssd-clear-cache SUCCESS [0.222559]
Sep 12 15:31:57 vm5 esmith::event[6752]: Event: group-create FAILED
</pre>

**Components**
nethserver-dc-1.0.3-1.ns7.x86_64

Thanks to @alepolidori for reporting it:
http://community.nethserver.org/t/error-creating-empy-group-with-nethserver-dc/4349

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.0.3-1.1.g70d2187.ns7.x86_64.rpm

**Comment by alepolidori** [comment]
It works ! thx @DavidePrincipi 

Output:

```
Sep 12 16:20:11 ns7beta2-1 esmith::event[10903]: Event: group-create groupone
Sep 12 16:20:13 ns7beta2-1 esmith::event[10903]: Added group groupone
Sep 12 16:20:13 ns7beta2-1 esmith::event[10903]: Action: /etc/e-smith/events/group-create/S40nethserver-dc-group-create SUCCESS [1.305823]
Sep 12 16:20:13 ns7beta2-1 esmith::event[10903]: Action: /etc/e-smith/events/group-create/S90nethserver-sssd-clear-cache SUCCESS [0.26607]
Sep 12 16:20:13 ns7beta2-1 esmith::event[10903]: Event: group-create SUCCESS
```

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-dc-1.0.4-1.ns7.x86_64.rpm

**Comment by alefattorini** [comment]
Tested from @gg_jr and @nsflatspin
