### ISSUE TITLE
Lucene IMAP Full Text Search

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5106]
The upstream ``dovecot`` package provides the Lucene-based FTS (Full Text Search) plugin. We can enable it by default on ns7.

**Comment by DavidePrincipi** [comment]
**TEST CASE**

After upgrading to the modified version the new feature must be enabled by default. For a performance comparison I suggest testing the modified version on a big mailbox.

* check the new config DB prop ``dovecot/FtsLuceneStatus`` is ``enabled``
* run an IMAP session, where two "search text" commands are executed. The first run takes a lot of time to build the index. The second run is very fast. 

<pre>
# nc -C localhost 143
* OK [...] Dovecot ready.
A LOGIN username password
A OK [CAPABILITY...] Logged in
C SELECT INBOX
* FLAGS ([...])
* OK [PERMANENTFLAGS ([...] \*)] Flags permitted.
* 3031 EXISTS
* 0 RECENT
* OK [...]
C OK [READ-WRITE] Select completed (0.086 secs).
B SEARCH TEXT nethserver
* OK Indexed 32% of the mailbox, ETA 0:20
* OK Indexed 69% of the mailbox, ETA 0:08
* OK Mailbox indexing finished
* SEARCH 20 26 27 28 29 36 42 43 [...] 3014
B OK Search completed (27.571 secs).
B SEARCH TEXT nethserver
* SEARCH 20 26 27 28 29 36 42 43 [...] 3014
D OK Search completed (0.000 secs).
</pre>

In nethserver-testing:
nethserver-mail-server-1.10.1-1.4.g92a12d0.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Indexes are generated as soon the search is fired, but only if the mailbox contains at least one message.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.2-1.ns7.noarch.rpm
