### ISSUE TITLE
restore-data interface: select from which backup file restore

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5108]
At the moment, files shown in interface are only from last backup.
User should be able to select from which backup files should be restored and see from interface files that are from the selected backup.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-restore-data-1.1.1-1.2.g7230cfb.ns7.noarch.rpm

*Test case*
- Configure a backup-data and execute it
- Try to restore a file from the web interface
- Move the date forward (at least one day)
- Execute the backup
- Try to restore a file from the latest and the oldest backup

**Comment by gsanchietti** [comment]
Released:
- nethserver-restore-data-1.2.0-1.ns7.noarch.rpm
