### ISSUE TITLE
Unhandled USB ethernet plug events

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5109]
The system doesn't create a new record inside the `networks` db when a USB ethernet is connected.

*Steps to reproduce*
- Attach a USB ethernet adapter to the system

*Expected behavior*
- The new ethernet interface should be displayed inside the "Network" page

*Actual behavior*
- The new ethernet device doesn't appear

*Workaround*
Execute:

    systemctl start nethserver-config-network.service

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-base-3.0.7-1.2.gadd7067.ns7.noarch.rpm

* Test case*
- Plug an USB ethernet adapter
- The new ethernet interface must be listed inside the 'Network' page

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-base-3.0.8-1.ns7.noarch.rpm
