### ISSUE TITLE
Nsdc domain join fails with long hostname

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5110]
**Steps to reproduce**

* Set a long system name (> 10 chars)
* Install and configure nethserver-dc 
* Start nsdc 

sssd fails to join the realm with the following errors in ``/var/log/messages``:

<pre>
Sep 15 16:48:32 plantaserver2 realmd: Enter Administrator's password:gss_init_sec_context failed with [Unspecified GSS failure.  Minor code may provide more information: Server not found in Kerberos database]
Sep 15 16:48:32 plantaserver2 realmd: kinit succeeded but ads_sasl_spnego_gensec_bind(KRB5) failed: An internal error occurred.
Sep 15 16:48:32 plantaserver2 realmd: Failed to join domain: failed to connect to AD: An internal error occurred.
</pre>

**Components**
nethserver-dc-1.0.4-1.ns7.x86_64.rpm

See also the community discussion:
http://community.nethserver.org/t/cant-get-samba-account-provider-work/4414

Thanks to Auto_Bitacora and @nsflatspin for help on finding and reproducing this bug!

**Comment by DavidePrincipi** [comment]
More info from Red Hat:
https://bugzilla.redhat.com/show_bug.cgi?id=1001667

I want to highlight this link I found there:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724220(v=vs.85).aspx?ppud=4

> The NetBIOS name is the OEM representation of the DNS host name up to MAX_COMPUTERNAME_LENGTH characters. If you set a DNS host name of more than MAX_COMPUTERNAME_LENGTH characters, the NetBIOS name is set to a truncated version of the DNS host name. Otherwise, the whole DNS host name is translated into the OEM NetBIOS name. Warning: If you modify the NetBIOS name so that it is not a truncated mapping of the DNS name, you will break applications that use functions such as DnsHostnameToComputerName which rely on this convention.

**Comment by DavidePrincipi** [comment]
**TEST CASE**

* Check the bug is not reproducible (for instance SystemName=vm5longname)
* Check there is no regression for short names (for instance SystemName=vm5)
* Check very long names work (for instance SystemName=vm5longnamemorethan15)

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.0.4-1.1.gcf23fbd.ns7.x86_64.rpm
nethserver-base-3.0.7-1.3.gab2608c.ns7.noarch.rpm
nethserver-sssd-1.0.3-1.3.g3e3e3b9.ns7.noarch.rpm

**Comment by nsflatspin** [comment]
Will test them as soon as possible, but later this day.

**Comment by nsflatspin** [comment]
Did the testinstallation without issue.

See also community discussion:
http://community.nethserver.org/t/cant-get-samba-account-provider-work/4414/20

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-dc-1.0.5-1.ns7.x86_64.rpm
nethserver-sssd-1.0.4-1.ns7.noarch.rpm
nethserver-base-3.0.8-1.ns7.noarch.rpm
