### ISSUE TITLE
Shared folder listing denied with special ACL

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5111]
**Steps to reproduce**

* Create ``shfo2`` Shared Folder, grant write access to owning group (i.e. ``assistenza@...``)
* Set RW ACL for an user that **is not** member of the owning group (i.e. ``davidep@...``)

<pre>
$ smbclient -U davidep%Nethesis,1234 -W ADNETHESIS  //192.168.122.5/shfo2 
Domain=[ADNETHESIS] OS=[Windows 6.1] Server=[Samba 4.2.10]
smb: \> ls
NT_STATUS_ACCESS_DENIED listing \*
</pre>

Additional info:

<pre>
    # getfacl /var/lib/nethserver/ibay/shfo2
getfacl: Removing leading '/' from absolute path names
# file: var/lib/nethserver/ibay/shfo2
# owner: administrator@adnethesis.it
# group: assistenza@adnethesis.it
# flags: -s-
user::rwx
user:davidep@adnethesis.it:rw-
group::rwx
mask::rwx
other::---
default:user::rwx
default:user:davidep@adnethesis.it:rw-
default:group::rwx
default:mask::rwx
default:other::---
</pre>

Please note  ``default:user:davidep@adnethesis.it:rw-`` is missing the executable bit!

**Components**
nethserver-ibays-3.0.0-1.ns7.noarch
nethserver-samba-2.0.1-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
Workaround: fix the ACL with ``setfacl``. Enable the executable bit on the shared folder:

    setfacl -m user:davidep@adnethesis.it:rwx /var/lib/nethserver/ibay/shfo2

**Comment by DavidePrincipi** [comment]
**TEST CASE**

Check Shared Folders ACLs are applied consistently on create/modify/delete and **reset permissions**.

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-ibays-3.0.0-1.1.gc24059b.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
- nethserver-ibays-3.0.1-1.ns7.noarch.rpm
