### ISSUE TITLE
Wrong port range separator in webvirtmgr-console 

### ISSUE THREAD

**Issue by nsflatspin** [NethServer/dev#5112]
**Steps to reproduce**
Install webvirtmgr from softwarecenter and look at config show webvirtmgr-console
After installation the portrange is TCPPorts=5900-5950,16509,6080, so the webvirtmgr-console is blocked

In ``/var/log/messages``:

<pre>
Sep 21 13:11:01 ns7test logger: ERROR:Shorewall restart failed
Sep 21 13:11:01 ns7test esmith::event[19534]: [ERROR] Shorewall restart: ERROR: The separator for a port range is ':', not '-' (5900-5950) /etc/shorewall/rules (line 191)
Sep 21 13:11:01 ns7test esmith::event[19534]: Action: /etc/e-smith/events/nethserver-firewall-base-save/S89nethserver-shorewall-restart FAILED: 1 [1.394856]
</pre>

**Package**
nethserver-webvirtmgr-1.1.0-1.ns7

**Workaround**

seperator for portrange in fw rule should be : not -

<pre>
config setprop webvirtmgr-console TCPPorts 5900:5950,16509,6080
expand-template /etc/shorewall/rules
systemctl restart shorewall.service
</pre>

refer to http://community.nethserver.org/t/firewall-webvirtmgr-console-error/4438

**Comment by DavidePrincipi** [comment]
Is there any relevant error message in ``/var/log/messages``?

**Comment by nsflatspin** [comment]
Sep 21 13:11:00 ns7test esmith::event[19534]: Action: /etc/e-smith/events/actions/generic_template_expand SUCCESS [0.378853]
Sep 21 13:11:00 ns7test systemd: Reloading.
Sep 21 13:11:00 ns7test systemd: Configuration file /usr/lib/systemd/system/auditd.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Sep 21 13:11:01 ns7test logger: ERROR:Shorewall restart failed
Sep 21 13:11:01 ns7test esmith::event[19534]: [ERROR] Shorewall restart:    ERROR: The separator for a port range is ':', not '-' (5900-5950) /etc/shorewall/rules (line 191)
Sep 21 13:11:01 ns7test esmith::event[19534]: Action: /etc/e-smith/events/nethserver-firewall-base-save/S89nethserver-shorewall-restart FAILED: 1 [1.394856]

**Comment by gsanchietti** [comment]
In nethforge-testing:
- nethserver-webvirtmgr-1.1.0-1.1.g60ab996.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Already tested:

```
config setprop webvirtmgr-console status enabled
signal-event firewall-adjust

[root@test ~]# shorewall show | grep webvirtmgr-console 
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpts:5900:5950 /* webvirtmgr-console */
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:16509 /* webvirtmgr-console */
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:6080 /* webvirtmgr-console */

```

**Comment by gsanchietti** [comment]
Released:
- nethserver-webvirtmgr-1.1.1-1.ns7.noarch.rpm
