### ISSUE TITLE
broken plugin link on nethserver-openvpn

### ISSUE THREAD

**Issue by dnutan** [NethServer/dev#5115]
**System Version:**
NethServer release 7.2.1511 (beta2)

**Problem:**
>PLUGIN_INIT: could not load plugin shared object /usr/lib64/openvpn/plugin/lib/openvpn-auth-pam.so: /usr/lib64/openvpn/plugin/lib/openvpn-auth-pam.so: cannot open shared object file: No such file or directory: No such file or directory (errno=2)

**Steps to reproduce:**

1. Install nethserver-openvpn: `yum -y install @nethserver-openvpn`
2. Configure OpenVPN Roadwarrior with  _Username, password and certificate_

**Relevant components:**
`openvpn-2.3.12-1.el7.x86_64` (from epel)
`nethserver-openvpn-1.4.0-1.ns7.noarch`

**Workaround:**
Temporary workaround (create a symbolic link):

    mkdir -p /usr/lib64/openvpn/plugin/lib
    ln -s /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so /usr/lib64/openvpn/plugin/lib/openvpn-auth-pam.so 

Suggested workaround:
https://github.com/NethServer/nethserver-openvpn/pull/7/commits/d88f3661d6293915736169b4c6769821962f4374

Thanks to GG_jr for [reporting it](http://community.nethserver.org/t/openvpn-service-not-started-on-ns-7b2/4487).

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-openvpn-1.4.0-1.1.g082653d.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducible

**Comment by dz00te** [comment]
VM KVM - Clean install of Nethserver 7b2 fully updated
Package Installed:  openvpn

*Install Updated Package*
`yum --enablerepo=nethserver-testing install nethserver-openvpn-1.4.0-1.1.g082653d.ns7.noarch`

*Test Results after update*
all OK. no more errors when selecting Authentication Mode: Username, password and certificate
openvpn@host-to-net.service is up and running

**Comment by gsanchietti** [comment]
Released:
- nethserver-openvpn-1.4.1-1.ns7.noarch.rpm
