### ISSUE TITLE
Controller provisioning fails with long domain name

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5116]
**Steps to reproduce**

* Set a long domain name (> 15 chars), like ``dpnetverylongdomainname.nethesis.it``
* Install nethserver-dc and configure the Samba  AD Domain Controller
* The DC start procedure hangs indefinitely

In ``journalctl -M nsdc``

<pre>
Sep 26 18:03:19 nsdc-vm5.dpnetverylongdomainname.nethesis.it samba-tool[24]: ERROR(<class 'samba.provision.InvalidNetbiosName'>): uncaught exception - The name ''DPNETVERYLONGDOMAINNAME'' is not a valid NetBIOS name
</pre>

**Packages**
nethserver-dc-1.0.5-1.ns7.x86_64

**See also**
http://community.nethserver.org/t/controller-provisioning-fails-with-long-domain-name/4484

Thanks to @nsflatspin for pointing it out!!

**Comment by DavidePrincipi** [comment]
**Workaround**

Replace domain/workgroup value with a truncated NetBIOS name:

* Edit ``/var/lib/machines/nsdc/etc/sysconfig/samba-provision``
* Edit ``/etc/samba/smb.conf``
* Remove ``/etc/samba/smb.conf`` inside the nsdc container
* Restart nsdc container
* ...

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.4-1.3.g4c72465.ns7.noarch.rpm
nethserver-dc-1.0.5-1.1.g083ca83.ns7.x86_64.rpm
nethserver-dc-debuginfo-1.0.5-1.1.g083ca83.ns7.x86_64.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
* nethserver-dc-1.0.5-1.2.gd1b3790.ns7.x86_64.rpm
* nethserver-dc-debuginfo-1.0.5-1.2.gd1b3790.ns7.x86_64.rpm
* (nethserver-sssd-1.0.4-1.3.g4c72465.ns7.noarch.rpm)

**Comment by nsflatspin** [comment]
Installed nethserver-dc-1.0.5-1.2.gd1b3790.ns7 and nethserver-sssd-1.0.4-1.3.g4c72465.ns7.
Tested creation of users and groups with long domain. No errors in messages.log. No error message on GUI.
see commuity disscusion 
http://community.nethserver.org/t/controller-provisioning-fails-with-long-domain-name/4484/18
Can I do more tests or is this issue solved?

**Comment by gsanchietti** [comment]
Before release add the following:
- inside the Active Directory page, add a read-only field  which displays the AD domain
- a note inside the administrator manual explaining the length limit (15 characters) of domain and system name

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
* nethserver-dc-1.0.6-1.ns7.x86_64.rpm
* nethserver-dc-debuginfo-1.0.6-1.ns7.x86_64.rpm
* nethserver-sssd-1.0.5-1.ns7.noarch.rpm
