### ISSUE TITLE
Bad event for expand-template in restore data

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#5118]
The `templates2events` action of `/etc/sudoers` is linked on `pre-backup-data` instead of `nethserver-restore-data-update` [Ref](https://github.com/NethServer/nethserver-restore-data/blob/master/createlinks#L32).

The `/etc/sudoers` file must be expanded only on update event, not on each `pre-backup-data` events.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-restore-data-1.0.0-1.4.g434a271.ns7.noarch.rpm

*Test case 1*
- Check the file `/etc/sudoers` is not expanded in `nethserver-restore-data-update`

*Test case 2*
- Configure a backup data
- Try to restore a file from the web interface

**Comment by gsanchietti** [comment]
The package correctly restore files from the web interface using the new sudoers configuration `/etc/sudoers.d/40_nethserver_restore_data`.

**Comment by gsanchietti** [comment]
Released:
- nethserver-restore-data-1.2.1-1.ns7.noarch.rpm
