### ISSUE TITLE
OpenVPN: static route not pushed to clients

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5120]
*Steps to reproduce*
- Install and enable OpenVPN server
- Add add a static route
- Download the .ovpn file into the client and start a new vpn

*Expected behavior*
- The route must be pushed to the client

*Actual behavior*
- The route is not pushed to the client

The warning is:

> WARNING in /etc/e-smith/templates//etc/openvpn/host-to-net.conf/40route: Use of uninitialized value $netmask in concatenation (.) or string at /etc/e-smith/templates//etc/openvpn/host-to-net.conf/40route line 50, <FH> line 1.
> WARNING: Template processing succeeded for //etc/openvpn/host-to-net.conf: 1 fragment generated warnings at /etc/e-smith/events/actions/generic_template_expand line 64.

Thanks to @dz00te !
Reference: http://community.nethserver.org/t/openvpn-route-problem-on-ns7b2/4525

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-openvpn-1.4.1-1.2.g944566a.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducible

**Comment by dz00te** [comment]
*System and  Package Version installed*
VM KVM - Clean install of Nethserver 7b2 fully updated
Package Installed:  OpenVPN

*Install Updated Package*
yum --enablerepo=nethserver-testing install nethserver-openvpn-1.4.1-1.2.g944566a.ns7.noarch

*Test Results after update*
all OK. the static route is correctly written in the config and accepted from the client

**Comment by gsanchietti** [comment]
Released:
- nethserver-openvpn-1.4.2-1.ns7.noarch.rpm
