### ISSUE TITLE
Web filter: can't create profiles involving users

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5121]
SquidGuard doesn't correctly handle users from SSSD, since the configuration file doesn't support the new format `<user>@<domain>`.

*Steps to reproduce*
- Install nethserver-dc and create a new user named "user1"
- Enable the proxy in authenticated mode
- Create a filter named "bad" which blocks everything
- Create a profile which involves "user1" and "bad" profile

*Expected behavior*
- The navigation must be blocked

*Actual behavior*
- The user can access all sites

This behavior can be debugged using the following command:
```
echo "http://www.example.com 10.0.0.1/- - GET" | squidGuard -c /etc/squid/squidGuard.conf  -d
```
Raised error:

> 2016-10-04 09:41:19 [31522] syntax error in configfile /etc/squid/squidGuard.conf line 413

Reference:
- http://community.nethserver.org/t/web-content-filter-fails-when-using-a-profile-with-a-user-or-group/4573
- http://community.nethserver.org/t/squidguards-group-based-profile-creation-broke-squid-and-shared-folders-permissions/4444

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-squidguard-1.5.0-1.2.g4a5b778.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducible

**Comment by chemnic** [comment]
I can confirm the fix is working. After creating a profile with a user Web filter is working.

I will keep testing this to see if there is some problem.

Thank you.

**Comment by gsanchietti** [comment]
Released:
- nethserver-squidguard-1.5.1-1.ns7.noarch.rpm

Thanks @chemnic for all the work!
