### ISSUE TITLE
Display NetBIOS domain name on DC configuration page

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5124]
(Split from @gsanchietti on #5116)
- inside the page to join Active Directory, add a read-only field  which displays the AD domain
- add a note inside the administrator manual explaining the length limit (15 characters) of [EDIT] ~~domain~~ [leftmost DNS domain part](https://technet.microsoft.com/en-us/library/cc961556.aspx) and system name

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-sssd-1.0.5-1.2.g394f818.ns7.noarch.rpm

*Test case 1*
- Install a clean machine and update nethserver-sssd
- Open the "Users and groups" page
- Select "Active Directory"
- Check the page displays the domain NetBIOS name

*Test case 2*
- Install a clean machine and update nethserver-sssd
- Execute:
```
config set samba service Workgroup test123
```
- Open the "Users and groups" page
- Select "Active Directory"
- Check the page displays "test123" in the domain NetBIOS name field

**Comment by DavidePrincipi** [comment]
Maybe it wasn't clear but...

the default NetBIOS domain name is not the truncated DNS domain suffix, but only the "leftmost" part.

> When you create a new domain during the Active Directory installation procedure, the system provides a default NetBIOS domain name that matches the leftmost label in the DNS domain name up to the first 15 bytes (NetBIOS names have a limit of 15 bytes).

https://technet.microsoft.com/en-us/library/cc961556.aspx

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
* nethserver-dc-1.0.6-1.2.gf7ecfd8.ns7.x86_64.rpm
* nethserver-dc-debuginfo-1.0.6-1.2.gf7ecfd8.ns7.x86_64.rpm
* nethserver-sssd-1.0.5-1.7.g5f547a7.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
* nethserver-sssd-1.0.6-1.ns7.noarch.rpm
* nethserver-dc-1.0.7-1.ns7.x86_64.rpm
* nethserver-dc-debuginfo-1.0.7-1.ns7.x86_64.rpm
