### ISSUE TITLE
repository of dovecot-antispam out of date

### ISSUE THREAD

**Issue by markVnl** [NethServer/dev#5126]
Could you  update the repository of dovecot-antispam, it quite out of date.
I the future I would like to make a PR with a small change in the spec file:

```
%{_mandir}/man7/dovecot-antispam.7*
-/usr/lib64/dovecot/lib90_antispam_plugin.so
+%{_libdir}/dovecot/lib90_antispam_plugin.so
```

This way it can be built on both 32 and 64 bit architectures.
(IMO this the proper way to define the default lib directory)

**Comment by gsanchietti** [comment]
I will gladly accept the pull request.

I checked also dovecot-antispam upstream repository and I don't think we need to update our package.
The package is built against 7f94cc6b4d8e commit, with a revert patch for the commit 5e8351bcfb29.

After those ones there isn't any other significant commit. All changes are about the build, but @DavidePrincipi has already correctly rebuilt the package for dovecot 2.2.

**Comment by DavidePrincipi** [comment]
I agree, with @gsanchietti. The PR idea is good (I guess it would be useful for alternative arches). Please go on with it!

Anyway I see no reason to rebuild the RPM. 

Feel free to reopen this issue if new elements come into play!
