### ISSUE TITLE
Unable to make FTP connection with virtualhost

### ISSUE THREAD

**Issue by markVnl** [NethServer/dev#5127]
Tested with different FTP clients (WinSCP, windows explorer and Fillezilla client) on a windows 10 machine. Had one go from a Linux machine (Arch Linux) trying to mount a FTP site with CurlFtpFS.

Initial connection succeeds, after this FTP clients complain about to be unable to retrieve a file list.

further info see:
http://community.nethserver.org/t/cant-ftp-into-virtualhost-ns7b2/4607/4

Probable cause firewall/shorewall 

(this is solely a remainder)

**Comment by gsanchietti** [comment]
The bug has been introduced in this commit: https://github.com/NethServer/nethserver-firewall-base/commit/d9f25843074681d8fc2ed0902d8c880747b9b082
To fix the bug we need to explictly load the new FTP helper.

See official Shorewall documentation: http://www.shorewall.org/FTP.html

**Comment by gsanchietti** [comment]
The same fix must applied to `nethserver-hylafax` package:
- add ftp helper with for port 4559 if hfaxd is enabled
- remove configuration for conntrack module

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-vsftpd-1.1.0-1.3.gf3da977.ns7.noarch.rpm
- nethserver-hylafax-1.2.0-1.2.g8b20bfb.ns7.noarch.rpm

*Test case 1*
- Install nethserver-vsftp from testing repository
- Enable the vsftpd server from the web interface
- Try to upload a file using an FTP client (eg. `ncftp`)

*Test case 2*
- Install nethserver-directory, create a group named `faxmaster`
- Create a user and add it to `faxmaster` group
- Install nethserver-hylafax from testing repository
- Try to send a fax with an Hylafax client (Java client for Linux and Windows http://download.yajhfc.de/releases/yajhfc-0_6_0.jar)

You can also verify that both helper are loaded using this command:
```
iptables -nvL -t raw
```

**Comment by gsanchietti** [comment]
If  `AUTOHELPERS` is set to `No`, shorewall blocks many protocols by default:

> root@test shorewall]# iptables -t raw -nvL | grep helper | awk '{print $14}' | sort | uniq
> amanda
> ftp
> helper
> irc
> netbios-ns
> pptp
> Q.931
> RAS
> sane
> sip
> snmp
> tftp

See also: http://community.nethserver.org/t/shorewall-blocking-vpn-connections/4672

Proposed solution:
- change default for `AUTOHELPERS` to `Yes`
- revert patch for `nethserver-vsftpd`
- change syntax inside the patch for `nethserver-hylafax`

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-firewall-base-3.1.1-1.1.g21ebba2.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.1-1.1.g21ebba2.ns7.noarch.rpm
- nethserver-hylafax-1.2.0-1.3.g190d6a1.ns7.noarch.rpm

`nethserver-vsftpd` is unchanged, download it from nethserver-updates:
- nethserver-vsftpd-1.1.0-1.ns7.noarch.rpm

*Test case 1*
- Install nethserver-vsftp from testing repository
- Enable the vsftpd server from the web interface
- Try to upload a file using an FTP client (eg. `ncftp`)

*Test case 2*
- Install nethserver-directory, create a group named `faxmaster`
- Create a user and add it to `faxmaster` group
- Install nethserver-hylafax from testing repository
- Try to send a fax with an Hylafax client (Java client for Linux and Windows http://download.yajhfc.de/releases/yajhfc-0_6_0.jar)

You can also verify that both helper are loaded using this command:
```
iptables -nvL -t raw
```

**Comment by markVnl** [comment]
yum --enablerepo=nethserver-testing update nethserver-firewall-base nethserver-firewall-base-ui

```
=====================================================================================================================
 Package                             Arch           Version                         Repository                  Size
=====================================================================================================================
Updating:
 nethserver-firewall-base            noarch         3.1.1-1.1.g21ebba2.ns7          nethserver-testing          74 k
 nethserver-firewall-base-ui         noarch         3.1.1-1.1.g21ebba2.ns7          nethserver-testing          51 k

Transaction Summary
=====================================================================================================================
```

Testcase 1

FTP in to existing virtualhost with FileZilla,  (Filezilla) log:
```
Status:	Resolving address of mirror.framassa.org
Status:	Connecting to 10.0.0.130:21...
Status:	Connection established, waiting for welcome message...
Status:	Insecure server, it does not support FTP over TLS.
Status:	Logged in
Status:	Retrieving directory listing...
Status:	Calculating timezone offset of server...
Status:	Timezone offset of server is 0 seconds.
Status:	Directory listing of "/" successful
```

Works like a charm!

**Comment by gsanchietti** [comment]
Released:
- nethserver-hylafax-1.2.1-1.ns7.noarch.rpm
- nethserver-firewall-base-3.1.2-1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.2-1.ns7.noarch.rpm
