### ISSUE TITLE
Collectd: add memory plugin

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5128]
Currently collectd is missing the memory plugin.

Add the memory plugin to default configuration.

Reference:
http://community.nethserver.org/t/ns7b2-collectd-memory-plugin-removed-ref-3414/4613/10:

Thanks to @markVnl for pointing it out!

**Comment by gsanchietti** [comment]
In nethserver-testing:
- 

*Test case*
- Install the new package along with nethserver-cgp
- Wait a couple of minutes, and check the memory graph from the web interface

**Comment by markVnl** [comment]
Thanks!

Installed from testing repository, works like a charm!

**Comment by gsanchietti** [comment]
Released:
- nethserver-collectd-3.0.2-1.ns7.noarch.rpm
