### ISSUE TITLE
Root's password change fails with OpenLDAP provider

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5129]
**Steps to reproduce**

* Install OpenLDAP account provider
* Change root's password from server manager

In ``/var/log/messages``:

<pre>
Oct 13 16:02:13 vm8 esmith::event[1194]: Event: password-modify root /tmp/ng-HO45MD
Oct 13 16:02:13 vm8 esmith::event[1194]: Changing password for user root.
Oct 13 16:02:13 vm8 esmith::event[1194]: passwd: all authentication tokens updated successfully.
Oct 13 16:02:13 vm8 esmith::event[1194]: Action: /etc/e-smith/events/password-modify/S25password-set SUCCESS [0.201298]
Oct 13 16:02:13 vm8 esmith::event[1194]: [WARN] Skipping user root, it doesn't belong to a domain.
Oct 13 16:02:13 vm8 esmith::event[1194]: Action: /etc/e-smith/events/password-modify/S30nethserver-directory-password-set SUCCESS [0.002451]
Oct 13 16:02:14 vm8 esmith::event[1194]: [ERROR] Account `root` not found.
Oct 13 16:02:14 vm8 esmith::event[1194]: Action: /etc/e-smith/events/password-modify/S40nethserver-directory-user-unlock FAILED: 255 [0.333066]
Oct 13 16:02:14 vm8 esmith::event[1194]: Action: /etc/e-smith/events/password-modify/S90password-cleanup SUCCESS [0.20764]
Oct 13 16:02:14 vm8 esmith::event[1194]: Event: password-modify FAILED
</pre>

**Components**

* nethserver-directory-3.0.1-1.ns7.noarch
* ~~nethserver-base-3.0.9-1.ns7.noarch~~

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-directory-3.0.1-1.2.gfd37800.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducible

**Comment by gsanchietti** [comment]
Root password changed:

> Oct 14 10:56:08 test esmith::event[7808]: Event: password-modify root /tmp/ng-OMDQ3c
> Oct 14 10:56:08 test esmith::event[7808]: Changing password for user root.
> Oct 14 10:56:08 test esmith::event[7808]: passwd: all authentication tokens updated successfully.
> Oct 14 10:56:08 test esmith::event[7808]: Action: /etc/e-smith/events/password-modify/S25password-set SUCCESS [0.054026]
> Oct 14 10:56:08 test esmith::event[7808]: [WARN] Skipping user root, it doesn't belong to a domain.
> Oct 14 10:56:08 test esmith::event[7808]: Action: /etc/e-smith/events/password-modify/S30nethserver-directory-password-set SUCCESS [0.00207]
> Oct 14 10:56:08 test dbus[611]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service'
> Oct 14 10:56:08 test dbus-daemon: dbus[611]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service'
> Oct 14 10:56:08 test systemd: Starting Time & Date Service...
> Oct 14 10:56:08 test dbus[611]: [system] Successfully activated service 'org.freedesktop.timedate1'
> Oct 14 10:56:08 test dbus-daemon: dbus[611]: [system] Successfully activated service 'org.freedesktop.timedate1'
> Oct 14 10:56:08 test systemd: Started Time & Date Service.
> Oct 14 10:56:08 test esmith::event[7808]: Action: /etc/e-smith/events/password-modify/S30nethserver-nethvoice-htpasswd SUCCESS [0.19277]
> Oct 14 10:56:08 test esmith::event[7808]: [WARN] Skipping user root, it doesn't belong to a domain.
> Oct 14 10:56:08 test esmith::event[7808]: Action: /etc/e-smith/events/password-modify/S40nethserver-directory-user-unlock SUCCESS [0.037764]
> Oct 14 10:56:08 test esmith::event[7808]: Action: /etc/e-smith/events/password-modify/S90password-cleanup SUCCESS [0.053249]
> Oct 14 10:56:08 test esmith::event[7808]: Event: password-modify SUCCESS

Also, using patched nethserver-base, the password is not displayed in clear text inside the secure log:

> Oct 14 10:56:08 test sudo:  srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/validate password-strength Users /tmp/ng-OMDQ3c

**Comment by markVnl** [comment]
installed updates : see #5130

after changing root passwd in UI, sucure log:
`Oct 17 14:37:45 sogoneth passwd: pam_unix(passwd:chauthtok): password changed for root`

`exit` (ssh)
ssh : log in with new password **OKE**

```
passwd
Changing password for user root.
New password:
```

logo out UI and log in with (2nd) new passwd **OKE**

Works just fine for me!

**Comment by gsanchietti** [comment]
Released:
- nethserver-directory-3.0.2-1.ns7.noarch.rpm
