### ISSUE TITLE
Clear-text password in /var/log/secure

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5130]
**Steps to reproduce**

* Log in as root to server-manager
* Change the root's password from UserProfile module

In ``/var/log/secure``
<pre>
ns7b2 sudo: srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/validate password-strength Users &lt;PasswInPlainText&gt;
</pre>

This happens also if a domain account provider is installed and root wants to change an other user's password, or an other user wants to change his own password.

**Components**

nethserver-base-3.0.9-1.ns7.noarch

Thanks to @markVnl for pointing this out!
http://community.nethserver.org/t/ns7b2-password-in-secure-log/4600

**Comment by DavidePrincipi** [comment]
See also #5129

**Comment by DavidePrincipi** [comment]
*QA NOTE*
As test case, check also the user creation when default password is set!

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
* nethserver-sssd-1.0.5-1.7.g5f547a7.ns7.noarch.rpm
* nethserver-base-3.0.9-1.4.gaff66bb.ns7.noarch.rpm

**Comment by fasttech** [comment]
yum --enablerepo=nethserver-testing update nethserver-base-3.0.9-1.ns7.noarch
then changed a users pwd in the gui logged in as root ...

Oct 14 10:30:04 server7c sudo:  srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/validate password-strength Users /tmp/ng-hKosak
Oct 14 10:30:31 server7c sudo:  srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/validate password-strength Users /tmp/ng-C6rEuS
Oct 14 10:30:32 server7c sudo:  srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/signal-event password-modify testnc@neth.test.local /tmp/ng-C6rEuS

then changed pwd for root

Oct 14 10:39:21 server7c sudo:  srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/validate password-strength Users /tmp/ng-4AoTsG
Oct 14 10:39:21 server7c sudo:  srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/pam-authenticate-pw
Oct 14 10:39:23 server7c sudo:  srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/signal-event password-modify root /tmp/ng-4AoTsG
Oct 14 10:39:23 server7c passwd: pam_unix(passwd:chauthtok): password changed for root

then reboot and changed the root pwd again

Oct 14 10:43:23 server7c sudo:  srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/validate password-strength Users /tmp/ng-i6NqkO
Oct 14 10:43:24 server7c sudo:  srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/pam-authenticate-pw
Oct 14 10:43:24 server7c sudo:  srvmgr : TTY=unknown ; PWD=/usr/share/nethesis/nethserver-manager ; USER=root ; COMMAND=/sbin/e-smith/signal-event password-modify root /tmp/ng-i6NqkO
Oct 14 10:43:24 server7c passwd: pam_unix(passwd:chauthtok): password changed for root

**Comment by DavidePrincipi** [comment]
Seems good, if nobody raise other issues we can mark this "verified"!

**Comment by markVnl** [comment]
yum --enablerepo=nethserver-testing update nethserver-sssd nethserver-directory nethserver-base 
 
```
=====================================================================================================================
 Package                        Arch             Version                          Repository                    Size
=====================================================================================================================
Updating:
 nethserver-base                noarch           3.0.9-1.4.gaff66bb.ns7           nethserver-testing           208 k
 nethserver-directory           noarch           3.0.1-1.2.gfd37800.ns7           nethserver-testing            47 k
 nethserver-sssd                noarch           1.0.5-1.7.g5f547a7.ns7           nethserver-testing            55 k

Transaction Summary
=====================================================================================================================
```


After creating new user no more passwords in secure log:

```
Oct 17 14:31:37 ... ; USER=root ; COMMAND=/sbin/e-smith/validate password-strength Users /tmp/ng-zhHSRR
Oct 17 14:31:37 ... ; USER=root ; COMMAND=/usr/libexec/nethserver/ldap-list-users
Oct 17 14:31:37 ... ; USER=root ; COMMAND=/sbin/e-smith/signal-event user-create sogo Sogo Test /usr/libexec/openssh/sftp-server
Oct 17 14:31:39 ... ; USER=root ; COMMAND=/usr/libexec/nethserver/ldap-list-groups
Oct 17 14:31:39 ... ; USER=root ; COMMAND=/sbin/e-smith/signal-event group-modify havak@havak.lan even sogo
Oct 17 14:31:40 ... ; USER=root ; COMMAND=/sbin/e-smith/signal-event password-policy-update sogo no
Oct 17 14:31:40 ... ; USER=root ; COMMAND=/sbin/e-smith/signal-event password-modify sogo@havak.lan /tmp/ng-zhHSRR
Oct 17 14:31:41 ... ; USER=root ; COMMAND=/usr/libexec/nethserver/ldap-list-groups
Oct 17 14:31:41 ... ; USER=root ; COMMAND=/usr/libexec/nethserver/ldap-list-users
Oct 17 14:31:54 ... ; USER=root ; COMMAND=/sbin/e-smith/logviewer -l
Oct 17 14:32:09 ... ; USER=root ; COMMAND=/sbin/e-smith/validate logfile /var/log/secure-20161016
Oct 17 14:32:09 ... ; USER=root ; COMMAND=/sbin/e-smith/logviewer /var/log/secure-20161016
Oct 17 14:32:25 ... ; USER=root ; COMMAND=/sbin/e-smith/logviewer -l
Oct 17 14:32:34 ... ; USER=root ; COMMAND=/sbin/e-smith/validate logfile /var/log/secure
Oct 17 14:32:34 ... ; USER=root ; COMMAND=/sbin/e-smith/logviewer /var/log/secure
```

after changing root passwd in UI, sucure log:
`Oct 17 14:37:45 sogoneth passwd: pam_unix(passwd:chauthtok): password changed for root`


`exit` (ssh) 
ssh : log in with new password OKE

```
passwd
Changing password for user root.
New password:
```

logo out UI and log in with (2nd) new passwd OKE

**Comment by gsanchietti** [comment]
Released:
- nethserver-base-3.0.10-1.ns7.noarch.rpm
