### ISSUE TITLE
XMPP over bosh does not work

### ISSUE THREAD

**Issue by alepolidori** [NethServer/dev#5131]
SO:
NethServer 7 Beta2
rpm:
ejabberd-16.01-0.x86_64
nethserver-ejabberd-1.1.1-1.ns7.noarch

Description:
connecting to `https://<SERVER_NAME>/http-bind` resulting in HTTP 500 Proxy error

Step to reproduce:
- curl -k -v https://192.168.5.197/http-bind

Error output
```
The proxy server could not handle the request
Reason: Error during SSL Handshake with remote server
```

**Comment by alepolidori** [comment]
In nethserver-testing:
- nethserver-ejabberd-1.1.1-1.2.g0a7d852.ns7.noarch.rpm

_Test case_

- curl -k -v https://192.168.5.197/http-bind (response must be 200)
- curl -k -v http://192.168.5.197/http-bind (response must be 200)

**Comment by gsanchietti** [comment]
It works as expected.

> [root@test ~]#  curl -svk https://192.168.5.246/http-bind -o /dev/null 2>&1 | grep HTTP
> > GET /http-bind HTTP/1.1
> < HTTP/1.1 200 OK
> 
> [root@test ~]#  curl -sv http://192.168.5.246/http-bind -o /dev/null 2>&1 | grep HTTP
> > GET /http-bind HTTP/1.1
> < HTTP/1.1 200 OK
>

**Comment by gsanchietti** [comment]
Released:
nethserver-ejabberd-1.1.2-1.ns7.noarch.rpm
