### ISSUE TITLE
Shared mailboxes default "0" element

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5132]
After installation of the Mail module, an initial element "0" is present on the "Shared mailboxes" page. It can't be deleted.

If a new shared mailbox is created, the "0" element disappears. When the last shared mailbox is deleted it appears again. 

**Steps to reproduce**

Just install Mail module

**Components**

nethserver-mail-server-1.10.2-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
It looks an UI-only problem

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.2-1.1.g68f3397.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
The web interface is fixed.

**Comment by gsanchietti** [comment]
Released:
- nethserver-mail-server-1.10.3-1.ns7.noarch.rpm
