### ISSUE TITLE
Alternative arch support for dovecot-antispam

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5133]
Use RPM macros in .spec file, to support alternative architectures on dovecot-antispam package.

Originally opened by @markVnl

See also:
- http://community.nethserver.org/t/update-dovecot-antispam-on-github/4632
- issue #5126

**Comment by DavidePrincipi** [comment]
In nethserver-testing:

* dovecot-antispam-0.0.49-3.3.gca425d9.ns7.x86_64.rpm
* dovecot-antispam-debuginfo-0.0.49-3.3.gca425d9.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
This is only a rebuild for an alternative architecture, no need to release it for x86_64.
Just marking as verified and closing.
