### ISSUE TITLE
Let's Encrypt: missing chain file

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5134]
When setting a Let's Encrypt (LE) certificate as server default, httpd and httpd-admin daemons do not use the chain file.
This can prevent a correct behavior in certain browsers.

*Steps to reproduce*
- Configure a server with all LE requirements
- Request a new LE certificate and set it as default
- Verify the certificate using an online tool ( https://sslanalyzer.comodoca.com, https://www.sslshopper.com/ssl-checker.html)

*Workaround*
Manually set the chain file:
```
config setprop pki ChainFile /etc/letsencrypt/live/`hostname`/chain.pem
signal-event certificate-update
```

Reference: https://letsencrypt.org/certificates/

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-base-3.0.10-1.2.g78528d5.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-base:
nethserver-base-3.0.11-1.ns7.noarch.rpm
