### ISSUE TITLE
Missing inline help in Password policy page

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5135]
**Steps to reproduce**

Server-manager

```
Security -> Password policies -> [Help]
```

> Not found
> Help document is not available!

Original post by @dnutan:
http://community.nethserver.org/t/try-out-nethserver-7-beta2/4347/14

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-sssd-1.0.6-1.13.gc532f66.ns7.noarch.rpm

**Comment by dnutan** [comment]
Inline help is shown correctly now.

**Comment by gsanchietti** [comment]
Wait for release until #5136 is ready.

**Comment by gsanchietti** [comment]
Released:
- nethserver-sssd-1.0.7-1.ns7.noarch.rpm
