### ISSUE TITLE
Useless Password policy page 

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5136]
**Steps to reproduce**
The password policy page is always visible, event if there's no account provider installed on the local machine.

**Expected behaviour**
That page should be hidden when it has nothing to configure in the underlying system.

**Component**
nethserver-sssd-1.0.6-1.ns7.noarch

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-sssd-1.0.6-1.15.gc13f194.ns7.noarch.rpm

*Test case 1*
- Install the update on a clean machine
- Check the "Password policies" link doesn't appear on left menu

*Test case 2*
- After test case 1, install nethserver-directory or nethserver-dc
- Check the "Password policies" link appears on left menu

**Comment by gsanchietti** [comment]
Released:
- nethserver-sssd-1.0.7-1.ns7.noarch.rpm
