### ISSUE TITLE
Missing home dir on RSAT-created accounts

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5137]
**Steps to reproduce**
- install nethserver-dc
- cretate an user account with RSAT tools
- The home directory is "/" 
  
  <pre>
  [root@neth7 ~]# getent passwd test@adc.local
  test@adc.local:*:1126401108:1126400513:Test Utente:/:/usr/libexec/openssh/sftp-server
  </pre>
- The `test` user cannot access his home directory

**Expected results**

The home directory is created when `test` PAM session is established:

```
/var/lib/nethserver/home/test
```

**Components**
nethserver-dc-1.0.7-1.ns7.x86_64.rpm

Originally post by **saitobenkei**. Also workaround is available from

http://community.nethserver.org/t/home-directory-of-users-in-ad/4733

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-sssd-1.0.6-1.17.gdac664a.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducible

**Comment by gsanchietti** [comment]
Verified with Samba tools:
1. Opened   `systemd-run -M nsdc -t /bin/bash`
2. Created goody user: `samba-tool  user add goofy --login-shell=/bin/ls --unix-home=/root/goofy --random-password`
3. Read goofy home from the  joined machine:

> [root@test ~]# /usr/bin/net ads search -P  '(objectCategory=user)' sAMAccountName unixHomeDirectory | grep goofy
> sAMAccountName: goofy
> unixHomeDirectory: /root/goofy

**Comment by gsanchietti** [comment]
Released:
- nethserver-sssd-1.0.7-1.ns7.noarch.rpm
