### ISSUE TITLE
Virtual host inline help does not include plugins

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5138]
**Steps to reproduce**
- Create an inline help plugin for NethServer_Module_VirtualHosts_ModifyPlugin_*.html
- The Virtual host page does not show it

**Components**

nethserver-virtualhosts-1.0.1-1.ns7.noarch.rpm

Original post by @stephdl 

http://community.nethserver.org/t/cannot-create-help-inline-page-for-plugin/4647
##

**Comment by DavidePrincipi** [comment]
In nethserver-testing

nethserver-virtualhosts-1.0.1-1.2.gc3d5a7e.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
- nethserver-virtualhosts-1.0.2-1.ns7.noarch.rpm
