### ISSUE TITLE
SambAudit: "Reload" button doesn't work

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5139]
SambaAudit web interface doesn't report any entry even if "Reload" button is clicked.
When the user hits the button, the following error appears inside `/var/log/httpd/error_log`:

> sudo: sorry, you must have a tty to run sudo

_Steps to reproduce_
- Install nethserver-dc along with nethserver-samba and nethserver-samba-audit
- Create a new share and enable samba audit on it
- Create a new user with permission to write/read the share
- Copy a file inside the shared folder using the new user with a Samba client
- Open the Samba Audit web interface and click on the "Reload" button

_Expected behavior_
- The web interface must display a new entry log of type "Write"

_Actual behavior_
- No log entry is displayed

Thanks to @GG_jr for reporting.
Reference: http://community.nethserver.org/t/reports-samba-audit-no-records/4777/4
##

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-samba-audit-1.1.0-1.3.g303ef5c.ns7.noarch.rpm

*Test case 1*
- Check the bug is not reproducible

*Test case 2 (bonus)*
- Check the "Action" field inside the search form, the "Edit" option must be gone

**Comment by dnutan** [comment]
Test case 1: OK
* Reload link triggers the log parsing; new entries are shown.
Test case 2: OK
* Edit action no longer present.

**Comment by gsanchietti** [comment]
Released:
nethserver-samba-audit-1.1.1-1.ns7.noarch.rpm
