### ISSUE TITLE
Guest cannot write to shared folder

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5141]
**Steps to reproduce**

* Install File and Samba DC modules
* Create a shared folder "iba1", grant rw access to both guest and owning group
* Connect as guest ``smbclient -U guest%guest //192.168.122.4/iba1``
* Upload a file ``smb: \> put README.rst``

Error
``NT_STATUS_ACCESS_DENIED opening remote file \README.rst``

**More info**

```
getfacl /var/lib/nethserver/ibay/iba1/
getfacl: Removing leading '/' from absolute path names
# file: var/lib/nethserver/ibay/iba1/
# owner: administrator@nethesis.it
# group: g1@nethesis.it
# flags: -s-
user::rwx
group::rwx
other::r-x
```

See also http://community.nethserver.org/t/shared-folder-no-write-access-for-guest/4799

**Components**
nethserver-dc-1.0.7-1.ns7.x86_64
nethserver-ibays-3.0.1-1.ns7.noarch
nethserver-samba-2.0.1-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-ibays-3.0.1-1.3.g78f6c32.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified tests:
- created new ibay, access in RW mode with authenticated user
- access in RW mode with guest access

**Comment by gsanchietti** [comment]
Released:
- nethserver-ibays-3.0.2-1.ns7.noarch.rpm
