### ISSUE TITLE
SMB filesystem ACLs are not applied

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5142]
**Steps to reproduce**

* join an AD domain
* install file server module
* create a shared folder
* connect with a Windows client and try to set filesystem ACLs

The ACLs are not applied (both Windows and ``getfacl`` does not show them)

See also
http://community.nethserver.org/t/acl-arent-applied-in-samba4-ad-shares-subfolders-files/4772

Thanks to **saitobenkei** for pointing this out!

**Workaround**

    yum install sssd-libwbclient
    systemctl restart smb nmb

**Components**
nethserver-samba-2.0.1-1.ns7.noarch
nethserver-ibays-3.0.1-1.ns7.noarch
nethserver-sssd-1.0.6-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
In nethserver-testing:

nethserver-samba-2.0.1-1.3.g2ba75e9.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
- nethserver-samba-2.0.2-1.ns7.noarch.rpm
