### ISSUE TITLE
Mysql error in Nextcloud log

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5143]
After I Installed nextcloud on a new vm I can see error in the log /var/www/html/nextcloud/data/nextcloud.log relative to a user and database creation.

```
{"reqId":"DHYMFCpYF6UJHmJp0ZvN","remoteAddr":"","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_admin\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'nextcloud'@'localhost' for table 'user'","level":3,"time":"2016-11-06T07:33:01+00:00","method":"--","url":"--","user":"--"}
{"reqId":"DHYMFCpYF6UJHmJp0ZvN","remoteAddr":"","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `nextcloud` . * TO 'nextcloud'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'nextcloud'@'localhost' to database 'nextcloud'","level":3,"time":"2016-11-06T07:33:01+00:00","method":"--","url":"--","user":"--"}
```

**Comment by gsanchietti** [comment]
The error is probably generated by this action:
https://github.com/NethServer/nethserver-nextcloud/blob/master/root/etc/e-smith/events/actions/nethserver-nextcloud-conf

At the end of the installation, does Nextcloud instance is fully accessible?

**Comment by alepolidori** [comment]
I've reproduced it with clean installation, however nextcloud works correctly.
Isn't it @stephdl ?

**Comment by stephdl** [comment]
yes the nextcloud instance seems to be functional, I have not much tested beyond the installation. My goal was to test a nextcloud jail for fail2ban

**Comment by alepolidori** [comment]
Also nextcloud community talks about this https://help.nextcloud.com/t/nextcloud-10-installation-mysql-setup-error/4952

**Comment by stephdl** [comment]
ok, then let's close it as upstream, maybe a bug should be raised to the nextcloud team
