### ISSUE TITLE
Legacy short user name support

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5144]
By default realmd enables the ``@domain`` suffix in user and group names in sssd.conf. This new convention confuses the system user, and force to reconfigure his account credentials on any network client. Moreover some applications require a configuration adjustment.

We can define an additional domain in sssd.conf, to support both name forms (short, long) and keep uid/gid numbers consistent. This has been discussed on

http://community.nethserver.org/t/upgrade-paths-to-ns7/4771/3

and documented on the wiki, too

http://wiki.nethserver.org/doku.php?id=developer:ns7_upgrade#issue_5_-_pam-based_services

**Comment by DavidePrincipi** [comment]
*Test case*

Test both ldap and AD providers (local/remote). After joining a domain, the ``getent`` calls must be consistent:

* ``getent passwd user`` and ``getent passwd user@domain`` must return the same record
* ``getent group user`` and ``getent group user@domain`` must return the same record

In nethserver-testing:

nethserver-sssd-1.0.6-1.9.g67cc734.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified:

> [root@test ~]# getent passwd test1
> test1:*:354601104:354600513:test1:/var/lib/nethserver/home/test1:/usr/libexec/openssh/sftp-server
> [root@test ~]# getent passwd test1@neth.eu
> test1@neth.eu:*:354601104:354600513:test1:/var/lib/nethserver/home/test1:/usr/libexec/openssh/sftp-server
> 
> [root@test ~]# getent group g1@neth.eu
> g1@neth.eu:*:354601108:test4@neth.eu
> [root@test ~]# getent group g1
> g1:*:354601108:test4
> [root@test ~]# getent passwd test1
> test1:*:354601104:354600513:test1:/var/lib/nethserver/home/test1:/usr/libexec/openssh/sftp-server
> [root@test ~]# getent passwd test1@neth.eu
> test1@neth.eu:*:354601104:354600513:test1:/var/lib/nethserver/home/test1:/usr/libexec/openssh/sftp-server
> 
> [root@test ~]# getent group g1@neth.eu
> g1@neth.eu:*:354601108:test4@neth.eu
> [root@test ~]# getent group g1
> g1:*:354601108:test4

Tested also with webtop4.

**Comment by gsanchietti** [comment]
Added in nethserver-testing:
- nethserver-mail-server-1.10.3-1.2.g184aa90.ns7.noarch.rpm

Already tested.

**Comment by gsanchietti** [comment]
Released:
- nethserver-sssd-1.0.7-1.ns7.noarch.rpm
- nethserver-mail-server-1.10.4-1.ns7.noarch.rpm
