### ISSUE TITLE
LDAP account with read-only privileges

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5145]
One of the purposes of ``NethServer::SSSD`` Perl module is providing an API for other NethServer modules to access the LDAP server with the right credentials. The LDAP server can be an Active Directory (use machine account credentials), builtin LDAP (``libuser`` credentials), other LDAP (read credentials from DB props).

``libuser`` has full read/write access to the LDAP tree. Instead, we must provide a restricted account credentials with read-only access to the LDAP tree.

**Comment by DavidePrincipi** [comment]
*Test case*

* Install the testing packages
* Run ``signal-event nethserver-sssd-save``

The following command must display ``ldapservice`` credentials:

    perl -MNethServer::SSSD -MJSON -e '$o = NethServer::SSSD->new();
        print JSON::to_json({"BaseDN" => $o->baseDN(), 'BindDN' => $o->bindDN(),
             "BindPassword" => $o->bindPassword(), "UserDN" => $o->userDN(),
             "GroupDN" => $o->groupDN()});' | python -mjson.tool


In nethserver-testing:

nethserver-directory-3.0.2-1.7.g9b9c620.ns7.noarch.rpm
nethserver-sssd-1.0.6-1.11.gc33c902.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing
nethserver-sssd-1.0.7-1.3.g75c7c79.ns7.noarch.rpm
nethserver-directory-3.0.2-1.8.gc48c7d8.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Tested also with ejabberd and roundcubemail

Before update:

> {
>     "BaseDN": "dc=neth,dc=eu",
>     "BindDN": "cn=libuser,dc=neth,dc=eu",
>     "BindPassword": "wuXEpGVJuCeuweWL",
>     "GroupDN": "ou=Groups,dc=neth,dc=eu",
>     "UserDN": "ou=People,dc=neth,dc=eu"
> }
> 
> [root@test ]# grep libuser /etc/roundcubemail/config.inc.php
>     'bind_dn'                => 'cn=libuser,dc=neth,dc=eu',
> 
> [root@test ]# grep libuser /etc/ejabberd/ejabberd.cfg
> {ldap_rootdn, "cn=libuser,dc=neth,dc=eu"}.

After:

> {
>     "BaseDN": "dc=neth,dc=eu",
>     "BindDN": "cn=ldapservice,dc=neth,dc=eu",
>     "BindPassword": "MYE2W6omaE_SQt1L",
>     "GroupDN": "ou=Groups,dc=neth,dc=eu",
>     "UserDN": "ou=People,dc=neth,dc=eu"
> }
>
> [root@test ]# grep ldapservice /etc/roundcubemail/config.inc.php
>     'bind_dn'                => 'cn=ldapservice,dc=neth,dc=eu',
> 
> [root@test ]# grep ldapservice /etc/ejabberd/ejabberd.cfg
> {ldap_rootdn, "cn=ldapservicer,dc=neth,dc=eu"}.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:

nethserver-sssd-1.0.8-1.ns7.noarch.rpm
nethserver-directory-3.1.0-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
See: http://community.nethserver.org/t/slapd-broken-after-latest-update/4932

**Comment by gsanchietti** [comment]
Released also:
- nethserver-nextcloud-1.0.3-1.ns7.noarch.rpm
