### ISSUE TITLE
Roundcube: no LDAP addressbook with OpenLDAP

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5146]
In a system with nethserver-directory as user provider, Roundcube doesn't display the list of current configured users inside the Address book.

*Steps to reproduce*
- Install nethserver-roundcubemail
- Create at least two contacts
- Access Roundcube and go to "Address book" page

*Expected behavior*
- The page must display the address book populated with local users

*Actual behavior*
- The page doesn't display any user

**Component**: nethserver-roundcubemail

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-roundcubemail-1.2.3-1.2.g298c3c7.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducible

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-roundcubemail-1.2.4-1.ns7.noarch.rpm
