### ISSUE TITLE
collectd: unixsock plugin: bind failed: Address already in use

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5147]
The unix socket `/var/run/collectd.sock`  can become unusable if collectd isn't shutdown correctly.
The `/var/log/messages` reports the following error:
> collectd: unixsock plugin: bind failed: Address already in use

The workaround is to delete the unix socket on each collectd restart.

Just change the value of  `DeleteSocket` option to true:
 https://github.com/NethServer/nethserver-collectd/blob/master/root/etc/collectd.d/unixsock.conf#L6

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-collectd-3.0.3-1.1.gad7083b.ns7.noarch.rpm

*Test case*
- On a clean machine install nethserver-collectd from updates repository
- Install the updated package
- Restart collectd
- Check the date of the unix socket changes on each restart:
```
stat /var/run/collectd.sock
```

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-collectd-3.0.4-1.ns7.noarch.rpm

In nethserver-updates/6.8:
nethserver-collectd-2.0.5-1.ns6.noarch.rpm
