### ISSUE TITLE
/etc/sssd/sssd.conf not expanded by nethserver-sssd-update

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5149]
With the legacy tricks to authenticate without the '@domain.xx' I saw that the file /etc/sssd/sssd.conf was not expanded by the event nethserver-sssd-update. In fact this event does not a lot of stuff, sure you have a good reason, but I preferred to raise a bug.

in short after the installation of nethserver-sssd
```
[root@NS7DEV2 ~]# rpm -qa nethserver-sssd
nethserver-sssd-1.0.8-1.ns7.noarch
```

after the installation I can see in /etc/sssd/sssd.conf
```

[sssd]
domains = stephdl.dyndns.org
config_file_version = 2
services = nss, pam

[domain/stephdl.dyndns.org]
enumerate = True
cache_credentials = True
default_shell = /usr/libexec/openssh/sftp-server
use_fully_qualified_names = True
id_provider = ldap
ldap_uri = ldap://127.0.0.1
ldap_search_base = dc=stephdl,dc=dyndns,dc=org
ldap_tls_reqcert = never


[nss]

```

after I launched the event nethserver-sssd-save
```
[sssd]
domains = stephdl.dyndns.org, legacy
config_file_version = 2
services = nss, pam

[domain/stephdl.dyndns.org]
enumerate = True
use_fully_qualified_names = True
id_provider = ldap
ldap_uri = ldap://127.0.0.1
ldap_search_base = dc=stephdl,dc=dyndns,dc=org
ldap_tls_reqcert = never
cache_credentials = True
default_shell = /usr/libexec/openssh/sftp-server


[domain/legacy]
enumerate = False
use_fully_qualified_names = False
id_provider = ldap
ldap_uri = ldap://127.0.0.1
ldap_search_base = dc=stephdl,dc=dyndns,dc=org
ldap_tls_reqcert = never
cache_credentials = True
default_shell = /usr/libexec/openssh/sftp-server


[nss]
```

My concern is that after the installation I cannot authenticate directly with the legacy (without @domain)

**Comment by DavidePrincipi** [comment]
Thanks for the report,

the template is already expanded by nethserver-sssd-update event, but only for new installations

https://github.com/NethServer/nethserver-directory/blob/master/root/etc/e-smith/events/actions/nethserver-directory-sssd

Updates does not expand it again. This is a known limitation because limits the possibility of releasing fixes, but does not harm at all.
