### ISSUE TITLE
Roundcube duplicate accounts with short legacy format

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5151]
**Steps to reproduce**

* install roundcube on rc2
* log in as first.user
* create an entry in the personal addressbook
* log out
* log in as first.user@domain
* the addressbook entry above is missing

Evidence in mysql roundcubemail db

<pre>
MariaDB [roundcubemail]> select * from users;
+---------+------------------------------+-----------+---------------------+---------------------+
| user_id | username                     | mail_host | created             | last_login          |
+---------+------------------------------+-----------+---------------------+---------------------+
|       1 | first.user                   | localhost | 2016-11-14 12:08:48 | 2016-11-14 12:08:48 |
|       2 | first.user@dpnet.nethesis.it | localhost | 2016-11-14 12:14:19 | 2016-11-14 12:14:19 |
+---------+------------------------------+-----------+---------------------+---------------------+
</pre>

**Components**

nethserver-roundcubemail-1.2.4

Discussion on

http://community.nethserver.org/t/roundcube-issues-connected-to-ldap/4947

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-roundcubemail-1.2.4-1.2.g88c2389.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
It was reported the fix actually prevents "root" to login on Roundcube. See
http://community.nethserver.org/t/roundcube-issues-connected-to-ldap/4947/9?u=davidep

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-roundcubemail-1.2.4-1.3.g83cf3f6.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Logged in with username `giacomo`, set interface theme to "Classic".
Logged in with username `giacomo@neth.eu`, the theme option is still applied.

Tested also with sieve filters.

**Comment by gsanchietti** [comment]
Released in 7.3.1611/base:
- nethserver-roundcubemail-1.2.5-1.ns7.noarch.rpm
