### ISSUE TITLE
bindDN() returns local domain suffix

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5153]
The default DN returned by ``bindDN()`` method in NethServer::SSSD module depends on the host name. ACLs in OpenLDAP configuration and UI expect a fixed string ``dc=directory,dc=nh``. This was a planned rule and cannot be changed now.

**Steps to reproduce**

Execute the command

    perl -MNethServer::SSSD -e '$o = NethServer::SSSD->new(); print $o->bindDN()'

The output contains the local domain suffix

    cn=ldapservice,dc=dpnet,dc=nethesis,dc=it

**Expected result**

    cn=ldapservice,dc=directory,dc=nh

**Components**

nethserver-sssd-1.0.8-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.8-1.2.g9e5d710.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
The library returns the correct DN: tested with nethserver-freepbx.

**Comment by gsanchietti** [comment]
Released in 7.3.1611/base:

- nethserver-sssd-1.1.0-1.ns7.noarch.rpm
