### ISSUE TITLE
Changing password fails if contains a space

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5154]
**Steps to reproduce**

* Install nethserver-directory
* Create a user
* Change password to "Nethesis 1234"

The event fails. In /var/log/messages:

<pre>
Nov 15 14:23:05 vm7 esmith::event[9654]: User 1234 does not exist.
Nov 15 14:23:05 vm7 esmith::event[9654]: Action: /etc/e-smith/events/password-modify/S30nethserver-directory-password-set FAILED: 2 [0.034339]
</pre>

**Components**

nethserver-directory-3.1.0-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-directory-3.1.0-1.2.gbd020fc.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified: tested both with spaces and special chars.

**Comment by gsanchietti** [comment]
Released in 7.3.1611/base:

- nethserver-directory-3.1.1-1.ns7.noarch.rpm
