### ISSUE TITLE
Nextcloud: upgrade to version 10.0.2

### ISSUE THREAD

**Issue by alepolidori** [NethServer/dev#5155]
New version 10.0.1 of nextcloud has been released.
https://download.nextcloud.com/server/releases/

Reference: http://community.nethserver.org/t/upgrading-to-nextcloud-10-0-1/4962
Thanks to @lucian for pointing it out.

**Comment by alepolidori** [comment]
Repo: testing
rpm:
nethserver-nextcloud-1.0.1-1.3.g61fafdc.ns7.noarch.rpm
nextcloud-10.0.1-1.ns7.noarch.rpm

**Comment by medworthy** [comment]
Both clean installation and upgrade of Nextcloud 10.0.1 (including nethserver-nextcloud-1.0.3-1.1.g103d8ab) has been tested and is working with NethServer v7.2.1511

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-nextcloud-1.0.3-1.8.ga3fe855.ns7.noarch.rpm
- nextcloud-10.0.2-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released in 7.3.1611/base:
- nextcloud-10.0.2-1.ns7.noarch.rpm
- nethserver-nextcloud-1.0.4-1.ns7.noarch.rpm
