### ISSUE TITLE
Empty users in roundcube public LDAP Addressbook

### ISSUE THREAD

**Issue by rolfbakker** [NethServer/dev#5156]
Hi,
I've installed NS7 rc1 with samba NS for users.
When I open roundcube, I see 6 users in the public LDAP addressbook:
3 that I added, and 3 that seems to be empty.
They can not be removed.

It is suggested that when you set up Samba AD, there are some hidden users, groups and accounts that are created by the AD inside the NS (3, 16, 2). It is about these three users.
These should be hidden.
(screenprint on http://community.nethserver.org/t/empty-users-in-roundcube-public-ldap-addressbook/4794 )

Related to that: an AD-user (user@dom1.com) that has a mailaddress with another domain (user@dom2.com) is listed twice in the suggested addresses when composing a new mail:
user@dom1.com
user@dom2.com
Preferably the user@dom1.com should be hidden as well.

**Comment by gsanchietti** [comment]
Currently the filter for address book on  AD is this: `(objectClass=user)`.

Can anyone suggest a better one for the AD LDAP tree?

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.8-1.25.g1340b2f.ns7.noarch.rpm
nethserver-roundcubemail-1.2.4-1.8.gdea6d52.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Created two users: giacomo, mario.

Both users are visible inside the addressbook, no empty contact is visible.

**Comment by gsanchietti** [comment]
Released in 7.3.1611/base:
- nethserver-roundcubemail-1.2.5-1.ns7.noarch.rpm
- - nethserver-sssd-1.1.0-1.ns7.noarch.rpm
