### ISSUE TITLE
Default "admins" config DB record

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5157]
Define an "admins" config DB record where to store the user/group name that applications will grant special privileges. 

This central point in config DB that enables applications to discover what grants are available is required to consistently upgrade ns6 to ns7.

The Active Directory account provider (both local and remote) defines by default the user ~~administrator~~ *admin* and group *administrators*. The default *administrator* must be disabled.

The default admin account is by default disabled. Its password must be set, before using it.

Checklist:

- [x] default db record
- [x] ~~show record values in sssd UI~~ wontfix
- [x] automatic creation in nethserver-directory during LDAP dit provisioning
- [x] automatic creation in nethserver-dc, during AD provisioning
- [x] disable default administrator account, during AD provisioning
- [x] show a TODO notification, until admin initial password has been set
- [x] documentation: restore the [Admin account](http://docs.nethserver.org/en/latest/accounts.html#admin-account) section (?)
- [x] fix server-manager "administrators" access

Discussion on community:

http://community.nethserver.org/t/need-to-share-on-the-defunct-admin-user/4630

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.8-1.12.gefcea6b.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.8-1.13.gaf927dc.ns7.noarch.rpm
nethserver-directory-3.1.0-1.20.g332631b.ns7.noarch.rpm
nethserver-base-3.0.11-1.4.geb68376.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-sssd-1.0.8-1.56.g3ee0f8e.ns7.noarch.rpm
- nethserver-dc-1.0.7-1.7.gb8ee717.ns7.x86_64.rpm
- nethserver-base-3.0.11-1.10.ge23c5f1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Just a note: to access the server-manager with admin privileges the user must be explicitly inside the "administrators" groups. If the user is inside "domain admins" group, the administrative access will not work since the web interface doesn't evaluate nested groups.

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
- nethserver-base-3.0.11-1.11.ge1b9cb1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released in 7.3.1611/base:

- nethserver-base-3.0.12-1.ns7.noarch.rpm
- nethserver-directory-3.1.1-1.ns7.noarch.rpm
- nethserver-sssd-1.1.0-1.ns7.noarch.rpm
- nethserver-dc-1.1.0-1.ns7.x86_64.rpm
