### ISSUE TITLE
Authenticated binds to a remote LDAP account provider

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5158]
We must honor ``BindDN`` and ``BindPassword`` props of ``sssd`` key when binding to a remote LDAP account provider. 

By default SSSD use anonymous binds. This works for our OpenLDAP setup on ns7, but does not work against a ns6 OpenLDAP, for instance.

Discussion on 

http://community.nethserver.org/t/i-need-help-to-configure-nethserver-to-use-external-openldap-server/4978

**Comment by DavidePrincipi** [comment]
*Test case*

Configure bind credentials:

    config setprop sssd BindDN uid=ns6user,ou=People,dc=directory,dc=nh BindPassword S3cret

Go to Users and groups page, select LDAP provider and BIND with ns6 IP address

It must be possible to log in via ssh with a ns6 user credentials (if shell is /bin/bash).

In nethserver-testing:
nethserver-sssd-1.0.8-1.4.g45fa2b0.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
See also issue #5161

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.8-1.21.g5b48e34.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Tested on two different NS 6 with following BindDN:
- uid=admin,ou=People,dc=nethesis,dc=it
- uid=admin,ou=People,dc=directory,dc=nh

Works great!

**Comment by gsanchietti** [comment]
Released in 7.3.1611/base:

- nethserver-sssd-1.1.0-1.ns7.noarch.rpm
