### ISSUE TITLE
nfsnobody local user/group listed on remote LDAP bound

### ISSUE THREAD

**Issue by dnutan** [NethServer/dev#5159]
**Issue Description**
*nfsnobody* local user and group introduced by a package dependent on **@nethserver-backup** is shown on **Users and Groups** section of an LDAP bound.

**Expected behavior**
*nfsnobody* user/group filtered out.

**Steps to reproduce**

  1. Install NethServer 7 (tested in RC2)
  2. Bind the server to an external LDAP account provider
  3. Check the users and groups are shown correctly
  4. Install *Backup* module: `yum install -y @nethserver-backup`
  5. Reboot the server
  6. Check the listed users and groups: *nfsnobody* is shown

**Reference**
http://community.nethserver.org/t/remote-nethserver-ldap-listing-nfsnobody-user-and-group/5016
Thanks to @DavidePrincipi for pointing out the solution

**Fix:**
Blacklist the user and group using `/etc/nethserver/system-users` and `/etc/nethserver/system-groups` of **nethserver-sssd** package. See PR:

* https://github.com/NethServer/nethserver-sssd/pull/29
* https://github.com/NethServer/nethserver-sssd/pull/30

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.8-1.12.gefcea6b.ns7.noarch.rpm

**Comment by dnutan** [comment]
The fix is working (tested with *nethserver-sssd-1.0.8.-1.13.gaf927dc.ns7.noarch.rpm* package)

**Comment by gsanchietti** [comment]
Released in 7.3.1611/base:

- nethserver-sssd-1.1.0-1.ns7.noarch.rpm
