### ISSUE TITLE
Revert Samba config to support NTLM auth by default

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5160]
**Steps to reproduce**

* install nethserver-samba and bind an AD account provider
* create an ibay ``iba1``, try to access it:

    smbclient -d 10 -U NETH\\first.user%Nethesis,1234 //192.168.122.4/iba1

<pre>
...
SPNEGO login failed: Logon failure
session setup failed: NT_STATUS_LOGON_FAILURE
</pre>

Kerberos login works (host name required):

    kinit first.user@NETH.EU
    ...
    smbclient -k //vm4.neth.eu/iba1

**Components**

nethserver-samba-2.0.2-1.ns7.noarch
nethserver-ibays-3.0.2-1.ns7.noarch
~~nethserver-sssd-1.0.8-1.13.gaf927dc.ns7.noarch~~

**Discussion**

http://community.nethserver.org/t/and-then-shared-folders-stopped-working/4927

**Comment by DavidePrincipi** [comment]
**Test case 1**

Check the bug is not reproducible (NTLM auth must work)

**Test case 2**

Switch to ``sssd``:

    config setprop smb Libwbclient samba
    signal-event nethserver-samba-update

Now only Kerberos auth works, and from any Windows domain workstation filesystem ACLs can be modified.


In nethserver-testing:

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-samba-2.0.2-1.3.gb1ea427.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Default configuration is set to "samba" and NTLM authentication correctly works.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-samba-2.0.3-1.ns7.noarch.rpm
