### ISSUE TITLE
Enable LDAPs protocol on Active Directory clients

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5161]
Recent Active Directory admin practice allows LDAP simple binds over SSL-protected connections only.

Our configuration uses clear-text protocol. This is not a problem if the Samba Active Directory provider is local but has two drawbacks:

* With a remote Microsoft AD provider, apps like SOGo, NextCloud that don't rely on PAM can't authenticate with the default configuration from SSSD.
* Machine credentials are sent in clear text.

We can enable ldaps against ns7 Samba Active Directory, because Samba generates an SSL certificate automatically. On Microsoft environments some additional configuration steps are required.

References:

1. https://blogs.technet.microsoft.com/russellt/2016/01/13/identifying-clear-text-ldap-binds-to-your-dcs/
2. https://blogs.technet.microsoft.com/russellt/2016/06/03/custom-ldap-certs/

This is the list of core packages that require the LDAPs setup:

- [x] roundcubemail (addressbook)
- [x] nextcloud
- [x] ejabberd
- [x] ~~webtop4~~ cantfix
- [x] nsdc (restore Samba defaults)

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.8-1.23.g58d5c9b.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.8-1.24.gb603ed6.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.8-1.25.g1340b2f.ns7.noarch.rpm
nethserver-directory-3.1.0-1.27.g646bbc2.ns7.noarch.rpm
nethserver-roundcubemail-1.2.4-1.8.gdea6d52.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
**Test case**

Account providers

Type | Local | Remote
---------|-------|-------
Active Directory | Samba | Samba, Microsoft (ldap, ldaps)
LDAP | ns7 | ns7, ns6, other

Packages

- nextcloud
- WebTop4
- ejabberd
- roundcubemail

We must check each package against any possible account provider. This is a huge work: please report any successful case!

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.0.8-1.52.g6546f32.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-sssd-1.0.8-1.56.g3ee0f8e.ns7.noarch.rpm
- nethserver-dc-1.0.7-1.7.gb8ee717.ns7.x86_64.rpm
- nethserver-base-3.0.11-1.10.ge23c5f1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
All tested applications are good.
Open a new issue for WebTop 4 as soon as a new release with LDAPs support is available.

**Comment by gsanchietti** [comment]
Released in 7.3.1611/base:

- nethserver-directory-3.1.1-1.ns7.noarch.rpm
- nethserver-sssd-1.1.0-1.ns7.noarch.rpm
- nethserver-ejabberd-1.1.3-1.ns7.noarch.rpm
- nethserver-nextcloud-1.0.4-1.ns7.noarch.rpm
- nethserver-roundcubemail-1.2.5-1.ns7.noarch.rpm
