### ISSUE TITLE
Don't work file sharing

### ISSUE THREAD

**Issue by dmitrz** [NethServer/dev#5162]
file sharing is installed, but I don't see ACL?

version: NethServer 7 rc2
![deepinscreenshot20161124150510](https://cloud.githubusercontent.com/assets/4159068/20597916/7ce2f91e-b257-11e6-83aa-97d870ce4143.png)

**Comment by DavidePrincipi** [comment]
Hi @dmitrz, before opening issues on GitHub we use to discuss them on http://community.netheserver.org!  Let's meet up there!

**Comment by DavidePrincipi** [comment]
The ACL tab is available only if NethServer has an Active Directory account provider.

I close here, if you have any question please write us on http://community.netheserver.org/
