### ISSUE TITLE
Cannot close Installation Source window when setting up

### ISSUE THREAD

**Issue by dcrobertson01** [NethServer/dev#5163]
When installing, at the Installation Summary page, if you click Installation Source, then the Done button, the window will not close and an error 'URL is empty'. The Auto-detect installation media' radio button is selected.

To close the window, you need to check the 'On the Network' radio button, then check the 'Auto-detect installation media' radio button, then click Done.

Also - checking the 'Verify' button gives 'This media is not good to install from', but installs.

I am new to Nethserver, CentOS and haven't used RPMs for decades (another Zentyal refugee), so don't know if there should be defaults in the Network area - was expecting to find a URL somewhere so updates could be installed as the system was installed.

Anyway - left me puzzled for a bit, so letting you know :-)

**Comment by DavidePrincipi** [comment]
Thank you for your report, @dcrobertson01 ! I guess you're talking about the Grub installation menu in our ISO... What ISO version are you referring to? ns6.8 or ns7rc2?

BTW: did you already registered on http://community.nethserver.org? Your GH account would be fine for the registration! We use to discuss bug there, then open the issues here on GitHub!

**Comment by dcrobertson01** [comment]
Oops, sorry. 7.0 rc2. Followed the link to the buds to see any one else has reported it.

On a different note, I messed up the installation of samba ad server, and re installed. This time send to be working perfectly. Good things happen when you read the documentation.

**Comment by gsanchietti** [comment]
These bugs should be reported to upstream project Anaconda.

> Also - checking the 'Verify' button gives 'This media is not good to install from', but installs.

This is because the ISO have been changed during the build project: currently there is no workaround.
But please, verify the iso after download using `md5sum` or `sha1sum` commands.
