### ISSUE TITLE
Store locally AD credentials

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5165]
Microsoft Active Directory does not accept simple binds with machine password. This is the error code it returns:

<pre>
ldap_bind: Invalid credentials (49)
	additional info: 80090308: LdapErr: DSID-0C0903D9, comment: AcceptSecurityContext error, data 710, v2580
</pre>

Whilst Samba AD could accept the machine credentials, we need an additional identity to bind the LDAP of Microsoft AD. 

LDAP simple bind is required by so-called "third party applications" that don't support the native Microsoft Kerberos/GSSAPI authentication (namely, SOGo, WebTop, Ejabberd, Roundcube, NextCloud).

~~We could ask the sysadmin to locally store the credentials provided to join the domain and return them to the applications described above.~~

In a second step, the sysadmin can provide an additional identity with read-only access to LDAP and a non-expiring password.

- [x] move provider selection to new SssdConfig UI page
- [x] display an error if the LDAP connection fails
- [x] relocate the DomainController page under the new SssdConfig page

**Comment by DavidePrincipi** [comment]
> We could ask the sysadmin to locally store the credentials provided to join the domain and return them to the applications described above

Storing that credentials in clear text is definitely a bad practice. Let's search for an alternative solution.

**Comment by DavidePrincipi** [comment]
**Test case**

New SssdConfig page

* on a new system, page "Domain accounts" shows a "Configure" button that points to SssdConfig
* on a new system, page "Users and groups" shows a "Configure" button that points to SssdConfig
* The SssdConfig page is always visible. Once an account Provider has been configured, it's always possible to switch it off, and on again or choosing another one.
* The "Advanced settings" section under SssdConfig page displays library defaults as input fields "watermarks" according to the currently selected account provider

*Failure cases*

* Invalid bind credentials (for instance when join Microsoft AD the default machine credentials are not valid)
* Connection timeout, failed for other reason
* AD with more than N users (where N, the size limit, is enforced by the server): a warning is displayed - only first N are fetched. MS AD sets N=1000.

In nethserver-testing:
- nethserver-httpd-admin-2.0.4-1.2.g0bd6b69.ns7.noarch.rpm
- nethserver-sssd-1.0.8-1.70.g9991bee.ns7.noarch.rpm
- nethserver-dc-1.0.7-1.10.gb889ac3.ns7.x86_64.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.0.7-1.13.gfd50618.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
The system works correctly, but in the future we will probably need to add some minor tweaks inside the SssdConfig page.

**Comment by gsanchietti** [comment]
Released in 7.3.1611/base:

- nethserver-sssd-1.1.0-1.ns7.noarch.rpm
- nethserver-dc-1.1.0-1.ns7.x86_64.rpm

Missing RPM:
- nethserver-httpd-admin
