### ISSUE TITLE
openldap writable with ldapservice

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5166]
I'm working on dokuwiki and I use NethServer::SSSD to write the good values either for openldap or samba4, but my problem is not here.

I use this configuration with dokuwiki
```

<?php

$conf['authtype'] = 'authldap';
$conf['plugin'][$conf['authtype']]['server'] = "ldap://127.0.0.1:389";
$conf['plugin'][$conf['authtype']]['version'] = '3';
$conf['plugin'][$conf['authtype']]['usertree'] = "ou=People,dc=stephdl,dc=dyndns,dc=org";
$conf['plugin'][$conf['authtype']]['grouptree'] = "ou=Groups,dc=stephdl,dc=dyndns,dc=org";
$conf['plugin'][$conf['authtype']]['userfilter'] = '(&(uid=%{user})(objectClass=inetOrgPerson))';
$conf['plugin']['authldap']['groupfilter']  = '(|(memberUid=%{user})(gidNumber=%{gid}))';
$conf['plugin'][$conf['authtype']]['groupkey'] = 'cn';
$conf['plugin']['authldap']['binddn']     = "cn=ldapservice,dc=stephdl,dc=dyndns,dc=org";
$conf['plugin']['authldap']['bindpw']     = "x2xQcGb11bTiNeoJ";
$conf['auth']['ldap']['starttls']   = 1;
$conf['useacl'] = 1;
?>
```
In dokuwiki you have a field to change the password of a user, with this option I can reset the password of the user created in the server-manager...I have tested it several time with two different users

nethserver-sssd-1.0.8-1.ns7.noarch
nethserver-directory-3.1.0-1.ns7.noarch

I was persuaded that the binduser ldapservice was only with read right :)

**Comment by DavidePrincipi** [comment]
> I was persuaded that the binduser ldapservice was only with read right

The user is granted write access to his LDAP entry. This allows changing his own password field.

Do you say any user can change the passwords of other users too?

The answer is in the slapd log file, where each BIND operation is reported.

**Comment by stephdl** [comment]
> Do you say any user can change the passwords of other users too?

Yes I can change the password of admin and another user created for the occasion 'toto', after that the password is changed, I can use it in the server-manager

**Comment by stephdl** [comment]
the  /var/log/slapd https://gist.github.com/stephdl/c48cf24bdbbd45596fdfc2ec3f6196ce

**Comment by stephdl** [comment]
just the log part when dokuwiki changes the password

https://gist.github.com/stephdl/95ee8a6c8fadc562344461116119edbf

**Comment by DavidePrincipi** [comment]
In this line I see BIND as toto. I think toto is changing password to himself:

https://gist.github.com/stephdl/95ee8a6c8fadc562344461116119edbf#file-gistfile1-txt-L35

**Comment by stephdl** [comment]
yes each user was changing it own password, I'm logged with the user 'toto' and in its preferences I change its password (given two times the new password and one time the old password)

**Comment by DavidePrincipi** [comment]
So ldapservice is not involved, can we close?

**Comment by stephdl** [comment]
no problem davidep, my goal is to declare what I found strange, and moreover I'm not confident with openldap/samba4 authentication.

set closed as per comment  above
