### ISSUE TITLE
admin with full permissions in the server-manager

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5167]
when you create the admin user with nethserver-directory and you use this user to log in the server-manager, this user is granted to full power.....does it is normal ?

**Comment by DavidePrincipi** [comment]
Yes, it is a member of the ``administrators`` group. As such it is granted full access to Server Manager.

Please, do not open issues on GitHub. Let's keep the discussion going on http://community.nethserver.org

**Comment by stephdl** [comment]
`Please, do not open issues on GitHub. Let's keep the discussion going on http://community.nethserver.org`

My bad I thought it was the bug report for NS7 and redmine for NS6, there are three places to report bugs.....ROTFL
