### ISSUE TITLE
Replace squidGuard with ufdbGuard

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5171]
CentOS will upgrade squid to version 3.5, which is not compatible with squidGuard. See:
http://bugs.squid-cache.org/show_bug.cgi?id=3978
We could switch to ufdbGuard which is compatible with squid-3.5 and, being based on squidGuard, can be adapted with a few modifications (see ufdbGuard reference manual, chapter 5.16).

Steps:
- [x] obsolete squidguard
- [x] add new ufdb daemon
- [x] migrate current configuration

References:
- https://www.urlfilterdb.com/products/ufdbguard.html
- Manual and RPMs: https://sourceforge.net/projects/ufdbguard/files/1.32/

**Comment by filippocarletti** [comment]
Test case:
1. update of a running system:
- the filter should continue to block the same webistes as before
- the squidGuard package should be absent
2. new install:
- try filter with two proxy configs:
1. only trasparent port 80
2. trasparent ssl port 443
- verify:
1. save and download blacklist
2. enable some categories
3. enable filter
4. block zip
5. change downloaded list
6. logs are rotated
7. in a profile, check the following who:
a local user
a group of local users
a host
a group of host
a zone
a CIDR subnet
an IP range
a user from Active Directory, if the server has joined the domain

- the block page should mention powder by ufdbGuard

**Comment by gsanchietti** [comment]
In nethserver-testing:
- ufdbGuard-1.32.3-CentOS7.x86_64.rpm
- nethserver-squidguard-1.5.1-1.10.g21fbb92.ns7.noarch.rpm

Before testing, make sure *cr* repository is enabled:
```
yum --enablerepo=cr,nethserver-testing install nethserver-squidguard
```

**Comment by gsanchietti** [comment]
Verified.
Please, note that uploading current ufdbGuard rpm fails repoclosure check:
```
package: ufdbGuard-1.32.3-CentOS7.x86_64 from temp
  unresolved deps: 
     /bin/perl
```

**Comment by gsanchietti** [comment]
Upstream has just released a fixed rpm.

Released 
- ufdbGuard-1.32.4-CentOS7.x86_64.rpm
- nethserver-squidguard-1.6.0-1.ns7.noarch.rpm
