### ISSUE TITLE
OpenVPN: bridged mode doesn't work

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5173]
When OpenVPN roadwarrior server is configured in bridged mode, the tap0 device is created but not started and not joined to br0.

*Steps to reproduce*
- Install nethserver-openvpn
- Create a bridge in the Network page for the green interface
- Enable the roadwarrior server with certificate authentication
- Set the server in bridged mode
- Create a VPN-only account
- Try to connect with a client

*Expected behavior*
The client must be connected and able to send data to client inside the LAN

*Actual behavior*
The client is connected but no traffic can be sent to LAN clients

*Workaround*
Add the tap device to existing bridge:
`brctl addif br0 tap0`

Thanks to @nsflatspin and @gerald_FS for pointing it out!

Reference:
- http://community.nethserver.org/t/openvpn-tap-device-not-joined-to-br0-after-installation/5006
- http://community.nethserver.org/t/openvpn-no-dns/5074

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-openvpn-1.4.2-1.3.geb83556.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducible

*Alternative test case*
- Configure the roadwarrior server in bridged mode
- Check the tap0 interface is bound to the bridge: `brctl show`
- Stop the openvpn service `systemctl stop openvpn@host-to-net.service` and check the tap0 interface is not bound to the bridge

**Comment by nsflatspin** [comment]
Installed new package on a VM. Tap0 was bound after enabling the service and was removed after disabling  the service and bound again after enabling the service again. After reboot there was the same behavior. Couldn't find error messages in relevant logs (openvpn.log, messages.log).

**Comment by gsanchietti** [comment]
Released:
nethserver-openvpn-1.4.3-1.ns7.noarch.rpm
