### ISSUE TITLE
Disable squid ssl certificate generation

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5176]
We should disable certificate generation by squid, since we no longer bump ssl requests.
Documentation says that generate-host-ceritficates is changed to on automatically:
http://www.squid-cache.org/Versions/v3/3.5/cfgman/https_port.html
But, thorugh experiments, we discovred that's untrue, probably a documentation bug:
http://bugs.squid-cache.org/show_bug.cgi?id=4627

As a side effect, disabling cert generation, will permit to run transparent ssl squid on arm (eg. Raspebby PI):
http://community.nethserver.org/t/build-web-filter-modules-for-arm/5236/17?u=filippo_carletti

Related to issue #5169

**Comment by filippocarletti** [comment]
Note for testing: tests should be carried on a freshly installed system, where the cert db dir in not present.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-squid-1.5.0-1.2.g611ad2d.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
_Test case 1 (fresh install):_

- install package
- enable squid transparent ssl
- check that squid is running
- `/var/lib/ssl_db/` should not exist
- (optional) browse to a https webiste through proxy

_Test case 2 (update):_

- update package on a system configured with transparent ssl
- squid should restart and keep running
- `/var/lib/ssl_db/` will be there empty

The paranoid sysadmin will delete `/var/lib/ssl_db/`.
I'd avoid adding code to remove it automatically.

**Comment by gsanchietti** [comment]
It works as expected.

**Comment by gsanchietti** [comment]
Released:
- nethserver-squid-1.5.1-1.ns7.noarch.rpm
