### ISSUE TITLE
ISO installer: keyboard layout ignored

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5178]
Keyboard layout selected by the user during interactive install is partially ignored.

*Steps to reproduce*
- Start the interactive install
- Go to keyboard layout page: add Italian (IT) layout and remove the English (US) one
- Complete the install

*Expected behavior*
Keyboard layout must be set to "it" both for "VC Keymap" (console) and "X11 Layout" options.

*Actual behavior*
Keyboard layout is set to "it" only for "X11 Layout" option:
```
# localectl 
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: it

```

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-createiso-1.4.4-1.2.g87003fa.ns7.noarch.rpm

Testing iso:
http://www.nethserver.org/nethserver-7.3.1611.rc3b-x86_64.iso

*Test case*
- Check the bug is not reproducible

**Comment by filippocarletti** [comment]
Using the new iso, at first login the keyboard map matches the one selected during install.
anaconda-ks.cfg now contains:
`keyboard --vckeymap=it --xlayouts='it','us'`
localectl reports VC Keymap: it.

**Comment by gsanchietti** [comment]
Released:
- nethserver-createiso-1.4.5-1.ns7.noarch.rpm

Removed testing ISO from www.nethserver.org
