### ISSUE TITLE
Backup-data not run after system crash

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5179]
If the system crashes (or a power loss occurs) during backup-data, duplicity leaves a lockfile that prevents further backups to run.
Steps to reproduce:
1. kill duplicity while backup-data is running
2. re-run backup-data
3. read root email looking for **Another instance is already running with this archive directory**

NethServer has a locking system to avoid concurrency of backup-data: if our lock is released we can safely delete duplicity lockfile.

Bug present also in NS6.

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-backup-data-1.2.2-1.3.g5f80a25.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducible

**Comment by gsanchietti** [comment]
Verified by @cotosso

**Comment by gsanchietti** [comment]
Released:
- nethserver-backup-data-1.1.9-1.ns6.noarch.rpm
- nethserver-backup-data-1.2.3-1.ns7.noarch.rpm
