### ISSUE TITLE
WebTop4: enable LDAPs protocol

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5180]
Configure WebTop 4 to use ldap when connecting to remote account providers.
Scenarios:
- remote LDAP
- remote Samba AD
- remote MS AS

Also make sure WebTop works for
- local LDAP
- local Samba AD

Original issue #5161

**Comment by gsanchietti** [comment]
**Test case**

Account providers

Type | Local | Remote
---------|-------|-------
Active Directory | samba4/nsdc | Samba, Microsoft (ldap, ldaps)
LDAP | slapd/ns7 | ns7, ns6, other

In nethserver-testing:
nethserver-webtop4-1.3.6-1.1.g6318930.ns7.noarch.rpm
webtop4-core-1.2.0-1.1.g7e502a5.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
Test case - new installation 

- [x] remote ldap
- [ ] remote Samba AD
- [ ] remote MS AD
- [ ] local LDAP
- [ ] local AD

**Comment by gsanchietti** [comment]
Problems found:

- webtop hangs after the first start because it tries to alter the `domains` table, which already has all required fields (see https://github.com/NethServer/nethserver-webtop4/commit/61838adf8ef34cffc40c20f7793bdbfb660ba2b3 for conflicting fields )
- the authentication doesn't work with a remote LDAP (NS 7):
  - authuri: ldapWebTop://192.168.5.246:389
  - auth_connection_security: STARTTLS
  - adminldap_as_full_dn: t
- when using a remote AD or LDAP the name of the user is not correctly filled: it displays the username instead of the full name
- mail shared folders don't work at all

**Comment by gsanchietti** [comment]
Upstream has released a new war file 457 which fixes:
- https://redmine.sonicle.com/issues/89
- https://redmine.sonicle.com/issues/92
- https://redmine.sonicle.com/issues/91

We need to:
- upgrade current webtop4-core package
- remove `/usr/share/tomcat/lib/postgresql-jdbc.jar` link
- set  `mail.username.stripdomain` option to `false`

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-webtop4-1.3.6-1.8.g8cb9462.ns7.noarch.rpm
- webtop4-zpush-1.2.1-1.ns7.noarch.rpm
- webtop4-core-1.2.2-1.ns7.noarch.rpm

*Test case*
See previous comments.

*Known bugs*
Users must login using the short-hand format (without `@domain` part)

**Comment by gsanchietti** [comment]
Released:
- nethserver-webtop4-1.3.7-1.ns7.noarch.rpm
- webtop4-core-1.2.3-1.ns7.noarch.rpm
- webtop4-zpush-1.2.1-1.ns7.noarch.rpm
