### ISSUE TITLE
UI users and groups list items are not sorted

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5182]
In ``Shared folders`` module, or ``Mail alias`` tab the items do not respect the string sorting order.

**Steps to reproduce**

- join a remote or local account provider
- install Shared folders and/or Email module

**Components**
nethserver-sssd-1.1.1-1.ns7.noarch
nethserver-mail-server-1.10.5-1.ns7.noarch
nethserver-samba-2.0.3-1.ns7.noarch
nethserver-ibays-3.0.2-1.ns7.noarch

Thanks to @dz00te for [pointing it out](http://community.nethserver.org/t/questions-about-ad-join/5283)

**Comment by DavidePrincipi** [comment]
This is a regression caused by NethServer/nethserver-sssd#34

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.1.1-1.4.g334d0e9.ns7.noarch.rpm

**Comment by dz00te** [comment]
*System and  Package Version installed*
VM KVM - Clean install of Nethserver 7rc3 fully updated
Package Installed:  nethserver-sssd

*Install Updated Package*
yum --enablerepo=nethserver-testing install nethserver-sssd-1.1.1-1.4.g334d0e9.ns7.noarch

*Test Results after update*
1. on a already joined/functional ns7rc3, with updated package now users/groups list are sorted 
2. installed before join a domain, all ok

**Comment by gsanchietti** [comment]
Released:
- nethserver-sssd-1.1.2-1.ns7.noarch.rpm
