### ISSUE TITLE
Antivirus web: replace Squidclamav

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5183]
Squid 3.5 for CentOS 7.3 drops C-ICAP support.
Replace current antivirus web implementation based on C-ICAP + Squidclamav with a new E-CAP based implementation.

See:
- http://wiki.squid-cache.org/ConfigExamples/ContentAdaptation/eCAP#Using_eCAP_for_GZip_support_with_Squid_3.x.2F4.x
- http://wiki.squid-cache.org/Features/eCAP
- http://www.e-cap.org/

**Comment by gsanchietti** [comment]
In nethserver-testing:
- ecap-clamav-2.0.0-1.ns7.x86_64
- nethserver-squidclamav-1.3.1-1.4.g6baa13a.ns7.noarch.rpm

*Test case 1*
- Enable squid and leave the antivirus disabled
- Check the eicar is not blocked (the command must return no output):
```
http_proxy=http://127.0.0.1:3128 curl -s -D - http://www.eicar.org/download/eicar.com  -o /dev/null | grep ERR_ACCESS_DENIED
```
*Test case 2*
- Enable the antivirus and squid
- Check the eicar is blocked.  The previous command must return
```
X-Squid-Error: ERR_ACCESS_DENIED 0
```

**Comment by filippocarletti** [comment]
Verified by VenimK (http://community.nethserver.org/t/anti-virus-proxy/5321/6)

**Comment by gsanchietti** [comment]
Released:
- ecap-clamav-2.0.0-1.ns7.x86_64.rpm
- nethserver-squidclamav-2.0.0-1.ns7.noarch.rpm

Now squidclamav is back inside the web filter group. Also release notes for rc3 have been updated.
