### ISSUE TITLE
Web filter: refresh block page

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5184]
Use the new ufdbguard sample cgi for block page.

The new CGI should be able to send back to client the correct content type of blocked resources.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-squidguard-1.6.1-1.6.g3749a67.ns7.noarch.rpm

*Test case 1*
- Check the web filter still blocks sites
- Check the web filter blocks images with a correct content type

*Test case 2*
- Update and existing installation
- Replicate the checks from test case 1

**Comment by filippocarletti** [comment]
With the updated package, downloading a "resource" (i.e. url ending with .js) from a blocked site returns an empty file instead of an error. Using a web browser, an empty page is shown (instead of the old block page).
Using curl to obtain more details, here are the difference in the headers:
```
-< HTTP/1.1 403 Forbidden
+< HTTP/1.1 204 no content
-< Content-Type: text/html; charset=UTF-8
+< Content-Type: text/plain; charset=UTF-8

```

**Comment by filippocarletti** [comment]
Note: the page in Italian has a syntax error and wording is not clear.
Pull request:
https://github.com/NethServer/nethserver-squidguard/pull/12

**Comment by gsanchietti** [comment]
I dug a bit into the CGI code and I found these problems:
- the script always create a debug file inside tmp directory
- images are not correctly served
- the scripts supports too many options which add complexity to the code and we do not use in our configuration
- the code is almost unreadable

If we want to integrate this CGI we need much more code refactor work.

I'm going to revert all the changes and close this issue.

**Comment by gsanchietti** [comment]
I did a bad thing:
- forcefully reverted the master branch to latest release (1.6.1)
- moved all the CGI work on ufdb-cgi branch: https://github.com/NethServer/nethserver-squidguard/tree/ufdb-cgi
