### ISSUE TITLE
Firewall services not initialized on install

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5185]
On a freshly installed system with the firewall-base package, the firewall services tab in the firewall objects page is empty.
According to https://github.com/NethServer/nethserver-firewall-base/pull/36/files it should contain some default services.

Steps to reproduce:
1. install nethserver
2. install firewall
3. go to Firewall Objects -> Services: the table is empty

We're missing the executable permission on the init script:
```
[root@rc3 ~]# db fwservices show
[root@rc3 ~]# /usr/libexec/nethserver/initialize-fwservices-database 
-bash: /usr/libexec/nethserver/initialize-fwservices-database: Permission denied
[root@rc3 ~]# ls -l /usr/libexec/nethserver/initialize-fwservices-database 
-rw-r--r--. 1 root root 966 Oct 17 15:35 /usr/libexec/nethserver/initialize-fwservices-database
[root@rc3 ~]# sh /usr/libexec/nethserver/initialize-fwservices-database 
[root@rc3 ~]# db fwservices show
dhcp=fwservice
    Description=
    Ports=67,68
    Protocol=tcpudp
```

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-firewall-base-3.1.2-1.2.g28469d8.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.2-1.2.g28469d8.ns7.noarch.rpm

*Test case*
Check the bug is not reproducible, you could do it following these steps:
```
rm -f /var/lib/nethserver/db/fwservices
yum --enablerepo=nethserver-testing update nethserver-firewall-base
```

Check the script has been executed and the services are inside the db:
```
 grep initialize-fwservices-database /var/log/messages
 db fwservices show
```

**Comment by gsanchietti** [comment]
Released:
- nethserver-firewall-base-3.1.3-1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.3-1.ns7.noarch.rpm
