### ISSUE TITLE
Shared Folder ACL applied to a group sometimes not respected

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5186]
The issue is well described here:
http://community.nethserver.org/t/shared-folder-acl-applied-to-a-group-sometimes-not-respected/5257/1

*Steps to reproduce*
- Create a user
- Create a group
- Add the user to the group
- Create share (Owning group=domain users, Allow write permission to owning group, Guest access=none, Browsable; Set Read ACL for the group)
- Uncheck the Allow write permission to owning group checkbox.
- Recheck the Allow write permission to owning group checkbox.

*Expected behavior*
The user should be able to write into the folder.

*Actual behavior*
The user can't write into the folder.

Thanks to @dnutan for pointing it out!

**Comment by gsanchietti** [comment]
@DavidePrincipi correctly noted that the problem depends on a wrong mask used by the `setfacl` command.

I could workaround the issue using this patch (but it's not tested enough):
```
diff -u /etc/e-smith/events/actions/nethserver-ibays-set-permissions.ori /etc/e-smith/events/actions/nethserver-ibays-set-permissions
--- /etc/e-smith/events/actions/nethserver-ibays-set-permissions.ori	2016-12-15 10:32:24.699181566 +0100
+++ /etc/e-smith/events/actions/nethserver-ibays-set-permissions	2016-12-15 10:32:45.722618036 +0100
@@ -63,7 +63,7 @@
 my $acl = calcAcls($perms);
 system("setfacl -b '$ibayPath'");
 if($acl) {
-    system("setfacl -m '$acl' '$ibayPath'");
+    system("setfacl -n -m '$acl' '$ibayPath'");
     if($? != 0) {
         warn "[ERROR] setting shared folder ACLs \"$acl\"\n";
         $errors++;
```

I also noticed that sometimes a share can't be owned by the `adminstrators` group, since SSSD doesn't play well with this special built-in group:

> [root@test ~]# chgrp administrators@local.neth.eu /var/lib/nethserver/ibay/share2
> chgrp: invalid group: ‘administrators@local.neth.eu’

I propose to remove `administrators` from the group list in shared folder page since the user can safly use the `domain admins` group.

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-ibays-3.0.2-1.2.g5bfb5ac.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
The bug is no more reproducible.

Davide suggested a fix for existing ibays:
> The  fix works for new shared folders. For existing ones, try with "Reset permissions" action on each of them.

**Comment by gsanchietti** [comment]
Released:
- nethserver-ibays-3.0.3-1.ns7.noarch.rpm
