### ISSUE TITLE
Traffic shaping for logical interfaces 

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5187]
Improve the web interface by adding traffic shaping related fields during the creation of logical interfaces.

The page should:
- display "Link name", "Link weight", "Inbound bandwidth", "Outbound bandwidth" during the creation wizard, when the "red" role is selected
- display the same fields when editing the virtual interface

Also take care of the special PPPoE interface case.

Thanks to @pigaille for pointing it out.
Reference: http://community.nethserver.org/t/no-traffic-shaping-parameters-on-pppoe-interfaces/5361

**Comment by pagaille** [comment]
Hi,

Just to let you know that I tried (with guidance) to manually add the fields FwOutBandwidth and FwInBandwidth without success.

Thanks for the good work, I stay tuned and ready to test if needed.

Matthieu

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-base-3.0.12-1.14.gdb1fb03.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
All tests passed.
Also tested other logical interface types.

**Comment by gsanchietti** [comment]
Released:
- nethserver-base-3.0.13-1.ns7.noarch.rpm

**Comment by pagaille** [comment]
Maybe is it my testing methodology, but even if the UI works correctly, I can't see any effective result : an internet bandwidth test still reports full bandwidth available even if I specify 1/10th of it in the fields. 

![screen shot 2017-01-11 at 21 05 54](https://cloud.githubusercontent.com/assets/1886799/21864418/fe48c8a2-d841-11e6-9633-9b6602c1b36c.png)

![screen shot 2017-01-11 at 21 08 09](https://cloud.githubusercontent.com/assets/1886799/21864447/21f5d128-d842-11e6-8cd8-1aed89277c71.png)

**Comment by pagaille** [comment]
Maybe is it my testing methodology, but while the UI looks working correctly, I can't see any effective result : 

![screen shot 2017-01-11 at 21 05 54](https://cloud.githubusercontent.com/assets/1886799/21864519/78318b54-d842-11e6-977d-a36ed44addbf.png)

![screen shot 2017-01-11 at 21 08 09](https://cloud.githubusercontent.com/assets/1886799/21864486/53ef14fa-d842-11e6-9506-3c39e9d05d36.png)

**Comment by gsanchietti** [comment]
The traffic shaping function doesn't cap the bandwidth.
Please continue the discussion on community.
