### ISSUE TITLE
DC: restore configuration fails

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5188]
Restoring a configuration backup of a machine with nethserver-dc installed brings to a non-working system.

*Steps to reproduce*
- Install nethserver-dc and configure it
- Add at least one user
- Execute the configuration backup: `backup-config`
- On a clean machine, restore the configuration backup:
```
cp backup-config.tar.xz /var/lib/nethserver/backup
restore-config
```

*Expected behavior*
The system should be up and running with nethserver-dc installed and configured with the original user.

*Actual behavior*
The system fails the restore and nethserver-dc is not fully installed (the container is not provisioned).

Reference: http://community.nethserver.org/t/disaster-recovery-attempts-keep-failing/5295
Thanks to @fasttech for reporting.

**Comment by gsanchietti** [comment]
The restore logic is built inside the `post-restore-config ` event, but when the event is fired, nethserver-dc package is not installed yet.

We should take care of these points:

- installation of packages should be hard-coded inside the restreo-config script
- the join after the restore can fail because the Administrator password has been changed
- the creation of default administrative accounts shouldn't fail if the accounts already exist

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.1.0-1.8.g673edfd.ns7.x86_64.rpm
nethserver-backup-config-1.5.1-1.4.gbfc5b7f.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
- [x] full restore of DC configuration: both host and container side
- [ ] inhibit applying shorewall config if network interfaces are different from the backup
- [ ] inhibit nsdc startup if network interfaces are different from the backup
- [ ] postpone nsdc startup to interface-update event (when the bridge has been restored)
- [ ] automatically run interface-update event if network interfaces are the same of backup

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-backup-config-1.5.1-1.7.g3ee8b93.ns7.noarch.rpm
nethserver-dc-1.1.0-1.11.g0c65188.ns7.x86_64.rpm
nethserver-base-3.0.13-1.3.g0860cc7.ns7.noarch.rpm
nethserver-firewall-base-3.1.3-1.5.gd5b90e1.ns7.noarch.rpm
nethserver-sssd-1.1.3-1.2.g2e64055.ns7.noarch.rpm
nethserver-samba-2.0.3-1.2.g919d80f.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-base-3.0.13-1.7.g5f73586.ns7.noarch.rpm

**Comment by fasttech** [comment]
Had a semi successful test... see my notes in the community discussion.

**Comment by gsanchietti** [comment]
Tested with physical and virtual machine with multiple modules installed and configured.

**Comment by gsanchietti** [comment]
Released:
- nethserver-base-3.0.14-1.ns7.noarch.rpm
- nethserver-firewall-base-3.1.4-1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.4-1.ns7.noarch.rpm
- nethserver-sssd-1.1.4-1.ns7.noarch.rpm
- nethserver-backup-config-1.5.2-1.ns7.noarch.rpm
- nethserver-dc-1.1.1-1.ns7.x86_64.rpm
- nethserver-samba-2.0.4-1.ns7.noarch.rpm
