### ISSUE TITLE
Logical interfaces UI tweaks

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5189]
In Network page support the following (secondary) scenarios

- [x] support vlan on bond and bridge
- [x] forbid release of role in the last slave of a bridge

See also #5187

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-httpd-admin-2.0.5-1.4.g0c07416.ns7.noarch.rpm
- 

*Test case 1*
- Create a bond with one interface
- Create a bridge with one interface
- Check the physical interfaces don't have the button "Release role"

*Test case 2*
After test case 1, do the following:
- try to create a vlan on the bond
- try to create a vlan on the bridge
- try to create a vlan on the physical interface
- configure the PPPoE device, check you can't create a vlan on the ppp0 device

**Comment by gsanchietti** [comment]
Released:
- nethserver-httpd-admin-2.0.6-1.ns7.noarch.rpm
- nethserver-httpd-admin-2.0.6-1.ns7.noarch.rpm
