### ISSUE TITLE
httpd-admin: use KillMode=process

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5190]
Systemd default `KillMode` is set to `control-group` which implies that all process (including ptrack) spawned by httpd-admin are killed when httpd-admin is restarted.
Reference: https://www.freedesktop.org/software/systemd/man/systemd.kill.html

Change httpd-admin systemd unit to use `process` as kill mode. The main advantage is that all applications which need to update httpd-admin configuration can safely execute the daemon restart without using the special action `nethserver-httpd-admin-asyncreload`.
The `nethserver-httpd-admin-asyncreload` is still useful when the `cetificate-update` event is invoked by the web interface.

Affected applications:
- nethserver-httpd-admin
- nethserver-bandwidthd 
- nethserver-cgp
- nethserver-samba-audit
- nethserver-lightsquid

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
- nethserver-bandwidthd-1.0.0-1.3.gbb79882.ns7.noarch.rpm
- nethserver-cgp-2.1.1-1.2.gd3ad264.ns7.noarch.rpm
- nethserver-httpd-admin-2.0.5-1.4.g0c07416.ns7.noarch.rpm
- nethserver-samba-audit-1.1.1-1.2.gffc7e83.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
- nethserver-httpd-admin-2.0.6-1.ns7.noarch.rpm
- nethserver-cgp-2.1.2-1.ns7.noarch.rpm
- nethserver-bandwidthd-1.0.1-1.ns7.noarch.rpm
- nethserver-samba-audit-1.1.2-1.ns7.noarch.rpm
- nethserver-lightsquid-1.1.2-1.ns7.noarch.rpm
