### ISSUE TITLE
Daily cron email about pulledpork.pl

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5191]
Every day, the cron system sends an email containing only the following line:
/bin/sh: /usr/bin/pulledpork.pl: No such file or directory

The right path is /usr/bin/pulledpork

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-pulledpork-2.0.0-1.1.gb00fc95.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducbile

**Comment by filippocarletti** [comment]
After update, I no longer received email from cron.

**Comment by gsanchietti** [comment]
Release after #5199

**Comment by gsanchietti** [comment]
Released:
- nethserver-pulledpork-2.0.1-1.ns7.noarch.rpm
