### ISSUE TITLE
Exhibit bad network configuration

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5193]
If the network configuration does not adhere to existing devices (i.e. NIC replacement, config restore on different hardware...) some operations must be inhibited to prevent the system to become unreachable (locking out).

When a *bad network configuration* is detected a file is created as a condition flag:

    /var/run/.nethserver-fixnetwork

For instance, when the condition occurs we must inhibit

- shorewall restart
- nsdc startup

This feature is required to correctly restore the configuration backup. See #5188

**Comment by DavidePrincipi** [comment]
*Test case 1*

Create the flag and reboot. The flag must be removed, because the file system is tmpfs

    touch /var/run/.nethserver-fixnetwork

*Test case 2*

1. Configure a red, green, orange, blue interface and shutdown
2. Replace all NIC with new ones
3. Power on. The system brings up ``brdef`` and requires network interface renaming

Verify the iptables config has been flushed.


In nethserver-testing:
nethserver-base-3.0.13-1.3.g0860cc7.ns7.noarch.rpm
nethserver-firewall-base-3.1.3-1.5.gd5b90e1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified.

**Comment by gsanchietti** [comment]
Released:
- nethserver-base-3.0.14-1.ns7.noarch.rpm
- nethserver-firewall-base-3.1.4-1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.4-1.ns7.noarch.rpm
