### ISSUE TITLE
Pulledpork: wrong configuration

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5199]
Pulledpork tries to access non-existent file.

Excerpt from `/usr/bin/pulledpork -c /etc/snort/pulledpork.conf -l` execution:

```
...
Unable to read: /etc/snort/enablesid.conf - No such file or directory
 at /usr/bin/pulledpork line 2151.
...
Unable to read: /etc/snort/disablesid.conf - No such file or directory
```

**Comment by gsanchietti** [comment]
In nehtserver-testing:
- nethserver-pulledpork-2.0.0-1.3.g6f36a0c.ns7.noarch.rpm

*Test case*
- Execute nethserver-squidguard-save
- Check the event doesn't raise any errors

**Comment by alefattorini** [comment]
Verified by Carlos here http://community.nethserver.org/t/pulledpork-package-wrong-version/5524/5

**Comment by gsanchietti** [comment]
Released:
- nethserver-pulledpork-2.0.1-1.ns7.noarch.rpm
