### ISSUE TITLE
Priority rule on email aliases

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5201]
This is the scenario with two additional email alias that deliver to different accounts:

    alias@ -> account1
    alias@domainA -> account2

The actual mail server configuration always delivers messages to account1, the ``alias@domainA`` entry is ignored and postfix warns in /var/log/messages:

    postmap: warning: /etc/postfix/virtual.db: duplicate entry: "alias@domainA"

Possible alternatives:

* **merge behavior**: the ns6 implementation delivers messages to ``alias@domainA`` to both account1 **and** account2
* **override behavior**: the old sme8 implementation delivers messages to ``alias@domainA`` to account2 whilst any other defined domain (i.e. alias@domainB, alias@domainC ...) to account1.

**Comment by DavidePrincipi** [comment]
I'd go with **override behavior** because on ns7 multiple accounts can be assigned to a single alias, thus the "merge behavior" of ns6 can easily obtained from the web interface or by a migration script.

**Comment by DavidePrincipi** [comment]
**Test case**

create two aliases, as described above and verify messages to ``alias@domainA`` and ``alias@domainSomething`` are delivered according to **override behavior**

In nethserver-testing:
nethserver-mail-server-1.10.5-1.8.g5e21750.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Test with 2 aliases:
```
[root@test ~]# db accounts show
goofy@=pseudonym
    Access=public
    Account=giacomo@local.neth.eu
    Description=Goffy generic
goofy@local.neth.eu=pseudonym
    Access=public
    Account=admin@local.neth.eu
    Description=
```
Mail delivered to admin:
> Jan 18 14:12:11 test postfix/lmtp[15274]: BA37D3097CAD: to=<admin@local.neth.eu>, orig_to=<goofy@local.neth.eu>, relay=test.local.neth.eu[/var/run/dovecot/lmtp], delay=0.21, delays=0.09/0.03/0.01/0.08, dsn=2.0.0, status=sent (250 2.0.0 <admin@local.neth.eu> MGcwM6tpf1irOwAAWXzwnQ Saved)

Test with 1 alias:
```
[root@test ~]# db accounts show
goofy@=pseudonym
    Access=public
    Account=giacomo@local.neth.eu
    Description=Goffy generic
```
Mail delivered to giacomo:
> Jan 18 14:12:56 test postfix/lmtp[15274]: 4E7823097CB0: to=<giacomo@local.neth.eu>, orig_to=<goofy@local.neth.eu>, relay=test.local.neth.eu[/var/run/dovecot/lmtp], delay=0.03, delays=0.01/0/0/0.02, dsn=2.0.0, status=sent (250 2.0.0 <giacomo@local.neth.eu> NWcwM6tpf1irOwAAWXzwnQ Saved)

**Comment by gsanchietti** [comment]
Released:
- nethserver-mail-server-1.10.6-1.ns7.noarch.rpm
