### ISSUE TITLE
Console message: failed to register logger

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5202]
At boot and on every firewall restart a "strange" message is logged to the console:
`log: failed to register logger`
See http://community.nethserver.org/t/failed-to-register-the-logger/4728 for details.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-firewall-base-3.1.4-1.4.g81af055.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.4-1.4.g81af055.ns7.noarch.rpm

*Test case*
- Execute `shorewall check` or `shorewall restart`
- Check the message doesn't appear on the console

**Comment by gsanchietti** [comment]
The message is gone, tested with these commands:
```
shorewall check
signal-event firewall-adjust
```

**Comment by gsanchietti** [comment]
Released:
- nethserver-firewall-base-3.1.5-1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.5-1.ns7.noarch.rpm
