### ISSUE TITLE
Web filter not working with profiles configured for a group

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5205]
Web filter profiles based on groups never match.
See http://community.nethserver.org/t/web-filter-not-working-with-profiles-configured-for-a-group/5517 for details.
Steps to reproduce:
1. create a restricted web filter profile
2. create a web filter profile using a group in the Who field
3. try to access a blocked site as a user contained in the group

**Comment by filippocarletti** [comment]
In nethserver-testing:
nethserver-squidguard-1.6.1-1.2.g2e08f4a.ns7.noarch.rpm

Test case:
Check that bug is not reproducible.

**Comment by gsanchietti** [comment]
Verified by @Carlos_Estrada

**Comment by gsanchietti** [comment]
Released:
nethserver-squidguard-1.6.2-1.ns7.noarch.rpm
