### ISSUE TITLE
Email alias does not expand group members

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5207]
**Steps to reproduce**

* Create a group  with some members, i.e. ``grp1@domain``, or use an existing one.
* Create an email alias ``first.group@domain`` and set ``grp1@domain`` as destination. Save the record.
* The resulting record has no destination

**Expected behavior**

The resulting record must have the members of ``grp1@domain`` set as destination. The UI must expand the group members when a group is selected as destination.

**Components**

NethServer 7 rc4
nethserver-mail-server-1.10.6

----

Thanks to @alefattorini for reporting this

**Comment by DavidePrincipi** [comment]
This is a regression bug probably caused by

NethServer/nethserver-sssd#34

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.5-1.14.ga5ab1fe.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Create one new group `tech` with two members `admin` and `giacomo`:
```
[root@test ~]# getent group tech
tech:*:1002:giacomo,admin
```

Adedd new `myalias` pseudonym pointing to the group:
```
[root@test ~]# grep myalias /etc/postfix/*
/etc/postfix/virtual:myalias@local.neth.eu                  admin@local.neth.eu,giacomo@local.neth.eu
```

**Comment by gsanchietti** [comment]
Released:
- nethserver-mail-server-1.10.7-1.ns7.noarch.rpm
