### ISSUE TITLE
dnsmasq.conf: invalid dhcp range

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5208]
dnsmasq fails to start with an error:
dnsmasq: bad dhcp-range at line 77 of /etc/dnsmasq.conf
I used systemctl status dnsmasq to see the error.

**Steps to reproduce**

- enable a dhcp range
- check if dnsmasq is running

nethserver-dnsmasq-1.6.2-1.ns7.noarch

**Comment by filippocarletti** [comment]
The issue arises only with short ethernet interface names.
dnsmasq-2.53 changed syntax for tagging, we should update our templates.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-dnsmasq-1.6.2-1.2.gcf881f2.ns7.noarch.rpm

*Test case*
Check the bug is not reproducible.

**Comment by filippocarletti** [comment]
```
dhcp-range=e0,192.168.56.1,192.168.56.254,255.255.255.0,86400
dhcp-option=e0,option:router,192.168.56.4

Jan 26 17:55:21 proxytest.neth.net dnsmasq[3430]: dnsmasq: bad dhcp-range at line 77 of /etc/dnsmasq.conf

Updated:
  nethserver-dnsmasq.noarch 0:1.6.2-1.2.gcf881f2.ns7

dhcp-range=set:e0,192.168.56.1,192.168.56.254,255.255.255.0,86400
dhcp-option=tag:e0,option:router,192.168.56.4

Jan 26 17:57:21 proxytest.neth.net dnsmasq-dhcp[3549]: DHCP, IP range 192.168.56.1 -- 192.168.56.254, lease time 1d

```

**Comment by gsanchietti** [comment]
Released:
- nethserver-dnsmasq-1.6.3-1.ns7.noarch.rpm
