### ISSUE TITLE
Domain admins members are not granted full server-manager access

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5209]
**Steps to reproduce**

- Join an AD account provider (local/remote)
- Add ``user1`` (no root, no admin, nor administrator) to group ``domain admins``
- Log in Server Manager as normal ``user1``

**Expected behavior**

``user1`` should be granted access to all modules, because ``domain admins`` is a subgroup of ``administrators``

**Actual behavior**

``user1`` has no special rights. Moreover ``administrators`` is not visible by glibc calls. This return nothing:

    getent group administrators@domain

**See also**

* #5157 
* #5168
* http://community.nethserver.org/t/change-the-default-admins-group/5570

**Components**

nethserver-sssd-1.1.4-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
We must change the default group name. ``administrators`` does not suit our needs because overlaps with the builtin AD group, that is not available from SSSD.

The new default could be ``domain admins``. The OpenLDAP provider is already fine with it.

- [ ] fix Server Manager policy parser to support a group name that contains a space
- [ ] update Administrator Manual
- [ ] change the default prop value admins/group

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-directory-3.1.2-1.3.g2545ef8.ns7.noarch.rpm
nethserver-base-3.0.16-1.2.g819865d.ns7.noarch.rpm
nethserver-sssd-1.1.4-1.3.gf6f614f.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified.

Tested with nethserver-directory and nethserver-dc.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:

nethserver-directory-3.1.3-1.ns7.noarch.rpm
nethserver-base-3.0.17-1.ns7.noarch.rpm
nethserver-sssd-1.1.5-1.ns7.noarch.rpm
