### ISSUE TITLE
Mail forward ignored by mail alias

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5210]
In /etc/postfix/virtual, if a mail alias expands to a mailbox address, any forward address defined by the mailbox is ignored.

**Steps to reproduce**

- Edit mailbox ``first.user@dpnet.nethesis.it``
- Define an external forward address and "Keep a message copy on this server"
- Create a mail alias ``first.user@[all domains]`` with destination ``first.user@dpnet.nethesis.it``

**Expected behavior**

The forward address is always honored

**Actual behavior**

Mail is delivered locally. In ``/var/log/messages``:

<pre>
...
Jan 31 12:04:51 vm5 esmith::event[15986]: postmap: warning: /etc/postfix/virtual.db: duplicate entry: "first.user@dpnet.nethesis.it"
Jan 31 12:04:51 vm5 esmith::event[15986]: Action: /etc/e-smith/events/pseudonym-create/S30nethserver-mail-postmap-update SUCCESS [0.209342]
Jan 31 12:04:51 vm5 esmith::event[15986]: Event: pseudonym-create SUCCESS
</pre>

**Components**

nethserver-mail-server-1.10.7-1.ns7.noarch

----

Thanks to @filippocarletti for pointing it out

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.7-1.5.g12fdd6d.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
No "duplicate entry..." in maillog.
Mail delivered to both addresses. Same behaviour for email on additional domain.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.8-1.ns7.noarch.rpm
