### ISSUE TITLE
Accounts DB: user type overrides existing pseudonym record

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5211]
**Steps to reproduce**

Given that ``dpnet.nethesis.it`` is the system domain name, and ``second.user@dpnet.nethesis.it`` is an existing user account.

Case 1:

- Create a mail alias record ``second.user@dpnet.nethesis.it`` with external destination
- Edit ``second.user@dpnet.nethesis.it`` mailbox properties, i.e. set a custom quota
- Save

Case 2:

- Edit ``second.user@dpnet.nethesis.it`` mailbox properties, i.e. set a custom quota
- Create a mail alias record ``second.user@dpnet.nethesis.it`` with external destination
- Save

**Expected behavior**

The UI must prevent the creation of a mail alias if its key corresponds to a system account.

**Actual behavior**

Case 1: The pseudonym record is lost! 

In ``/var/log/messages``:

<pre>
Jan 31 12:05:26 vm5 /sbin/e-smith/db[16037]: /var/lib/nethserver/db/accounts: OLD second.user@dpnet.nethesis.it=pseudonym|Access|public|Account|second.user@dpnet.nethesis.it|Description|override
...
Jan 31 12:05:26 vm5 /sbin/e-smith/db[16037]: /var/lib/nethserver/db/accounts: NEW second.user@dpnet.nethesis.it=user|MailForwardAddress||MailForwardKeepMessageCopy|no|MailForwardStatus|disabled|MailQuotaCustom|15|MailQuotaType|custom|MailSpamRetentionStatus|disabled|MailSpamRetentionTime|180d|MailStatus|enabled|QuotaStatus|disabled
</pre>

Case 2: The user record is lost!

**Components**

nethserver-mail-server-1.10.7-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.7-1.9.g00fe7ed.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
Added string translations to Transifex

Translated to Italian

**Comment by filippocarletti** [comment]
In both test cases, the system prevented the creation of the mail alias with the error "An user account with the same name already exists".
I used nethserver-mail-server-1.10.7-1.12.g60661bd.ns7.noarch which contains the fix.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.8-1.ns7.noarch.rpm
