### ISSUE TITLE
Support short login with POP3 

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5212]
**Steps to reproduce**

Given ``first.user@dpnet.nethesis.it`` is a valid user account and its mailbox has one new message, run the following POP3 session:

<pre>
[root@vm5 ~]# nc -C localhost 110
+OK Dovecot ready.
USER first.user@dpnet.nethesis.it
+OK
PASS Nethesis,1234
+OK Logged in.
STAT
+OK 1 1581
QUIT
+OK Logging out.
</pre>

Now use short user name form:

<pre>
[root@vm5 ~]# nc -C localhost 110
+OK Dovecot ready.
USER first.user
+OK
PASS Nethesis,1234
+OK Logged in.
STAT
+OK 0 0
QUIT
+OK Logging out.
</pre>

**Expected behavior**

Both login forms should lead to the same mailbox:

    /var/lib/nethserver/vmail/first.user@dpnet.nethesis.it/

**Actual behavior**

Only long user name form works: the short form leads to an empty mailbox.

A wrong mailbox is created by dovecot:

    /var/lib/nethserver/vmail/first.user

**Components**

nethserver-mail-server-1.10.7-1.ns7.noarch

**See also**

- http://docs.nethserver.org/en/v7rc/accounts.html#credentials-for-services
- http://community.nethserver.org/t/pop3-imap-shows-empty-folders-on-ns7-3-rc4-if-ns-adc-only/5612

----

Thanks to **Andreas Schloegl** for the help with finding the bug

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.7-1.12.g60661bd.ns7.noarch.rpm

**QA note**

The POP3 log message must now be directed to ``/var/log/imap``.

**Comment by filippocarletti** [comment]
```
$ nc 192.168.56.234 110
+OK Dovecot ready.
user filippo.carletti
+OK
pass x
+OK Logged in.
stat
+OK 1 692
quit
+OK Logging out.

$ nc 192.168.56.234 110
+OK Dovecot ready.
user filippo.carletti@neth.net
+OK
pass x
+OK Logged in.
stat
+OK 1 692
quit
+OK Logging out.

[root@ns7-com ~]# tail /var/log/imap
Feb 13 11:30:03 ns7-com dovecot: pop3-login: Login: user=<filippo.carletti>, method=PLAIN, rip=192.168.56.1, lip=192.168.56.234, mpid=18029, session=<rWYu7mZIggDAqDgB>
Feb 13 11:30:08 ns7-com dovecot: pop3(filippo.carletti@neth.net): Disconnected: Logged out top=0/0, retr=0/0, del=0/1, size=692
Feb 13 11:30:35 ns7-com dovecot: pop3-login: Login: user=<filippo.carletti@neth.net>, method=PLAIN, rip=192.168.56.1, lip=192.168.56.234, mpid=18037, session=<1gAU8GZIwADAqDgB>
Feb 13 11:30:40 ns7-com dovecot: pop3(filippo.carletti@neth.net): Disconnected: Logged out top=0/0, retr=0/0, del=0/1, size=692

[root@ns7-com ~]# rpm -q nethserver-mail-server
nethserver-mail-server-1.10.7-1.12.g60661bd.ns7.noarch


```

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.8-1.ns7.noarch.rpm
