### ISSUE TITLE
OpenVPN: clients not restarted after modification

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5213]
Modifications to OpenVPN clients are not applied.

**Steps to reproduce**

- Got to "OpenVPN" page and open "Cleitn" tab
- Create a client
- Check the client is started
- Modify a client

**Expected behavior**

The client must be restarted with new configuration

**Actual behavior**

The client is not restarted

**Workaround**

Manually restart the service:
```
systemctl restart openvpn@clientname
```

**Components**
nethserver-openvpn-1.4.4-1.ns7.noarch

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-openvpn-1.4.4-1.1.g24c5e5b.ns7.noarch.rpm

**Comment by cotosso** [comment]
I tested the packet and it worked as expected.

**Comment by gsanchietti** [comment]
Released:
- nethserver-openvpn-1.4.5-1.ns7.noarch.rpm
