### ISSUE TITLE
disk usage: no graph showed

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#5214]
**Steps to reproduce**

- Backup-data path configured
- Open Disk Usage graph tab in NethServer GUI

**Expected behavior**

The disk usage component must show the graph correctly

**Actual behavior**

The screen is blank

**Components**

NethServer **6.8** and NethServer **7**
`nethserver-duc` `1.0.5` in 6.8
`nethserver-duc` `1.4.1` in 7

**See also**

http://community.nethserver.org/t/disk-usage-no-graph/5668/13

**Comment by gsanchietti** [comment]
In nethserver-testing for NS 7:
- nethserver-duc-1.4.1-1.2.g509d5e7.ns7.noarch.rpm

*Test case*
- Check the bug is not reproducibile

**Comment by gsanchietti** [comment]
Tested, ok.

**Comment by gsanchietti** [comment]
Released:
- nethserver-duc-1.0.6-1.ns6.noarch.rpm
- nethserver-duc-1.4.2-1.ns7.noarch.rpm
