### ISSUE TITLE
Help the sysadmin on configuring the accounts provider

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5215]
If an accounts provider is not configured yet, the Domain accounts and "Users and groups" pages could display some background information to help the sysadmin on deciding what to do.

See also:
http://community.nethserver.org/t/discussion-scenarios-to-choose-an-account-provider/5009/14?u=davidep

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.1.6-1.1.gfd4ff7c.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
## New install, no accounts provider configured:

```
Updated:
  nethserver-httpd-admin.noarch 0:2.0.7-1.1.ga42bd06.ns7                 nethserver-sssd.noarch 0:1.1.6-1.1.gfd4ff7c.ns7
```

Everything's in order.
Clicking on the Configure button, I see the Accounts provider page
Clicking on Install, I got to the Software Center.
Clicking "No. thanks!", I found myself on the dashboard.

## Update of Samba AD (nethserver-dc) provider

No visible changes

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-sssd-1.1.7-1.ns7.noarch.rpm
