### ISSUE TITLE
User mail quota ignored during message delivery

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5216]
**Steps to reproduce**

- enable general mail quota with default 500MB
- first.user@domain has 400MB in his mailbox
- set user quota to first.user@domain at 300MB
- login with roundcube and try to save a draft message: an error message says there's no space left
- send a message to first.user@domain: message is delivered

**Expected behavior**

The message must not be delivered, and a bounce message "Quota exceeded (mailbox for user is full)" sent back to the sender.

**Actual behavior**

The message is actually delivered ignoring the 300MB limit.

**Components**

nethserver-mail-server-1.10.7

**See also**

http://community.nethserver.org/t/mail-quota-not-updated-if-user-quota-changed/5656

----

Thanks to Andreas Schloegl for pointing it out!

**Comment by DavidePrincipi** [comment]
Se could also avoid bounces by implementing a quota service for postfix:

http://wiki2.dovecot.org/Quota

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.8-1.18.g75debea.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.8-1.21.g0869a51.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
On a clean installation it works as expected.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.9-1.ns7.noarch.rpm
