### ISSUE TITLE
Squid parent proxy can no be set to ADDRESS:PORT in Ui

### ISSUE THREAD

**Issue by bachp** [NethServer/dev#5217]
**Steps to reproduce**

1. Activate the squid (web proxy) module
2. Go to Web Proxy configuration
3. In the advanced section enter a proxy with port number like this: `1.2.3.4:1234`

**Expected behavior**

The proxy is accepted and configured.

**Actual behavior**

The value is rejected saying only empty or IPv4 address is allowed.

**Components**

NethServer 7

**See also**

I think the issue is here: https://github.com/NethServer/nethserver-squid/blob/52d818f16896ddda3ccbc80cd86c101082012eb0/root/usr/share/nethesis/NethServer/Module/Proxy/Squid.php#L45

As it validates only against ` Validate::IPv4_OR_EMPTY`.
For a test I changed it to ` Validate::ANYTHING` an then it works. Not sure this is the correct validation.
I'm also not sure if DNS names should be allowed like: `xyz.examle.com:8118`?

**Comment by bachp** [comment]
I just confirmed that DNS names are working for Squid so I think the should be allowed too.

**Comment by DavidePrincipi** [comment]
Thank you for your detailed report @bachp! We usually discuss issues on

http://community.nethserver.org

before filling a bug report here! 

Why do you need to change the default port? What is your goal?

**Comment by bachp** [comment]
I wanted to use a different upstream proxy then the global one. It was mainly a test.
The upstream proxy is not listening on the default port `3128` but something else and as the input field clearly states to enter "IP:port" I thought I report the issue.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-squid-1.5.2-1.2.g692f83a.ns7.noarch.rpm

*Test case*
Check the bug is not reproducible.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-squid-1.5.3-1.ns7.noarch.rpm
