### ISSUE TITLE
Install on CentOS: nethserver-install fails

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5218]
**Steps to reproduce**

- install CentOS 7.3 minimal
- install nethserver-release
- run nethserver-install

**Expected behavior**

NethServer is installed and configured

**Actual behavior**

The nethserver-install script outputs

<pre>
Failed to start nethserver-system-init.service: Operation refused, unit nethserver-system-init.service may be requested by dependency only.
</pre>

**Components**

nethserver-release-7-1.ns7.noarch

**See also**

See http://community.nethserver.org/t/accountprovider-error-1-direct-after-configuring-active-directory/5771

----

Thanks to stevest81 for reporting this issue

**Comment by DavidePrincipi** [comment]
**NOTE**

firewalld and NetworkManager could be running on a CentOS system

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-release-7-1.1.ge9e2319.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
*Test case*

- On a clean CentOS 7, execute:
```
yum install http://packages.nethserver.org/nethserver/7.3.1611/testing/x86_64/Packages/nethserver-release-7-1.1.ge9e2319.ns7.noarch.rpm -y
nethserver-install
```
Then check the system-init has been successfully executed.

**Comment by gsanchietti** [comment]
Tested on:
- Digital Ocean
- dply.co

**Comment by dz00te** [comment]
test on c7 on proxmox.. all ok

**Comment by gsanchietti** [comment]
Released:
- nethserver-release-7.0.8-1.ns7.noarch.rpm
