### ISSUE TITLE
OpenVPN: remove net2net client mode with user name and password authentication

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5219]
Inside the "Clients" tab of OpenVPN page, the user can configure a vpn client using only user name and password.

But current version of OpenVPN doesn't allow such scenario: the client is always required to have the CA certificate.

Since this mode is almost unused, we can remove it and promote the user of net2net client connections using certificate.

Reference: https://openvpn.net/index.php/open-source/documentation/howto.html#auth

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-openvpn-1.4.5-1.2.g4f80c30.ns7.noarch.rpm

*Test case*
- Open the "Clients" tab under "OpenVPN" page
- Try to create a new client and check "Username and password" authentication mode is gone  
- Check the English inline help doesn't contain the related documentation

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-openvpn-1.4.6-1.ns7.noarch.rpm
