### ISSUE TITLE
dahdi kernel modules not present for kernel 3.10.0-514.6.1.el7

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5221]
kmod-dahdi-linux install kernel modules under /lib/modules/3.10.0-514.el7.x86_64/extra/dahdi/. weak-updates is expected to copy those modules under new kernel directory on its installation, but this doesn't happen.

**Steps to reproduce**
Install nethserver-freepbx NethServer 7
`yum install -y centos-release-scl`
`yum --enablerepo=nethserver-testing clean all` 
`yum --enablerepo=nethserver-testing install nethserver-freepbx`

make sure kernel is updated 
`yum update`

**Expected behavior**

being able to load dahdi modules
have dahdi modules under /lib/modules/3.10.0-514.2.2.el7.x86_64/extra/

**Actual behavior**

modprobe can't find any modules, empty /lib/modules/3.10.0-514.6.1.el7.x86_64/extra/ directory

**Components**

NethServer release 7.3.1611 (Final)
kmod-dahdi-linux-2.11.1-3.10.0_514.el7.ns7.x86_64

**Comment by Stell0** [comment]
- EDIT -
kernel modules are correctly moved in /lib/modules/3.10.0-514.6.1.el7.x86_64/weak-updates/dahdi but aren't automatically loaded at boot.

**Comment by Stell0** [comment]
nethserver-testing kmod-dahdi-linux-2.11.1-3.10.0_514.el7.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
Recompiled to increase the release:

- dahdi-linux-kmod-2.11.1-3.10.0_514.el7.1.ns7.src.rpm 
- kmod-dahdi-linux-2.11.1-3.10.0_514.el7.1.ns7.x86_64.rpm

These packages will be in nethserver-testing until nethserver-freepbx release.
