### ISSUE TITLE
Mail domain option Accept unknown recipients overrides valid addresses

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5222]
"Mail domain > deliver locally" page. If the checkbox "Accept unknown recipients" is checked and an account is given, all E-Mail is wrongly delivered to this account and not the original (existing!) recipient.

**Steps to reproduce**

- Create Email domain "xyz.intern", choose "Deliver locally".
- Check "Accept unknown recipients", set "Deliver to" = "administrator@xyz.intern".
- Create user "test@xyz.intern" (admin and administrator user already exist)
- Send an E-Mail to "test@xyz.intern"

**Expected behavior**

Message is delivered to "test@xyz.intern"

**Actual behavior**

Message is delivered to "administrator@xyz.intern"

**Components**

nethserver-mail-server-1.10.8-1.ns7.noarch

**See also**

http://community.nethserver.org/t/e-mail-wrongly-delivered-to-account-given-in-accept-unknown-recipients/5865

----

Thanks to **uliversal** (Uli Gr) for his bug report!

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.8-1.5.g8683219.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
*note* successfully installed on a production mail server, catchall disabled

**Comment by gsanchietti** [comment]
Catchall enabled, mail to non existing address correctly redirected:
```
Feb 28 17:45:23 testms postfix/lmtp[8652]: 6DD753124593: to=<giacomo@nethesis.it>, orig_to=<unknonw@mylocal.org>, relay=testms.nethesis.it[/var/run/dovecot/lmtp], delay=0.02, delays=0/0/0/0.01, dsn=2.0.0, status=sent (250 2.0.0 <giacomo@nethesis.it> dRyjCg6ptVjNIQAAUbCteQ Saved)
```

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.9-1.ns7.noarch.rpm
