### ISSUE TITLE
Allow removal of primary mail domain

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5227]
If the host (primary) domain is not in DNS, the corresponding record in *domains* e-smith DB should be removed. The mail server configuration must support this use case. Mail directed to any address in the primary domain must be rejected.

**See also**

http://community.nethserver.org/t/how-to-name-the-ad-domain/5924

----

Thanks to **uliversal**

**Comment by DavidePrincipi** [comment]
*Test case 1*

- remove the primary domain record from *domains* e-smith DB
- connect to port 25 from an external host, start a SMTP session
- check any address in the primary domain is now rejected

*Test case 2*

- recreate the primary domain record
- check the existing mail addresses in primary domain are now accepted
- non-existing mail addresses must be rejected

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.8-1.5.g8683219.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified both test cases.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.9-1.ns7.noarch.rpm
