### ISSUE TITLE
Samba secrets.tdb is missing from backup set

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5228]
After restoring a configuration backup the "Domain accounts" page has the following error message:

    Join to domain is not valid: NT code 0xfffffff6

Users and groups page

    AccountProvider_error_1

In ``/var/log/messages``:

<pre>
Feb 14 17:35:09 server7c httpd: [ERROR] NethServer\Tool\UserProvider: AccountProvider_Error_1
Feb 14 17:35:09 server7c httpd: [ERROR] Traceback (most recent call last):#012  File "<stdin>", line 3, in <module>#012KeyError: 'SECRETS/MACHINE_PASSWORD/domain'#012Traceback (most recent call last):#012  File "<stdin>", line 3, in <module>#012KeyError: 'SECRETS/MACHINE_PASSWORD/domain'#012(1) 00002020: Operation unavailable without authentication
Feb 14 17:35:40 server7c httpd: [ERROR] NethServer\Tool\GroupProvider: AccountProvider_Error_1
Feb 14 17:35:40 server7c httpd: [ERROR] Traceback (most recent call last):#012  File "<stdin>", line 3, in <module>#012KeyError: 'SECRETS/MACHINE_PASSWORD/domain'#012Traceback (most recent call last):#012  File "<stdin>", line 3, in <module>#012KeyError: 'SECRETS/MACHINE_PASSWORD/domain'#012(1) 00002020: Operation unavailable without authentication
</pre>

These symptoms originate from a bad backup archive: the samba secrets.tdb is missing from backup set!

**Steps to reproduce**

- Run ``backup-config``
- Search for ``secrets_tdb.dump`` in backup-config archive
<pre>
 tar tfv /var/lib/nethserver/backup/backup-config.tar.xz  | grep -F secrets_tdb.dump
</pre>

**Expected behavior**

The file is present

**Actual behavior**

The file is not present

**Components**

nethserver-backup-config-1.5.2-1.ns7.noarch
nethserver-backup-data-1.2.3-1.ns7.noarch
nethserver-sssd-1.1.7-1.ns7.noarch
nethserver-samba-2.0.4-1.ns7.noarch
nethserver-dc-1.1.2-1.ns7.x86_64

**See also**

http://community.nethserver.org/t/disaster-recovery-failure-revisited/5832

----

Thanks to @fasttech for reporting the issue

**Comment by DavidePrincipi** [comment]
**Workaround**

<pre>
signal-event nethserver-sssd-leave
realm join -U admin $(hostname -d)
    ...[enter admin's password]
signal-event nethserver-sssd-save
</pre>

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.1.7-1.5.g514186f.ns7.noarch.rpm

**Comment by fasttech** [comment]
Success!!
Full config and data restore.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-sssd-1.1.8-1.ns7.noarch.rpm
