### ISSUE TITLE
LDAP users not listed with remote accounts provider

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5229]
User entries in a remote LDAP accounts provider, RFC2307 compliant, could be missing the "shadowAccount" objectClass. Such entries are not shown by the User tab in Server Manager. 

**Steps to reproduce**

- bind to a remote LDAP accounts provider, where user entries do not have shadowAccount objectClass (i.e. Zentyal)
- go to Users tab

**Expected behavior**

The list of users is shown

**Actual behavior**

The list is empty

**Components**

nethserver-sssd-1.1.7-1.ns7.noarch

**See also**

http://community.nethserver.org/t/bind-to-zentyal-ldap/5964
http://community.nethserver.org/t/zentyal-2-ldap-as-accounts-provider/6028/2

----

Many thanks to **gondrano** for reporting the issue and suggesting the fix!

**Comment by DavidePrincipi** [comment]
To test the fix with a local LDAP accounts provider

Create ``first.user``, then strip shadowAccount attributes with the following command:

<pre>
ldapmodify -Y EXTERNAL &lt;&lt;EOF
dn: uid=first.user,ou=People,dc=directory,dc=nh  
changetype: modify
delete: shadowWarning
-
delete: shadowMin
-
delete: shadowMax
-
delete: shadowInactive
-
delete: shadowExpire
-
delete: shadowLastChange
-
delete: shadowFlag
-
delete: objectClass
objectClass: shadowAccount
EOF
</pre>

**Comment by gsanchietti** [comment]
The fix has been tested with success.

**Comment by gsanchietti** [comment]
Released:
- nethserver-sssd-1.1.9-1.ns7.noarch.rpm
