### ISSUE TITLE
nethserver-diagtools in nethserver@iso

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5230]
I worked on a module to diagnose some network issues -> https://github.com/stephdl/nethserver-diagtools/tree/ns7

I would be pleased if it could be incorporated in the base systems, principally because when you need it, you cannot install something and it drives you to use the CLI to understand your problem.

The discussion could be on the email test Tab, it could be elsewhere, but the module works.

**Comment by DavidePrincipi** [comment]
I agree with you! This great contribution deserves a place in the ISO!

Before doing this, I think two steps are required:

* Add a license header on every source file, and add a COPYING file with the full license text. I suggest GPLv3, as the other NethServer components. You can cut-paste these [license header models](http://docs.nethserver.org/projects/nethserver-devel/en/v7/license_headers.html). Please **fix the Copyright section** with your name and email address.
* On GitHub, transfer the repository ownership to NethServer (of course, you'll retain write access on it!)

**Comment by stephdl** [comment]
sorry I missed this post.

Do [this license](http://www.wtfpl.net/) is possible and compatible with the previous Licences of Nethserver. Do we need to to find a lawyer ?

I agree to transfer the repository :)

**Comment by stephdl** [comment]
ok, license and repository ownership done

**Comment by DavidePrincipi** [comment]
Thank you for distributing you work under the GPL license! I was afraid you were applying WTFPL :sweat_smile:

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-diagtools-0.0.8-1.4.g89e1d13.ns7.noarch.rpm

**Not for release**

Add the package to ``nethserver-iso`` package group

**Comment by dz00te** [comment]
Tested on:
- a new and updated VM
- my home firewall (2 eth green)
- my test raspberry (eth+wifi green bridged)
- tested update script

all ok. tnx!

**Comment by stephdl** [comment]
@dz00te, first thank for your time for testing and verifying. I just would suggest you to add in your verification template the exact name with the version you tested. In case of several rpm it could be beneficial.
@+

**Comment by dz00te** [comment]
@stephdl,  yes, you are right, in effect my template for qa is a little different and include package version. Usually i use it but this time I  was in hurry... sorry. This is the report also with some note I had not written for the same reason. 
Let me know if you think i should also add other information on template. tnx


*System and  Package Version installed*
Test1: HP N36L - Production install of NS7.3 full updated
Test2: VM KVM - Clean install of Nethserver 7.3 fully updated
Test3: RaspberryPi 3 - NS7.3 Arm on not so clean Dev/test environment

*Install Updated Package*
yum --enablerepo=nethserver-testing install nethserver-diagtools-0.0.8-1.4.g89e1d13.ns7.noarch
(on rpi3 installed with yum localinstall)

*Test Results after update*
Test1:
installed and tested different function OK
test update script OK

Test2:
installed and tested different function OK
test update script OK

Test3
update package (version of stephdl repo already installed)
and tested different function OK
test update script OK


note: 
- just only a minor graphics in scan tab: the second text line "Starting arp-scan..." is a little bigger than the outside line
- "i'll comply" with @DavidePrincipi request to avoid sending an empty email message, but i liked to receive the email :)
- does the diagnostic need also an inline help?

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-diagtools-1.0.0-1.ns7.noarch.rpm

(added to comps https://github.com/NethServer/comps/commit/72bccd1919b6360f3d11b5212529212e1cdd78aa)

**Comment by stephdl** [comment]
thank @dz00te and all others, nice to see this work online...let's go further :)
