### ISSUE TITLE
WebTop 4 goes in maintenance mode

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5231]
Every time tomcat is restarted, WebTop 4 goes in maintenance mode.

**Steps to reproduce**

- Install nethserver-webtop4 and nethserver-directory
- Login into WebTop
- Restart tomcat: ``systemctl restart tomcat``

**Expected behavior**

The user must be able to login again into WebTop.

**Actual behavior**

The user can't login because WebTop is in maintenance mode.

**Components**

nethserver-webtop4-1.3.7-1.ns7.noarch

----

Thanks to @lucagasparini

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-webtop4-1.3.7-1.2.g640077c.ns7.noarch.rpm

**Test case**
Check the bug is not reproducible.

**Comment by wbilger** [comment]
I tried the fix and it worked, thanks.

**Comment by gsanchietti** [comment]
Released:
- nethserver-webtop4-1.3.8-1.ns7.noarch.rpm
