### ISSUE TITLE
Relay rejected for primary mail domain

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5233]
**Steps to reproduce**

- Under Email > Domains edit the primary domain (i.e. example.com)
- Select transport ``Relay`` to ``remote-host.example.com``

**Expected behavior**

When a message is sent to ``user@example.com`` the mail system relays it to ``remote-host.example.com``.

**Actual behavior**

The email is rejected with the following message:

<pre>
Recipient address rejected: User unknown in virtual mailbox table;
</pre>

**Components**

nethserver-mail-server-1.10.9-1.ns7.noarch

**See also**

http://community.nethserver.org/t/relay-to-internal-mail-server/6060

----

Thanks to **Ya_Ley** for reporting it!

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.9-1.4.gbb782b9.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
- Tested on a production system with local delivery
- Tested by Ya_Ley on his gateway

**Comment by gsanchietti** [comment]
Tested also on a clean machine.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.10-1.ns7.noarch.rpm
