### ISSUE TITLE
NFR: Web filter https default block page

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5236]
The new web filter (based on ufdbguard) has an option to redirect blocked https sites to a different page.
To improve the user experience, the page should be served from a web server with a "valid" (issued by a CA) certificate.
I propose to use blocked.nethserver.org hosted on www.nethserver.org which has a LE cert.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-squidguard-1.6.2-1.2.gdca652f.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
Test case

Try to browse a blocked site (add one if necessary): you should see the block page (the browser will probably display a warning about the certificate being for www.nethserver.org).

**Comment by DavidePrincipi** [comment]
**VERIFIED**

Firefox blocks the site and don't allow to see blocked.nethserver.org at all

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-squidguard-1.7.0-1.ns7.noarch.rpm
