### ISSUE TITLE
WebTop 5: contacts don't work at all

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5237]
See upstream issue: https://redmine.sonicle.com/issues/145

**Components**

- nethserver-webtop5-1.0.0-1.ns7.noarch.rpm
- webtop5-core-1.0.0-1.ns7.noarch.rpm
- webtop5-libs-1.0.0-1.ns7.noarch.rpm
- webtop5-zpush-1.0.0-1.ns7.noarch.rpm

**See also**
http://community.nethserver.org/t/deeper-investigation-into-using-webtop-for-our-mail/6072/7

----

Thanks to @GG_jr for reporting.

**Comment by gsanchietti** [comment]
The fix is available here: http://www.sonicle.com/nethesis/webtop5/nethesis-webtop5-rc5.zip

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-webtop5-1.0.0-1.1.g819126f.ns7.noarch.rpm
- webtop5-core-1.0.0-1.1.g9447a2a.ns7.noarch.rpm

*Test case*
Check the bug is not reproducible

**Comment by lucagasparini** [comment]
OK!
The bug is no longer present.

**Comment by gsanchietti** [comment]
Released:
- webtop5-core-1.0.1-1.ns7.noarch.rpm
- nethserver-webtop5-1.0.1-1.ns7.noarch.rpm
