### ISSUE TITLE
OpenVPN: no internet access if Route all client traffic through VPN is on

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5238]
**Steps to reproduce**

- configure host to net openvpn with Route all client traffic through VPN enabled
- connect a client via vpn
- try to browse the net from the client: no route

**Expected behavior**

The client should access the internet through nethserver

**Actual behavior**

No internet access

**Components**

nethserver-openvpn-1.4.6-1.ns7.noarch

**See also**

http://community.nethserver.org/t/shorewall-block-openvpn-traffic-out/6075/16?u=filippo_carletti

----

Thanks to Simplimus and JOduMonT

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-openvpn-1.4.5-1.5.gfe99259.ns7.noarch.rpm

**Test case**
Check the bug is not reproducible.

**Comment by dz00te** [comment]
> In nethserver-testing:
nethserver-openvpn-1.4.5-1.5.gfe99259.ns7.noarch.rpm

is the package name correct? i've already installed nethserver-openvpn-1.4.6-1.ns7.noarch....

**Comment by gsanchietti** [comment]
You're right, we messed up with the tags.
I just added the correct packages in nethserver-testing:
- nethserver-openvpn-1.4.6-1.4.g66f51df.ns7.noarch.rpm

**Comment by dz00te** [comment]
*System and  Package Version installed*
HP N40L -  Production Home Firewall install Nethserver 7.3 fully updated
Package Installed:  openvpn-2.3.14-1.el7.x86_64
nethserver-openvpn-1.4.6-1.ns7.noarch
and a lot of other

*Test Original Problem*
Enable “Route all client traffic through VPN”, block all internet traffic

*Install Updated Package*
yum --enablerepo=nethserver-testing install nethserver-sssd-1.1.1-1.4.g334d0e9.ns7.noarch

*Test Results after update*
1. installed while openVPN client (openvpn fedora 25) was still active, after a auto-restart of the connection, browsing internet is ok (while i can't ping external site, but this could be a problem of my config)

note: also if my test is ok, i don't set it as verified.
My test server has some custom-template on openvpn server and some changes on client config. So i would like if someone else could test it on a more "normal" installation

**Comment by gsanchietti** [comment]
Tested also on my machine, it's ok.

**Comment by gsanchietti** [comment]
Released:
- nethserver-openvpn-1.4.7-1.ns7.noarch.rpm
