### ISSUE TITLE
WebTop5: can't access with master user

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5239]
The administrator can't access all mailboxes with the master user.

**Steps to reproduce**

- Install nethserver-directory and create a user named ``goofy``
- Install nethserver-webtop5
- Go to the login page and fill the user field with ``admin!goofy``
- Fill the password field with admin password

**Expected behavior**

The admin user should be able to access the goofy mail.

**Actual behavior**

The admin user can't login.

The vmail password is saved under ``com.sonicle.webtop.core`` option, while it should be under ``com.sonicle.webtop.mail``.

**Components**

nethserver-webtop5-1.0.1-1.ns7.noarch

**Workaround**
Execute this query on webtop5 DB:
```
INSERT INTO "core"."settings" VALUES ('com.sonicle.webtop.mail', 'nethtop.vmail.secret', 'vmailsecret');
```
where ``vmailsecret`` is the value found inside ``/var/lib/nethserver/secrets/vmail``

**Comment by gsanchietti** [comment]
You can check the new option using this command:
```
su - postgres -c 'psql webtop5'
```
Then execute this query:
```
select * from core.settings where service_id = 'com.sonicle.webtop.mail' and key = 'nethtop.vmail.secret';
```

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-webtop5-1.0.1-1.1.gaea3970.ns7.noarch.rpm

**Test case**
Check the bug is not reproducible.

**Comment by lucagasparini** [comment]
The bug is fixed.
Note:
The admin user can access a user's profile if the user that performed the first login

**Comment by gsanchietti** [comment]
Released:
- nethserver-webtop5-1.0.2-1.ns7.noarch.rpm
