### ISSUE TITLE
Migration to NS7: time not synced

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5240]
Migrated an old sme8 to NS7, the new system does not sync date from external ntp server.
`chronyc sources -v` reports 0 sources.
The problems comes from:
https://github.com/NethServer/nethserver-ntp/commit/a8d031e7dbc17ba116a9730f16d28a2221230e50

```
[root@ns7ent ~]# config show chronyd
chronyd=service
    NTPServer=smeserver.pool.ntp.org
    UDPPort=123
    access=green
    status=enabled
```

```
[root@mail ~]# ping -c 1 smeserver.pool.ntp.org
ping: unknown host smeserver.pool.ntp.org
```

**Comment by DavidePrincipi** [comment]
It seems the configuration is wrong on sme8, too!

Should we add an ad-hoc automatic replacement, ``smeserver.pool.ntp.org => pool.ntp.org`` ?

**Comment by filippocarletti** [comment]
No, on sme8 the prop is used to build the correct hostname during template expansion.
@gsanchietti suggested to remove the migration fragment, since the user has already set TZ during the FCW and the pooo.ntp.org default works.

**Comment by DavidePrincipi** [comment]
I'm concerned about losing a customized value: whilst the great part of my customers have the default value, some of them have NTPServer customized. I can't assume the ``pool.ntp.org`` default value is suitable for them.

I'd go with the default replacement only if the source value is at sme8 default, too.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-ntp-1.1.2-1.2.g072594c.ns7.noarch.rpm

**Test case**
Check the bug is not reproducibile

**Comment by DavidePrincipi** [comment]
**VERIFIED**

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-ntp-1.1.3-1.ns7.noarch.rpm
