### ISSUE TITLE
Nextcloud 11

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5242]
Upgrade Nextcloud to latest upstream release (11.0.2).
The new package must handle new installation and the upgrade from Netxtcloud 10.

See upstream commit: https://github.com/nextcloud/server-packages/commit/c4e817ac222d420db48c50bff5fc0a7eb66f6a48

**Packages**

* nethserver-nextcloud
* nextcloud

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nextcloud-11.0.2-1.ns7.noarch.rpm
* nethserver-rh-php56-php-fpm
* nethserver-nextcloud-1.0.4-1.4.g0b07b4f.ns7.noarch.rpm

**Test case 1**
- Install on a clean machine with local LDAP or Samba AD
- Check everything correctly works

**Test case 2**
- Install on a clean machine with remote LDAP or AD
- Check everything correctly works

**Test case 3**
- Upgrade a running machine with Netxtcloud 10 with local LDAP or Samba AD
- Check everything correctly works

**Test case 4**
- Upgrade a running machine with Netxtcloud 10 with remote LDAP or AD
- Check everything correctly works

*Note*
The "Strict-Transport-Security"  header can be set only on a dedicate virtual host.
https://docs.nextcloud.com/server/11/admin_manual/configuration_server/harden_server.html

**Comment by alepolidori** [comment]
**Test case 1**  (using LDAP)

Installed packages:
```
[root@nscom73 nextcloud]# rpm -q nextcloud nethserver-nextcloud nethserver-rh-php56-php-fpm
nextcloud-11.0.2-1.ns7.noarch
nethserver-nextcloud-1.0.4-1.4.g0b07b4f.ns7.noarch
nethserver-rh-php56-php-fpm-0.0.1-1.2.g73acebd.ns7.noarch
nethserver-directory-3.1.4-1.ns7.noarch
```
**Basic functions work great: are very fast !**

*Note*
I've uploaded some files, navigated through tree directory, opened video file, opened pdf file, shared file with another LDAP user,...
The only problem I've to report is opening pdf file with empty space into the filename, but as the screenshot shows, I think this is a problem of the "files_pdfviewer" nextcloud app that uses pdf.js library and not of the nethserver-nextcloud !

![nc_error_pdf](https://cloud.githubusercontent.com/assets/1625334/24005048/3882cf1a-0a68-11e7-9b46-0b12114c7469.png)

Log of /var/log/httpd/ssl_error_log:
````
[Thu Mar 16 17:02:23.193426 2017] [proxy_fcgi:error] [pid 16667] [client 192.168.5.60:50064] Invalid status line from script 'Nextcloud%20Manual.pdf': 0, referer: https://192.168.5.46/nextcloud/apps/files_pdfviewer/vendor/pdfjs/build/pdf.worker.js?v=1.0.1
````

**Comment by alepolidori** [comment]
**Test case 1**  (using AD)

Installed packages:
```
[root@nscom73 ~]# rpm -q nextcloud nethserver-nextcloud nethserver-rh-php56-php-fpm
nextcloud-11.0.2-1.ns7.noarch
nethserver-nextcloud-1.0.4-1.4.g0b07b4f.ns7.noarch
nethserver-rh-php56-php-fpm-0.0.1-1.2.g73acebd.ns7.noarch
```

**Basic functions work great !**

*Note*
The "users" page show some additional items of AD:
![usernc](https://cloud.githubusercontent.com/assets/1625334/24041279/e74cd4c4-0b0c-11e7-802a-34d7be088385.png)

**Comment by alepolidori** [comment]
**Test case 3**  (using AD)

Result: _failed_

This is the login page after update:

![ncupdatead](https://cloud.githubusercontent.com/assets/1625334/24050547/6c6d3f00-0b2f-11e7-8b2b-22676fb71df6.png)

A section from /var/log/messages contains:
```
Mar 17 16:31:51 nscom73 esmith::event[23982]: 
Mar 17 16:31:51 nscom73 su: (to apache) root on none
Mar 17 16:31:51 nscom73 esmith::event[23982]: Nextcloud is not installed - only a limited number of commands are available
Mar 17 16:31:51 nscom73 esmith::event[23982]: 
Mar 17 16:31:51 nscom73 esmith::event[23982]:                                                                  
Mar 17 16:31:51 nscom73 esmith::event[23982]:  [Symfony\Component\Console\Exception\CommandNotFoundException]
Mar 17 16:31:51 nscom73 esmith::event[23982]:  There are no commands defined in the "ldap" namespace.
```

This can be caused by "occ" tool.
Once upgraded the only commands it provides are:
```
[root@nscom73 nextcloud]# runuser -s /bin/bash apache -c "./occ"
Nextcloud is not installed - only a limited number of commands are available
Nextcloud version 11.0.2

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --no-warnings     Skip global warnings, show command output only
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  _completion           BASH completion hook.
  check                 check dependencies of the server environment
  help                  Displays help for a command
  list                  Lists commands
  status                show some status information
 app
  app:check-code        check code to be compliant
 integrity
  integrity:check-app   Check integrity of an app using a signature.
  integrity:check-core  Check integrity of core code using a signature.
  integrity:sign-app    Signs an app using a private key.
  integrity:sign-core   Sign core using a private key.
 l10n
  l10n:createjs         Create javascript translation files for a given app
 maintenance
  maintenance:install   install Nextcloud

```

**Comment by dnutan** [comment]
**Test case 3** (using AD)
Result: failed

Same result reported by @alepolidori 
After the update *occ* is no longer at `/var/www/html/nextcloud/occ` but `/usr/share/nextcloud/occ`

**Comment by gsanchietti** [comment]
> The "users" page show some additional items of AD:

Those are Active Directory default groups, I'd prefer to not hide them with a special LDAP filter.

I just updated the RPM which should handle the upgrade:

- nethserver-nextcloud-1.0.4-1.6.gbc8a610.ns7.noarch.rpm

**Comment by alepolidori** [comment]
**Test 3** (using AD)
Now it works ! :+1:

**Comment by alepolidori** [comment]
**Test 1, Test 3** OK !

**Comment by DavidePrincipi** [comment]
Test 2, 4 verified

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-nextcloud-1.1.0-1.ns7.noarch.rpm
nethserver-nextcloud-1.1.0-1.ns7.src.rpm
nextcloud-11.0.2-1.ns7.noarch.rpm
