### ISSUE TITLE
Runlevel-adjust fails if service not exists

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5243]
If there is a service `record` inside the `configuration` db without an associated systemd unit, the `runlevel-adjust` event fails with the following error:

> Failed to execute operation: No such file or directory

**Steps to reproduce**

- Create a fake service:
```
config set fw_cd3o service status enabled TCPPorts 3616 UDPPorts 3616 access green
```
- Execute the runlevel-adjust event
```
signal-event runlevel-adjust
```

**Expected behavior**

The event shouldn't try to adjust the `fw_cd30` service.

**Actual behavior**

The event tries to adjust the `fw_cd30` service, raises the reported error and exits with code 1.

**Components**

nethserver-lib-2.2.2-1.ns7.noarch

**See also**

http://community.nethserver.org/t/runlevel-adjust-failed-leads-to-false-error-on-software-update/6272

----

Thanks to Eddie Atherton

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-lib-2.2.2-1.3.gaf18e67.ns7.noarch.rpm

**Test case**
Check the bug is not reproducible.

**Comment by LotusGuy** [comment]
Verified.

Cheers.

**Comment by gsanchietti** [comment]
In nethserver-testing (again):

- nethserver-lib-2.2.2-1.5.gbb56c82.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
*Additional test case*

When a package is removed (say nethserver-samba) its associated services must be stopped.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-lib-2.2.3-1.ns7.noarch.rpm
