### ISSUE TITLE
Multi-WAN: backup mode rules priority

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5245]
Symptom:
Traffic originating from the system itself can't be source routed.

When using multi-WAN in backup mode, traffic priority is ruled by weight, using shorewall/rtrules.
shorewall manual defines priority ranges:

```
           1000-1999
               Before Shorewall-generated 'MARK' rules

           11000-11999
               After 'MARK' rules but before Shorewall-generated rules for ISP interfaces.

           26000-26999
               After ISP interface rules but before 'default' rule.

```

NethServer uses the 11000-11999 range.
This configuration creates rules like the following:

```
10000:	from all fwmark 0x10000/0xf0000 lookup adsl 
10001:	from all fwmark 0x20000/0xf0000 lookup fibra 
11900:	from all lookup adsl 
11901:	from all lookup fibra 
20000:	from 10.70.70.2 lookup adsl 
20000:	from 93.57.48.70 lookup fibra 

```

Rule 11900 matches all traffic (from all) so that rule 11901 never matches.
As a general rule, stricter rules should go before wider rules.
I think that we should put rules in the 26000-26999 range.

Steps to reproduce:
`ping -I 93.57.48.70 8.8.8.8`
Traffic goes out via adsl (instead of fibra).

**Comment by gsanchietti** [comment]
In nethesis-testing:
- nethserver-firewall-base-3.1.6-1.6.gd915c38.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.6-1.6.gd915c38.ns7.noarch.rpm

**Test case**
- Replicate the described scenario
- Try to ping a remote host by selecting the source IP
- Check the ping goes through the correct red interface

**Comment by filippocarletti** [comment]
```
[root@demosecurity ~]# ping -I 93.57.48.70 8.8.4.4
PING 8.8.4.4 (8.8.4.4) from 93.57.48.70 : 56(84) bytes of data.
64 bytes from 8.8.4.4: icmp_seq=1 ttl=44 time=59.0 ms
64 bytes from 8.8.4.4: icmp_seq=2 ttl=44 time=59.0 ms

26900:	from all lookup adsl 
26901:	from all lookup fibra 

[root@demosecurity ~]# ping -I 93.57.48.70 8.8.4.4
PING 8.8.4.4 (8.8.4.4) from 93.57.48.70 : 56(84) bytes of data.
64 bytes from 8.8.4.4: icmp_seq=1 ttl=47 time=30.1 ms

```
Dai tempi di risposta ai ping si vede che prima del fix i pacchetti escono per adsl, poi per fibra.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-firewall-base-3.1.7-1.ns7.noarch.rpm
nethserver-firewall-base-ui-3.1.7-1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-updates (6.9):
nethserver-firewall-base-2.11.3-1.ns6.noarch.rpm
nethserver-firewall-base-ui-2.11.3-1.ns6.noarch.rpm
