### ISSUE TITLE
Allow capital letters in shared folder name

### ISSUE THREAD

**Issue by SebastianMB-IT** [NethServer/dev#5247]
The validator of shared folder name is too restrictive.

**Current validator**

The names of shared folders are validated by USERNAME validator that is too restrictive.

**Changes**

Current validator will be replaced by a new validator.

The new validator checks if the name you entered meets the Windows naming conventions.

Naming conventions can be checked here: 

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions

**See also**

http://community.nethserver.org/t/cannot-have-a-capital-letter-in-a-share/6063

**Comment by SebastianMB-IT** [comment]
**Test case 1**

* Install the testing package
* Create a shared folder with capital letters 

The shared folder is created 

**Test case 2**

* Create a shared folder with a name that contains the following characters \ / : * ? " < > | ] [ and an error label occurs

----

In nethserver-testing:
nethserver-ibays-3.0.4-1.8.ga6a9c72.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Tested with spaces, special, lower and upper case chars.

Verified.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-ibays-3.1.0-1.ns7.noarch.rpm
