### ISSUE TITLE
WebTop 5: upgrade to RC6

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5250]
Upgrade WebTop to upstream RC6 release.
This release includes:

- Switch all code to GPL license
- Recurring events can not be modified
https://redmine.sonicle.com/issues/155
- New contact not functional
https://redmine.sonicle.com/issues/145
- User date-format not honored in Event form
https://redmine.sonicle.com/issues/142
- Cloud: can’t share uploaded resources
https://redmine.sonicle.com/issues/140
- Identity sharing properties saved only on the last entry
https://redmine.sonicle.com/issues/159
- Message source view keyboard navigation not working
https://redmine.sonicle.com/issues/153
- Content in windows cannot be selected
https://redmine.sonicle.com/issues/151
- Error after deleting records, refreshing folder with just one record left
https://redmine.sonicle.com/issues/149
- Key pressing enter of "Location" field, inserts double event
https://redmine.sonicle.com/issues/148
- Managing new identity froze Webtop
https://redmine.sonicle.com/issues/147
- Missing shared identity
https://redmine.sonicle.com/issues/146

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-webtop5-1.0.2-1.1.g8ce1a9f.ns7.noarch.rpm
- webtop5-core-1.0.2-1.ns7.noarch.rpm

**Test case 1**
- Install on a clean machine
- Check everything works fine

**Test case 2**
- Upgrade and existing machine
- Check everything works fine

**Comment by lucagasparini** [comment]
Test case 1: OK

Test case 2: OK

**Comment by gsanchietti** [comment]
Released:
- nethserver-webtop5-1.0.3-1.ns7.noarch.rpm
- webtop5-core-1.0.2-1.ns7.noarch.rpm
