### ISSUE TITLE
DC: container upgrade procedure

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5251]
Implement an upgrade procedure for nsdc container.

**Changes**
- Add a new ``nethserver-dc-upgrade`` event
- The event must update the Samba installation and the whole container
- Also upgrade to Samba 4.6.0

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-dc-1.1.3-1.30.g0ef96fa.ns7.x86_64.rpm

**Test case 1**
- Install nethserver-dc from stable repositories
- Provision nsdc container
- Create a user and set a password for it
- Join a windows machine to the domain
- Execute the upgrade event:
```
signal-event nethserver-dc-upgrade
```
- Check the machine is still joined to the domain
- Change the user password
- Check users are listed inside the nethserver-

**Test case 2**
- Install nethserver-dc from testing repository
- Provision nsdc container
- Create a user and set a password for it
- Join a windows machine to the domain

**Comment by SebastianMB-IT** [comment]
- In both test cases all is ok.

Instead after machine reboot it shows me an error with account provider.

**Steps to reproduce**

1. Install nethserver-dc from software center
2. Provision nsdc container
3. Update dc with package in testing
4. Reboot

Error:
Account provider error: invalid DN. Check Base DN, Groups DN and Users DN in Accounts provider configuration

**Comment by gsanchietti** [comment]
Tested again with the new web interface.

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
* nethserver-dc-1.2.0-1.ns7.x86_64.rpm
