### ISSUE TITLE
WebTop5: extended time format not set

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5254]
The extended time format for users is not set. If this options is not set, the user can't change its own preferences from the right-corner menu.

**Steps to reproduce**

- Install nethserver-webtop5
- Change WebTop timezone:
```
config setprop webtop DefaultTimezone  "Europe/Rome"
signal-event nethserver-webtop5-update
```
- Access the user preferences and try to change a field

**Expected behavior**

The modifications should be saved.

**Actual behavior**

Modifications are not saved and the extended time format field is empty.

**Components**

nethserver-webtop5-1.0.2

----

Thanks to @lucagasparini

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-webtop5-1.0.2-1.2.g158baf8.ns7.noarch.rpm

**Test case**

Check the bug is not reproducible.

**Comment by lucagasparini** [comment]
Test: OK !

**Comment by gsanchietti** [comment]
Released:
- nethserver-webtop5-1.0.3-1.ns7.noarch.rpm
