### ISSUE TITLE
Make ufdbguard logs readable by the Server Manager

### ISSUE THREAD

**Issue by SebastianMB-IT** [NethServer/dev#5255]
Ufdbguard logs can't be readed by the server-manager.

**Where are the log files**

Currently the log files are located in /var/ufdbguard/logs/.

**Where logs should be**

Log files should be in /var/log/ufdbguard to be readed by the server-manager.

**Changes**

1. - Create ufdbguard directory in /var/log.
2. - Change the logdir in ufdbGuard.conf from /var/ufdbguard/logs/ to /var/log/ufdbguard.

**See also**

https://www.urlfilterdb.com/files/downloads/ReferenceManual.pdf#page=29

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-squidguard-1.6.2-1.4.g5271a11.ns7.noarch.rpm

**Test case 1**
- Install nethserver-squidguard on a clean machine
- Enable the web filter and try to access a blocked site
- Check logs are written inside ``/var/log/ufdbguard.`` directory

**Test case 2**
- Upgrade and existing machine with web filter enabled
- Try to access a blocked site
- Check logs are written inside ``/var/log/ufdbguard.`` directory

**Comment by DavidePrincipi** [comment]
**VERIFIED**

Both update and fresh install direct the log to /var/log/ufdbguard directory

**Comment by SebastianMB-IT** [comment]
Ufdbguard needs some changes to make logrotate working.

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-squidguard-1.6.2-1.8.g62e0422.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
**VERIFIED**

log rotates as expected

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-squidguard-1.7.0-1.ns7.noarch.rpm
