### ISSUE TITLE
Slapd: decrease log verbosity

### ISSUE THREAD

**Issue by SebastianMB-IT** [NethServer/dev#5256]
Change slapd config to decrease log verbosity.

**Actual behavior**

Slapd default config makes log too verbose.

**Changes**

Log verbosity removed completely.
- Set LogLevel = 0 in cn=config

LogLevel 0 makes /var/log/slapd empty.

**How to manually change LogLevel**

To set your favorite log level follow the next guide 

http://docs.nethserver.org/projects/nethserver-devel/en/v7/nethserver-directory.html#logging

**Ldap developer guide**

http://www.openldap.org/devel/admin/slapdconf2.html

**Comment by SebastianMB-IT** [comment]
In nethserver-testing:

- nethserver-directory-3.1.4-1.21.g2ac5876.ns7.noarch.rpm

Test case 1

- Install nethserver-directory on a clean machine
- Create user or groups
- Check logs are written inside /var/log/slapd.

Test case 2

- Upgrade and existing machine with nethserver-directory
- Try to access a blocked site
- Check logs are written inside /var/log/slapd.

**Comment by DavidePrincipi** [comment]
**VERIFIED**

The last log line was

    Apr 03 16:23:43 vm5.dpnet.nethesis.it slapd[2778]: conn=1000 op=4 MOD attr=olcLogLevel olcTLSCACertificatePath

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-directory-3.2.0-1.ns7.noarch.rpm
