### ISSUE TITLE
Ufdbguard: Add checkbox to select all categories in the Filters tab

### ISSUE THREAD

**Issue by SebastianMB-IT** [NethServer/dev#5257]
Add checkbox to select all categories inside Filters tab new filter.

**Steps to reproduce**

- Inside web filter content click on Filters tab 
- Create a new filter

**Expected behavior**

You should select all categories of installed lists.

**Actual behavior**

You have to manually select each category.

**Changes**

Add a checkbox to select all categories together.

**Comment by SebastianMB-IT** [comment]
In nethserver-testing:

 -  nethserver-squidguard-1.6.2-1.5.g7fe72c2.ns7.noarch.rpm

Test case 1

 -  Install nethserver-squidguard on a clean machine
 -  Install lists with categories
 -  Create e new filter and use the check all box to select all categories

Test case 2

 -  Upgrade an existing machine with nethserver-squidguard
 -  Create e new filter and use the check all box to select all categories

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-squidguard-1.6.2-1.11.g3ce7bac.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-squidguard-1.7.0-1.ns7.noarch.rpm
