### ISSUE TITLE
Squid: integrated authentication doesn't work

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5259]
When installed, Squid is disabled by default and  Kerberos keytab is not created inside the nethserver-squid-update event.

For this reason, integrated authentication doesn't work.

Log extract:
```
2017/03/29 17:30:14 kid1| helperOpenServers: Starting 1/10 'negotiate_kerberos_auth' processes
2017/03/29 17:30:14| negotiate_kerberos_auth: ERROR: krb5_kt_start_seq_get: Key table file '/var/lib/misc/nsrv-squid.keytab' not found
2017/03/29 17:30:14| negotiate_kerberos_auth: ERROR: krb5_read_keytab: Key table file '/var/lib/misc/nsrv-squid.keytab' not found
2017/03/29 17:30:14 kid1| ERROR: Negotiate Authentication validating user. Result: {result=BH, notes={message: received type 1 NTLM token; }}
````

**Steps to reproduce**

- Install nethserver-dc and join a Windows machine to the domain
- Install nethserver-squid
- Enable the proxy with authentication
- Try to browse internet from the Windows machine

**Expected behavior**

The user should be able to browse internet without typing username and password.

**Actual behavior**

The browser ask the username and password and the authentication doesn't work.

**Workaround**

Execute:
```
/usr/libexec/nethserver/smbads initkeytab && systemctl restart squid
```

**Components**

nethserver-squid-1.5.3

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-squid-1.5.3-1.4.g9a354c2.ns7.noarch.rpm

**Comment by SebastianMB-IT** [comment]
1. - Installation on a cleaned machine works.
2. - Instead installation on a machine with squid already installed needs `systemctl restart squid.service` to takes effect.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-squid-1.5.4-1.ns7.noarch.rpm
