### ISSUE TITLE
PPPoE backup connection restart failure

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5260]
When a PPPoE connection is used in a multiwan setup, if the link goes down and up again, traffic is no longer sent to the PPPoE connection.

**Steps to reproduce**

See http://dev.nethserver.org/issues/3394

**Comment by DavidePrincipi** [comment]
In nethserver-testing **ns7**

nethserver-firewall-base-3.1.6-1.8.g646ccb0.ns7.noarch.rpm
nethserver-firewall-base-ui-3.1.6-1.8.g646ccb0.ns7.noarch.rpm

In nethserver-testing **ns6**

nethserver-firewall-base-2.11.1-1.1.g7760acb.ns6.noarch.rpm
nethserver-firewall-base-ui-2.11.1-1.1.g7760acb.ns6.noarch.rpm

**Comment by cotosso** [comment]
Installed on **ns6**, everything went as expected.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-firewall-base-3.1.7-1.ns7.noarch.rpm
nethserver-firewall-base-ui-3.1.7-1.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates (6.9)
nethserver-firewall-base-2.11.2-1.ns6.noarch.rpm
nethserver-firewall-base-ui-2.11.2-1.ns6.noarch.rpm
