### ISSUE TITLE
squid: trusted networks not enabled

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5261]
A freshly added new trusted network can't browse the web through squid web proxy.

**Steps to reproduce**

- squid web proxy enabled
- add a trusted network
- browse the net from a client in the trusted network

**Expected behavior**

The client should surf the web

**Actual behavior**

The client sees an Access denied page

Issuing a `signal-event nethserver-squid-save` enabled the client

**Comment by gsanchietti** [comment]
This bug affects also NS 6.

**Comment by gsanchietti** [comment]
In testing repository:
- nethserver-testing/7: nethserver-squid-1.5.3-1.8.g236f6fb.ns7.noarch.rpm
- nethserver-testing/6.9: nethserver-squid-1.3.12-1.1.g9e54dc3.ns6.noarch.rpm

**Test case**
- Check the bug is not reproducible

**Comment by DavidePrincipi** [comment]
**NS7 VERIFIED**

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-squid-1.5.4-1.ns7.noarch.rpm
nethserver-squid-1.3.13-1.ns6.noarch.rpm
