### ISSUE TITLE
NextCloud WebDAV authentication failure

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5263]
After updating to nethserver-nextcloud-1.1.0, the WebDAV authentication fails.

**Steps to reproduce**

- update/install nethserver-nextcloud-1.0.0 from nethserver-updates
- run the following command 

      curl --basic -u admin:Nethesis,1234 -k https://$(hostname)/nextcloud/remote.php/webdav/

**Expected behavior**

Authentication with default admin credentials succeedes:

<pre>
This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.
</pre>

**Actual behavior**

Authentication fails!

<pre>
&lt;?xml version="1.0" encoding="utf-8"?>
&lt;d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  &lt;s:exception>Sabre\DAV\Exception\NotAuthenticated&lt;/s:exception>
  &lt;s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured&lt;/s:message>
&lt;/d:error>
</pre>

**Components**

nethserver-nextcloud-1.1.0-1.ns7.noarch
nextcloud-11.0.2-1.ns7.noarch
rh-php56-php-fpm-5.6.25-1.el7.x86_64
nethserver-rh-php56-php-fpm-1.0.0-1.ns7.noarch

**See also**

http://community.nethserver.org/t/nextcloud-11-and-webdav/6451

----

Thanks to @dz00te for reporting the issue!

**Comment by dz00te** [comment]
adding as first line

`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

to /etc/httpd/conf.d/nextcloud.conf
seems to work... or at least authentication with admin or ldap user succeed 

see also:
https://central.owncloud.org/t/no-basic-authentication-headers-were-found-message/819

**Comment by DavidePrincipi** [comment]
Thanks @dz00te for the hint!

In nethserver-testing:
nextcloud-11.0.2-1.1.g5558ad2.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nextcloud-11.0.2-1.3.gbcd069aa.ns7.noarch.rpm

**Comment by dz00te** [comment]
**additional test case 1**
 - connection using webdav = ok
 - manage files with space in name = ok
 - connection with nc client = ok 

**additional test case 2**
 - set a bigger upload size using in GUI Additional Settings > File Handling = OK
- using occ: sorry i did not found the right command to do it :(

note: all ok on a clean installation, but updating the previous nc11 package, i got
Running transaction
  Updating   : nextcloud-11.0.2-1.3.gbcd069aa.ns7.noarch                                                          1/2 
warning: /etc/httpd/conf.d/nextcloud.conf created as /etc/httpd/conf.d/nextcloud.conf.rpmnew

and .user.ini while already present was not written with the right permission... but i think this is a particular case and should note be a problem....
should i try to update from nc10?

**Comment by dz00te** [comment]
Tested also an update from nc10 (clean install), all OK no probs

**Comment by DavidePrincipi** [comment]
> using occ

As we have php56 from SCL the procedure to run occ is quite complex. Please see this line for reference

https://github.com/NethServer/nethserver-nextcloud/blob/master/root/etc/e-smith/events/actions/nethserver-nextcloud-occ-conf#L11

> warning: /etc/httpd/conf.d/nextcloud.conf created as /etc/httpd/conf.d/nextcloud.conf.rpmnew

Did you locally modified it?

> and .user.ini while already present was not written with the right permission..

As above, do you have any local modification? What permissions does it have? What are the expected perms?

**Comment by dz00te** [comment]
> As we have php56 from SCL the procedure to run occ is quite complex

yes i've found how to run it, 
`sudo -u apache /opt/rh/rh-php56/root/usr/bin/php /usr/share/nextcloud/occ -V`
 but didn't find a valid option to change the post_max_size...

for the other notes, i think they aren't a problem, i have tried the update on my test vm, where i've changed perm and modified... 
tested the update from 10 (also because at the moment no one in using 11 on ns7) give me no probs

**Comment by DavidePrincipi** [comment]
My bad, @dz00te ! I must read the docs next time :blush: 

They say the PHP upload limit is set from the admin user interface, not ``occ``! I'm sorry for wasting your time :cry:

**Comment by dz00te** [comment]
:smile:   no probs, so it seems all ok, i'll set as verified. tnx!

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-nextcloud-1.1.0-1.ns7.noarch.rpm
nethserver-rh-php56-php-fpm-1.0.0-1.ns7.noarch.rpm
nextcloud-11.0.2-1.4.ns7.noarch.rpm

**Note**
The PR to nextcloud package is still open. The release commit is here:

https://github.com/DavidePrincipi/server-packages/commit/d3cf1db4572c6ec748e20ac3e185422b8ccd958d
