### ISSUE TITLE
Add  /root/.ssh directory to backup-config

### ISSUE THREAD

**Issue by SebastianMB-IT** [NethServer/dev#5264]
The directory /root/.ssh with ssh keys inside isn't added to backup files.

**Actual  behavior**

Ssh keys arent in any backup.

**Expected  behavior**

Directory /root/.ssh should be in backup-config.

**Changes**

Add /root/.ssh directory to nethserver-openssh.include file used by backup-config.

**Comment by SebastianMB-IT** [comment]
**In nethserver-testing**
nethserver-openssh-1.2.0-1.3.g2d8f003.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
**VERIFIED**

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-openssh-1.2.1-1.ns7.noarch.rpm
