### ISSUE TITLE
Redirection of postmaster to external e-mail address

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5266]
As a mail domain administrator I want to receive only the messages sent to ``postmaster@...`` and exclude other messages from the system delivered to root.

Mail to ``postmaster@...`` is delivered to root's mailbox (eventually forwarded). This behavior is hardcoded in the ``virtual`` template.

Change that behavior to allow ``pseudonym`` records (mail aliases) to override the final destination of messages sent to ``postmaster@...``.

**See also**

http://community.nethserver.org/t/redirection-of-postmaster-to-external-e-mail-address/6409

**Comment by DavidePrincipi** [comment]
**Test case 1**

- install/update nethserver-mail-server
- define additional domains: dom1 dom2 dom3
- run ``grep ^postmaster /etc/postfix/virtual`` and **check** ``postmaster@dom1``, ``postmaster@dom2``, ``postmaster@dom3`` point to ``postmaster`` (default)
- from the UI, define ``postmaster@<alldomains>`` mail alias to some _Account_ (internal or external)
- **check** ``postmaster@dom1``, ``postmaster@dom2``, ``postmaster@dom3`` point to _Account_ (general override)
- from the UI, define ``postmaster@dom2`` to some _Account2_ and **check** it is expanded correctly by the template (specific override)
- from the UI, delete the general override ``postmaster@<alldomains>`` and **check** dom1, dom2 are at default, whilst dom2 retains the specifc override

**Comment by filippocarletti** [comment]
Installed nethserver-mail-server-1.10.10-1.9.g0156b6e.ns7.noarch.rpm.
Accounts provider is local ldap.
All tests passed.

```
[root@rc3 ~]# grep ^postmaster /etc/postfix/virtual
postmaster@d2.it                       postmaster
postmaster@neth.net                    postmaster
[root@rc3 ~]# grep ^postmaster /etc/postfix/virtual
postmaster@d2.it                       filippo.carletti@neth.net
postmaster@neth.net                    filippo.carletti@neth.net
[root@rc3 ~]# grep ^postmaster /etc/postfix/virtual
postmaster@d2.it                       admin@neth.net
postmaster@d2.it                       filippo.carletti@neth.net
postmaster@neth.net                    filippo.carletti@neth.net
[root@rc3 ~]# tail -f /var/log/maillog 
Apr 11 11:42:58 rc3 postfix/postmap[3596]: warning: /etc/postfix/virtual.db: duplicate entry: "postmaster@d2.it"
Apr 11 11:43:40 rc3 postfix/postmap[3639]: warning: /etc/postfix/virtual.db: duplicate entry: "postmaster@d2.it"
[root@rc3 ~]# grep ^postmaster /etc/postfix/virtual
postmaster@neth.net                    postmaster
postmaster@d2.it                       admin@neth.net

```

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-server-1.10.11-1.ns7.noarch.rpm
