### ISSUE TITLE
Asterisk wrong gid / uid

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5267]
**Steps to reproduce**

- Make sure gid 995 is already in use

```
# getent group | grep 995
chrony : x : 995:
```

- install nethserver-freepbx
- Asterisk package fails install 

**Expected behavior**

Asterisk sould be installed also if gid 995 and uid 995 are already in use

**Actual behavior**

Asterisk package isn't installed

**Components**

asterisk13-core-13.15.0-1.sng7.x86_64

wrong lines in .spec are:

```
getent group asterisk >/dev/null || groupadd -g 995 -r asterisk
getent passwd asterisk >/dev/null || useradd -r -u 995 -s /bin/bash -d /home/asterisk asterisk
```
Suggested solution: 
change the previous lines with

```
%{_sbindir}/groupadd -r asterisk &>/dev/null || :
%{_sbindir}/useradd  -r -s /sbin/nologin -d /var/lib/asterisk -M -c 'Asterisk User' -g asterisk asterisk &>/dev/null || :
```

**Workaround**

before installation, launch

```
groupadd -r asterisk
useradd  -r -s /sbin/nologin -d /var/lib/asterisk -M -c 'Asterisk User' -g asterisk asterisk
```

**Comment by gsanchietti** [comment]
I guess the testing RPM is ` asterisk13-core-13.15.0-1.ns7.x86_64`.

After installation, this is the asterisk user:
```
[root@test ~]# getent passwd asterisk
asterisk:x:993:989:Asterisk User:/var/lib/asterisk:/sbin/nologin
```
preinstall scriptlet (using /bin/sh):
```
# Make sure the 'asterisk' user exists
/usr/sbin/groupadd -r asterisk &>/dev/null || :
/usr/sbin/useradd  -r -s /sbin/nologin -d /var/lib/asterisk -M -c 'Asterisk User' -g asterisk asterisk &>/dev/null || :
```
Verified.

**Comment by gsanchietti** [comment]
Release the RPM within #5270
