### ISSUE TITLE
Backup-data: remove .ssh directory from backup

### ISSUE THREAD

**Issue by SebastianMB-IT** [NethServer/dev#5269]
Backup-data makes backup of all directories in root included .ssh directory saved in backup-config to.

**Expected behavior**

No conflicts between ssh keys in backup restore.

**Actual behavior**

Backup-data overwrites backup-config keys.

**Changes**

Remove .shh directory from backup-data.

**See also**

https://github.com/NethServer/dev/issues/5264

**Comment by SebastianMB-IT** [comment]
In nethserver-testing:

- nethserver-backup-data-1.3.0-1.1.g6db181c.ns7.noarch.rpm

Test case

- Install Backup
- Update nethserver-backup-data from testing
- Make a config backup
- Change something in .ssh directory
- Make a data backup
- Restore config backup
- Restore data backup
- Checks that the .ssh directory is like first config backup

**Comment by gsanchietti** [comment]
Before update:

> [root@test ~]# backup-data-list  | grep ssh
> Thu Apr 20 17:25:25 2017 root/.lesshst
> Thu Apr 20 17:40:01 2017 root/.ssh
> Tue Nov 22 10:34:20 2016 root/.ssh/authorized_keys
> Thu Apr 20 17:40:01 2017 root/.ssh/known_hosts

After update:

> [root@test ~]# backup-data-list  | grep ssh
> Thu Apr 20 17:25:25 2017 root/.lesshst

Verified.

**Comment by gsanchietti** [comment]
Released:
- nethserver-backup-data-1.3.1-1.ns7.noarch.rpm
