### ISSUE TITLE
Asterisk and dependencies RPMs that need to be rebuild

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5270]
Some RPMs needed by nethserver-freepbx, Asterisk and FreePBX are now taken from Sangoma repositories, but we need to be rebuilt them:

- [x] Asterisk13 : packages has a bug in %pre NethServer/dev#5267 and uses old libsrtp (1.4) that has known issues with WebRTC
- [x] asterisk-sounds-extra
- [x] asterisk-sounds
- [x] dahdi-firmware
- [x] dahdi-linux
- [x] dahdi-tools
- [x] kmod-dahdi-linux: already rebuilt because Sangoma one doesn't use weak updates
- [x] libopenr2
- [x] libpri
- [x] libresample
- [x] libsrtp
- [x] libss7
- [x] libtonezone
- [x] mISDNuser
~~- [ ] libwat~~
- [x] pjproject

**Comment by Stell0** [comment]
libopenr2 version downgraded from 1.3.4 to 1.3.3, because I can't find original sources for 1.3.4. Changes from the 1.3.3 to Sangoma 1.3.4 are introduced in package as a patch. That means that libopenr2-1.3.4 has to be removed from our repositories

**Comment by Stell0** [comment]
libtonezone is built from dahdi-tools sRPM

**Comment by Stell0** [comment]
Packages to test:
* [ ] asterisk13*-13.15.0-1.ns7.x86_64.rpm
* [ ] asterisk-sounds-extra-en-*-1.5-2.ns7.noarch.rpm
* [ ] asterisk-sounds-core-*-*-1.5-2.ns7.noarch.rpm
* [ ] dahdi-firmware-3.0.0-1.ns7.noarch.rpm
* [ ] dahdi-linux-2.11.1-1.ns7.x86_64.rpm
* [ ] dahdi-tools-2.11.1-1.ns7.x86_64.rpm
* [ ] libtonezone-2.11.1-1.ns7.x86_64.rpm
* [ ] libopenr2-1.3.3-1.ns7.x86_64.rpm
* [ ] libpri-1.4.15-13.ns7.x86_64.rpm
* [ ] libresample-0.1.3-20.ns7.x86_64.rpm
* [ ] libsrtp-1.5.4-3.ns7.x86_64.rpm
* [ ] libss7-2.0.0-1.ns7.x86_64.rpm
* [ ] mISDNuser-2.0.19-1.2.x86_64.rpm
* [ ] pjproject-2.5.5-1.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
Everything has been installed correctly.
Just a note, mISDNuser doesn't have ns7 dist tag.

To be released with #5074
