### ISSUE TITLE
OpenVPN 2.4 breaks CRL (Certificate Revocation List)

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5271]
EPEL released OpenVPN 2.4 which changes CRL implementation.
All existing installations will block connections to existing clients.

**Steps to reproduce**

- Install nethserver-openvpn with OpenVPN 2.3
- Configure a client with certificate authentication
- Upgrade OpenVPN to 2.4

**Expected behavior**

Existing clients should be able to reconnect to the server.

**Actual behavior**

Clients can't connect, error in `` /var/log/openvpn/openvpn.log``:
```
VERIFY ERROR: depth=0, error=CRL has expired: C=-- ....
```
**Workaround**

Regenerate the CRL:
```
/usr/bin/openssl ca -gencrl -out /var/lib/nethserver/certs/crl.pem -config /var/lib/nethserver/certs/ca.cnf
systemctl restart openvpn@host-to-net
```

**Components**

openvpn-2.3.14-1.el7.x86_64 upgraded to openvpn-2.4.1-1.el7.x86_64

**See also**

http://community.nethserver.org/t/after-updating-openvpn-client-doesnt-connect-to-the-server/6551

----

Thanks to @dz00te, @pasing

**Comment by filippocarletti** [comment]
openvpn restart is not needed after CRL generation.

**Comment by gsanchietti** [comment]
Restart removed from PR.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-openvpn-1.4.8-1.2.g404ecfc.ns7.noarch.rpm

**Test case**
- Check the bug is not reproducible

**Comment by cotosso** [comment]
I just tried the update in an installation with the problem and everything worked as expected.

**Comment by cotosso** [comment]
Now the CRL  is valid for the next 10 years:
[root@fw1 openvpn]# openssl crl -in /var/lib/nethserver/certs/crl.pem -text | grep Update
        Last Update: Apr 20 10:11:08 2017 GMT
        Next Update: Apr 18 10:11:08 2027 GMT

**Comment by gsanchietti** [comment]
Released:
- nethserver-openvpn-1.4.9-1.ns7.noarch.rpm
