### ISSUE TITLE
Ipaddr prop missing from green+DHCP interface

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5272]
**Steps to reproduce**

- setup a NethServer 7 with a static green (eth0) and a *unconfigured* additional interface (eth1). Anaconda must not configure it at all!
- after FirstConfig wizard go to Network and set eth1 as seconday green with DHCP

**Expected behavior**

``/etc/dhcp/dhclient.d/nethserver.sh`` assigns ``ipaddr`` prop to ``eth1``.

**Actual behavior**

No ``ipaddr`` prop in ``eth1`` record, and a template expansion error occurs (/etc/shorewall/hosts). In ``/var/log/messages``:

<pre>
Apr 20 10:54:02 vm8 esmith::event[16221]: WARNING in /etc/e-smith/templates//etc/shorewall/hosts/20green: Use of uninitialized value $_[0] in pattern match (m//) at /usr/share/perl5/vendor_perl/Net/IPv4Addr.pm l
ine 54.
Apr 20 10:54:02 vm8 esmith::event[16221]: WARNING in /etc/e-smith/templates//etc/shorewall/hosts/20green: Use of uninitialized value $_[0] in pattern match (m//) at /usr/share/perl5/vendor_perl/Net/IPv4Addr.pm l
ine 55.
Apr 20 10:54:02 vm8 esmith::event[16221]: WARNING in /etc/e-smith/templates//etc/shorewall/hosts/20green: Use of uninitialized value $_[0] in pattern match (m//) at /usr/share/perl5/vendor_perl/Net/IPv4Addr.pm l
ine 93.
Apr 20 10:54:02 vm8 esmith::event[16221]: WARNING in /etc/e-smith/templates//etc/shorewall/hosts/20green: Use of uninitialized value $error[2] in join or string at /usr/share/perl5/vendor_perl/Carp.pm line 311.
Apr 20 10:54:02 vm8 esmith::event[16221]: ERROR in /etc/e-smith/templates//etc/shorewall/hosts/20green: Program fragment delivered error <<Net::IPv4Addr: invalid IPv4 address:
Apr 20 10:54:02 vm8 esmith::event[16221]: at /usr/share/perl5/vendor_perl/esmith/util.pm line 354.>> at template line 1
Apr 20 10:54:02 vm8 esmith::event[16221]: ERROR: Template processing failed for //etc/shorewall/hosts: 4 fragments generated warnings, 1 fragment generated errors
Apr 20 10:54:02 vm8 esmith::event[16221]: at /etc/e-smith/events/actions/generic_template_expand line 64.
Apr 20 10:54:02 vm8 esmith::event[16221]: [WARNING] expansion of /etc/shorewall/hosts failed
</pre>

...the following command fixes the problem:

     signal-event interface-update

**Components**

nethserver-base-3.0.18-1.ns7.noarch
nethserver-firewall-base-3.1.7-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-base-3.0.18-1.4.g7e9f833.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified in the following scenarios:

- multiple green
- green + red
- single green with DHCP on system-init

**Comment by gsanchietti** [comment]
Released:
- nethserver-base-3.0.19-1.ns7.noarch.rpm
