### ISSUE TITLE
Nextcloud config not backuped

### ISSUE THREAD

**Issue by nrauso** [NethServer/dev#5273]
As stated in [nethserver-nextcloud repository](https://github.com/NethServer/nethserver-nextcloud) _Nextcloud_ configuration should be backuped but it's not.
Package includes

`/var/www/html/nextcloud/config/config.php`

to backup-config as _Nextcloud_ configuration backup path but it doesn't exist.
The right path seems to be:

`/usr/share/nextcloud/config/config.php`

**Components**
`nethserver-nextcloud-1.1.0-1.ns7.noarch`
`nextcloud-11.0.2-1.4.ns7.noarch`

**Comment by dnutan** [comment]
https://github.com/NethServer/nethserver-nextcloud/pull/15

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-nextcloud-1.1.0-1.4.gcd46a93.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Configured a backup with new RPM:
>[root@test ~]# backup-data-list | grep config.php
>Mon Apr 24 09:05:01 2017 usr/share/nextcloud/config/config.php

Verified.

**Comment by gsanchietti** [comment]
Released:
- nethserver-nextcloud-1.1.1-1.ns7.noarch.rpm
