### ISSUE TITLE
Bad port forward to host inside a green alias network

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5274]
Can't create valid port forward to hosts inside green network alias.

**Steps to reproduce**

- Configure a machine with one green (192.168.1.253) and one red interface (network 10.0.0.1)
- Create an alias for green interface (192.168.100.253)
- Create a new host inside the Firewall object: myhost, 192.168.100.22 (this host belong to the alias network)
- Create a port forward to ``myhost``

**Expected behavior**

The port forward must be created inside the NAT chain: net2loc

**Actual behavior**

The web interface raises an error:
```
ERROR: Unknown destination zone (alias) /etc/shorewall/rules (line 74)
```
The ``myhost`` object is resolved inside the invalid ``alias`` zone, instead of inheriting the green zone.

**Components**

nethserver-firewall-base-3.1.7-1.ns7.noarch

The issue also affects NS 6.

----

Thanks to @filippocarletti

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-firewall-base-3.1.7-1.2.g28c4169.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.1.7-1.2.g28c4169.ns7.noarch.rpm

**Test case**
Check the bug is not reproducible.

**Comment by DavidePrincipi** [comment]
**VERIFIED** on ns7

**Comment by gsanchietti** [comment]
Released fo NS 7:
nethserver-firewall-base-3.1.8-1.ns7.noarch.rpm
nethserver-firewall-base-ui-3.1.8-1.ns7.noarch.rpm

Released for NS 6:
nethserver-firewall-base-2.11.4-1.ns6.noarch.rpm
nethserver-firewall-base-ui-2.11.4-1.ns6.noarch.rpm
