### ISSUE TITLE
Fax printing fail

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5277]
**Steps to reproduce**

Enable automatic printing of received faxes
Receive a fax

**Expected behavior**

A page from the printer.

**Actual behavior**

Nothing is printed.
CUPS log contains:
`Returning IPP client-error-bad-request for Send-Document`
The error is due to an empty documents, because conversion from tiff to ps fails with error:
```
/usr/bin/tiff2ps -a -w 8.20 -h 11.54 -H 11.90 recvq/fax000000002.tif > /tmp/test.ps
-H: Max viewport height cannot exceed page height.

```

Removing -H option from tiff2fax resolves the issue.

**Comment by filippocarletti** [comment]
We should probaly add option "-p":
       -p     Force the generation of (non-Encapsulated) PostScript.
to avoid a warning message.

**Comment by filippocarletti** [comment]
Working command:
`/usr/bin/tiff2ps -a -w 8.20 -h 11.54 -p recvq/faxnnn`

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-hylafax-1.2.3-1.2.g0760088.ns7.noarch.rpm

**Test case**
Check the bug is not reproducible.

**Comment by nrauso** [comment]
tested:**OK**

Automatic printing of received faxes works correctly.

**Comment by gsanchietti** [comment]
Released:
nethserver-hylafax-1.2.4-1.ns7.noarch.rpm
