### ISSUE TITLE
PKI: self-signed certificate not renewed

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5278]
When the self-signed certificate has expired, it will not be automatically renewed.

**Steps to reproduce**

- Install a clean machine
- Move the date 11 years forward
```
date -s "Wed May 10 12:22:32 CEST 2028"
```
- Execute certificate renewal script: 
```
/etc/cron.daily/nethserver-check-builtin-certificate
```

**Expected behavior**

The certificate must be renewed.
To check expiration date, use this command:
```
/usr/libexec/nethserver/pki-info -e /etc/pki/tls/certs/NSRV.crt
```

**Actual behavior**

The certificate is not renewed.

**Components**

nethserver-base-3.0.19-1.ns7.noarch

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-base-3.0.19-1.2.g5d7950d.ns7.noarch.rpm

**Test case**
Check the bug is not reproducible

**Comment by DavidePrincipi** [comment]
@gsanchietti, the certificate is regenerated and a notification mail is delivered to root.

However no ``certificate-update`` event is triggered and httpd-admin (for instance) is not restarted. 

The UI shows the new certificate in a "selected" (default) state.

How to load the new certificate? I think we should run ``certificate-update`` if the self-signed cert is selected as "default".

**Comment by gsanchietti** [comment]
The self-signed certificate is not valid, thus restarting services has no benefits (but it could break all OpenVPN connections).

See also https://github.com/NethServer/dev/issues/5174

**Comment by gsanchietti** [comment]
Released:
nethserver-base-3.0.20-1.ns7.noarch.rpm
