### ISSUE TITLE
mail-filter: enable spamassassin anti-backscatter rules

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5280]
We could automatically enable some rules to identify backascatter adding the FQDN to a spamaassassin configuration file.

See https://wiki.apache.org/spamassassin/VBounceRuleset for information.

**Comment by filippocarletti** [comment]
To file or discard backscatter bounces create a sieve rules like the following
```
if header :contains "x-spam-status" "ANY_BOUNCE_MESSAGE"
{
        fileinto "Bounce";
        stop;
}

```

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-filter-1.4.3-1.2.g72daa22.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-mail-filter-1.4.4-1.ns7.noarch.rpm
