### ISSUE TITLE
NUT UPS master unreachable from clients

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5282]
**Steps to reproduce**

- Configure a new UPS cable-connected to a server (master)
- Configure a new UPS as slave, network-connected to the master

**Expected behavior**

The slave can talk to the master, the slave dashboard shows ups information

**Actual behavior**

The slave can't connect to master. /var/log/Messages contains:
`UPS [UPS@nethesis.it]: connect failed: Connection failure: Connection refused`

Workaround:
1. run `signal-event firewall-adjust` after configuring the master ups to open port 3493

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-nut-1.3.0-1.3.g5dae104.ns7.noarch.rpm

**Test case**
Check the bug is not reproducible

**Comment by gsanchietti** [comment]
Before enabling, tcp port 3493 is closed, after enabling the server:
```
[root@test ~]# iptables -nvL | grep 3493
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:3493 /* nut-server */
```

Verified.

**Comment by gsanchietti** [comment]
Released:
nethserver-nut-1.3.1-1.ns7.noarch.rpm
