### ISSUE TITLE
PKI: SSL chain file not updated after certificate-update

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5283]
After switching from self-signed NS certificates to LetsEncrypt, the httpd.conf configuration file for the Server Manager doesn't appear to be recreated. This means that the SSLCertificateChainFile parameter, for the LetsEncrypt intermediate certificate is not included.

~~Note that this setting should also be manually added to the ssl.conf file for the regular https web server~~

**Steps to reproduce**

- Configure Let's Encrypt certificate
- Set is ad default certificate

**Expected behavior**

SSL chain file should be applied both to httpd and httpd-admin daemons.

**Actual behavior**

SSL chain file is not applied.

**Components**

nethserver-httpd-3.1.2-1.ns7.noarch
nethserver-httpd-admin-2.0.9-1.ns7.noarch

**See also**

http://community.nethserver.org/t/minor-issue-with-server-manger-certificates-after-switch-to-letsencrypt/6798

----

Thanks to @EddieA

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-httpd-3.1.2-1.2.g0d6e0cb.ns7.noarch.rpm
nethserver-httpd-proxypass-3.1.2-1.2.g0d6e0cb.ns7.noarch.rpm
nethserver-httpd-admin-2.0.9-1.2.ga08a224.ns7.noarch.rpm

**Test case**
Check the bug is not reproducible

**Comment by DavidePrincipi** [comment]
**VERIFIED**

**Comment by gsanchietti** [comment]
Released:
nethserver-httpd-3.1.3-1.ns7.noarch.rpm
nethserver-httpd-proxypass-3.1.3-1.ns7.noarch.rpm
nethserver-httpd-admin-2.0.10-1.ns7.noarch.rpm
