### ISSUE TITLE
Default userPrincipalName is not an email address

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5284]
Since the AD realm can be different from DomainName, the default ``userPrincipalName`` value do not match a valid email address. Mail applications (like Roundcube address book) do not work properly.

**Steps to reproduce**

- Set host name ``vm5.dpnet.nethesis.it``
- Configure a local AD provider with realm ``ad.dpnet.nethesis.it``
- Create a new user

**Expected behavior**

    userPrincipalName: first.user@dpnet.nethesis.it

**Actual behavior**

    userPrincipalName: first.user@ad.dpnet.nethesis.it

**Components**

nethserver-dc-1.2.1-1.ns7.x86_64
nethserver-sssd-1.2.0-1.ns7.noarch

**See also**

#5253

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.2.1-1.5.g66659b0.ns7.x86_64.rpm
nethserver-sssd-1.2.0-1.4.g2d2f56a.ns7.noarch.rpm
nethserver-nextcloud-1.1.2-1.5.g8209b77.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-sssd-1.2.0-1.6.ga9bed9c.ns7.noarch.rpm
nethserver-roundcubemail-1.2.6-1.3.g2332424.ns7.noarch.rpm
nethserver-ejabberd-1.1.4-1.3.g2419ba9.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Everything works as excepted, tested:
- sssd
- ejabberd
- rouncubemail
- sogo

**Comment by gsanchietti** [comment]
Released:
nethserver-nextcloud-1.1.3-1.ns7.noarch.rpm
