### ISSUE TITLE
Nextcloud: update to 11.0.3

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5285]
Upgrade Nextcloud to latest upstream release (11.0.3).
The new package must handle new installation and the upgrade from Netxtcloud 10.

See upstream commit: https://github.com/nextcloud/server-packages/commit/9999bcbac36e990780a8dacf13d352ee5c9df05a

**Packages**

nethserver-nextcloud
nextcloud

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nextcloud-11.0.3-2.ns7.noarch.rpm
- nethserver-nextcloud-1.1.2-1.5.g8209b77.ns7.noarch.rpm

**Test case 1**
- Install on a clean machine with LDAP or Samba AD
- Check everything correctly works

**Test case 2**
- Upgrade a running machine with Netxtcloud 11.0.2 with  LDAP or Samba AD
- Check everything correctly works

**Test case 3**
- Install on a new machines with local LDAP or AD
- Apply fixes from NethServer/dev#5284
- Check the mail field inside user profile is correctly set

**Comment by DavidePrincipi** [comment]
*Test case 2*

upgrade is fine here

**Comment by gsanchietti** [comment]
Released:
nethserver-nextcloud-1.1.3-1.ns7.noarch.rpm
nextcloud-11.0.3-2.ns7.noarch.rpm
