### ISSUE TITLE
If MySQL starts after Asterisk, CDR report is disabled

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5286]
**Steps to reproduce**

It doesn't happen always, it depends on the time MySQL take to start.
* install and configure FreePBX CDR module
* Reboot
* check /var/log/messages 

```
May 17 15:48:27 nethvoice systemd: Starting MariaDB database server...
May 17 15:48:27 nethvoice systemd: Started Asterisk PBX and telephony daemon..
May 17 15:48:27 nethvoice systemd: Starting Asterisk PBX and telephony daemon....
May 17 15:48:35 nethvoice systemd: Started MariaDB database server.
```
* If MySQL is slow enough, you should see this error in asterisk full log

```
ERROR[2949] res_config_mysql.c: MySQL RealTime: Failed to connect database server asteriskcdrdb on localhost (err 2002). Check debug for more info.
```

* You may want to add a delay at the beginning of /usr/bin/mysqld_safe to be sure that mysql is really slow

**Expected behavior**

MySQLd should start before Asterisk

**Actual behavior**

Sometimes Asterisk starts too early and cdr desn't work anymore without users being alerted

**Components**

Asterisk 13
nethserver-freepbx-0.0.1-1.110.g751eeea.ns7.noarch.rpm

**Comment by Stell0** [comment]
Test case: 
* install new package
* `systemctl daemon-reload`
* `systemctl status asterisk`
* make sure that additional rule for asterisk are loaded

```
  Drop-In: /etc/systemd/system/asterisk.service.d
           └─cdr.conf
```
* delay mysqld start inserting in `/usr/bin/mysqld_safe` a `sleep 30`, at the beginning of the script
* `reboot`
* check starting order in messages

```
grep systemd: Start.*Asterisk\|systemd: Start.*MariaDB' /var/log/messages
```
* Bad :(

```
May 17 18:08:29 nethvoice systemd: Starting MariaDB database server...
May 17 18:08:29 nethvoice systemd: Started Asterisk PBX and telephony daemon..
May 17 18:08:29 nethvoice systemd: Starting Asterisk PBX and telephony daemon....
May 17 18:08:37 nethvoice systemd: Started MariaDB database server.
```
* Good :)

```
May 18 08:47:32 73 systemd: Starting MariaDB database server...
May 18 08:48:05 73 systemd: Started MariaDB database server.
May 18 08:48:05 73 systemd: Started Asterisk PBX and telephony daemon..
May 18 08:48:05 73 systemd: Starting Asterisk PBX and telephony daemon....
```

nethesis-testing **nethserver-freepbx-0.0.1-1.112.gff0ef06.ns7.noarch.rpm**

**Comment by gsanchietti** [comment]
Verified.

**Comment by gsanchietti** [comment]
Release with #5074
