### ISSUE TITLE
Unable to validate Samba domain password

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5289]
After sme8 migration procedure a legacy network scanner fails to access a Samba share. This should be true for ns6 upgrade too.

**Steps to reproduce**

- copy ``smb.conf`` to the local directory
- edit it and set ``client NTLMv2 auth = no``
- run ``smbclient``

```
smbclient -U 'DPNET\davidep%Nethesis,1234' -s smb.conf //192.168.122.8/iba1
```

**Expected behavior**

Access to shared folder is granted

**Actual behavior**

In ``/var/log/messages`` (server side):

    domain_client_validate: unable to validate password for user davidep in domain DPNET to Domain controller NSDC-VM8.AD.DPNET.NETHESIS.IT. Error was NT_STATUS_WRONG_PASSWORD.

**Components**

nethserver-sssd-1.2.0-1.ns7.noarch
nethserver-dc-1.2.1-1.ns7.x86_64

**See also**

http://badlock.org/

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.2.1-1.7.g6a00a29.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
Verified.

**Comment by gsanchietti** [comment]
Released:
nethserver-dc-1.2.2-1.ns7.x86_64.rpm
