### ISSUE TITLE
Migrate LogonDrive prop

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5290]
The ``smb{LogonDrive}`` prop from sme8 is not honored.

**Steps to reproduce**

- run sme8 migration from a PDC backup
- ``net ads search -P samaccountname=... homeDirectory homeDrive`` 

**Expected behavior**

Both ``homeDirectory`` and ``homeDrive`` are set

**Actual behavior**

AD LDAP attributes are not set

**Components**

nethserver-sssd-1.2.0
nethserver-dc-1.2.1

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-directory-3.2.2-1.2.g9be3157.ns7.noarch.rpm
nethserver-dc-1.2.2-1.3.gbe84744.ns7.src.rpm

**Additional test case**

Check the additional upnSuffix is effectively added after migration event:

    ldapsearch -LLL -D admin@$(/sbin/e-smith/config getprop sssd Realm) -W \
        -H ldaps://$(/sbin/e-smith/config getprop nsdc IpAddress) \
        -s base -b cn=Partitions,cn=Configuration,$(perl -MNethServer::SSSD -e 'print NethServer::SSSD->new()->baseDN();') \
        uPNSuffixes

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-samba-2.0.6-1.2.g40165e7.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified for NS 6 upgrade and SME migration.

**Comment by gsanchietti** [comment]
Released:
nethserver-directory-3.2.3-1.ns7.noarch.rpm
nethserver-samba-2.0.7-1.ns7.noarch.rpm
nethserver-dc-1.2.3-1.ns7.x86_64.rpm
