### ISSUE TITLE
Multiple forward addresses in mailboxes

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5292]
The UI page "Email addresses > User mailboxes > Edit" page allows setting one forward address only.

Allow multiple forward addresses.

See also

http://community.nethserver.org/t/forwarding-emails-to-more-than-one-email-address/6836

Thanks phonon112358 for pointing that out

**Comment by DavidePrincipi** [comment]
**Test case**

After installing the testing version multiple forward addresses can be set under  "Email addresses > User mailboxes"

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.14-1.24.g033a3d3.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified with valid and invalid addresses.

**VERIFIED**

**Comment by gsanchietti** [comment]
Released:
nethserver-mail-server-1.10.15-1.ns7.noarch.rpm

**Comment by phonon112358** [comment]
thanks! 
I am not so often on github and hadn't seen that there was a test version... 
but now it works!! ;)
