### ISSUE TITLE
Set a group name as mail alias destination

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5293]
The page "Email addresses > Mail aliases > Edit" allows picking a group name in Destinations field.

![image](https://cloud.githubusercontent.com/assets/2920838/26441833/695a419e-4132-11e7-9eaa-a81abdf55d1d.png)

When the record is saved the group is expanded to its members list.

As admin, if a mail alias is named after a group I want the members list is not expanded and the mail alias is retained in Destinations list after saving.

For instance, if ``team1@`` mail alias is a distribution list for ``team1@dpnet.nethesis.it`` group members, and I want to create a ``support@`` mail alias pointing to it, I don't want the group members expanded, I want the mail address  ``team1@dpnet.nethesis.it`` retained as destination.

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.14-1.9.gcd16a58.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Created an alias "g1" pointing to  "g1" group with "admin" and "giacomo" users inside; then created a "g2" alias pointing to "g1":
```
g1@local.neth.eu                       admin@local.neth.eu,giacomo@local.neth.eu
g2@local.neth.eu                       g1@local.neth.eu
```

**Comment by gsanchietti** [comment]
Released:
nethserver-mail-server-1.10.15-1.ns7.noarch.rpm
