### ISSUE TITLE
Add "Local network only" option to User mailboxes

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5295]
The "Local network only" checkbox is implemented in "Mail aliases". When checked the alias can receive messages from trusted clients only (local networks and smtp auth).

The "Email addresses > User mailboxes > Edit" page lacks a "Local network only" option.

**Comment by DavidePrincipi** [comment]
**Test case 1**

 - after installing the testing package, a "Local network only" checkbox is available for each item in "Email addresses > User mailboxes" (except root). The checkbox is documented in the inline help and has the same semantics of that one under "Mail aliases" page.
- if the checkbox is set, a message coming from SMTP port 25 is rejected

Sample SMTP session:

<pre>
$ nc -C 192.168.122.5 25
220 vm5.dpnet.nethesis.it ESMTP Postfix
ehlo nethesis.it
250-vm5.dpnet.nethesis.it
250-PIPELINING
250-SIZE 20000000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
mail from: <davidep@nethesis.it>
250 2.1.0 Ok
rcpt to: <fifth.user@dpnet.nethesis.it>
554 5.7.1 <fifth.user@dpnet.nethesis.it>: Recipient address rejected: Access denied
quit
221 2.0.0 Bye
</pre>

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.14-1.24.g033a3d3.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Created a user "giacomo" and set the access to "Local network only".
The mailbox address is correctly added to ``/etc/postfix/virtual``:
```
[root@test ~]# grep giacomo@local.neth.eu /etc/postfix/virtual | head -n 1
giacomo@local.neth.eu            giacomo@nethesis.it,mario@nethesis.it, giacomo@local.neth.eu
```

But I'd like to see what mailboxes are configured as "Local network only" from the table view.

**VERIFIED**

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.14-1.26.gab36555.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
nethserver-mail-server-1.10.15-1.ns7.noarch.rpm
