### ISSUE TITLE
List builtin entries in User mailboxes and Mail aliases pages

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5296]
The "Email addresses > User mailboxes" and "Mail aliases" pages are missing some builtin elements.

- The ``root`` mailbox
- The ``postmaster`` mail alias

**Comment by DavidePrincipi** [comment]
**Test case 1**

- after installing the testing package, a ``root`` item is listend under "Email addresses > User mailboxes". If the "Edit profile" is pressed, the UserProfile page is shown.

**Test case 2**

- after installing the testing package, a ``postmaster@`` alias must be present under "Email addresses > Mail aliases"
- if the alias is removed it will be recreated next time a package is installed/removed
- if the alias is removed the RFC-mandatory postmaster alias is still available

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.14-1.24.g033a3d3.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Both postmaster and root are available and editable inside the web interface.

**VERIFIED**

**Comment by gsanchietti** [comment]
Released:
nethserver-mail-server-1.10.15-1.ns7.noarch.rpm
