### ISSUE TITLE
Add an example to FQDN validator

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5297]
When the FQDN value is validated in "Server name" page the following message may appear:

    Fully qualified domain name
    host name with domain composed by 2 parts at least

The "2 parts" refers to the domain, but is a bit ambiguous. An example would clarify the meaning

    Fully qualified domain name
    must contain at least two dots, like myhost.example.com

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-httpd-admin-2.0.10-1.1.g7ca831e.ns7.noarch.rpm
nethserver-base-3.0.20-1.3.g267cb12.ns7.noarch.rpm

Pushed transifex source translations for nethserver-base and nethgui repos.

**Comment by gsanchietti** [comment]
Tried to set ``test`` as FQDN, the error says:
> must contain at least two dots, like "myhost.example.com"

**Verified**

**Comment by gsanchietti** [comment]
Released:
nethserver-httpd-admin-2.0.11-1.ns7.noarch.rpm
nethserver-base-3.0.21-1.ns7.noarch.rpm
