### ISSUE TITLE
Do not list shared mailbox subfolders

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5298]
If a group of users has write access to a shared mailbox (Public IMAP namespace), during the time  subfolders could be created.

**Steps to reproduce**

- create a shared mailbox
- add some messages to it, including subfolders

**Expected behavior**

The "Email addresses > Shared mailboxes" page must list only first level elements.

**Actual behavior**

Subfolders are listed, too.

**Components**

nethserver-mail-server-1.10.13-1.ns7.noarch

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.14-1.4.g31983f6.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Created "testpub" public shared mailbox with "nested" dir.

Only "testpub" appears inside the web interface.

**Comment by gsanchietti** [comment]
Released:
nethserver-mail-server-1.10.15-1.ns7.noarch.rpm
