### ISSUE TITLE
Web proxy: support bypass by domains

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5299]
When Squid web proxy is configured as transparent, the administrator should be able to allow destination bypass using domains.
Example: bypass the proxy when visiting "www.nethserver.org" and "google.com".

The implementation can take advantage of dnsmasq ipset option.

How it works:
- a client requests access to a bypassed domain (eg. www.nethserver.org)
- the name is resolved by dnsmasq and the IP address is added to a well-known ipset
- all addresses inside the ipset are excluded from the REDIRECT in shorewall

Things  to be done:
- [x] configure dnsmasq with the ipset option
- [x] add a prop to save the list of bypassed domains
- [x] create a web interface to add all bypassed domains

----

Thanks to @filippocarletti  for the working prototype

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-squid-1.5.4-1.10.g971257d.ns7.noarch.rpm

**Test case**
- Configure a machine with web proxy in transparent mode for green
- Add a domain to the bypass list
- Check the domain is bypassed when visited from a client inside the green network

**Comment by DavidePrincipi** [comment]
I'm testing this enhancement. @filippocarletti , @gsanchietti please tell me if the following behavior is expected:

- a domain name "help.nextcloud.com" was added to "Domains without proxy"
- green client connects via HTTP to "help.nextcloud.com"
- the first response **contains** the proxy headers
- subsequent responses do **not contain** proxy headers any more

When this feature is combined with the web-filter I can't predict the effect of blocking the first request when a complex web page is loaded. 

Should we add the same domains to the filter whitelist?

Side note: domain names do not match subdomains (i.e. example.com do not match sub.example.com).

**Comment by filippocarletti** [comment]
Your client DNS server should be set to NethServer [add a note to online help/manual?]
The first response should NOT contain proxy headers.
No need to add domains to any additional list.
AFAIK, domain names should match subdomains, see `man dnsmasq`, address and server section.

**Comment by DavidePrincipi** [comment]
> Your client DNS server should be set to NethServer

You're right: it fixes the problem. I'd rather say **it must** be set to NethServer!

Let's fix the docs!

> domain names should match subdomains

When the DNS is fixed, the sub domain match occurs. I see multiple IP in the ipset

<pre>
[root@vm5 ~]# ipset list
Name: squid-bypass
Type: hash:ip
Revision: 1
Header: family inet hashsize 1024 maxelem 65536 timeout 43200
Size in memory: 16656
References: 1
Members:
88.198.160.135 timeout 43185
88.198.160.129 timeout 43168
</pre>

**Comment by gsanchietti** [comment]
Missing documentation to be added before release:
- add DNS note to inline help
- add note about domain matching subdomains
- update administrator manual
- update developer manual

**Comment by filippocarletti** [comment]
A common scenario is:
1. windows pc client have dns server set to their windows AD server
2. AD server uses NethServer as forwarder

**Comment by gsanchietti** [comment]
Released:
nethserver-squid-1.6.0-1.ns7.noarch.rpm
