### ISSUE TITLE
Remove "vmail+" prefix from Mail aliases page

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5300]
As admin, when I create a new mail alias the shared mailboxes are named with "vmail+" prefix. Also in the table view the "vmail+" prefix is displayed.

That prefix is awkward and unclear, should be expanded as "shared mailbox" or similar.

See also

http://community.nethserver.org/t/ns7-shared-mailbox-update/3757/4

---

Thanks to @filippocarletti

**Comment by DavidePrincipi** [comment]
**Test case**

After upgrading to the testing package the "Email addresses > Mail aliases" page no longer display **shared mailboxes** with "vmail+" prefix. On the contrary, a " (shared mailbox)" suffix is appended to UI labels. This must be true both on table view and when editing the single mail alias "destinations" field.

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.14-1.24.g033a3d3.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
All shared mailbox are listed as "<name> (shared mailbox)".

**Verified**

**Comment by gsanchietti** [comment]
Released:
nethserver-mail-server-1.10.15-1.ns7.noarch.rpm
