### ISSUE TITLE
nDPI: BUG: scheduling while atomic

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5301]
/var/log/messages contains lines like the following:
`Apr 12 20:11:43 nsec-backup kernel: BUG: scheduling while atomic: swapper/3/0/0x10000500
`
I can't reproduce the problem at will, but I'm running a patched version of ndpi since 3 weeks and log lines have disappeared.

**Comment by gsanchietti** [comment]
In nethesis-testing:
kmod-xt_ndpi-2.0.0-1.3.g47baae2.ns7.x86_64.rpm

**Test case 1**
- Install on a clean machine
- Check the error message is gone

**Test case 2**
- Update an existing machine with nethserver-ndpi installed
- Check the error message is gone

**Comment by gsanchietti** [comment]
Verified both on a clean install and on an update machine.

**Comment by gsanchietti** [comment]
Released:
kmod-xt_ndpi-2.0.1-1.ns7.x86_64.rpm
