### ISSUE TITLE
 Same FQDN can be set to different virtualhosts

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5303]
**Steps to reproduce**

Create a virtualhost, set a fqdn domain name
create a second virtualhost, set the same fqdn domain name

**Expected behavior**

I expect that an error is displayed, you cannot have two virtualhosts reachable by the same domain name

**Actual behavior**

No error and the template in /etc/httpd/conf.d/virtualhosts.conf is correctly written with the same domain name for the two virtualhost

**Components**

nethserver-virtualhosts-1.0.2-1.ns7.noarch
NethServer release 7.3.1611 (Final)

**See also**

http://community.nethserver.org/t/same-fqdn-can-be-set-to-different-virtualhosts/6920/1

----

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-virtualhosts-1.0.3-1.3.g8c19de1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
It works as expected.

**VERIFIED**

**Comment by gsanchietti** [comment]
Released:
nethserver-virtualhosts-1.0.4-1.ns7.noarch.rpm
