### ISSUE TITLE
Roundcube web access permission error

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5304]
**Steps to reproduce**

- install Roundcube
- ``https://server/webmail`` is always accessible from LAN
- outside LAN, Roundcube is not accessible

**Expected behavior**

Access roundcube interface from outside LAN

**Actual behavior**

Apache error message

     Forbidden - You don't have permission to access /webmail/ on this server.

**Components**

nethserver-roundcubemail-1.2.7-1.ns7.noarch

**See also**

http://community.nethserver.org/t/roundcubemail-forbidden-you-dont-have-permission-to-access-webmail-on-this-server/6923

----

Thanks to 

**jose_manuel_Insausti** for pointing it out, @stephdl for the bug analysis

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-roundcubemail-1.2.7-1.4.gf06d49f.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Verified.

Added a new README to nethserver-roundcubemail respository.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-roundcubemail-1.2.8-1.ns7.noarch.rpm
