### ISSUE TITLE
Multi WAN: false alarm on busy link

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5305]
**Steps to reproduce**

Note: hard to reproduce

- Setup a multi wan, set lost ping number to 2
- Try to fill the pipe with a big upload
- Check that the line is disabled while the upload still goes on

**Expected behavior**

Provider should not be disabled, it's working

**Actual behavior**

The provider is disabled and re-enabled within seconds

Theory: during a fast upload, especially if bandwidth management is not configured (or wrongly configured), lsm pings to check wan status may get answered with a big delay.

I experimented a bit with higher lsm ping timeout values, borrowing from a well-established project (https://wiki.openwrt.org/doc/howto/mwan3).
I propose to set the timeout to 4 seconds.

**Comment by gsanchietti** [comment]
Are you suggesting to raise this option from 2000 to 4000?

https://github.com/NethServer/nethserver-lsm/blob/master/root/etc/e-smith/templates/etc/lsm/lsm.conf/10base#L28

**Comment by filippocarletti** [comment]
Yes. Thank you.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-lsm-1.2.2-1.3.g288bc1d.ns7.noarch.rpm

**Test case**
Check LSM is more tolerant when provider bandwidth is full.

**Comment by filippocarletti** [comment]
I tested the update on some systems that were showing the fast down/up issue.
Most of the problems went away.

**Comment by gsanchietti** [comment]
Backported also to NS 6.

Released:
- NS 7: nethserver-lsm-1.2.3-1.ns7.noarch.rpm
- NS 6: nethserver-lsm-1.1.4-1.ns6.noarch.rpm
