### ISSUE TITLE
Nextcloud: update to 12.0.0

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5306]
Upgrade Nextcloud to latest upstream release (12.0.0).
The new package must handle new installation and the upgrade from Netxtcloud 10.

See upstream release: https://github.com/nextcloud/server-packages/releases/tag/centos-12.0.0

**Packages**

nethserver-nextcloud
nextcloud

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nextcloud-12.0.0-1.ns7.noarch.rpm
- nethserver-nextcloud-1.1.3-1.2.g7f11a17.ns7.noarch.rpm

**Test case 1**
- Install on a clean machine with LDAP or Samba AD
- Check everything correctly works

**Test case 2**
- Upgrade a running machine with Netxtcloud 11.0.2 with  LDAP or Samba AD
- Check everything correctly works

**Comment by fasttech** [comment]
Tested upgrade from 11.0.3 on AD machine, no issues observed, tested against browser gui, win and ios clients, all users good.

**Comment by gsanchietti** [comment]
Tested also by @robb, everything seems good.

**Comment by gsanchietti** [comment]
Released:
- nextcloud-12.0.0-1.ns7.noarch.rpm
- nethserver-nextcloud-1.1.4-1.ns7.noarch.rpm
