### ISSUE TITLE
Web filter not working with profiles configured for a group (again)

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5307]
Web filter profiles based on groups never match.

**Steps to reproduce**

1. create a group named "g1" with a user "goofy" inside
2. create a restricted web filter profile which blocks a site, eg "www.nethserver.org"
3. create a web filter profile using the "g1" group in the "Who" field
3. try to access a blocked site as a user contained in the group

The issue can be tested using following command:
```
 echo "http://www.nethserver.org 192.168.1.2/ goofy - GET" | /usr/sbin/ufdbgclient -d
```

**Expected behavior**

The access must be denied and the user must be redirect to the block page.
Above command must return something like:
```
OK status=302 url="http://192.168.1.1/cgi-bin/nethserver-block.cgi?clientaddr=192.168.1.2&clientname=unknown&clientident=goofy&srcclass=src_tgroup&targetgroup=test&url=http%3A%2F%2Fwww.nethserver.org"
```

**Actual behavior**

The user can access the blocked site.
Above command returns:
```
OK
```

**Components**

nethserver-squidguard-1.7.0-1.ns7.noarch

**See also**

http://community.nethserver.org/t/groundhog-day-web-filter-not-working-with-profiles-configured-for-a-group-again/6871

----

Thanks to @renen for finding the bug!

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-squidguard-1.7.0-1.3.g31c6d50.ns7.noarch.rpm

**Test case**
Check the bug is not reproducible.

**Comment by DavidePrincipi** [comment]
A filesystem permission error prevents accessing the ContentFilter UI page

    Nethgui:
        404 - Not found
        1324379722+0

**Comment by DavidePrincipi** [comment]
**VERIFIED**

**Comment by gsanchietti** [comment]
Released:
nethserver-squidguard-1.7.1-1.ns7.noarch.rpm
