### ISSUE TITLE
Realm join fails with poor entropy

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5308]
When a new Samba DC is provisioned, a new self-signed SSL certificate is generated. This operation takes some time (depending on hardware speed and random numbers availability). The nethserver-join action might fail during ``realm join`` operation if certificate generation takes more than 15 seconds.

**Steps to reproduce**

Configure a local AD accounts provider in a slow or poor entropy system.

**Expected behavior**

The nethserver-join action succeedes.

**Actual behavior**

The nethserver-join action fails.

In ``/var/log/messages``:

<pre>
Jun  1 16:39:27 firewall esmith::event[22285]: Action: /etc/e-smith/events/nethserver-dc-save/S95nethserver-dc-waitstart SUCCESS [102.541861]
...
Jun  1 16:39:32 firewall systemd: Started Realm and Domain Configuration.
Jun  1 16:39:32 firewall realmd: * Resolving: _ldap._tcp.ad.nethserver.org
Jun  1 16:39:32 firewall realmd: * Performing LDAP DSE lookup on: 192.168.2.3
Jun  1 16:39:32 firewall realmd: ! Can't contact LDAP server
...
Jun  1 16:39:45 firewall esmith::event[22285]: realm: Cannot join this realm
Jun  1 16:39:45 firewall realmd: ! Can't contact LDAP server
Jun  1 16:39:45 firewall esmith::event[22285]: [WARNING] DC join attempt 3 of 3 failed! Wait a few seconds...
Jun  1 16:39:50 firewall esmith::event[22285]: [ERROR] DC join failed
Jun  1 16:39:50 firewall esmith::event[22285]: Action: /etc/e-smith/events/nethserver-dc-save/S96nethserver-dc-join FAILED: 1 [22.535393]
</pre>

This is the nsdc journal excerpt:

<pre>
Jun 01 16:39:22 nsdc-firewall.ad.nethserver.org samba[37]: samba version 4.6.4 started.
Jun 01 16:39:22 nsdc-firewall.ad.nethserver.org samba[37]: Copyright Andrew Tridgell and the Samba Team 1992-2017
Jun 01 16:39:24 nsdc-firewall.ad.nethserver.org samba[37]: samba: using 'standard' process model
Jun 01 16:39:24 nsdc-firewall.ad.nethserver.org samba[37]: Attempting to autogenerate TLS self-signed keys for https for hostname 'NSDC-FIREWALL.ad.nethserver.org'
Jun 01 16:39:24 nsdc-firewall.ad.nethserver.org winbindd[49]: [2017/06/01 16:39:24.875896,  0] ../source3/winbindd/winbindd_cache.c:3171(initialize_winbindd_cache)
Jun 01 16:39:24 nsdc-firewall.ad.nethserver.org winbindd[49]:   initialize_winbindd_cache: clearing cache and re-creating with version number 2
Jun 01 16:39:26 nsdc-firewall.ad.nethserver.org smbd[41]: [2017/06/01 16:39:26.404337,  0] ../lib/util/become_daemon.c:124(daemon_ready)
Jun 01 16:39:26 nsdc-firewall.ad.nethserver.org smbd[41]:   STATUS=daemon 'smbd' finished starting up and ready to serve connections
Jun 01 16:39:26 nsdc-firewall.ad.nethserver.org winbindd[49]: [2017/06/01 16:39:26.498499,  0] ../lib/util/become_daemon.c:124(daemon_ready)
Jun 01 16:39:26 nsdc-firewall.ad.nethserver.org winbindd[49]:   STATUS=daemon 'winbindd' finished starting up and ready to serve connections
Jun 01 16:39:45 nsdc-firewall.ad.nethserver.org samba[37]: TLS self-signed keys generated OK
</pre>

**Components**

nethserver-dc-1.2.3

----

Thanks to @nrauso for pointing it out

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.2.3-1.2.ge02897d.ns7.x86_64.rpm

**Comment by nrauso** [comment]
tested: **OK**

In the same conditions the nethserver-join action succeedes.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-dc-1.2.4-1.ns7.x86_64.rpm
