### ISSUE TITLE
Backup data: duplicity fails with "FilePrefixError: +"

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5309]
The backup data fails if an include or exclude file contains empty lines.
Extract from `` /var/log/backup-data.log``:

> Reading globbing filelist /tmp/oNVMjZ4ftO
> Traceback (most recent call last):
> File "/usr/bin/duplicity", line 1546, in 
> with_tempdir(main)
> File "/usr/bin/duplicity", line 1540, in with_tempdir
> fn()
> File "/usr/bin/duplicity", line 1375, in main
> action = commandline.ProcessCommandLine(sys.argv[1:])
> File "/usr/lib64/python2.7/site-packages/duplicity/commandline.py", line 1154, in ProcessCommandLine
> set_selection()
> File "/usr/lib64/python2.7/site-packages/duplicity/commandline.py", line 978, in set_selection
> sel.ParseArgs(select_opts, select_files)
> File "/usr/lib64/python2.7/site-packages/duplicity/selection.py", line 272, in ParseArgs
> for sf in self.filelist_globbing_get_sfs(filelists[filelists_index], 1, arg):
> File "/usr/lib64/python2.7/site-packages/duplicity/selection.py", line 371, in filelist_globbing_get_sfs
> yield self.glob_get_sf(line, include)
> File "/usr/lib64/python2.7/site-packages/duplicity/selection.py", line 434, in glob_get_sf
> sel_func = self.glob_get_filename_sf(glob_str, include)
> File "/usr/lib64/python2.7/site-packages/duplicity/selection.py", line 502, in glob_get_filename_sf
> raise FilePrefixError(filename)
> FilePrefixError: +

**Steps to reproduce**

- Install nethserver-backup-data and configure it
- Install nethserver-virtualhosts but do not configure it
- Execute the backup from command line: ``backup-data``

**Expected behavior**

The backup should be successful.

**Actual behavior**

The ``backup-data`` command exits with status code 1.
The bug is present each time an include file contains an empty line.
Check the content of ``/etc/backup-data.d/nethserver-virtualhosts.include`` for a test case.

**Components**

nethserver-backup-config-1.5.5-1.ns7.noarch

**See also**

- http://community.nethserver.org/t/backup-data-error-fileprefixerror/6982
- http://community.nethserver.org/t/duplicity-error-on-full-backup-to-nfs-share/6962

----

Thanks to @Andrey_Romakhin, @dnutan, @Guus, @indra

**Comment by gsanchietti** [comment]
Already tested by multiple users.

**Comment by gsanchietti** [comment]
Released:
nethserver-backup-config-1.5.6-1.ns7.noarch.rpm

**Comment by jbnv** [comment]
I'm getting this error for the `--exclude` option, no matter what I specify to exclude and even if I `--exclude-filelist`. Here's an example of my trace. I'm using Ubuntu 18.04.3 LTS. I juts uninstalled and reinstalled duplicity today.

```
Traceback (innermost last):
  File "/usr/bin/duplicity", line 1555, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 1541, in with_tempdir
    fn()
  File "/usr/bin/duplicity", line 1380, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1149, in ProcessCommandLine
    set_selection()
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 973, in set_selection
    sel.ParseArgs(select_opts, select_files)
  File "/usr/lib/python2.7/dist-packages/duplicity/selection.py", line 250, in ParseArgs
    self.add_selection_func(self.glob_get_sf(arg, 0))
  File "/usr/lib/python2.7/dist-packages/duplicity/selection.py", line 434, in glob_get_sf
    sel_func = self.glob_get_filename_sf(glob_str, include)
  File "/usr/lib/python2.7/dist-packages/duplicity/selection.py", line 502, in glob_get_filename_sf
    raise FilePrefixError(filename)
 FilePrefixError: .git
```

**Comment by gsanchietti** [comment]
> I'm using Ubuntu 18.04.3 LTS. I juts uninstalled and reinstalled duplicity today.

Sorry @jbnv , but this issue is relative to Duplicity installed on NethServer.
By the way, I can suggest you to remove all empty lines from your exclude file.

For more info, please see the upstream project: http://duplicity.nongnu.org/
