### ISSUE TITLE
Allow WebSocket Proxy Pass

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5311]
Isn't possible tocreate ws and wss proxy pass because only destination starting with http are allowed from interface. 
When a destination starting with ws or wss is manually inserted into proxypass db, template is correctly generate and web socket proxy pass works correctly.

**Comment by Stell0** [comment]
nethserver-testing repository: 
* **nethserver-httpd-3.1.3-1.2.gd40ba82.ns7.noarch.rpm**
* **nethserver-httpd-proxypass-3.1.3-1.2.gd40ba82.ns7.noarch.rpm**

Test case: 
* create a new ProxyPass with ws:// and wss:// destination
* check that /etc/httpd/conf.d/proxypass.conf contains correct proxy pass 

```
ProxyPass       /test   wss://myhttpurl.it
ProxyPassReverse        /test   wss://myhttpurl.it
```

* check that Web Socket proxy pass actually works

**Comment by gsanchietti** [comment]
Tested with ``wss``, ``ws`` and ``smtp://`` (invalid).

**VERIFIED**

**Comment by gsanchietti** [comment]
Released:
- nethserver-httpd-3.1.4-1.ns7.noarch.rpm
- nethserver-httpd-proxypass-3.1.4-1.ns7.noarch.rpm
