### ISSUE TITLE
OpenvPN: improve net2net tunnels 

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5313]
Improve current implementation of OpenVPN tunnel.

The administrator should be able to:

- create an unlimited number of tunnels each one with different configuration options (routes, psk, etc)
- select multiple wan for connections when configuring OpenVPN clients
- easily transfer configuration from tunnel server to tunnel client

--- 

See also: http://community.nethserver.org/t/feedback-on-new-openvpn-tunnels/7199

**Comment by gsanchietti** [comment]
OpenVPN page has been split in two pages:
- OpenVPN roadwarrior
- OpenVPN tunnels

Work in progress: https://github.com/gsanchietti/nethserver-openvpn/tree/tunnels

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-openvpn-1.5.1-1.21.gbf57f47.ns7.noarch.rpm

**Test case 1**
*This is the most important test case since we should not break existing installations*
- Update an existing machine with an OpenVPN client already configured
- Check the client can still connect after the update
- Try to change something from the web interface
- Check the client can still connect after changes

**Test case 2**
- On the master firewall, create a tunnel server with p2p topology
- Download the configuration file and upload to the slave firewall
- Check that connected remote networks can ping each other

**Test case 3**
- On the master firewall, create a tunnel server with subnet topology
- Download the configuration file and upload to the slave firewall
- Check that connected remote networks can ping each other

**Test case 4**
- Try to change any server option (cipher, protocol, compression, etc)
- Manually configure a client and check everything is working as exptected

**Comment by gsanchietti** [comment]
Changes:
- UI tweaks
- fix client template
- fix firewall configuration for server

In nethserver-testing:
nethserver-openvpn-1.5.1-1.26.g70da8d6.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
**VERIFIED**

Tested all 4 cases work for me. My testing environment is built on dply.co VPS provider, provisioned with this script:

https://gist.github.com/DavidePrincipi/5907bf4bc122e44c842ec46f66958829

**Comment by gsanchietti** [comment]
Released:
nethserver-openvpn-1.6.0-1.ns7.noarch.rpm

Adminsitrator and developer manual already up to date.
