### ISSUE TITLE
collectd ping plugin segfault

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5316]
```
Dec  6 09:57:41 demosecurity collectd[3377]: ping plugin: host 192.168.6.253 has not answered 30 PING requests, triggering resolve
Dec  6 09:57:41 demosecurity kernel: collectd[3416]: segfault at 600001d00 ip 00007fee91ee2020 sp 00007fee84967a20 error 4 in liboping.so.0.2.9[7fee91edf000+4000]
Dec  6 09:57:41 demosecurity systemd: collectd.service: main process exited, code=killed, status=11/SEGV
```

collectd has a segmentation fault which restarts the daemon, loosing some samples ("holes" in the graphs) when a pinghost doesn't answer.
It seems that the segfault happens when collectd tries to re-resolve the host after 30 failed pings.
I disabled MaxMissed and all segfault disappeared.

**Steps to reproduce**

- Set an unrachable pinghost
- wait about 3 minutes

Resolution: add MaxMissed -1

**Comment by Stell0** [comment]
nethserver-testing: nethserver-collectd-3.0.5-1.1.g94143ac.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
```
# grep Max /etc/collectd.d/ping.conf 
MaxMissed -1

```

**Comment by gsanchietti** [comment]
Released:
nethserver-collectd-3.0.6-1.ns7.noarch.rpm
