### ISSUE TITLE
AD account provider: web interface doesn't correctly display users with password expiration

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5318]
When modifying an existing user, the web interface always displays "Enable password expiration" option as disabled, regardless of the real value inside the account provider.

**Steps to reproduce**

- Install a local AD account provider
- Create a user "goofy" and make sure "Enable password expiration" is enabled
- Click on "Edit" for the created user

**Expected behavior**

The web interface should display a tick beside "Enable password expiration" option.

**Actual behavior**

The "Enable password expiration" option is shown as disabled.

**Components**

nethserver-sssd-1.2.1-1.ns7.noarch

----

Thanks to @nrauso

**Comment by gsanchietti** [comment]
In nehtserver-testing:
- nethserver-sssd-1.2.1-1.2.g033769b.ns7.noarch.rpm

**Test case**
- Install a local Samba AD
- Make sure password expiration is enabled inside "Password policy" page
- Create a user "user1" with password expiration enabled
- Create a user "user2" with password expiration disabled
- Try to edit both users and check the password expiration checkbox is checked for "user1" and not check for "user"

**Comment by DavidePrincipi** [comment]
The checkbox state appears consistent. However the underlying ``pdbedit`` output seems to report an inverted condition.

My test, in UI:

* first.user checked
* second.user unchecked

Pdbedit output:

```text
bash-4.2# pdbedit  -v  first.user
Unix username:        first.user
NT username:          
Account Flags:        [U          ]

Password last set:    Tue, 27 Jun 2017 17:13:06 CEST
Password can change:  Tue, 27 Jun 2017 17:13:06 CEST
Password must change: never

bash-4.2# pdbedit  -v  second.user
Unix username:        second.user
NT username:          
Account Flags:        [UX         ]
Password last set:    Tue, 27 Jun 2017 17:13:28 CEST
Password can change:  Tue, 27 Jun 2017 17:13:28 CEST
Password must change: Tue, 19 Jan 2038 04:14:07 CET
```

Furthermore, the default password expiration was set to 30 days.

**Comment by DavidePrincipi** [comment]
The output of ``pdbedit`` is unclear, the "Password must change" value is misleading. It reports correctly the "X" under "Account Flags" field. 

To get when the user password expires this is the [correct command](https://blogs.technet.microsoft.com/poshchap/2014/02/21/one-liner-get-a-list-of-ad-users-password-expiry-dates/):

    net ads search -P samaccountname=first.user msDS-UserPasswordExpiryTimeComputed

**VERIFIED**

**Comment by DavidePrincipi** [comment]
The bug fix is verified. I also added a PR that removes the obsolete password warning slider.

**Comment by gsanchietti** [comment]
Released:
nethserver-sssd-1.2.2-1.ns7.noarch.rpm
