### ISSUE TITLE
Smbd do not listen additional IP

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5319]
If an IP alias is configured, smbd listens on either original or alias IP. It seems smbd chooses to bind to the lowest IP address.

**Steps to reproduce**

- set green ip ``192.168.122.5``
- install file server module, create shared folder ``iba1``
- define an IP alias ``192.168.122.4``

**Expected behavior**

smbclient -U 'guest%guest' //192.168.122.4/iba1
smbclient -U 'guest%guest' //192.168.122.5/iba1

Both should work.

**Actual behavior**

Only 192.168.122.4 works.

Also

```text
ss -4nlp | grep smbd
tcp    LISTEN     0      50     127.0.0.1:139                   *:*                   users:(("smbd",pid=3845,fd=38))
tcp    LISTEN     0      50     192.168.122.4:139                   *:*                   users:(("smbd",pid=3845,fd=36))
tcp    LISTEN     0      50     127.0.0.1:445                   *:*                   users:(("smbd",pid=3845,fd=37))
tcp    LISTEN     0      50     192.168.122.4:445                   *:*                   users:(("smbd",pid=3845,fd=35))
```

**Components**

nethserver-samba-2.0.7-1.ns7.noarch
nethserver-ibays-3.1.1-1.ns7.noarch
(no accounts provider)

**See also**

http://community.nethserver.org/t/smb-do-not-listen-on-alias-ip/7113

----

Thanks to **sharpec** for pointing it out!

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-samba-2.0.7-1.6.g2440d2e.ns7.noarch.rpm

**Comment by SebastianMB-IT** [comment]
**Tested**

smbclient -U 'guest%guest' //192.168.122.4/iba1
smbclient -U 'guest%guest' //192.168.122.5/iba1

Both work.

**Comment by gsanchietti** [comment]
Released:
nethserver-samba-2.0.8-1.ns7.noarch.rpm
