### ISSUE TITLE
OpenVPN: add extra push options to roadwarrior server

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5320]
The administrator should be able to:

- select if the client must receive all configured static routes or only routes for green networks 
- push extra DHCP options:
  - Domain
  - DNS server
  - WINS server
  - NBDD server

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-openvpn-1.5.1-1.11.g2ec7429.ns7.noarch.rpm

**Test case 1**
- Update an existing machine with a roadwarrior server already enabled
- Check connected clients can still reconnect after the server restart

**Test case 2**
- Change the new fields from the web interface
- Check the new options are pushed to client

**Comment by DavidePrincipi** [comment]
In nethserver-testing:

nethserver-openvpn-1.5.1-1.14.gb1a13e2.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
nethserver-openvpn-1.6.0-1.ns7.noarch.rpm
