### ISSUE TITLE
Cannot connect DC sysvol share on gateway

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5321]
If both a red interface is configured and local Samba AD module is installed a client from a secondary green network cannot reach the DC host.

**Steps to reproduce**

- Configure a red interface, and primary green (192.168.122.0/24)
- Configure a secondary green network (192.168.101.0/24)
- Install local Samba AD accounts provider (192.168.122.55)

**Expected behavior**

A client in seconday green can ping DC and connect sysvol share on DC

**Actual behavior**

Ping fails, smbclient fails

```text
smb: \> [root@vm8 ~]# smbclient -U 'DPNET\admin%Nethesis,1234' //192.168.122.55/sysvol
Connection to 192.168.122.55 failed (Error NT_STATUS_IO_TIMEOUT)
```

**Components**

nethserver-dc-1.2.4

**See also**

A similar problem could occur from VPN/trusted networks.

http://community.nethserver.org/t/smb-do-not-listen-on-alias-ip/7113/22

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.2.4-1.5.ge8f6663.ns7.x86_64.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing
nethserver-dc-1.2.4-1.6.g0f9daf1.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
Tested on virtual environment bridged to a physical one.

**VERIFIED**

**Comment by gsanchietti** [comment]
Samba updated to 4.6.5.

Released:
- nethserver-dc-1.2.5-1.ns7.x86_64.rpm
