### ISSUE TITLE
IPSec tunnels: UI tweaks

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5323]
Improve the web interface:

- allow IP addresses and host names in the "Remote IP" field
- enable and disable tunnels from the table view by adding two new actions

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-ipsec-tunnels-1.1.0-1.4.gb0aa578.ns7.noarch.rpm

**Test case**
- Check a tunnel can be enabled and disabled from table view
- Try to insert and host name inside the "Remote IP" field
- When creating a new tunnel, check the PSK field is pre-compiled

**Comment by SebastianMB-IT** [comment]
**Tested**

**Comment by gsanchietti** [comment]
Released:
nethserver-ipsec-tunnels-1.1.1-1.ns7.noarch.rpm
