### ISSUE TITLE
Virtual hosts: add indexes option

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5324]
Allow the administrator to choose if enable Apache index options inside each virtual hosts.

See:
- https://httpd.apache.org/docs/2.4/mod/core.html
- http://community.nethserver.org/t/no-matching-directoryindex-index-html-index-php/6797

----

Thanks to @stephdl  for the idea and the implementation!

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-virtualhosts-1.0.4-1.4.g2d7fefc.ns7.noarch.rpm

**Test case 1**
- Update an existing machine
- Check the index behavior doesn't change

**Test case2**
- Create a new virtual hosts
- Enable the Index option
- Check the user can see the list of files

**Comment by SebastianMB-IT** [comment]
Tested

**Comment by gsanchietti** [comment]
Released:
nethserver-virtualhosts-1.0.5-1.ns7.noarch.rpm
