### ISSUE TITLE
Backup-data: add bayes db

### ISSUE THREAD

**Issue by SebastianMB-IT** [NethServer/dev#5325]
Bayes db is not added to any backup

**Changes**

Add /var/spool/amavisd/.spamassassin/ to backup-config

**Comment by SebastianMB-IT** [comment]
In nethserver-testing:

-  nethserver-backup-data-1.3.1-1.8.g7a4a90d.ns7.noarch.rpm

**Test case**

- Update nethserver-backup-data from testing
- Make a backup data
- Delette all files from /var/spool/amavisd/.spamassassin/
- Restore backup

**Comment by SebastianMB-IT** [comment]
In nethserver-testing:

-  nethserver-mail-common-1.6.3-1.1.g41baf7a.ns7.noarch.rpm

**Test case**

- Update nethserver-mail-common from testing
- Make a backup data
- Delette all files from /var/spool/amavisd/.spamassassin/
- Restore backup

**Comment by gsanchietti** [comment]
Added a fake ``goofy`` file:
```
touch  /var/spool/amavisd/.spamassassin/goofy
backup-data
[root@test ~]# backup-data-list  | grep spamassassin
Thu Jul  6 15:50:52 2017 var/spool/amavisd/.spamassassin
Thu Jul  6 15:50:52 2017 var/spool/amavisd/.spamassassin/goofy
```

**VERIFIED**

**Comment by gsanchietti** [comment]
Released:
nethserver-mail-common-1.6.4-1.ns7.noarch.rpm
