### ISSUE TITLE
Web proxy: support divert and priority rules

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5327]
Firewall rules for routing traffic to a specific provider, or decrease/increase priority, are applied only to network traffic which traverse the gateway.
These rules don't apply if the traffic goes through the proxy because the traffic is generated from the gateway itself.

Scenario:
- Web proxy enabled in transparent mode
- the firewall contains a rule like:  the traffic from the host ``goofy`` to the public Internet must have low priority
- when ``goofy`` tries to access a non-HTTP service like SSH, the traffic has low priority
- when ``goofy`` tries to access a web site, the traffic is intercepted by the proxy and the low priority rule is not applied

The new web interface for the web proxy, will allow to create rules like:

- HTTP/S traffic from host badpc has low priority
- HTTP/S traffic from CIDR service_net has high priority
- HTTP/S traffic from myprinter diverted to myslownet provider (automatic failover)
- HTTP/S traffic from mywebserver forced to myfastnet provider (no switch if the WAN goes down)

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-squid-1.6.0-1.6.g8f87c5d.ns7.noarch.rpm

**Test case 1**
- Configure a machine with at least 2 red interfaces
- Create rules to divert traffic to the first provider
- Check the rules are applied
- Disable the provider: ``shorewall disable <provider>``
- Check the traffic flows trough the second provider

**Test case 2**
- Configure a machine with at least 2 red interfaces
- Create rules to divert traffic to the first provider
- Check the rules are applied
- Disable the provider: ``shorewall disable <provider>``
- Check the client can't surf the web

**Test case 3**
- Configure a machine with 1 or more red interfaces
- Create rules to lower the priority of a host
- Create rules to raise the priority of a host

**Comment by DavidePrincipi** [comment]
**VERIFIED**

*Test case 3*: packets are marked correctly (0x2 0x3) but it seems that traffic shaping is not working. We need to investigate it further.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-squid-1.7.0-1.ns7.noarch.rpm
