### ISSUE TITLE
OpenVPN firewall policy: allow ovpn to net

### ISSUE THREAD

**Issue by SebastianMB-IT** [NethServer/dev#5328]
Always allow network traffic from OpenVPN to Internet.

**Use case**

Internet access through roadwarrior remote tunnel

**Actual behaviour**

Ovpn to net isn't allowed by default in firewall

**Expected behaviour**

Ovpn to net is always allowed in firewall

**Changes**

Set ovpn to net always allowed in firewall

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-openvpn-1.6.0-1.4.g7180e49.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Just after installation, the new policy is active:
```
[root@test ~]# grep ovpn /etc/shorewall/policy
loc            ovpn           ACCEPT
ovpn           loc            ACCEPT
ovpn           $FW            ACCEPT
$FW            ovpn           ACCEPT
ovpn           net            ACCEPT
```

**Comment by gsanchietti** [comment]
Added a warning if the selected mode is "bridged" and no bridge is configured.

**Comment by gsanchietti** [comment]
**VERIFIED**

**Comment by gsanchietti** [comment]
Released:
nethserver-openvpn-1.6.1-1.ns7.noarch.rpm
