### ISSUE TITLE
Nextcloud: add logrotate

### ISSUE THREAD

**Issue by SebastianMB-IT** [NethServer/dev#5329]
Add logrotate for nextcloud logs

**Actual behaviour**

Nextcloud log file isn't added to logrotate

**Change**

Create nextcloud file in logrotate.d

**See also**

http://community.nethserver.org/t/can-nextcloud-logs-be-cleared/7071

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-nextcloud-1.1.4-1.3.g3a5e408.ns7.noarch.rpm

**Test case**
Check the log is correctly rotated

**Comment by filippocarletti** [comment]
```
# ls -l /var/lib/nethserver/nextcloud/nextcloud.log*
-rw-r-----  1 apache apache     957 Jul 10 09:06 /var/lib/nethserver/nextcloud/nextcloud.log
-rw-r-----. 1 apache apache 1618506 Jul  8 14:45 /var/lib/nethserver/nextcloud/nextcloud.log-20170709

```

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-nextcloud-1.1.5-1.ns7.noarch.rpm
