### ISSUE TITLE
Web interface for changing nsdc IP address

### ISSUE THREAD

**Issue by dnutan** [NethServer/dev#5330]
Implement the UI that invokes ``nethserver-dc-change-ip`` event

See also

http://community.nethserver.org/t/change-the-ip-of-the-nsdc-linux-container-also-from-ui/7170
http://community.nethserver.org/t/change-the-ip-address-of-samba-domain-controller/5294

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-sssd-1.2.2-1.9.gd81ea98.ns7.noarch.rpm
nethserver-dc-1.2.5-1.1.gbc319d2.ns7.x86_64.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-sssd-1.3.0-1.ns7.noarch.rpm
nethserver-dc-1.2.6-1.ns7.x86_64.rpm
