### ISSUE TITLE
DHCP server breaks on new logical interface

### ISSUE THREAD

**Issue by SebastianMB-IT** [NethServer/dev#5331]
When an already configured network interface become part of a new bridge or bond the DHCP server breaks.

**Steps to reproduce**

1) Configure one or more interfaces
2) Configure DHCP server
3) Create a new bond/bridge logical interface with inside interface or interfaces previously configured

**Actual behaviour**

- When an interface (ethernet, bridge, bond, vlan) with DHCP configuration wants to become part of a logical interface the DHCP configuration is not updated automatically so DHCP breaks. 
- When more than one interfaces (ethernet, bridge, bond, vlan) become part of a logical interface dhcp breaks because of conflicts without announce.

**Expected behaviour**

- In the case of a single interface copy the dhcp configuration.
- In the case of more interfaces advise about the dhcp conflict.

**Changes**

- [x] Define platform validator "new-logical-interface" ( type, part1, part2, part3... ) in nethserver-base 
- [x] Add action to nethserver-dnsmasq to copy dhcp configuration or advise about the conflicts

**See also**

http://community.nethserver.org/t/changes-to-network-interfaces-break-dhcp-configuration/7048

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dnsmasq-1.6.4-1.5.g5b68e84.ns7.noarch.rpm
nethserver-base-3.0.33-1.8.ga734b38.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-dnsmasq-1.6.5-1.ns7.noarch.rpm
nethserver-base-3.0.34-1.ns7.noarch.rpm
