### ISSUE TITLE
Syntax error prevents ipsec tunnel from starting

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5332]
After some modifications to the configuration, ipsec tunnels fail to start.

**Steps to reproduce**

- create/modify an ipsec tunnel
- see /var/log/messages

**Expected behavior**

Tunnel starts correctly

**Actual behavior**

Error logged:

```text
addconn: cannot load config '/etc/ipsec.conf': /etc/ipsec.d/tunnels.conf:19: syntax error, unexpected STRING [Protocol]
```

on line /etc/ipsec.d/tunnels.conf:19

```text
conn xxxxxx_ipsec-tunnel
    Protocol=udp                          <--line 19
    Topology=subnet                    <--line 20
    authby=secret
    auto=start
    compress=no
```

**Components**

nethserver-openvpn-1.6.0-1.ns7.noarch
nethserver-ipsec-tunnels-1.1.0-1.ns7.noarch

**See also**

http://community.nethserver.org/t/ipsec-failed-to-start-protocol-topology/7349

----

Thanks to **sharpec** for pointing it out

**Comment by filippocarletti** [comment]
The issue is caused by nethserver-openvpn-1.6.0-1.ns7.noarch. :-)

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-openvpn-1.6.1-1.1.gf06e946.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-openvpn-1.6.1-1.2.g0d56f95.ns7.noarch.rpm

**Comment by cotosso** [comment]
vpn db is fixed after the installation of the new rpm.
New ipsec tunnels are created correctly


`[root@demosecurity ~]# diff -u before after 
--- before      2017-07-10 17:51:47.273793737 +0200
+++ after       2017-07-10 17:52:57.555262838 +0200
@@ -1,6 +1,4 @@
 a1=ipsec-tunnel
-    Protocol=udp
-    Topology=subnet
     compress=no
     dpdaction=hold
     esp=auto
@@ -52,14 +50,10 @@
     status=disabled
 test-vpn-user=vpn
     OpenVpnIp=
-    Protocol=udp
-    Topology=subnet
     VPNRemoteNetmask=
     VPNRemoteNetwork=
     status=enabled
 test11=ipsec-tunnel
-    Protocol=udp
-    Topology=subnet
     compress=no
     dpdaction=hold
     esp=custom
`

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-openvpn-1.6.2-1.ns7.noarch.rpm
