### ISSUE TITLE
Shorewall config error with X11 forwarding

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5336]
If a SSH session spawns a local sshd server to enable X11 forwarding, the Shorwall configuration produces a syntax error.

**Steps to reproduce**

- Install ``xauth`` and ``xterm`` (?)  packages
- Connect to NethServer via SSH and enable X11 forwarding (``ssh -A -X ...``)
- Signal event ``firewall-adjust``

**Expected behavior**

Shorewall configuration is correct.

**Actual behavior**

The event fails. In ``/var/log/messages``:

```text
Jul 24 09:34:04 vm5 esmith::event[2310]: Compiling /etc/shorewall/stoppedrules...
Jul 24 09:34:04 vm5 esmith::event[2310]:   ERROR: Invalid TARGET (6010) /etc/shorewall/stoppedrules (line 20)
```

The corresponding fragment is:

```text
    11	# 
    12	# Always keep httpd-admin, SSH and ping available
    13	
    14	ACCEPT  -  $FW  icmp
    15	ACCEPT  -  $FW  tcp  22
    16	ACCEPT  -  $FW  tcp  980
    17	
    18	# Make sure running sshd port is open
    19	ACCEPT  -  $FW  tcp  22
    20	6010
    21	
```

**Components**

nethserver-firewall-base-3.2.4-1.ns7.noarch

**See also**

http://community.nethserver.org/t/shorewall-error-6010-in-the-line-20/7424

----

Thanks to **Rodrigo Vieira Da Costa**, **James Nesbitt**, @dnutan, @filippocarletti

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-firewall-base-3.2.4-1.2.g1faa6f1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.2.4-1.2.g1faa6f1.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
nethserver-firewall-base-3.2.5-1.ns7.noarch.rpm
nethserver-firewall-base-ui-3.2.5-1.ns7.noarch.rpm
