### ISSUE TITLE
Undesired group nesting

### ISSUE THREAD

**Issue by dnutan** [NethServer/dev#5337]
**Steps to reproduce**

- Install nethserver-dc account provider (don't know if nethserver-directory is affected too)
- Go to Users and Groups panel and create some groups (ex. Group1, Group2...)
- Set a group as a member of itself
- Set Group1 as member of Group2, and Group2 as member of Group1

**Expected behavior**
Both group nesting types should be disallowed

**Actual behavior**
Both group nesting types are allowed

**Components**
<= nethserver-sssd-1.3.0-1

**See also**
http://community.nethserver.org/t/nested-groups-assignment/7441

**Comment by DavidePrincipi** [comment]
>  cycles seem to be allowed in AD and RSAT tools

It's weird, but actual behavior is consistent with AD implementation!
