### ISSUE TITLE
MariaDB (MySQL): do not restore root password within configuration backup

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5339]
When the administrator restores a configuration backup on a machine where MariaDB is already installed, the root user can't access any database until a full backup data is restored.

The ``mysql`` command reports the following error:

> ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

This behavior could be misleading for users, so the implementation should be changed to move the restore of database root password inside the configuration backup.

**Comment by gsanchietti** [comment]
In nethserver-testing:
* nethserver-mysql-1.1.1-1.2.g5cb89dc.ns7.noarch.rpm

**Test case 1: new backup format**
- Install nethserver-mysql *from *esting* on a clean machine
- Create at least one database named ``test`` with grants to a new MariaDB user
- Configure the backup data
- Restore only the configuration backup on a new machine with nethserver-mysql installed *from testing*
- Verify MariaDB is accessible with ``mysql`` command
- Restore the data backup
- Verify MariaDB is still accessible and the ``test`` database exists

**Test case 2: old backup format**
- Install nethserver-mysql *from updates* on a clean machine
- Create at least one database named ``test`` with grants to a new MariaDB user
- Configure the backup data
- Restore only the configuration backup on a new machine with nethserver-mysql installed *from testing*
- MariaDB should *not* be accessible accessible with ``mysql`` command
- Restore the data backup
- Verify MariaDB is accessible and the ``test`` database exists

**Comment by DavidePrincipi** [comment]
OK - Test case 1: new backup format

Note: the restore from new backup format works with old packages too

OK - Test case 2: old backup format

----

@filippocarletti @gsanchietti an alternative approach could be

1. include the mysql root's password in backup-config
2. add the following commands in ``post-restore-config`` event:

```shell
newpass=$(cat /var/lib/nethserver/secrets/mysql)
/usr/bin/mysql mysql -u root -e "update user set password=PASSWORD(\"$newpass\") where User='root'; flush privileges;"
```

**Comment by DavidePrincipi** [comment]
In netheserver-testing:
nethserver-mysql-1.1.1-1.5.g8903da5.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Excellent: elegant code, works as expected.

**Comment by gsanchietti** [comment]
Released:
nethserver-mysql-1.1.2-1.ns7.noarch.rpm
