### ISSUE TITLE
OpenVPN: tunnel server stopped after runlevel-adjust

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5340]
OpenVPN tunnels are stopped every time the ``runlevel-adjust`` action is executed.
The ``runlevel-adjust`` action is executed when a package is installed or updated.

The service is stopped because there is a ``service`` record inside the ``configuration`` database (actually used for the firewall) but there isn't a corresponding file inside ``/etc/e-smith/db/configuration/defaults/<service>/type``.

**Steps to reproduce**

- Create an OpenVPN tunnel server named ``test1``
- Execute the firewall adjust: 
```
/etc/e-smith/events/actions/runlevel-adjust  fake-event
```

**Expected behavior**

The ``openvpn@test1`` service must be up and running.

**Actual behavior**

The ``openvpn@test1`` service is stopped.

**Components**

nethserver-openvpn-1.6.3-1.ns7.noarch

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-openvpn-1.6.3-1.2.g0e50dc4.ns7.noarch.rpm

**Test case**

Check the bug is not reproducibile

**Comment by filippocarletti** [comment]
```
Updated:
  nethserver-openvpn.noarch 0:1.6.3-1.2.g0e50dc4.ns7
# systemctl is-active openvpn@tottt
active
# /etc/e-smith/events/actions/runlevel-adjust aaa
# systemctl is-active openvpn@tottt
active
# iptables -vnL | grep 1281
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1281 /* openvpn-tunnel-server: tottt */
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1281 /* openvpn-tunnel-server: tottt */

```

**Comment by gsanchietti** [comment]
Released:
nethserver-openvpn-1.6.4-1.ns7.noarch.rpm
