### ISSUE TITLE
NS 6 upgrade: avoid restore-data when possible

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5343]
Many users upgrade existing NS 6 installations to NS 7 using only the configuration backup, but the actual procedure is designed to require also a restore of data backup.

Improve the current implementation by avoiding the `restore-data` step when possible.

The post-restore-data event can be automatically fired if: 
- backup data is not installed
- backup data is installed but not configured
    
Otherwise:
- if backup data is installed, configured and enabled: data restore is needed
- if backup data is installed, configured but disabled: let the user choose how to end the upgrade procedure

See also:
NethServer/dev#5234

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-backup-config-2.0.1-1.5.g64d5d24.ns7.noarch.rpm
- nethserver-firewall-base-3.2.4-1.4.g500baa7.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.2.4-1.4.g500baa7.ns7.noarch.rpm

**Test case 1**
- Upgrade using a NS6 configuration backup without backup-data installed
- Check the post-restora-data event is automatically fired at the end of the restore

**Test case 2**
- Upgrade using a NS6 configuration backup with backup-data installed but not configured
- Check the post-restora-data event is automatically fired at the end of the restore

**Test case 3**
- Upgrade using a NS6 configuration backup with backup-data installed, configured and enabled
- At the end of the restore, the web interface must display a yellow box with a message inviting the user to execute the `restore-data` command

**Test case 4**
- Upgrade using a NS6 configuration backup with backup-data installed and configured but disabled
- At the end of the restore, the web interface must display a yellow box with a message inviting the user to execute the `restore-data` or `signal-event post-restore-data` commands

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-lib-2.2.5-1.6.gf3b6d71.ns7.noarch.rpm
nethserver-firewall-base-3.2.4-1.6.g861d5e3.ns7.noarch.rpm
nethserver-firewall-base-ui-3.2.4-1.6.g861d5e3.ns7.noarch.rpm

**Test case 5**

Run restore of configuration from UI. The backup must contain a different SSL certificate. Check the procedure completes correctly and the server manager does not freeze.

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-backup-config-2.0.1-1.6.g51a5b12.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-backup-config-2.0.1-1.7.g4e3a710.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Test case 1: VERIFIED
Test case 2: VERIFIED
Test case 3: VERIFIED
Test case 4: VERIFIED

**Comment by gsanchietti** [comment]
Released:
- nethserver-lib-2.2.6-1.ns7.noarch.rpm
- nethserver-firewall-base-3.2.5-1.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.2.5-1.ns7.noarch.rpm
- nethserver-backup-config-2.0.2-1.ns7.noarch.rpm
