### ISSUE TITLE
EveBox

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5346]
Add support for EveBox, a  web based alert and event management tool for events generated by Suricata.
Along with EveBox, Suricata should be refactored to allow the selection of rules  category.

Things to be implemented:

- [x] always enable Eve log in Suricata
- [x] create a new nethserver-evebox package
- [x] disable Snort community rules and use only Emerging Threats ones (nethserver-pulledpork)
- [x] refactor Suricata web interface allowing selection of rule categories

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-suricata-1.0.1-1.12.g186868d.ns7.noarch.rpm
- nethserver-pulledpork-2.0.1-1.11.gf70729e.ns7.noarch.rpm
- nethserver-evebox-0.0.1-1.ns7.noarch.rpm

**Test case 1**
- Install on a clean machine
- Enter `IPS` configuration page inside the Server Manager
- Click the Download button
- Enable one or more categories
- Try to generate traffic hitting the rules
- Access EveBox from the `Applications` page and see the report

**Test case 2**
- Upgrade an existing installation
- Then follow the test case 1

**Note**: when upgrading an existing machine, the user should always access the Server Manager and review the list of enabled/disabled categories.

**Comment by cotosso** [comment]
Test case 1 Verified - Evebox works as expected.

**Comment by cotosso** [comment]
Test Case2 : verified.
Suricata remains enabled after the upgrade.
We just need to download and choose the rules we want to be enabled.

**Comment by gsanchietti** [comment]
Released:
- evebox-0.8.0-1.x86_64.rpm
- nethserver-evebox-1.0.0-1.ns7.noarch.rpm
- nethserver-squidclamav-3.0.0-1.ns7.noarch.rpm
- nethserver-pulledpork-2.1.0-1.ns7.noarch.rpm
