### ISSUE TITLE
latest nethgui changes not included in nethserver-httpd-admin 2.0.12-1

### ISSUE THREAD

**Issue by dnutan** [NethServer/dev#5347]
**Actual behavior**
Latest updates (2017-09-08) include a refactored file upload handler. Nethgui files are not up to date in the latest nethserver-httpd-admin package release, causing error messages on different modules using this functionality:

>[1] Undefined class constant 'FORM_ENC_MULTIPART

I think it could be due to the definition of nethgui_commit not being up to date in the spec file:
https://github.com/NethServer/nethserver-httpd-admin/blob/master/nethserver-httpd-admin.spec#L1

**See also**
http://community.nethserver.org/t/openvpn-module-error-form-enc-multipart/7712/
http://community.nethserver.org/t/form-enc-multipart-error-on-first-time-config-wizard/7714/3

----

Thanks to kelevra (Евгений Копьев) for reporting.

**Comment by gsanchietti** [comment]
Released:
nethserver-httpd-admin-2.0.13-1.ns7.noarch.rpm

The package should be soon propagated to all mirrors.
In the meanwhile, you can disable `mirrorlist` option and enable `baseurl` from `/etc/yum.repos.d/NethServer.repo`

**Comment by gsanchietti** [comment]
Everything seems good, also for NS 6.
