### ISSUE TITLE
Sieve errors prevent mail forwarding

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5351]
A sieve rule to forward mail from a sender fails to trigger with the following error in maillog:
`save failed to open mailbox badh: Mailbox doesn't exist: badh
`
.dovecot.sieve.log contains the same error.

**Steps to reproduce**

- Send a malformed email (bad headers, i.e. bad date)
- Check maillog

**Comment by DavidePrincipi** [comment]
Suggested custom-template

```text
[root@nethservice ~]# cat  /etc/e-smith/templates-custom/etc/amavisd/amavisd.conf/99remove_extension_addresses
#
# 99remove_extension_address
#
@addr_extension_virus_maps = ();
@addr_extension_banned_maps = ();
@addr_extension_spam_maps = ();
@addr_extension_bad_header_maps = ();
```

**Comment by DavidePrincipi** [comment]
In nethserver-testing (7.3.1611)
nethserver-mail-common-1.6.4-1.3.g8417272.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
In nethserver-testing (7.3.1611)
nethserver-mail-common-1.6.4-1.3.g8417272.ns7.noarch.rpm
nethserver-mail-filter-1.4.4-1.2.g8dae3a2.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
From maillog:
```
Oct  4 15:46:40 server amavis[23149]: (23149-11) skip local delivery(3): <pippo@xxx.com> -> <bad-header-quarantine>
Oct  4 15:46:40 server dovecot: lmtp(25217, admin@xxx.com): 6rsyOj7m1FmBYgAA2BkgOg: sieve: msgid=unspecified: stored 
mail into mailbox 'INBOX'

```

**Comment by DavidePrincipi** [comment]
In nethserver-updates (7.3, 7.4)
nethserver-mail-common-1.6.5-1.ns7.noarch.rpm
nethserver-mail-filter-1.4.5-1.ns7.noarch.rpm
