### ISSUE TITLE
squid crashes when ecap-clamav is enabled

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5352]
**Steps to reproduce**

- Enable antivirus in web content filter
- Experience web browsing slowness and random errors
- Check cache.log

**Components**

nethserver-squidclamav-2.0.0-1.ns7.noarch
ecap-clamav-2.0.0-1.ns7.x86_64

Log excerpts:
Many:
`FATAL: Received Segment Violation...dying.`
Sometimes also:
```
kid1| ERROR: NAT/TPROXY lookup failed to locate original IPs on local=192.168.0.88:3130 remote=192.168.0.241:46760 FD 15 flags=33
kid1| ERROR: NF getsockopt(ORIGINAL_DST) failed on local=192.168.0.88:3129 remote=192.168.0.93:62215 FD 16 flags=33: (2) No such file or directory
```

We switched from icap to ecap when upstream removed icap support. Now they brought it back.
I did a test reverting to icap using:
```
squidclamav-6.15-1.ns7.x86_64.rpm
nethserver-squidclamav-1.3.1-1.ns7.noarch.rpm

```
Workaround: disable web antivirus.

**Comment by gsanchietti** [comment]
In 7.4/nethserver-updates:
- nethserver-squidclamav-2.0.0-1.10.g3390ee1.ns7.noarch.rpm
- c-icap-0.5.2-1.ns7.x86_64.rpm
- squidclamav-6.16-1.ns7.x86_64.rpm

**Comment by cotosso** [comment]
Tested and working as expected.

**Comment by gsanchietti** [comment]
Released:
- nethserver-squidclamav-3.0.0-1.ns7.noarch.rpm
- squidclamav-6.16-1.ns7.x86_64.rpm
- squidclamav-debuginfo-6.16-1.ns7.x86_64.rpm
- c-icap-0.5.2-1.ns7.x86_64.rpm
- c-icap-debuginfo-0.5.2-1.ns7.x86_64.rpm
- c-icap-devel-0.5.2-1.ns7.x86_64.rpm
- c-icap-ldap-0.5.2-1.ns7.x86_64.rpm
- c-icap-libs-0.5.2-1.ns7.x86_64.rpm
- c-icap-perl-0.5.2-1.ns7.x86_64.rpm
- c-icap-progs-0.5.2-1.ns7.x86_64.rpm
