### ISSUE TITLE
Spam training is not triggered

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5353]
The ``dovecot-antispam`` plugin triggers ``sa-learn`` when an IMAP message is moved to/from the spam folder. The default spam folder name has been changed in ns7 (``junkmail`` became ``Junk``). The upgrade procedure retains the old value. If the spam folder name is different than default, spam training is not triggered.

**Steps to reproduce**

- Change the default spam folder name (``Junk`` => ``junkmail``)
- From an IMAP client move messages to/from junkmail
- Follow the logs:

      tail -f /var/log/maillog | grep -5 spamtrain

**Expected behavior**

The command above matches some lines

**Actual behavior**

Nothing happens

**Components**

nethserver-mail-server-1.10.16-1.ns7.noarch

**See also**

https://github.com/NethServer/nethserver-mail-server/pull/11

----

Thanks to @filippocarletti for pointing it out

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.16-1.2.g2bc1308.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
```
Updated:
  nethserver-mail-server.noarch 0:1.10.16-1.2.g2bc1308.ns7

```

From maillog:

```
Oct  3 17:00:50 nethservice spam-training.sh/filippo@nethesis.it[12791]: Message enqueued as spam
Oct  3 17:00:51 nethservice postfix/pipe[12792]: 935F935631447: to=<filippo@nethesis.it+spam@spamtrain.nh>, relay=spamtrain, delay=1.1, delays=0.01/0.01/0/1.1, dsn=2.0.0, status=sent (delivered via spamtrain service)

```

**Comment by DavidePrincipi** [comment]
In nethserver-updates (7.3.1611 and 7.4.1708)
nethserver-mail-server-1.10.17-1.ns7.noarch.rpm
