### ISSUE TITLE
PPPoE connect timeout

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5358]
After link failures, PPPoE links do not reconnect.

**Steps to reproduce**

- Wait for failure (or simulate it)
- Check that the system is not connected to internet

I found this sentence in rp-pppoe documentation file /usr/share/doc/rp-pppoe-3.11/configs/pppoe.conf:

> If you are using rp-pppoe on a physically-inaccessible host, set
> CONNECT_TIMEOUT to 0.  This makes SURE that the machine keeps trying
> to connect forever after pppoe-start is called.  Otherwise, it will
> give out after CONNECT_TIMEOUT seconds and will not attempt to
> connect again, making it impossible to reach.
> CONNECT_TIMEOUT=30

I added the suggested option to some systems that had the problem and the issue seems to be resolved.
The file to change is /etc/sysconfig/network-scripts/ifcfg-ppp0.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-firewall-base-3.2.6-1.2.g15a1dc6.ns7.noarch.rpm
- nethserver-firewall-base-ui-3.2.6-1.2.g15a1dc6.ns7.noarch.rpm

**Test case**
- Configure a PPPoE connection
- Checl connect_timeout is set to 0

**Comment by gsanchietti** [comment]
Also in 6.9 testing:
- nethserver-firewall-base-ui-2.11.4-1.1.g890f9f1.ns6.noarch.rpm
- nethserver-firewall-base-2.11.4-1.1.g890f9f1.ns6.noarch.rpm

**Comment by filippocarletti** [comment]
Verified on a live 6.9 system where I found the problem.

**Comment by gsanchietti** [comment]
Released for 6.9:
nethserver-firewall-base-2.11.5-1.ns6.noarch.rpm
nethserver-firewall-base-ui-2.11.5-1.ns6.noarch.rpm

Released for 7.4:
nethserver-firewall-base-3.2.7-1.ns7.noarch.rpm
nethserver-firewall-base-ui-3.2.7-1.ns7.noarch.rpm
