### ISSUE TITLE
Accounts Provider: probe AD for SSL/TLS support

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5365]
In page Accounts Provider, the procedure that probes a remote AD to set up the connection do not recognize if SSL is available or not.

Implement an SSL/STARTTLS capability check in /usr/sbin/account-provider-test for AD.

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-sssd-1.3.2-1.5.g09ce67f.ns7.noarch.rpm

**Test case 1**
- Install a clean machine
- Join the machine to an existing Microsoft/Samba AD domain with STARTTLS enabled
- The value of `sssd[StartTls]` prop must be `enabled`:
```
config getprop sssd StartTls
```

**Test case 2**
- Install a clean machine
- Join the machine to an existing Microsoft/Samba AD domain with STARTTLS disabled
- The value of `sssd[StartTls]` prop must be `disabled`:
```
config getprop sssd StartTls
```

**Comment by Stell0** [comment]
Test case 1 verified

**Comment by gsanchietti** [comment]
Released:
nethserver-sssd-1.3.3-1.ns7.noarch.rpm
