### ISSUE TITLE
GSSAPI error from Postfix smarthost client

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5366]
When NethServer acts as smarthost and is bound to an AD accounts provider it announces SMTPAUTH with GSSAPI mechanism. Another NethServer (Postfix SMTP client) attempts to use the "best" auth mechanism available, but fails because it is not configured to use GSSAPI.

**Steps to reproduce**

Two NethServers are involved. The problem is on the "client" side

- Configure 1st ns7 "A" mail server with AD accounts provider
- Configure 2nd ns7 "B" to send mail through smarthost "A"

**Expected behavior**

Mail from "B" is sent through smarthost "A"

**Actual behavior**

Found in ``/var/log/messages``

```
default/smtp[26254]: warning: SASL authentication failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Credentials cache file '/tmp/krb5cc_89' not found)
```

**Components**

nethserver-mail-smarthost-0.1.1-1.ns7.noarch
nethserver-mail-common-1.6.5-1.ns7.noarch
nethserver-mail-server-1.10.17-1.ns7.noarch

<b><ins>This issue affects also ns6</ins></b>

----

Thanks to @filippocarletti for pointing it out

**Comment by filippocarletti** [comment]
Workaround: filter login mechanisms on client.
Add
`smtp_sasl_mechanism_filter = plain, login`
in /etc/postfix/main.cf/

**Comment by DavidePrincipi** [comment]
In nethserver-testing (7.4):
nethserver-mail-smarthost-0.1.1-1.2.gaad9639.ns7.noarch.rpm

In nethserver-testing (6.9):
nethserver-mail-common-1.5.6-1.1.g7888948.ns6.noarch.rpm

**Comment by gsanchietti** [comment]
Verified by @nrauso

**Comment by gsanchietti** [comment]
Released:
- 6.9: nethserver-mail-common-1.5.7-1.ns6.noarch.rpm
- 7: nethserver-mail-smarthost-1.0.0-1.ns7.noarch.rpm
