### ISSUE TITLE
Suricata rules download error

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5370]
**Steps to reproduce**

- Install nethserver-suricata
- Go to "IPS" page
- Click on "download rules" button

**Expected behavior**

ET rules should be downloaded and the web interface should display the list of rule categories.

**Actual behavior**

Rules are not downloaded, extract from `/var/log/messages`:

> Oct 31 11:20:27 mail2 esmith::event[48715]: #011Error 404 when fetching https://rules.emergingthreats.net/open-nogpl/suricata/emerging.rules.tar.gz.md51 at /usr/bin/pulledpork line 534.
> Oct 31 11:20:27 mail2 esmith::event[48715]: #011main::md5file('open-nogpl', 'emerging.rules.tar.gz', '/tmp/', 'https://rules.emergingthreats.net/open-nogpl/suricata/') called at /usr/bin/pulledpork line 2006
> Oct 31 11:20:27 mail2 esmith::event[48715]: IP Blacklist download of http://talosintelligence.com/feeds/ip-filter.blf....
> Oct 31 11:20:27 mail2 esmith::event[48715]: Reading IP List...
> Oct 31 11:20:27 mail2 esmith::event[48715]: Checking latest MD5 for emerging.rules.tar.gz....
> Oct 31 11:20:27 mail2 esmith::event[48715]: #011A 404 error occurred, please verify your filenames and urls for your tarball!
> Oct 31 11:20:27 mail2 suricata: 31/10/2017 -- 11:20:27 - - rule reload starting
> Oct 31 11:20:27 mail2 suricata: 31/10/2017 -- 11:20:27 - - [ERRCODE: SC_ERR_INVALID_ARGUMENT(13)] - Invalid rule-files configuration section: expected a list of filenames.
> Oct 31 11:20:27 mail2 suricata: 31/10/2017 -- 11:20:27 - - [ERRCODE: SC_ERR_EVENT_ENGINE(210)] - can't suppress sid 2022913, gid 1: unknown rule
> Oct 31 11:20:27 mail2 suricata: 31/10/2017 -- 11:20:27 - - [ERRCODE: SC_ERR_EVENT_ENGINE(210)] - can't suppress sid 2011124, gid 1: unknown rule
> Oct 31 11:20:27 mail2 suricata: 31/10/2017 -- 11:20:27 - - rule reload complete

**Components**

nethserver-pulledpork

**See also**

https://community.nethserver.org/t/suricata-rules-download-error/8176

----

Thanks to @Stefano_Zamboni

**Comment by gsanchietti** [comment]
In nethserver-testing:
- nethserver-pulledpork-2.1.0-1.2.g199825a.ns7.noarch.rpm
- nethserver-suricata-1.1.0-1.2.g3f81797.ns7.noarch.rpm

**Test case**
- Check rules can be downloaded
- New rule categories should be translated (search for "HTTP events" or "TLS events")

**Comment by filippocarletti** [comment]
Downloaded without errors. New categories didn't appear, maybe ET changed/fixed something.

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
- nethserver-suricata-1.1.1-1.ns7.noarch.rpm
- nethserver-pulledpork-2.1.1-1.ns7.noarch.rpm

**Comment by jodumont** [comment]
Hi there;

I have this error
in my /var/log/suricata/suricata.log 

This is Suricata version 4.0.4 RELEASE
installed from package nethserver-suricata-1.1.1-1.ns7.noarch

> 25/7/2018 -- 20:56:24 - <Warning> - [ERRCODE: SC_ERR_EVENT_ENGINE(210)] - can't suppress sid 2022913, gid 1: unknown rule
> 25/7/2018 -- 20:56:24 - <Warning> - [ERRCODE: SC_ERR_EVENT_ENGINE(210)] - can't suppress sid 2011124, gid 1: unknown rule
> 25/7/2018 -- 20:56:25 - <Notice> - all 6 packet processing threads, 2 management threads initialized, engine started.

**Comment by gsanchietti** [comment]
Reported error can be ignored: not all Snort rules are valid Suricata rules.
Please, open such requests inside https://community.nethserver.org :)
