### ISSUE TITLE
logrotate: httpd-admin fails reload with "sbin/reload: No such file or directory" error

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5371]
**Steps to reproduce**

See logrotate configuration:

> [root@ns7dev9 ~]# cat /etc/logrotate.d/httpd-admin 
> /var/log/httpd-admin/*log {
>     missingok
>     notifempty
>     sharedscripts
>     delaycompress
>     postrotate
>         /sbin/reload httpd-admin > /dev/null 2>/dev/null || true
>     endscript
> }

The above command doesn't work:

>  [root@ns7dev9 ~]# /sbin/reload httpd-admin
>     -bash: /sbin/reload: No such file or directory

**Expected behavior**

Httpd-admin instance should be reloaded using:
```
systemctl reload httpd-admin
```

**Affected components**

- nethserver-httpd-admin

**Comment by stephdl** [comment]
https://github.com/NethServer/nethserver-httpd-admin/pull/24

**Comment by stephdl** [comment]
https://github.com/NethServer/nethserver-httpd-admin/pull/25

sorry @filippocarletti I did a mistake and I removed my branch instead of creating a new commit

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-httpd-admin-2.0.13-1.2.g97cfd91.ns7.noarch.rpm

**Test case**
Check if the bug is still reproducible.

**Comment by DavidePrincipi** [comment]
**VERIFIED**

httpd-admin logs are now rotated correctly

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-httpd-admin-2.0.14-1.ns7.noarch.rpm
