### ISSUE TITLE
Minimize nsdc update downtime

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5372]
When nsdc container is updated, a full nsdc stop/start cycle is performed. We can minimize the service downtime by keeping the samba DC running while packages are downloaded.

Also we can restart only the samba service in nsdc, instead of fully restarting nsdc container, to avoid veth device "file exists" failure.

**See also**

- https://community.nethserver.org/t/update-dc-task-completed-with-error/6914/4
- https://github.com/systemd/systemd/issues/2173

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.3.0-1.1.g9c2eb55.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
Verified on 4 different installations.

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-dc-1.3.1-1.ns7.x86_64.rpm
