### ISSUE TITLE
nethserver-janus: allow to change NAT behaviour

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5373]
nethserver-janus configuration doesn't allow to change nat settings in Janus Gateway configuration template
Consequences are that audio doesn't work when janus server or client is behind NAT because RTP packets are sent to local addresses

- change default NAT settings to STUN, with ICE disabled
- allow to switch from STUN to ICE or NAT 1:1

**Comment by Stell0** [comment]
nethserver-testing nethserver-janus-1.0.0-1.2.g158d2d6.ns7.noarch.rpm

**Comment by Stell0** [comment]
**Test case 1:**
- install package
- verify that in configuration file there is a stun server and port configured
**Test case 2:**
- set mode to ICE 
`config setprop janus-gateway NatMode ice`
`signal-event nethserver-janus-update`
- verify that in configuration file there is `ice_lite = true` and there isn't a stun server configured
**Test case 2:**
- set mode to NAT 1:1
`config setprop janus-gateway NatMode 1:1`
`config setprop janus-gateway PublicIP 1.2.3.4`
`signal-event nethserver-janus-update`
- verify that in configuration file there is `nat_1_1_mapping = 1.2.3.4`

**Comment by gsanchietti** [comment]
Released:
nethserver-janus-1.0.1-1.ns7.noarch.rpm
