### ISSUE TITLE
janus-gateway ignores rtp_port_range option

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5374]
**Steps to reproduce**

- install nethserver-janus
- make a call
- check RTP traffic using tcpdump and/or wireshark

**Expected behavior**

RTP traffic should be sent by client to ports in range from 10000 to 20000, accoording to configuration 
`rtp_port_range = 10000-20000` in /opt/janus/etc/janus/janus.cfg

**Actual behavior**

- RTP arrives in random ports

**Components**

janus-gateway-0.2.3-5.ns7.x86_64

**See also**

Meetecho support  told us that rtp_port_range is supported only with libnice > 0.1.4 and suggest to compile janus-gateway using libnice = 0.1.13. At the moment, janus-gateway is built using 0.1.3

**Comment by Stell0** [comment]
nethserver-testing:
- janus-gateway-0.2.4-1.1.gedd99d9.ns7.x86_64.rpm
- libnice-0.1.4-1.ns7.x86_64.rpm (and libnice-devel-0.1.4-1.ns7.x86_64.rpm used for janus-gateway build)

**Test case 1:**
- install / update janus-gateway and libnice from nethserver-testing repo
- Verify that janus calls send RTP traffic in 10000-20000 UDP port range

**Comment by gsanchietti** [comment]
Released:
janus-gateway-0.2.5-1.ns7.x86_64.rpm
janus-gateway-debuginfo-0.2.5-1.ns7.x86_64.rpm
libnice-0.1.4-1.ns7.x86_64.rpm
libnice-debuginfo-0.1.4-1.ns7.x86_64.rpm
libnice-devel-0.1.4-1.ns7.x86_64.rpm
