### ISSUE TITLE
Update Asterisk 13 packages

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5375]
Asterisk 13 needs to be updated, because release 13.17.2 address some security vulnerability: http://downloads.asterisk.org/pub/security/AST-2017-008.html

**Comment by Stell0** [comment]
nethserver-testing:
- asterisk13-tds-13.17.2-1.ns7.x86_64.rpm
- asterisk13-voicemail-odbcstorage-13.17.2-1.ns7.x86_64.rpm
- asterisk13-13.17.2-1.ns7.x86_64.rpm
- asterisk13-ogg-13.17.2-1.ns7.x86_64.rpm
- asterisk13-addons-mysql-13.17.2-1.ns7.x86_64.rpm
- asterisk13-curl-13.17.2-1.ns7.x86_64.rpm
- asterisk13-snmp-13.17.2-1.ns7.x86_64.rpm
- asterisk13-alsa-13.17.2-1.ns7.x86_64.rpm
- asterisk13-doc-13.17.2-1.ns7.x86_64.rpm
- asterisk13-addons-13.17.2-1.ns7.x86_64.rpm
- asterisk13-core-13.17.2-1.ns7.x86_64.rpm
- asterisk13-sqlite3-13.17.2-1.ns7.x86_64.rpm
- asterisk13-configs-13.17.2-1.ns7.x86_64.rpm
- asterisk13-dahdi-13.17.2-1.ns7.x86_64.rpm
- asterisk13-addons-core-13.17.2-1.ns7.x86_64.rpm
- asterisk13-resample-13.17.2-1.ns7.x86_64.rpm
- asterisk13-devel-13.17.2-1.ns7.x86_64.rpm
- asterisk13-debuginfo-13.17.2-1.ns7.x86_64.rpm
- asterisk13-odbc-13.17.2-1.ns7.x86_64.rpm
- asterisk13-speex-13.17.2-1.ns7.x86_64.rpm
- asterisk13-voicemail-imapstorage-13.17.2-1.ns7.x86_64.rpm
- asterisk13-pgsql-13.17.2-1.ns7.x86_64.rpm
- asterisk13-voicemail-13.17.2-1.ns7.x86_64.rpm
- asterisk13-addons-bluetooth-13.17.2-1.ns7.x86_64.rpm
- asterisk13-addons-ooh323-13.17.2-1.ns7.x86_64.rpm

**NOTE:** this package has been built using CentOS 7.4 libraries, so it WON'T work wit NethServer < 7.4

**Comment by nethsupport** [comment]
Verified

**Comment by gsanchietti** [comment]
Updated RPM changelog.

Released in nethserver-updates:
asterisk13-13.17.2-1.ns7.x86_64.rpm
asterisk13-addons-13.17.2-1.ns7.x86_64.rpm
asterisk13-addons-bluetooth-13.17.2-1.ns7.x86_64.rpm
asterisk13-addons-core-13.17.2-1.ns7.x86_64.rpm
asterisk13-addons-mysql-13.17.2-1.ns7.x86_64.rpm
asterisk13-addons-ooh323-13.17.2-1.ns7.x86_64.rpm
asterisk13-alsa-13.17.2-1.ns7.x86_64.rpm
asterisk13-configs-13.17.2-1.ns7.x86_64.rpm
asterisk13-core-13.17.2-1.ns7.x86_64.rpm
asterisk13-curl-13.17.2-1.ns7.x86_64.rpm
asterisk13-dahdi-13.17.2-1.ns7.x86_64.rpm
asterisk13-debuginfo-13.17.2-1.ns7.x86_64.rpm
asterisk13-devel-13.17.2-1.ns7.x86_64.rpm
asterisk13-doc-13.17.2-1.ns7.x86_64.rpm
asterisk13-odbc-13.17.2-1.ns7.x86_64.rpm
asterisk13-ogg-13.17.2-1.ns7.x86_64.rpm
asterisk13-pgsql-13.17.2-1.ns7.x86_64.rpm
asterisk13-resample-13.17.2-1.ns7.x86_64.rpm
asterisk13-snmp-13.17.2-1.ns7.x86_64.rpm
asterisk13-speex-13.17.2-1.ns7.x86_64.rpm
asterisk13-sqlite3-13.17.2-1.ns7.x86_64.rpm
asterisk13-tds-13.17.2-1.ns7.x86_64.rpm
asterisk13-voicemail-13.17.2-1.ns7.x86_64.rpm
asterisk13-voicemail-imapstorage-13.17.2-1.ns7.x86_64.rpm
asterisk13-voicemail-odbcstorage-13.17.2-1.ns7.x86_64.rpm
