### ISSUE TITLE
LocalDelivery mail domain actually relayed

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5378]
If the _primary_ mail domain is configured to relay messages elsewhere, any other mail domain configured as LocalDelivery actually relays its messages.

**Steps to reproduce**

- Install local LDAP accounts provider and create a user ``second.user@primary.tld``
- Install mail module
- Configure ``primary.tld`` mail domain to relay to ``fail.example.com``
- Create email domain ``lseconday.tld`` with local delivery
- Create alias ``two@lsecondary.tld => second.user@primary.tld``
- Send a SMTP message through port 25 on local green interface

**Expected behavior**

The message is delivered to local user ``second.user@primary.tld``

**Actual behavior**

Mail server attempts to deliver the message through relay host "fail.example.com"

```text
 grep bounce /var/log/maillog
Dec 20 14:37:50 vm5 postfix/smtp[3650]: 48B0148045E: to=<second.user@primary.tld>, orig_to=<two@lsecondary.tld>, relay=none, delay=0.21, delays=0.01/0.01/0.19/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=fail.example.com type=AAAA: Host not found)
Dec 20 14:37:50 vm5 postfix/bounce[3651]: 48B0148045E: sender non-delivery notification: 7D870480468
```

**Components**

nethserver-mail-server-1.10.17-1.ns7.noarch
nethserver-mail-common-1.6.4-1.ns7.noarch

----

Thanks to @filippocarletti

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-common-1.6.5-1.2.g9b20a64.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
The UI now doesn't allow the selection of "Relay to another server" option.

*Verified*

**Comment by gsanchietti** [comment]
Released:
nethserver-mail-common-1.6.6-1.ns7.noarch.rpm
