### ISSUE TITLE
Bad mail delivery to non-existing mailbox with catchall address

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5379]
The catchall address is a free email value. If it has been set to something that does not match any user mailbox the final delivery of a message occurs on a wrong directory.

More in detail, if the catch all corresponds to a shared mailbox alias, the final delivery occurs in a directory named after the alias, instead of the shared mailbox.

**Steps to reproduce**

- Set the primary mail domain ``primary.tld`` for local delivery
- Create a shared mailbox ``shmbx1`` with alias ``shared@``
- Set the catch all address to ``shared@primary.tld``
- Send a mail to ``nonexisting@primary.tld``

**Expected behavior**

The mail is delivered to the catch all mailbox "vmail" under the subfolder "shmbx1".

**Actual behavior**

Mail is delivered to the bad mailbox ``shared@primary.tld``.

```text
find /var/lib/nethserver/vmail/
...
/var/lib/nethserver/vmail/shared@primary.tld/Maildir/new/1513854049.M865989P13556.vm5.primary.tld,S=1400,W=1432
```

In /var/log/messages, dovecot allows delivering to non-existing mailbox ``nonexisting@primary.tld``, with ``shared@primary.tld`` as homedir

```
Dec 21 12:05:46 vm5 dovecot: lmtp(13760, nonexisting@primary.tld): 55z2H3SVO1rANQAAXdYZ9Q: sieve: msgid=<20171220155511.A6D6749C422@vm5.primary.tld>: stored mail into mailbox 'INBOX'
```

**Components**

nethserver-mail-server-1.10.17-1.ns7.noarch

----

Thanks to **CharlieWhiting**

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.17-1.3.g2afe107.ns7.noarch.rpm

**Comment by filippocarletti** [comment]
After installing the update, the email is delivered to the user selected in the interface.
Note: maillog doesn't contain any reference the the final destinatio, i.e. the username selected in the server-manager never appears in the logs.

**Comment by DavidePrincipi** [comment]
We could change the log format like this:
```diff
- Nov 13 17:55:58 vm5 dovecot: lmtp(7624, admin@dpnet.nethesis.it): 8SEwH57OCVrIHQAAXdYZ9Q...
+ Nov 13 17:55:58 vm5 dovecot: lmtp(7624, catchall): 8SEwH57OCVrIHQAAXdYZ9Q...
```

By adding ``user=catchall`` to the userdb definition
```diff
userdb {
  args = allow_all_users=yes
  driver = static
+  override_fields = user=catchall uid=990 gid=986 home=/var/lib/nethserver/vmail/admin@dpnet.nethesis.it
-   override_fields = uid=990 gid=986 home=/var/lib/nethserver/vmail/admin@dpnet.nethesis.it
  skip = found
}
```

**Comment by gsanchietti** [comment]
Released:
nethserver-mail-server-1.10.18-1.ns7.noarch.rpm
