### ISSUE TITLE
Shorewall config error with multiple sshd instances

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5380]
If there are multiple OpenSSH daemon running sessions, Shorwall configuration produces a syntax error.

**Steps to reproduce**

- Start an extra sshd instance:
```
/usr/sbin/sshd -D -f /etc/ssh/sshd_config_extra
```
- Execute `signal-event firewall-adjust`

**Expected behavior**

The firewall configuration should be applied.

**Actual behavior**

Shorewall fails with error like this one:
```
Checking /etc/shorewall/stoppedrules...
   ERROR: Invalid TARGET (22) /etc/shorewall/stoppedrules (line 17)
```

**Components**

nethserver-firewall-base-3.2.7-1.ns7.noarch

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-firewall-base-3.2.7-1.2.gba72d62.ns7.noarch.rpm
nethserver-firewall-base-ui-3.2.7-1.2.gba72d62.ns7.noarch.rpm

**Test case**
The bug should not be reproducible

**Comment by filippocarletti** [comment]
```
# expand-template /etc/shorewall/stoppedrules 
WARNING in /etc/e-smith/templates//etc/shorewall/stoppedrules/20running_sshd: Bareword found where operator expected at /etc/e-smith/templates//etc/shorewall/stoppedrules/20running_sshd line 7, near "// handle"
WARNING in /etc/e-smith/templates//etc/shorewall/stoppedrules/20running_sshd: 	(Missing operator before handle?)
ERROR in /etc/e-smith/templates//etc/shorewall/stoppedrules/20running_sshd: Program fragment delivered error <<syntax error at /etc/e-smith/templates//etc/shorewall/stoppedrules/20running_sshd line 7, near "// handle multiple ">> at template line 1
ERROR: Template processing failed for //etc/shorewall/stoppedrules: 2 fragments generated warnings, 1 fragment generated errors
 at /sbin/e-smith/expand-template line 45.

```

Removing the "// comment" works as expected.

**Comment by gsanchietti** [comment]
Released:
nethserver-firewall-base-3.2.8-1.ns7.noarch.rpm
nethserver-firewall-base-ui-3.2.8-1.ns7.noarch.rpm
