### ISSUE TITLE
Shared mailboxes not restored from configuration backup

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5381]
The shared mailboxes are not restored. Both mailboxes definition and permissions are available in data backup. Until data backup is fully restored, messages cannot be delivered to the missing shared mailboxes; they are wrongly delivered to vmail's root maildir.

**Steps to reproduce**

Restore a configuration state including some shared mailboxes

**Expected behavior**

Empty shared mailboxes are restored with saved permissions

**Actual behavior**

Shared mailboxes are missing

**Components**

nethserver-mail-server-1.10.17-1.ns7.noarch
nethserver-backup-config-2.0.3-1.ns7.noarch

**See also**

https://community.nethserver.org/t/configuration-backup-shared-mailboxes-missing/8275

----

Thanks to **Andreas Schloegl** and @mrmarkuz

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-mail-server-1.10.17-1.5.g03b8294.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
Fixed missing permissions on restore. Reported by @mrmarkuz [here](https://community.nethserver.org/t/configuration-backup-shared-mailboxes-missing/8275/5?u=davidep)

In nethserver-testing
nethserver-mail-server-1.10.17-1.6.g5d0730b.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
Fixed intermediate dirs permissions problem, again reported by @mrmarkuz [here](https://community.nethserver.org/t/configuration-backup-shared-mailboxes-missing/8275/11?u=davidep)

In nethserver-testing:
nethserver-mail-server-1.10.17-1.7.ge1e3160.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
Released:
nethserver-mail-server-1.10.18-1.ns7.noarch.rpm
