### ISSUE TITLE
Cannot contact any KDC for realm (sssd)

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5382]
Under some circumstances, the Samba DC container looses the krb5.conf file state and samba DC fails to start the KDC services. The service seems to run but ports 88 (kerberos-sec) and 464 (kpasswd5) are closed and some services fail to authenticate correctly (say SSSD, account listings...).

**Steps to reproduce**

Real world:

- Configure a local AD accounts provider
- Create a config backup
- Restore the config backup on a clean 7.4
- Update/Reinstall krb5-libs in nsdc container
```text
yum --installroot=/var/lib/machines/nsdc reinstall krb5-libs
```
- Restart samba service in nsdc container
```text
systemctl -M nsdc restart samba
```

Testing environment shortcut:

- Configure a local AD accounts provider
- Remove ``/var/lib/machines/nsdc/var/lib/samba/private/krb5.conf``
- Restart samba service in nsdc container
- Get users list ``/usr/libexec/nethserver/list-users``

**Expected behavior**

Get the list of users

**Actual behavior**

Error message:
```text
(1) SASL:[GSSAPI]: Failed to start authentication backend: NT_STATUS_INTERNAL_ERROR at /usr/share/perl5/vendor_perl/NethServer/LdapClient.pm line 126.
```

In sssd journal ``journalctl -u sssd``:
```text
Failed to initialize credentials using keytab [MEMORY:/etc/krb5.keytab]: Cannot contact any KDC for realm 'AD.DPNET.NETHESIS.IT'. Unable to create GSSAPI-encrypted LDAP connection.
```
In samba dc journal ``journalctl -M nsdc -u samba``:
```text
task_server_terminate: [kdc: krb5_init_context failed]
```

**Components**

nethserver-sssd-1.3.3-1.ns7.noarch
nethserver-dc-1.3.1-1.ns7.x86_64

**See also**

https://community.nethserver.org/t/sssd-ldap-error-cannot-contact-any-kdc/8204

----

Thanks to @fasttech and André Wismer

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.3.1-1.1.g6d41531.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
Verified by @mrmarkuz

**Comment by gsanchietti** [comment]
Released:
nethserver-dc-1.3.2-1.ns7.x86_64.rpm
