### ISSUE TITLE
OpenVPN Tunnels don't restart after network modification

### ISSUE THREAD

**Issue by cotosso** [NethServer/dev#5386]
**Steps to reproduce**

- Create one ore more OpenVPN tunnel (server or client)
- Go to the Network panel page and make some modification (or just type from console: `signal-event interface-update`)

**Expected behavior**

All the openvpn tunnels are UP and working

**Actual behavior**

Only the OpenVPN RoadWarrior (tunrw) is up and working after the command, all the other openvpn processes are running, but their interfaces are all down.

**Supposed Reason**

The event

`/etc/e-smith/events/interface-update/S04network-stop`

put all the interfaces down, after that other events do the restart of all the interfaces:

the OpenVPN roadwarrior server has it's own event to bring up the interface:

`/etc/e-smith/events/interface-update/services2adjust/openvpn@host-to-net`

```
cat /etc/e-smith/events/interface-update/services2adjust/openvpn@host-to-net
restart
```

Other OpenVPN tunnels haven't an event to bring their interface up.

**Components**

NethServer release 7.4.1708 (Final)
nethserver-openvpn-1.6.6-1.ns7.noarch

----

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-openvpn-1.6.6-1.2.g47344f9.ns7.noarch.rpm

**Test case**
The bug shouldn't be present anymore.

**Comment by cotosso** [comment]
I tested the new rpm, now the interfaces are up, but also the interfaces of the **disabled** tunnels are up (disabled tunnels should have their interface down).

**Comment by gsanchietti** [comment]
Thanks for pointing out!

New package in nethserver-testing:

- nethserver-openvpn-1.6.6-1.4.ge6b6604.ns7.noarch.rpm

**Comment by cotosso** [comment]
The new rpm works as expected: only **enabled** tunnel interfaces are up after the interface-update.

**Comment by gsanchietti** [comment]
Released:
nethserver-openvpn-1.6.7-1.ns7.noarch.rpm
