### ISSUE TITLE
iaxmodem: logrotate failure

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5387]
I received a mail from anacron saying:

> /etc/cron.daily/logrotate:
> 
> error: failed to rename /var/log/iaxmodem/iaxmodem-20170514-20170521-20170528-20170604-20170611-20170618-20170625-20170702-20170709-20170716-20170723-20170730-20170806-20170813-20170820-20170827-20170903-20170910-20170917-20170924-20171001-20171008-20171015-20171022-20171029-20171105-20171112 to /var/log/iaxmodem/iaxmodem-20170514-20170521-20170528-20170604-20170611-20170618-20170625-20170702-20170709-20170716-20170723-20170730-20170806-20170813-20170820-20170827-20170903-20170910-20170917-20170924-20171001-20171008-20171015-20171022-20171029-20171105-20171112-20171119: File name too long
> 

**Steps to reproduce**

- Install nethserver-iaxmodem-1.2.3-1.ns7.noarch
- Type `logrotate -f /etc/logrotate.conf` two times
- See /var/log/iaxmodem/:
```
-rw-r----- 1 root root 0 Nov 22 12:15 iaxmodem
-rw-r----- 1 root root 0 Nov 22 12:16 iaxmodem-20171122
-rw-r----- 1 root root 6 Nov 22 12:12 iaxmodem-20171122-20171122
```
**Expected behavior**

Only two logfiles instead of 3

**Components**
nethserver-iaxmodem-1.2.3-1.ns7.noarch

**Comment by filippocarletti** [comment]
The problem comes from /etc/logrotate.d/iaxmodem which contains a wildcard:
`/var/log/iaxmodem/* {`

I think that our best option to fix the problem is to use the **old** directory.
I evaluated patching iaxmodem and leaving log handling to iaxmodem itself.
From iaxmodem manual:

> By default iaxmodem, when starting, will examine an existing log file
> to see if it is larger than 1GB.  If it is, then iaxmodem will rename
> that file with ".old" at the end, deleting any existing ".old" log 
> file.  The purpose in this is to prevent iaxmodem logging from 
> consuming too much disk space.  However, the astute iaxmodem 
> administrator should probably employ a system-wide logrotate service
> to rotate the iaxmodem logging independently.
> 
> An appropriate logrotate.d entry for iaxmodem may look like this:
> 
> /var/log/iaxmodem/*.log {
> 

As you can see, the logrotate fragment has a good syntax (*.log), but iaxmodem creates log that do not end in ".log".

**Comment by filippocarletti** [comment]
For reference, we missed part of the fix here:
https://github.com/NethServer/dev/issues/5317

**Comment by gsanchietti** [comment]
I agree to add `olddir` option to `/etc/logrotate.d/iaxmodem` file, but we also need this option: `createolddir 0640 root root`

**Comment by filippocarletti** [comment]
I'd prefer to add `/var/log/iaxmodem/old` in nethserver-iaxmodem.

**Comment by alepolidori** [comment]
repo: testing
`nethserver-iaxmodem-1.2.3-1.2.g46f1037.ns7.noarch.rpm`

how to test
- install rpm
- type:
```
# echo "12345" > /var/log/iaxmodem/iaxmodem
# logrotate -f /etc/logrotate.conf
# echo "12345" > /var/log/iaxmodem/iaxmodem
# date -s "+10 days"
# logrotate -f /etc/logrotate.conf
```
- verify the content of /var/log/iaxmodem:
```
[root@vmalep3 ~]# find /var/log/iaxmodem/
/var/log/iaxmodem/
/var/log/iaxmodem/old
/var/log/iaxmodem/old/iaxmodem-20171124
/var/log/iaxmodem/old/iaxmodem-20171204
/var/log/iaxmodem/iaxmodem
```

**Comment by gsanchietti** [comment]
Verified on a clean machine and on existing one.

**Comment by gsanchietti** [comment]
Released:
nethserver-iaxmodem-1.2.4-1.ns7.noarch.rpm
