### ISSUE TITLE
Asterisk: remove lazymembers patch and update

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5435]
Asterisk 13 RPM has been built upon Sangoma SRPM and has a patch for a feature that commercial FreePBX has: LazyMembers
https://wiki.freepbx.org/display/PPS/lazymembers+patch+to+app_queue

Since this feature is available only on commercial FreePBX and this patch regularly break asterisk build, it should be removed

Queue should be tested well after this patch has been removed

**Comment by gsanchietti** [comment]
Do not apply such modifications for now to not change the behavior of installations (if such) using this feature.

On a new Asterisk release, if any compilation problem arises, feel free to reopen and directly merge the PR.
