### ISSUE TITLE
PBX installation fails because iksemel no longer mantained by epel

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5552]
Asterisk 13 needs iksemel, a package from epel, but its support has been dropped:
https://src.fedoraproject.org/cgit/rpms/iksemel.git/commit/?h=epel7

A new build of Asterisk has been done without the need for iksemel, but it is still in testing and the fact that this package is missing don't allow any PBX installation or disaster recovery restore.

**Steps to reproduce**

- Install NethServer PBX with  Asterisk 13.17 (just without enabling nethserver-testing)

**Expected behavior**

- PBX installed

**Actual behavior**

- missing RPM

**Components**

Asterisk 13.17
iksemel 1.4-6

**See also**

https://community.nethserver.org/t/can-not-install-freepbx/10327/3

**Comment by filippocarletti** [comment]
Removed for security reasons:
https://bugzilla.redhat.com/show_bug.cgi?id=1594986
