### ISSUE TITLE
Unable to install smtp-proxy as it conflicts with  nethserver-mail-common

### ISSUE THREAD

**Issue by biofool** [NethServer/dev#5557]
**Steps to reproduce**

From the UI select smtp-proxy then click the add button

**Expected behavior**

smtp-proxy should install

**Actual behavior**
Package fails to install because of conflict with nethserver-mail-common

**Components**
NethServer release 7.5.1804 (final)

**Workaround**
From the command line:
```
yum remove nethserver-mail-server nethserver-mail-common
```

**Comment by DavidePrincipi** [comment]
Hi @biofool, we are gradually moving to the new email module based on Rspamd. For more info, please refer to 

http://docs.nethserver.org/en/v7/mail2.html#email2-section

To discuss issues like this, please open a topic on community.nethserver.org
