### ISSUE TITLE
Mail clients install old mail stack as dependency

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5558]
When installing WebTop 5 or Roundcube from the "Software Center", yum installs the old mail stack (nethserver-mail-common and nethserver-mail-server) instead of the new one (nethserver-mail2-common and nethserver-mail2-server).

**Steps to reproduce**

- Access the "Software Center" and install "Roundcube web mail" or "WebTop 5 groupware"

**Expected behavior**

Yum should install `nethserver-mail2-common` package as dependency.

**Actual behavior**

Yum installs `nethserver-mail-common` package as dependency.
Command to check what package has been installed :
```
rpm -qa | grep 'nethserver-mail' | grep   'common'
```
----
Thanks to @lucagasparini

**Comment by gsanchietti** [comment]
**Proposed solution**

Add mail2 components to `nethserver-webtop5-groupware` and `nethserver-roundcubemail` groups.
This solution will force the installation of the new stack on freshly installed machines but has two major drawbacks:
- where nethserver-mail-common is installed, the user will not be able to install nor Roundcube nor WebTop from the Software Center since the conflicts between mail and mail2 packages
- on existing machines with the old mail stack, "Roundcube web mail" and "WebTop 5 groupware" will be marked as not installed

For now, no modifications will take place, since we will soon switch every installation to the new mail implementation.

**Current workaround**
To make sure installing the new mail stack, follows these steps:

1. Install the mail server server
2. Install the mail client (WebTop/Roundcube or SOGo)

**Comment by markVnl** [comment]
_Side note_

For a private project experienced  the opposite; even if the version of nethserver-mail-common is explicitly given (`Requires: nethserver-mail-common = 1.6.7-1.ns7`) it pulls in nethserver-mail2-common.

my best guess here is the rpmlint warning about versioning in the SPEC at 

```
Conflicts: nethserver-mail-common
Provides: nethserver-mail-common 
```

In future you might consider to "version"  here too.

**Comment by stephdl** [comment]
Unfortunately we do not have rpm > 4.13 
http://rpm.org/user_doc/boolean_dependencies.html

**Comment by DavidePrincipi** [comment]
Alternative (works only from software center):
add nethserver-mail2-common to Roundcube and WebTop5 group composition

**Comment by DavidePrincipi** [comment]
The new YUM groups composition has been applied and will be delivered to mirrors soon
