### ISSUE TITLE
UfdbGuard: upgrade to 1.33.7

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5627]
Upgrade UfdbGuard package to latest available release: 1.33.7

**Proposed solution**

RPM are available here: https://www.urlfilterdb.com/downloads/packages.html

Available RPM: https://www.urlfilterdb.com/files/downloads/ufdbGuard-1.33.7-CentOS7.x86_64.rpm

**Comment by gsanchietti** [comment]
In testing:
http://packages.nethserver.org/nethserver/7.5.1804/testing/x86_64/Packages/ufdbGuard-1.33.7-CentOS7.x86_64.rpm

**Comment by gsanchietti** [comment]
**Test case 1**
- Update an existing machine
- Check ufdbGuard is still working after the upgrade

**Test case 2**
- Install on a clean machine
- Configure the filter and check ufdbGuard is working

**Comment by stephdl** [comment]
test case 1 OK

test case 2 OK

Not familiar with this software but this what I did

after the installation

- update the list by the cronjob `/etc/cron.daily/update-squidguard-blacklists `
- enable squid `Transparent with SSL` on green interface and the webcontent filter
- create a default profile for the green zone
- edit default filter `Transparent with SSL`, enable all categories
- enable `Université Toulouse (free)`

web site even on https are blocked, as a side note https://www.google.com is blocked even with the old rpm, the message is 
`
The owner of www.google.com has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.`

**Comment by gsanchietti** [comment]
We also have this version running on our server since a while: no problems so far.

**Comment by DavidePrincipi** [comment]
In nethserver-updates 7.6.1810:
- ufdbGuard-1.33.7-CentOS7.x86_64.rpm
