### ISSUE TITLE
Rspamd: upgrade to 1.8.2

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5652]
Upgrade rspamd to 1.8.2 for centos 7.6

The rpm is waiting in nethserver-testing 

**See also**

- https://community.nethserver.org/t/rspamd-upgrade-to-1-8-2/11274
- https://github.com/rspamd/rspamd/issues/2637
- https://github.com/rspamd/rspamd/issues/2658

**Comment by dz00te** [comment]
installed without problem, seems to work as usual

**Comment by DavidePrincipi** [comment]
If the upstream developer does't revert to the old behavior,  the wrapper is our only possible solution.

I guess `rspamc learn_spam || :` can't work from Postfix master.cf because it's a Bash command. Thus a wrapper script is required.

**Comment by stephdl** [comment]
not ideal but this is our spare wheel in case

`/etc/postfix/master.cf`
```
-   flags=X user=_rspamd:_rspamd argv=/usr/bin/rspamc -h localhost:11334 -P !soph,14helene1975 ${extension}
+   flags=X user=_rspamd:_rspamd argv=/usr/bin/rspamd-rspamc ${extension}
```

```
#!/usr/bin/bash
PASSWORD=$(/usr/sbin/e-smith/db configuration getprop rspamd password)
/usr/bin/rspamc -h localhost:11334 -P "$PASSWORD" $@ 
exit $?
```

**Comment by stephdl** [comment]
the upstream issue has been patched to non fatal error

**Comment by stephdl** [comment]
ok back to testing, the fix of upstream close the issue https://github.com/rspamd/rspamd/issues/2637#issuecomment-442206732

As a side note we should test it with getmail and p3scan what do you think @DavidePrincipi

**Comment by gsanchietti** [comment]
I guess the rspamd-1.8.2.2 should be uploaded to testing. Am I wrong?

**Comment by gsanchietti** [comment]
In nethserver-testing:
- rspamd-1.8.2-2.x86_64.rpm

**Comment by gsanchietti** [comment]
Seems to work now:
```
Nov 28 11:02:17 nethservice spam-training/giacomo@nethesis.it[16985]: Message enqueued as learn_spam
Nov 28 11:02:55 nethservice spam-training/giacomo@nethesis.it[17092]: Message enqueued as learn_ham
```

No bounce mail.

**Comment by stephdl** [comment]
you beat me @gsanchietti

**Comment by stephdl** [comment]
@gsanchietti could you please check if in the history row (rspamd UI) you do not have (too much) log traces about the `already learned error`

**Comment by gsanchietti** [comment]
There are quite frequent errors: about one error every 1,5-2 minutes.

**Comment by stephdl** [comment]
same for me with 1.8.2-2 I downgraded to 1.8.1 to see it

**Comment by stephdl** [comment]
Verification with nethserver-mail-getmail --> OK

Push junk to my gmail account via thunderbird (thank to quarantine)
Use getmail to retrieve the email from my gmail account to my server (local user)
Emails go again in quarantine with the tag `reject`

**Comment by gsanchietti** [comment]
Marking as verified.
Release it for 7.6 if no fix has been released and tested for upstream issue 2658.

**Comment by DavidePrincipi** [comment]
In nethserver-updates 7.6.1810:
- rspamd-1.8.2-2.x86_64.rpm
