### ISSUE TITLE
missing backup (data) options

### ISSUE THREAD

**Issue by criticview** [NethServer/dev#5669]
After experiencing several backup errors, and digging through the comunity to hopefully get them fixed, a few suggestions to make life a bit easier: 
- add a button to test connection to backup host and read/write permissions. This will take out the issue one has to wait until the next scheduled backup has been initiated before finding out weather or not it was successful.
- For filesystems where applicable: add a minimum version combo box. This will ensure that for instance smb servers that have been configured to use protocol 2.0 (or higher) [netgear nas can do so] will receive the backup without throwing an error.

**Comment by gsanchietti** [comment]
As a side note I would also highlight that both issues have already been addressed:

- Cockpit already has a "test connection" button for backups
- CentOS 7.6 already negotiate the best Samba protocol when mounting CIFS resources

**Comment by gsanchietti** [comment]
Closing it for now.
