### ISSUE TITLE
nethserver-rh-php72: import to nethserver repository

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5682]
First import to nethserver repository to install and configure rh-php72 from [software collection ](https://www.softwarecollections.org/en/scls/rhscl/rh-php72/)

For now the source are at : https://github.com/stephdl/nethserver-rh-php72-php-fpm

**Components**
```
Installed:
  nethserver-rh-php72-php-fpm.noarch 0:1.0.0-1.ns7                                                                                                    

Dependency Installed:
  rh-php72.x86_64 0:1-2.el7                          rh-php72-php-cli.x86_64 0:7.2.10-3.el7          rh-php72-php-common.x86_64 0:7.2.10-3.el7        
  rh-php72-php-fpm.x86_64 0:7.2.10-3.el7             rh-php72-php-json.x86_64 0:7.2.10-3.el7         rh-php72-php-pear.noarch 1:1.10.5-1.el7          
  rh-php72-php-process.x86_64 0:7.2.10-3.el7         rh-php72-php-xml.x86_64 0:7.2.10-3.el7          rh-php72-php-zip.x86_64 0:7.2.10-3.el7           
  rh-php72-runtime.x86_64 0:1-2.el7 
```
**See also**

https://community.nethserver.org/t/two-versions-of-php-installed/11603

----

thank AveryFreeman

**Comment by stephdl** [comment]
QA
Install from testing

- check the service rh-php72-php-fpm is up and running 
- use it in a vhost, you can use this example https://github.com/stephdl/nethserver-php-scl/blob/ns7/root/etc/e-smith/templates/etc/httpd/conf.d/www.conf/10base
- restart httpd
- verify that the phpinfo gives back the good phpversion

**Comment by gsanchietti** [comment]
The migration should be done only when NS 7.7 will be released and rh-php71 will not be available.

On NS 7.7, each application using php71 should migrate to php72.
Also php72 10 probably will obsolete the php71 and use the same listening port.

This issue should be used as a reminder for NS 7.7
