### ISSUE TITLE
nethserver-rh-postgresql10: import to nethserver-repository

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5684]
**Steps to reproduce**
First import to nethserver repository to install and configure  [rh-postgresql10](https://www.softwarecollections.org/en/scls/rhscl/rh-postgresql10/)

For now the source is at https://github.com/stephdl/nethserver-postgresql10

**Components**

```
Installed:
  nethserver-postgresql10.noarch 0:1.0.0-1.ns7                                                                                                        

Dependency Installed:
  rh-postgresql10.x86_64 0:3.1-1.el7                                       rh-postgresql10-postgresql.x86_64 0:10.5-1.el7                            
  rh-postgresql10-postgresql-libs.x86_64 0:10.5-1.el7                      rh-postgresql10-postgresql-server.x86_64 0:10.5-1.el7                     
  rh-postgresql10-runtime.x86_64 0:3.1-1.el7                               scl-utils.x86_64 0:20130529-19.el7           
```            

**See also**

https://community.nethserver.org/t/rh-postgresql-9-4-is-eol/11625

**Comment by stephdl** [comment]
Install from testing
* test if the service is up and running
* create a database

**Comment by gsanchietti** [comment]
The migration should be done only when NS 7.7 will be released and rh-postrgresql 94 will not be available.

On NS 7.7, each application using postgresql 9.4 should migrate to postgresql 10 via the dump&restore procedure as analyzed by @Amygos.
Also postgresql 10 probably will obsolete the 9.4 and use the same listening port.

This issue should be used as a reminder for NS 7.7
