### ISSUE TITLE
Cockpit: NethServer version after update

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5690]
NethServer cockpit login page still shows the old version after an update to a new release.

**Steps to reproduce**

- Install NethServer 7.5 and cockpit
- Update to NethServer 7.6
- Reboot

**Expected behavior**

Login page shows NethServer 7.6

**Actual behavior**

Login page shows NethServer 7.5

**Comment by gsanchietti** [comment]
This is unlikely to happen since a new NS release will also bring a new cockpit release which will expand the template and restart the process.

Closing as wantfix for now.
