### ISSUE TITLE
Cockpit: password expiration is not checked in the user edit panel

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5716]
**Steps to reproduce**

- install cockpit version nethserver-cockpit-0.3.0-1.14.g521d9a9.ns7.noarch
- install nethserver-directory
- Create a group
- Create a user and you check the checkbox about  the password expiration
- save
- edit the user, the password expire is not checked

![screenshot_2019-02-22 system - ns7loc15 nethservertest org 2](https://user-images.githubusercontent.com/3164851/53230115-40ab5a80-3686-11e9-92ea-6effa9ca39db.png)

**Expected behavior**

I expect the checkbox is check

**Actual behavior**

the checkbox is not checked and the json api read, demonstrate that the settings saved is `no`

`echo '{"action":"list-users"}' | /usr/bin/sudo /usr/libexec/nethserver/api/system-users/read | jq`
```
  "toto": {
    "locked": 0,
    "gecos": "toto",
    "expired": 0,
    "groups": [],
    "shell": "/bin/bash",
    "new": 0,
    "expires": "no"
  }
```

but the save API did the good job 
```
  echo '{"action":"user-create","name":"toto","groups":["plip"],"gecos":"toto","expires":"yes","shell":"/bin/bash","newPassword":"!Soph,14","confirmNewPassword":"!Soph,14"}' | /usr/bin/sudo /usr/libexec/nethserver/api/system-users/create | jq
```

**Components**
nethserver-cockpit-0.3.0-1.14.g521d9a9.ns7.noarch
nethserver-directory-3.3.2-1.ns7.noarch.rpm

**Comment by stephdl** [comment]
The issue comes from [this code](https://github.com/NethServer/nethserver-directory/blob/master/root/etc/e-smith/events/actions/nethserver-directory-password-policy#L81), we test if the `$passwordstrength{PassExpires}` is set to yes before to save the passwordExpire property of the user.
In short, if this property is not set to yes, then checkbox of the user can be checked, nothing wont be saved. 
This behavior is the same in nethgui, so either we could let as is and do a won't fix, or test in VueJS if we display this checkbox (if `$passwordstrength{PassExpires}=yes`)

up to you @gsanchietti @edospadoni ?

**Comment by gsanchietti** [comment]
So the global `$passwordstrength{PassExpires}` takes precedence, and if it is set to no, password expiration can't be set for a specific user.
IMO this is not the expected behavior, but since we have it since ages, we shouldn't change it.

To reflect the system behavior, let's hide the checkbox if the global option is disabled.

**Comment by DavidePrincipi** [comment]
> let's hide the checkbox

...or display it disabled?

I agree to not touch the existing behavior. I think we'll rework the LDAP password policy if/when we migrate from OpenLDAP to 389 DS...

**Comment by gsanchietti** [comment]
> ...or display it disabled?

Yes, much better disabled!

**Comment by stephdl** [comment]
ok go for disabled

**Comment by gsanchietti** [comment]
**Test case**
Check the bug is not reproducible

**Comment by DavidePrincipi** [comment]
**VERIFIED**

The user's checkbox is disabled when the global setting is not checked.

When the global setting is checked, the user's checkbox can be modified and the change is persisted in LDAP shadow attributes.

**Comment by gsanchietti** [comment]
in `7.6.1810/updates`:
- nethserver-cockpit-0.4.0-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.6.1810/updates/x86_64/Packages/nethserver-cockpit-0.4.0-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.6.1810/updates/armhfp/Packages/nethserver-cockpit-0.4.0-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.6.1810/updates/aarch64/Packages/nethserver-cockpit-0.4.0-1.ns7.noarch.rpm) 
- nethserver-cockpit-lib-0.4.0-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.6.1810/updates/x86_64/Packages/nethserver-cockpit-lib-0.4.0-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.6.1810/updates/armhfp/Packages/nethserver-cockpit-lib-0.4.0-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.6.1810/updates/aarch64/Packages/nethserver-cockpit-lib-0.4.0-1.ns7.noarch.rpm)
