### ISSUE TITLE
Fail2ban cockpit UI

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5745]
Make a UI for Fail2ban with cockpi, the goal is : 

- to make the UI with all the features of nethgui
- to learn VueJS
- to make fun

**Comment by stephdl** [comment]
QA

install fail2ban and cockpit, test all features, all previous functionalities must work

**Comment by DavidePrincipi** [comment]
Little glitch: we are removing the "NethServer" word from app names, i.e. "NethServer Fail2ban" should be just "Fail2ban".

**Comment by gsanchietti** [comment]
After some days in testing, everything seems good to me.
We can release it.

@edospadoni is suggesting to change the logo to better fit the general look&fill, but it's outside of my skills.

**Comment by stephdl** [comment]
released as [nethserver-fail2ban-1.1.6-1.ns7.noarch.rpm](http://packages.nethserver.org/nethserver/7.6.1810/updates/x86_64/Packages/nethserver-fail2ban-1.1.6-1.ns7.noarch.rpm)

**Comment by daniel-wtd** [comment]
Hi @stephdl, I just stumbled over this issue. Is there any chance to provide this to the official cockpit project?

**Comment by stephdl** [comment]
hi @daniel-wtd  not sure it is feasible like this because we rely on internal function we have developed, maybe @edospadoni @gsanchietti could also give their advices/tips

let's wait their inputs

**Comment by edospadoni** [comment]
Hi @daniel-wtd , Fail2Ban UI for Cockpit is only available for NethServer/CentOS. Fail2Ban module is composed by:
- UI (only static HTML, CSS, JS files)
- API (scripts to configure properly the Fail2Ban)

you need both to use Fail2Ban UI in the correct way.

This packages:
- http://packages.nethserver.org/nethserver/7.6.1810/updates/x86_64/Packages/nethserver-fail2ban-1.1.6-1.ns7.noarch.rpm

provides the UI and API but as mentioned before it only works on NethServer/CentOS.
