### ISSUE TITLE
nethserver-freepbx: mark /usr/lib/systemd/system/asterisk.service as config noreplace

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#5766]
Some custom configuration of Asterisk that has a huge number of calls, could need a bigger limit of open files. This could be done by setting 
LimitNOFILE in /usr/lib/systemd/system/asterisk.service, but this file needs to marked as config noreplace to avoid been overwritten on update

Asterisk error:
[2019-05-23 11:47:52] ERROR[118430] tcptls.c: TCP/TLS accept failed: Too many open files

**Steps to reproduce**

- change any option in `/usr/lib/systemd/system/asterisk.service`
- update nethserver-freepbx

**Expected behavior**

customization should be maintained after update

**Actual behavior**

- changes are now overwritten

nethserver-freepbx

**Comment by gsanchietti** [comment]
The override asterisk unit configuration just drop a file inside `/etc/systemd/system/asterisk.service.d` directory.
