### ISSUE TITLE
IDS: disabled ET rules dropping connections

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#5780]
Emerging Threats ships some rules disabled by default. See their FAQ:
https://docs.emergingthreats.net/bin/view/Main/EmergingFAQ#Why_would_a_rule_ship_disabled

If we choose to set a category to block traffic, all rules in the category are set to block, even those disabled by default. The result is that we sometimes block connections that shouldn't be blocked.

**Steps to reproduce**

- Set to Block the Attack response (ET-emerging-attack_response) category
- Run the following command:
`grep 2009244 /etc/suricata/rules/ET-emerging-attack_response.rules | awk '{print $1}'
`
- The output will be `drop`, meaning that rule 2009244 will block traffic

**Expected behavior**

Rules 2009244 is disabled by default, the above command should return nothing.
See the # at the beginning of line here:
https://doc.emergingthreats.net/2009244

**Actual behavior**

Rule is set to drop.

**Components**

pulledpork-0.7.3-1.el7.noarch

**Comment by filippocarletti** [comment]
In nethserver-testing:
pulledpork-0.7.3-5.ns7.noarch.rpm

Check bug is not reproducible.

**Comment by francescopari** [comment]
Verified.

Before package's installation:
`~]# grep 2009561 /etc/suricata/rules/*
/etc/suricata/rules/ET-emerging-attack_response.rules:drop tcp $EXTERNAL_NET any -> $HOME_NET any (msg:"ET ATTACK_RESPONSE Metasploit Meterpreter Process Migration Detected"; flreference:url,www.nologin.org/Downloads/Papers/meterpreter.pdf; reference:url,doc.emergingthreats.net/2009561; classtype:successful-user; sid:2009561; rev:2; metadata:affected_pmeter, deployment Internet, deployment Internal, deployment Datacenter, tag Metasploit, signature_severity Critical, created_at 2010_07_30, updated_at 2016_07_01;)
grep: /etc/suricata/rules/iplists: Is a directory`

After package's installation:
`~]# grep 2009561 /etc/suricata/rules/*
grep: /etc/suricata/rules/iplists: Is a directory`

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
pulledpork-0.7.3-5.ns7.noarch.rpm
