### ISSUE TITLE
IPS Bypass in Cockpit UI

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#5797]
Implement the bypass (Src and Dst) in nethserver-suricata

The new nethserver-suricata Cockpit module should provide:

- [x]  UI implementation (Bypass page)
- [x]  API implementation
- [x] Database, Props and Templates implementation
- [x] Documentation
- [ ] Release

**Comment by edospadoni** [comment]
Test:
- install nethserver-suricata
- check if menù `Bypass` is shown
- try to create bypasses (both src and dst)
- check if `/etc/shorewall/rules` contains the bypasses
- check if the bypasses work

**Comment by gsanchietti** [comment]
After some tests and a deep analysis, we found the following problems:
- if a remote host is added as source bypass, that host has access to all system services (including the ones which should be accessible only from green)
- a specific accept rule for a host always override the bypass
  example: bypass for source 1.2.3.4, create a rule which accepts the traffic from 1.2.3.4 to port 80 of the firewall -> the traffic to port 80 is redirect to the IPS
- bypass has no effect on port forward

It's very hard to find a solution which fits in all scenarios without breaking user expectations.
A mitigation for the current implementation, could be creating more specific rules for bypass: each rule should contain at least source, destination and a destination port.

Probably, the correct solution is to add a new property "bypass IPS" (or target "ACCEPT without IPS") to all firewall rules and port forwards. Such modification can have a huge impact and requires further analysis.

As for now, we are going to revert involved PRs and document a template custom on how to obtain the bypass.

**Comment by gsanchietti** [comment]
Reverted commits in nethserver-suricata:
- e595d73bab37752017955d687cd2f49dcd727186.
- 0a4b920a97f40830dba758ead42a75d9376ae415.
