### ISSUE TITLE
Trusted networks: builtin networks not shown

### ISSUE THREAD

**Issue by andre8244** [NethServer/dev#5847]
**Steps to reproduce**

- Go to "Trusted Networks" page on Cockpit

**Expected behavior**

Builtin trusted networks (e.g. "Nethesis remote support", "Green", ...) are shown in the list of trusted networks

**Actual behavior**

Builtin trusted networks aren't shown in the list of trusted networks

**Components**

nethserver-cockpit

**Comment by andre8244** [comment]
Test case:

- Go to "Trusted Networks" page
- Verify that builtin trusted networks (e.g. "Nethesis remote support", "Green", ...) are shown in the list of trusted networks

**Comment by gsanchietti** [comment]
Verified.

**Comment by gsanchietti** [comment]
in `7.7.1908/updates`:
- nethserver-cockpit-1.0.0-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.7.1908/updates/x86_64/Packages/nethserver-cockpit-1.0.0-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.7.1908/updates/armhfp/Packages/nethserver-cockpit-1.0.0-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.7.1908/updates/aarch64/Packages/nethserver-cockpit-1.0.0-1.ns7.noarch.rpm) 
- nethserver-cockpit-lib-1.0.0-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.7.1908/updates/x86_64/Packages/nethserver-cockpit-lib-1.0.0-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.7.1908/updates/armhfp/Packages/nethserver-cockpit-lib-1.0.0-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.7.1908/updates/aarch64/Packages/nethserver-cockpit-lib-1.0.0-1.ns7.noarch.rpm)
