### ISSUE TITLE
Firewall: MAC validation toggle always disabled

### ISSUE THREAD

**Issue by andre8244** [NethServer/dev#5879]
**Steps to reproduce**

- Go to **Firewall / Settings** on Cockpit
- Enable **MAC validation (IP/MAC binding)** toggle
- Refresh the page

**Expected behavior**

**MAC validation (IP/MAC binding)** toggle is enabled

**Actual behavior**

**MAC validation (IP/MAC binding)** toggle is disabled

**Components**

nethserver-firewall-base

**Comment by andre8244** [comment]
**Test Case**

- Check that bug is not reproducible

**Comment by mamengoni** [comment]
Bug not reproducible.
I didn't find the problem.

**Comment by gsanchietti** [comment]
in `7.7.1908/updates`:
- nethserver-firewall-base-3.7.3-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.7.1908/updates/x86_64/Packages/nethserver-firewall-base-3.7.3-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.7.1908/updates/armhfp/Packages/nethserver-firewall-base-3.7.3-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.7.1908/updates/aarch64/Packages/nethserver-firewall-base-3.7.3-1.ns7.noarch.rpm) 
- nethserver-firewall-base-ui-3.7.3-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.7.1908/updates/x86_64/Packages/nethserver-firewall-base-ui-3.7.3-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.7.1908/updates/armhfp/Packages/nethserver-firewall-base-ui-3.7.3-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.7.1908/updates/aarch64/Packages/nethserver-firewall-base-ui-3.7.3-1.ns7.noarch.rpm)
