### ISSUE TITLE
Firewall: informative description for MAC validation (IP/MAC binding)

### ISSUE THREAD

**Issue by andre8244** [NethServer/dev#5883]
Provide an informative description for MAC validation (IP/MAC binding) controls:

- **MAC validation** toggle switch
- **MAC validation policy** checkbox

Improve label text for **MAC validation policy** checkbox

**Components**

nethserver-firewall-base

**Comment by edospadoni** [comment]
Test case:
- check the label and the behavior is correct

**Comment by cotosso** [comment]
I checked it and now it worked as expected

**Comment by gsanchietti** [comment]
in `7.7.1908/updates`:
- nethserver-firewall-base-3.7.3-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.7.1908/updates/x86_64/Packages/nethserver-firewall-base-3.7.3-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.7.1908/updates/armhfp/Packages/nethserver-firewall-base-3.7.3-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.7.1908/updates/aarch64/Packages/nethserver-firewall-base-3.7.3-1.ns7.noarch.rpm) 
- nethserver-firewall-base-ui-3.7.3-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.7.1908/updates/x86_64/Packages/nethserver-firewall-base-ui-3.7.3-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.7.1908/updates/armhfp/Packages/nethserver-firewall-base-ui-3.7.3-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.7.1908/updates/aarch64/Packages/nethserver-firewall-base-ui-3.7.3-1.ns7.noarch.rpm)
