### ISSUE TITLE
Cockpit: issues on already configured web content filter (with Shalla blacklist)

### ISSUE THREAD

**Issue by nrauso** [NethServer/dev#5916]
If you have already configured the web content filter through the old server-manager (NethGUI) you could run into some issues tring to manage the filter from the new server-manager (Cockpit).

**Steps to reproduce**

- Install the web content filter, enable and configure it from the old server-manager (NethGUI);
- Download the filtering categories using `Shalla` db;
- Configure the default profile - or define a new one - choosing to block `sex` category and add some domains to global whitelist/blacklist boxes;
- Go to new server-manager (Cockpit) and try to add others blocked categories or whitlist/blacklist domains to content filter profiles.

**Expected behavior**

The module must adopt the new configuration.

**Actual behavior**

The module doesn't implement the whitlist/blacklist modifications and gives back an invalid categories error if you try to add some category.

The issues seem related to the way Shalla define some caregories, `sex` for example:

```
~]# grep "NAME: " /var/squidGuard/blacklists/global_usage | grep sex
NAME:   sex/lingerie
NAME:   sex/education
```

to workaround these issues you need to substitute the "culprit" category (`sex` in our example) with its sub-catecories (`lingerie` and `education` in our example) into web content filter configuration in Cockpit.

**Components**

nethserver-cockpit-1.2.1-1.ns7.noarch
nethserver-cockpit-lib-1.2.1-1.ns7.noarch
nethserver-squid-1.10.1-1.ns7.noarch
nethserver-squidguard-1.9.1-1.ns7.noarch

**Comment by gsanchietti** [comment]
The issue is not relative to Cockpit, but to NethGUI which generates an invalid filter.
In fact, `sex` is not a valid category. The valid categories should be `sex/lingerie` and `sex/education`

**Comment by gsanchietti** [comment]
This issue is invalid and it has been replaced by #5926
