### ISSUE TITLE
CentOS 8 and NethServer?

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5918]
I have a CentOS 8 Server, how can we install NethServer?

**Comment by federicoballarini** [comment]
Hi, NethServer is not available on CentOS 8 at the moment (it will be in the future). I suggest you to write on community (https://community.nethserver.org) and not here (bug tracer). You can install NethServer on Centos 7. You can download NethServer iso here: www.nethserver.org.

**Comment by Neustradamus** [comment]
@federicoballarini: Thanks for your reply!

It is possible to have access to the devel-testing repositories based on CentOS 8?

Do not close this ticket, I am not alone :)
