### ISSUE TITLE
Cockpit: Applications -> ... -> "Add to home page" does not work

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5919]
There is a problem in the Cockpit:
- Applications part -> On an application -> ... -> "Add to home page" -> It does not work (after, it is "Remove from home page" but there is nothing on the main page)
-> https://IP:9090/

Note: "Add shortcut" works, the link is here at left.

**Comment by gsanchietti** [comment]
The launcher it's available only if there is no other home page configured.
Please see the official doc:
- http://docs.nethserver.org/en/v7/base_system2.html#add-to-home-page
- https://docs.nethserver.org/projects/nethserver-devel/en/latest/nethserver-httpd.html#welcome-page

And there is also a thread inside the community: https://community.nethserver.org/t/launcher-customization/13752

If you still have problems, feel free to open a new thread in the community forum.
