### ISSUE TITLE
Cockpit: Slash problems

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5921]
Slash problems, for examples:
- https://IP:9090/nethserver/#/applications
- https://IP:9090/nethserver//#/software-center
- https://IP:9090/nethserver///#/subscription
- https://IP:9090/nethserver////#/terminal
- https://IP:9090/nethserver///////#/applications/nethserver-antivirus
- https://IP:9090/nethserver//////#/applications/nethserver-mail
- https://IP:9090/nethserver////////#/applications/nethserver-vpn-ui
- https://IP:9090/nethserver/////#/applications/nethserver-httpd
- ...

And there is a second problem too:
- https://IP:9090/cockpit/HASH/nethserver/index.html#/
- https://IP:9090/cockpit/HASH/nethserver/index.html#/certificates
- ...

In the same time, I think it is possible to have only:
- https://IP:9090/nethserver#example
or
- https://IP:9090/nethserver/#example
or
- https://IP:9090/nethserver/example

**Comment by gsanchietti** [comment]
This is an internal limitation of upstream Cockpit.
Since these URLs can work well with all browsers, this is not should be considered a bug.

If you have any further question, please open a new topic at https://community.nethserver.org/

**Comment by Neustradamus** [comment]
@gsanchietti: About Cockpit Slash and Hash problems:
- https://github.com/cockpit-project/cockpit/issues/13171

About Cockpit Username/Password problems:
- https://github.com/cockpit-project/cockpit/issues/13172
