### ISSUE TITLE
Webmail (Roundcube) in Cockpit: Applications -> ... -> "Add shortcut" is missing

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5922]
There is a problem in the Cockpit:
- Applications part -> On Webmail application -> ... -> "Add shortcut" is missing
-> https://IP:9090/nethserver#/applications

Note: There is "Add to home page".

**Comment by gsanchietti** [comment]
This is by design: external applications shouldn't be added to the shortcut menu because such apps don't have any settings page.

Please report such questions into the community forum: https://community.nethserver.org/
