### ISSUE TITLE
Cockpit: SSL certificate problem after 1st launch (Company changes)

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5924]
After installation of the server, there is a message to change the informations of the Company but the SSL certificate has not changed: NethServer, O=Example Org, ST=SomeState, OU=Main
-> https://IP:9090/nethserver#/certificates

**Comment by gsanchietti** [comment]
Since NS 7, changes to the organization details are not reflect to the certificate.
You can still change the certificate itself from the page you linked.

This is a design choice, but right now I can't find further information on this.
Please report such questions into the community forum: https://community.nethserver.org/

**Comment by Neustradamus** [comment]
@gsanchietti: I think that you must improve this part, can you generate the certificate after the good company part?

**Comment by danb35** [comment]
The most common (and indeed, recommended) scenario would be for you to obtain a cert from Let's Encrypt, which you can do from inside the GUI.  Those certificates don't reflect the organization information, or anything other than the domain name(s).  But, as noted above, this would be better discussed on the community forum.

**Comment by Neustradamus** [comment]
Yes I know for Let's Encrypt but it will be easy to add the creation of a complete certificate (in nethgui and cockpit) after company informations and manually.

Currently nothing here:
- https://IP:980/en-US/Pki
- https://IP:9090/nethserver/index.html#/certificates

Can you see for add manually generation?

There are no change of default certificates after, can you add window for example "Do you want generate a new certificate":
In nethgui:
- Server name: https://192.168.3.200:980/en-US/FQDN
- Organization contacts: https://192.168.3.200:980/en-US/Organization

Cockpit:
- Company: https://192.168.3.200:9090/nethserver

There are vhosts too.

**Comment by Neustradamus** [comment]
There is Let's Encrypt but it is not an obligation:

Observation:
After installation of the server, there is a message to change the informations of the Company but the SSL certificate has not changed: "NethServer, O=Example Org, ST=SomeState, OU=Main"
-> https://IP:9090/nethserver#/certificates

1/ It will be easy to add the creation of a complete certificate (in nethgui and cockpit) manually.

Currently nothing here:
- https://IP:980/en-US/Pki
- https://IP:9090/nethserver#/certificates

Can you see for add manually generation?


2/ There is no change of default certificates after company informations, can you add window for example "Do you want generate a new certificate?":

In nethgui:
- Server name: https://IP:980/en-US/FQDN
- Organization contacts: https://IP:980/en-US/Organization

Cockpit:
- Company: https://IP:9090/nethserver

Do not forget that there are vhosts too.

**Comment by danb35** [comment]
Again, this is better discussed on a forum thread.  It may be that the
effort required to implement this would be pretty low, but on the other
hand, what's the benefit?  What value is there in having the "correct"
organization information on a self-signed certificate that no browser is
going to trust anyway?  IMO, the only thing the self-signed cert is there
for is to enable TLS in the server manager long enough for you to get in
there and install a real cert.

Now, if you were going to set up your Nethserver as a CA, trust its CA cert
in your users' browsers, and use that to issue certs, this would make a bit
more sense--but then you're talking not about simply updating the server's
self-signed cert when you change the organization contact info (which might
be easy to do, but would also result in new cert errors, breaking any
exceptions you've already added, any time you change that information), but
implementing an entire web-based CA system--which is obviously much more
work.  I don't personally see much value in this, though others on the
forum have discussed it--suggest you search there for further discussion on
this.

**Comment by Neustradamus** [comment]
I have created on the forum ;)
