### ISSUE TITLE
missing pppoe interface when creating a port forward 

### ISSUE THREAD

**Issue by cotosso** [NethServer/dev#5925]
This behavior happens when we have a MultiWAN environment with a PPPoE interface.

**Steps to reproduce**

- Configure a system with at least 2 red interface, one of them must be a PPPoE
- Try to create a port forward valid only for traffic incoming from PPPoE interface

**Expected behavior**

The port forward modify panel must allows to create a port forward on all interfaces or on a single red interface/alias.
Actually red interface are identified by their main ip address

**Actual behavior**
All works as described above except that it is not possible to enable a port forward ONLY for the PPPoE interface, only ip address from ethernet cards are showed in the panel.

**Components**

NethServer release 7.7.1908 (final)
nethserver-firewall-base-ui-3.7.3-1.ns7.noarch
nethserver-firewall-base-3.7.3-1.ns7.noarch

----

**Comment by gsanchietti** [comment]
This is a new feature which requires an analysis on how it can be implemented inside Shorewall.

**Comment by gsanchietti** [comment]
This is the relevant Shorewall doc (`man shorewall-rules` section `ORIGDEST`):
> ORIGDEST - [-|address[,address]...[exclusion]|exclusion]
           Optional. If ACTION is DNAT[-] or REDIRECT[-] then if this column is included and is different from the IP address given in the DEST column, then connections destined for that address will be forwarded to the IP and port
           specified in the DEST column.
> ...
> Beginning with Shorewall 4.4.17, the primary IP address of a firewall interface can be specified by an ampersand ('&') followed by the logical name of the interface as found in the INTERFACE column of
           shorewall-interfaces[9] (5).

If the rule must be applied to interfaces with a dynamic IP, shorewall rules will have to be regenerated on each IP change.
Such implementation it's quite complex and can introduce regressions.

The only workaround is to create a port forward valid for all red interfaces.

Closing as WONTFIX.
