### ISSUE TITLE
Transifex: group name error for ejabberd

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5930]
Can you rename Ejabber to Ejabberd or ejabberd in:
- https://www.transifex.com/nethserver/nethserver/

**Comment by DavidePrincipi** [comment]
Yes we can and you can too, by opening a pull request or joining the Transifex translations team!

As stated in the contributing guidelines summary, we always encourage discussions on https://community.nethserver.org/, especially for typos or small fixes like this one.

When opening a bug report provide information by filling the [bug report form](https://github.com/NethServer/dev/issues/new?labels=bug&template=bug_report.md)
