### ISSUE TITLE
ejabberd upgrade?

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5932]
Can you update the ejabberd to last?
- https://github.com/processone/ejabberd
- https://github.com/processone/ejabberd/releases

After 19.09.1, there were changes: https://github.com/processone/ejabberd/commits/master

And can you add some ejabberd-contrib modules too?
- https://github.com/processone/ejabberd-contrib

**Comment by DavidePrincipi** [comment]
Yes, updating the ejabberd package is a good thing. I do not know ejabberd-contrib and what they can do. Let's continue this discussion on https://community.nethserver.org/

As stated in the [contributing guidelines summary](https://github.com/NethServer/dev/blob/master/CONTRIBUTING.md), we always encourage discussions on https://community.nethserver.org/

**Comment by Neustradamus** [comment]
It is not invalid, it is in progress.
- https://community.nethserver.org/t/ejabberd-upgrade/13980

**Comment by Neustradamus** [comment]
@DavidePrincipi: Can you reopen this ticket?
