### ISSUE TITLE
ejabberd: 3 unknown accounts in roster

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5933]
In the roster of users, there are 3 unknown accounts:
- Administrator@domain.tld (not enabled)
- Guest@domain.tld
- krbtgt@domain.tld

Can you remove or hide it?

**Comment by DavidePrincipi** [comment]
Those are builtin user accounts of Active Directory. We didn't find a way to hide them. Could you suggest a solution?

As stated in the contributing guidelines summary, we always encourage discussions on https://community.nethserver.org/

Let's continue this discussion on https://community.nethserver.org/
