### ISSUE TITLE
Users & Groups: problem of groups/rights

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5934]
On https://IP:9090/nethserver#/users-groups

When we create an user, we have only:
- domain admins

There are others, no?

Example, when we enable the ejabberd webadmin:
- "Access is granted to members of the "jabberadmins" group"

Note: In the same time, it will be nice to change this group name for be perfect ;)

**Comment by DavidePrincipi** [comment]
> When we create an user, we have only domain admins

The jabberadmins group must be created manually. Probably the docs here are not clear enough
http://docs.nethserver.org/en/v7/chat.html#administrators

I opened a pull request to fix them.

What you're asking is interesting, please provide a pull request here or continue this discussion on https://community.nethserver.org/ 

I'm sure your expertise on Ejabberd will lead to many improvements!
