### ISSUE TITLE
SOGo and Roundcube Address Book and groups/users

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5936]
In Address Book of SOGo:
- https://IP/SOGo/so/XXXX/Contacts/view#!/addressbooks/personal

-> No contact (It is normal)

In domain groups:
- https://IP/SOGo/so/XXXX/Contacts/view#!/addressbooks/AD_Groups

I enter for example "ad", I obtain: 5 matching contacts (without email address):
- Domain Admins (Designated administrators of the domain)
- Enterprise Admins (Designated administrators of the enterprise)
- Enterprise Read-only Domain Controllers (Members of this group are Read-Only Domain Controllers in the enterprise)
- Read-only Domain Controllers (Members of this group are Read-Only Domain Controllers in the domain)
- Schema Admins (Designated administrators of the schema)

I enter for example "do", I obtain: 7 matching contacts (without email address):
- Domain Admins (Designated administrators of the domain)
- Domain Computers (All workstations and servers joined to the domain)
- Domain Controllers (All domain controllers in the domain)
- Domain Guests (All domain guests)
- Domain Users (All domain users)
- Enterprise Read-only Domain Controllers (Members of this group are Read-Only Domain Controllers in the enterprise)
- Read-only Domain Controllers (Members of this group are Read-Only Domain Controllers in the domain)

Why?
It is possible to hide it?

In domain users:
- https://IP/SOGo/so/XXXX/Contacts/view#!/addressbooks/AD_Users

I enter for example "ad", I obtain: 3 matching contacts:
- Administrator (locked account)
- NethServer Administrator (locked account)
- NethServer LDAP simple auth identity

Why?
It is possible to hide it?

In Address Book of Roundcube:
Personal:
- https://IP/webmail/?_task=addressbook&_source=0

-> I see no contact, it is normal

No group.

Public:
- https://IP/webmail/?_task=addressbook&_source=public

I see 2 contacts:
- NethServer LDAP simple auth identity
- NethServer Administrator (locked account)

Why?
It is possible to hide it?

**Comment by DavidePrincipi** [comment]
As stated in the contributing guidelines summary, we always encourage discussions on https://community.nethserver.org/

If you think something is wrong, there you can set the #bug category.

If you want to open a bug here, please respect the bug form structure: 

https://github.com/NethServer/dev/issues/new?labels=bug&template=bug_report.md
