### ISSUE TITLE
Cockpit and nethgui: problem

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#5939]
In first time, we configure the server with the Cockpit:
- https://IP:9090/

After it, when we launch the nethgui, it is needed to configure a new time the server.
- https://IP:980/

**Comment by DavidePrincipi** [comment]
The "first configuration wizard" procedure is a part of the Nethgui-based server manager. The Cockpit-based server manager is not aware of Nethgui.

Both interfaces act on the system in the same way, but they are designed differently: Cockpit does not provide a "wizard" procedure.

We cannot disable the Nethgui "first configuration wizard" from the Cockpit interface.
