### ISSUE TITLE
Cockpit: simple user can access some configuration

### ISSUE THREAD

**Issue by federicoballarini** [NethServer/dev#5944]
A simple user (with shell access) can access some configuration (but not modify) like Ejabberd, by left applications shortcuts. By clicking shortcut user can access application: some app returns error, some others returns the configuration (not editable).

**Proposed solution**

Best solution can be to hide shortcut if user do not have permission to access application.

**Alternative solutions**

An alternative solution can be to unify all applications returning identical error.

**See also**

Three examples:
- ejabberd: returns visible config page, but if user try to modify get error
- antivirus: returns reading config error
- web server dashboard: loading loop

Note that into Applications list user can't see these applications.
In Applications list are missing public applications as Webtop, Roundcube, Nextcloud: to complete work we can add also it in list, without right control menu.

**Comment by gsanchietti** [comment]
The application shortcuts come from a template and can't be changed on the user login.
Reworking how the user can access non-delegated apps requires a big effort without a real outcome.

The user accessing the non-delegated application can't edit the configuration, this is the important thing.
If you want to hide the access to a non-delegated application, just do not add it as a shortcut.

I'm going to close this feature request as `wontfix`, feel free to promote such discussion on community forum.
