### ISSUE TITLE
Cockpit: improve logs view

### ISSUE THREAD

**Issue by federicoballarini** [NethServer/dev#5945]
Some Cockpit modules do not have new logs view with regex filter.
We need to verify:
- nethserver-ejabberd
- nethserver-fail2ban
- ~~nethserver-mattermost~~
- ~~nethserver-nextcloud~~

These modules should be updated as following:
- add list containing logs files
- add regex filter
- change follow button graphic

This is an image of new view

<img width="1406" alt="Schermata 2019-11-21 alle 20 59 59" src="https://user-images.githubusercontent.com/17910311/69372435-ffda8380-0ca1-11ea-8d17-69de3f49a6d9.png">

instead of

<img width="1405" alt="Schermata 2019-11-21 alle 21 00 15" src="https://user-images.githubusercontent.com/17910311/69372460-0a951880-0ca2-11ea-8851-e11c0b32166e.png">

**Comment by gsanchietti** [comment]
I back this proposal for nethserver-fail2ban and nethserver-ejabberd.
On the other end, nextcloud log is in JSON format and it's not well suited for grep searching, let's leave the form as is.
Mattermost doesn't usually display much in logs, so we do not really need a filter feature there.

I will leave the issue open, let's see if we have some spare time to work on it but this feature is not not a priority right now.

**Comment by gsanchietti** [comment]
@stephdl could you consider this improvement for the fail2ban package. We can schedule it with other UI improvements with low priority.

@DavidePrincipi we can schedule the improvements for ejabberd along with the work for ejabebrd 19.

I'm closing this issue.
