### ISSUE TITLE
Cockpit: add destination check to backup menu

### ISSUE THREAD

**Issue by federicoballarini** [NethServer/dev#5955]
Sometimes, when backup fails, can be helpful to check the backup destination.

**Proposed solution**

Add check button on backup data menu, without open "Edit" menu.

**See also**

https://community.nethserver.org/t/cockpit-check-backup-destination/

**Comment by federicoballarini** [comment]
First development part, closed. I wait for feedback.
Could you verify it @gsanchietti @DavidePrincipi ?

**Comment by gsanchietti** [comment]
Before adding new features, please open a thread on https://comunnity.nethserver.org and discuss it there.
