### ISSUE TITLE
FreePBX: music files no more included into freepbx installation package

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#6001]
freepbx-14.0-7.ns7.noarch doesn't include anymore the creative commons default music on hold.
I'm not able to find anything about why they removed those files, and at the moment they are still listed with credits in framework module README: https://github.com/FreePBX/framework/blob/release/14.0.12.12/README.md#music

**Steps to reproduce**

- make a VoIP PBX fresh install
- check if there are default music on hold in /var/lib/asterisk/moh/
- check FreePBX music on hold module

**Expected behavior**

- in /var/lib/asterisk/moh/ I expect to find the default music on hold files:
macroform-cold_day.wav  macroform-robot_dity.wav  macroform-the_simplicity.wav  manolo_camp-morning_coffee.wav  reno_project-system.wav
- in FreePBX music on hold module, I should find default music on hold class with those default songs

**Actual behavior**

- /var/lib/asterisk/moh/ is empty
- default music on hold class is empty

**Components**

freepbx-14.0-7.ns7.noarch

**Comment by DavidePrincipi** [comment]
In nethserver/updates

- freepbx-14.0-8.ns7.noarch.rpm
