### ISSUE TITLE
Cockpit: UI to force the shell of users

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6074]
With the last development we have brought some feature relative SSH and SSSD shell overwrite, we need a UI to enable it

**Proposed solution**

Make a widget switch to enable/disable the $sssd{ShellOverwriteStatus} property under the settings page of cockpit

**See also**

https://community.nethserver.org/t/ssh-sftp-restricted-authorizations/14246/33

**Comment by DavidePrincipi** [comment]
I'd like to release this feature when

- The new User password changing page is available
- Docs is complete

**Comment by gsanchietti** [comment]
The new "User password page" will also enable the ShellOverrideStatus as requirement.
Once enabled, the prop cannot be changed back to disabled from UI.

Replaced by #6100

**Comment by DavidePrincipi** [comment]
The switch is still required but has to be adapted with #6100

**Comment by edospadoni** [comment]
Replaced by: https://github.com/NethServer/dev/issues/6100

**Comment by DavidePrincipi** [comment]
Please @edospadoni, close the issue when #6100 has been released with a reference to the new RPMs

**Test case**

See #6100

**Comment by gsanchietti** [comment]
The UI correctly handle sall user cases and fires the correct events.

**Comment by gsanchietti** [comment]
in `7.7.1908/updates`:
- nethserver-cockpit-1.6.0-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.7.1908/updates/x86_64/Packages/nethserver-cockpit-1.6.0-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.7.1908/updates/armhfp/Packages/nethserver-cockpit-1.6.0-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.7.1908/updates/aarch64/Packages/nethserver-cockpit-1.6.0-1.ns7.noarch.rpm) 
- nethserver-cockpit-lib-1.6.0-1.ns7.noarch.rpm [x86_64](http://packages.nethserver.org/nethserver/7.7.1908/updates/x86_64/Packages/nethserver-cockpit-lib-1.6.0-1.ns7.noarch.rpm) [armhfp](http://packages.nethserver.org/nethserver/7.7.1908/updates/armhfp/Packages/nethserver-cockpit-lib-1.6.0-1.ns7.noarch.rpm) [aarch64](http://packages.nethserver.org/nethserver/7.7.1908/updates/aarch64/Packages/nethserver-cockpit-lib-1.6.0-1.ns7.noarch.rpm)
