### ISSUE TITLE
WebTop 5: anonymous SMTP session with SmtpAuth enabled and SmtpStarttls disabled

### ISSUE THREAD

**Issue by lucagasparini** [NethServer/dev#6076]
If you enable smtp authentication on webtop without enabling TLS encryption, the session on postfix on port 587 is always anonymous

**Steps to reproduce**
- `config setprop webtop SmtpAuth enabled SmtpStarttls disabled`
- `signal-event nethserver-webtop5-update`

- login on webtop and send an email

**Expected behavior**
the smtp session is opened with authentication:
```
postfix/smtpd[18254]: 7798612262C: client=localhost[127.0.0.1], sasl_method=LOGIN, sasl_username=lucag@nethesis.it
```

**Actual behavior**
the smtp session is opened without authentication:
```
postfix/smtpd[17910]: 309CA12262C: client=localhost[127.0.0.1]
```
**Components**
```
webtop5-1.4.3-1.4
nethserver-webtop5-1.5.1-1.5
```

**See also**

With this commit
https://github.com/NethServer/nethserver-mail/pull/100/commits/f368b4dc870bcbf88577e768495c3741059657ad
the port 10587 was introduced for sessions authenticated by localhost without TLS

If you change the SMTP port from 587 to 10587 the problem is solved:
```
su - postgres -c 'psql webtop5'
webtop5=# update core.settings set value='10587' where service_id='com.sonicle.webtop.core' and key='smtp.port';
```

It is recommended to change the SMTP port (from 587 to 10587) set by default with this init:
https://github.com/NethServer/nethserver-webtop5/blob/ec20d3ac8e0268cc0e3befe23058de2a80f7cddb/root/usr/share/webtop/sql/data/init-data-nethserver.sql#L9 

----

**Comment by gsanchietti** [comment]
WebTop conflicting configuration should be removed.
Issue replaced by #6080
