### ISSUE TITLE
Add ACME server option for certbot

### ISSUE THREAD

**Issue by mmaridev** [NethServer/dev#6114]
In an internal-pki environment, in which ACME is used to issue SSL certificates signed by the internal CA, it would be useful to be able to set the serve directory via cli/gui.

**Proposed solution**

Add a variable to the letsencrypt module configuration and add the `--server` directive to certbot options.

**Alternative solutions**

Manually modify the letsencrypt-certs file (what I'm doing right now).

**Comment by gsanchietti** [comment]
Thank you for sharing your feature request!
It seems this is a very very specific need which is not required by most of NethServer users.
The right place to discuss such feature request is https://community.nethserver.org/, please join us there!

Regarding your specific need, I think it can be solved just using a certbot [configuration file](https://certbot.eff.org/docs/using.html#configuration-file).
In this case, create a file named `/etc/letsencrypt/cli.ini` containing the `server` option.
Eg:
```
server=http://my.mightyacme.com
```

Certbot command line will honour it. You can test it using:
```
/usr/libexec/nethserver/letsencrypt-certs -v  -d test.org
```

I'm willing to close this issue as invalid.

If you want to continue the discussion, please open a new thread inside https://community.nethserver.org/.
