### ISSUE TITLE
Promote Cockpit to stable, P3scan is deprecated

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#6117]
Update yum groups accordingly to these new policies:

- [x] Remove `beta` tag from `nethserver-cockpit` group
- [x] Hide `nethserver-p3scan` group: P3scan is now deprecated
- [x] Remove `nethserver-p3scan2` and `nethserver-p3scan` from groups

Documentation:
- [x] Remove `pop3_proxy.rst` from `index.rst`
- [x] Add to index all pages related to the new Server Manager

Such modifications should be reflected also on Enterprise yum groups.

**Comment by gsanchietti** [comment]
**Test case 1**
- Access the Software Center and verify the `beta` tag has been removed from Cockpit

**Test case 2**
- Access the Software Center and verify the P3scan group is not visible anymore

**Comment by stephdl** [comment]
QA

test1 : I did not find where I could read before or after a `beta`; but on all my machines cockpit is installed now, I need some clues

test2: I believe it is a partial fail, either before to upgrade to testing of after, I can find the p3scan as available let me show the png

![Screenshot (52)](https://user-images.githubusercontent.com/3164851/80086072-79301800-8559-11ea-8d78-45e1651db446.png)

however the p3scan is not listed anymore in the email server stack

![Screenshot (53)](https://user-images.githubusercontent.com/3164851/80086128-8c42e800-8559-11ea-9980-ffe8f7bd3247.png)

please @gsanchietti  I need some clues

**Comment by gsanchietti** [comment]
Until 7.8 is not out, you need to hack with the yum config to test such things.

> test1 : I did not find where I could read before or after a `beta`, but on all my machines cockpit is installed now, I need some clues

Try with this:
```
yum --disablerepo=* --enablerepo=nethserver-updates grouplist -v  | grep "New Server Manager"
```

Then edit `NethSever.repo`, disable mirrorlist, enable baseurl and manually change the release to `7.8.2003`. Finally, clean yum metadata and execute again the command above.

> test2: I believe it is a partial fail, either before to upgrade to testing of after, I can find the p3scan as available let me show the png

After previous test case, you can check with:
```
yum --disablerepo=* --enablerepo=nethserver-updates grouplist -v  | grep p3scan
```
It must report and empty output

**Comment by stephdl** [comment]
After I have modified the NethServer.repo It is OK

```
[root@ns7loc14 ~]# yum --disablerepo=* --enablerepo=nethserver-updates grouplist -v  | grep p3scan
[root@ns7loc14 ~]# yum --disablerepo=* --enablerepo=nethserver-updates grouplist -v  | grep "New Server Manager"
   New Server Manager (nethserver-cockpit)
```
set verified

**Comment by Neustradamus** [comment]
I think it is better to wait the solution of the 2164 security bug of Cockpit:
- https://github.com/cockpit-project/cockpit/issues

**Comment by Neustradamus** [comment]
From @kellcomnet2 (2020/04/27 22:15 (UTC+2)) on issue specified previously:
> 
> 
> I can confirm that for me using the following config I am no longer getting the basic auth prompt when I was previously.
> 
> ```
> [WebService]
> Origins = https://******.us wss://******.us
> ProtocolHeader = X-Forwarded-Proto
> 
> [gssapi]
> action = none
> 
> [negotiate]
> action = none
> ```
> 
> this is the part that I added
> 
> ```
> [negotiate]
> action = none
> ```

Dear @gsanchietti, @stephd: Can you look it?

Thanks in advance.

**Comment by gsanchietti** [comment]
Thank you reporting @Neustradamus. I don't think this is a security fix, but for sure we can disable kerberos authentication as reported in the new documentation PR: https://github.com/cockpit-project/cockpit/pull/13982/files
