### ISSUE TITLE
Samba DC upgrade 

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#6119]
Currently shipped Samba release is 4.9.18 which has been deprecated 

Possible candidates:

- [Samba  4.10](https://www.samba.org/samba/history/samba-4.10.0.html) which should be simpler and is supported until September 2020
- [Samba  4.12](https://www.samba.org/samba/history/samba-4.12.0.html) which requires Python 3.5 and GNU TLS and is supported until September 2021

**See also**

https://wiki.samba.org/index.php/Samba_Release_Planning

**Comment by Neustradamus** [comment]
@gsanchietti; Thanks to listen me :)
- https://community.nethserver.org/t/samba-new-branch-upgrade/15063

For 4.12 directly and it will be better to update/upgrade later too.

**Comment by gsanchietti** [comment]
We are going to update to Samba 4.11.7 because samba 4.12 required GnuTLS 3.4 which is not supported on CentOS 7.

**Comment by Neustradamus** [comment]
@gsanchietti: GnuTLS 3.4 is possible with RHEL/CentOS 7.x
- https://samba.tranquil.it/centos7/samba-4.12/x86_64/

Look:
- compat-gnutls34-3.4.17-0.1.el7.x86_64.rpm	2020-03-10 14:47
- compat-gnutls34-debuginfo-3.4.17-0.1.el7.x86_64.rpm	2020-03-10 14:47
- compat-gnutls34-devel-3.4.17-0.1.el7.x86_64.rpm	2020-03-10 14:47
- compat-gnutls34-utils-3.4.17-0.1.el7.x86_64.rpm	2020-03-10 14:47
- ...

**Comment by gsanchietti** [comment]
Thank you @Neustradamus, I've already seen the RPMs but we are not going down that way if it's not really necessary, so *probably* later 2021.

**Comment by DavidePrincipi** [comment]
From Samba 4.11 release notes: SMB1 is now disabled by default. We probably need to re-enable it to provide backward compatibility during upgrades to 7.8.

https://www.samba.org/samba/history/samba-4.11.0.html

**Comment by Neustradamus** [comment]
@DavidePrincipi: An option in Nethgui/Cockpit?

**Comment by gsanchietti** [comment]
After days of work, we think that upgrading to Samba 4.11 could lead to regressions due to python3 requirement and changed default for SMBv1 without real benefits.

We are going to drop this upgrade, and we will stick to Samba 4.9 as long as possible.
The only reason to upgrade Samba should be a security vulnerability which can't be fixed in current release.

The linked PR correctly install a new DC but the upgrade scenarios has not been not implemented. Code will be preserved for future use.

I'm going to close this issue and reject the feature for NS 7.8.

**Comment by Neustradamus** [comment]
A very very bad news...

**Comment by Neustradamus** [comment]
New versions out!
- Samba 4.12.2
- Samba 4.11.8
- Samba 4.10.15

Source:
- https://www.samba.org/
