### ISSUE TITLE
Backup Data Restic Failed - Fatal: wrong password or no key found

### ISSUE THREAD

**Issue by khuyenht** [NethServer/dev#6137]
**Steps to reproduce**
Schedule Run daily backup failed with error Fatal: wrong password or no key found
I run daily backup data using restic ( backup to external hard disk ), backup data working well for 2 weeks, today i received report email notify backup Failed 
Fatal: create repository at /mnt/backup-daily-backup-restic failed: config file already exists

Fatal: wrong password or no key found
Backup failed
Action 'backup-data-restic daily-backup-restic': FAIL Backup status: FAIL

**Components**

dante-0.3.0-1.ns7.x86_64
dovecot-deleted-to-trash-0.6-4.ns7.x86_64
duc-1.4.2-1.ns7.x86_64
libopenr2-1.3.3-1.ns7.x86_64
libss7-2.0.0-1.ns7.x86_64
nethserver-antivirus-1.5.0-1.ns7.noarch
nethserver-backup-config-2.5.0-1.ns7.noarch
nethserver-backup-data-1.7.1-1.ns7.noarch
nethserver-base-3.7.6-1.ns7.noarch
nethserver-cockpit-1.6.3-1.ns7.noarch
nethserver-cockpit-lib-1.6.3-1.ns7.noarch
nethserver-collectd-3.1.0-1.ns7.noarch
nethserver-dante-1.0.2-1.ns7.noarch
nethserver-dc-1.8.1-1.ns7.x86_64
nethserver-diagtools-1.0.3-1.ns7.noarch
nethserver-dnsmasq-1.7.2-1.ns7.noarch
nethserver-duc-1.7.0-1.ns7.noarch
nethserver-firewall-base-3.8.9-1.ns7.noarch
nethserver-hosts-1.2.2-1.ns7.noarch
nethserver-httpd-3.8.1-1.ns7.noarch
nethserver-httpd-admin-2.4.0-1.ns7.noarch
nethserver-httpd-virtualhosts-3.8.1-1.ns7.noarch
nethserver-lang-cockpit-1.4.4-3.ns7.noarch
nethserver-lang-en-1.4.4-3.ns7.noarch
nethserver-letsencrypt-1.1.6-1.ns7.noarch
nethserver-lib-2.2.11-1.ns7.noarch
nethserver-lsm-1.2.3-1.ns7.noarch
nethserver-mail-common-2.12.4-1.ns7.noarch
nethserver-mail-filter-2.12.4-1.ns7.noarch
nethserver-mail-getmail-2.12.4-1.ns7.noarch
nethserver-mail-server-2.12.4-1.ns7.noarch
nethserver-mail-smarthost-2.12.4-1.ns7.noarch
nethserver-memcached-1.1.0-1.ns7.noarch
nethserver-mysql-1.1.4-1.ns7.noarch
nethserver-netdata-1.1.0-1.ns7.noarch
nethserver-nethforge-release-7-3.ns7.noarch
nethserver-nextcloud-1.9.2-1.ns7.noarch
nethserver-ntp-1.1.3-1.ns7.noarch
nethserver-openssh-1.5.2-1.ns7.noarch
nethserver-phonehome-1.4.0-1.ns7.noarch
nethserver-php-1.2.1-1.ns7.noarch
nethserver-release-7-16.ns7.noarch
nethserver-restore-data-2.0.6-1.ns7.noarch
nethserver-rh-php72-php-fpm-1.1.1-1.ns7.noarch
nethserver-samba-4.5.3-1.ns7.noarch
nethserver-samba-audit-1.3.1-1.ns7.noarch
nethserver-smartd-1.1.0-1.ns7.noarch
nethserver-sssd-1.6.0-1.ns7.noarch
nethserver-subscription-3.5.4-1.ns7.noarch
nethserver-subscription-inventory-3.5.4-1.ns7.x86_64
nethserver-subscription-ui-3.5.4-1.ns7.noarch
nethserver-unbound-1.1.0-1.ns7.noarch
nethserver-vsftpd-1.1.1-1.ns7.noarch
nethserver-yum-1.4.1-1.ns7.noarch
olefy-1.1.0-1.ns7.x86_64
perl-Mail-RFC822-Address-0.3-1.ns7.noarch
perl-Net-DBus-1.1.0-4.ns7.x86_64
restic-0.9.6-1.ns7.x86_64
sogo-4.3.0-1.ns7.x86_64
sogo-activesync-4.3.0-1.ns7.x86_64
sogo-ealarms-notify-4.3.0-1.ns7.x86_64
sogo-tool-4.3.0-1.ns7.x86_64
sope49-appserver-4.9-20191218_1900.ns7.x86_64
sope49-cards-4.3.0-1.ns7.x86_64
sope49-core-4.9-20191218_1900.ns7.x86_64
sope49-gdl1-4.9-20191218_1900.ns7.x86_64
sope49-gdl1-contentstore-4.3.0-1.ns7.x86_64
sope49-gdl1-mysql-4.9-20191218_1900.ns7.x86_64
sope49-ldap-4.9-20191218_1900.ns7.x86_64
sope49-mime-4.9-20191218_1900.ns7.x86_64
sope49-sbjson-2.3.1-20191218_1900.ns7.x86_64
sope49-xml-4.9-20191218_1900.ns7.x86_64

**See also**

**Comment by federicoballarini** [comment]
Hi @khuyenht, I use restic everyday and I have no problem. To analyze your troubles I suggest you to open a thread on https://community.nethserver.org and we can help you.
Then, if we'll found an issue we'll open it here.
Thank you for your collaboration.
