### ISSUE TITLE
Before 7.8 release: Do not forget to change ejabber (etc) to ejabberd...

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#6139]
Reminder:
- Do not forget to update the NS code before 7.8.

I have done a lot of PRs and commits about it.

Please look archives.

Linked to:
- ejabberd
- fail2ban
- lang
- ...

Thanks in advance.

**Comment by gsanchietti** [comment]
All work for ejabberd has been already merged and it's ready to be released.

**Comment by Neustradamus** [comment]
@gsanchietti: No several months ago, the team said me that my changes will be in the next NethServer release.

Always the problem in the code, one example here:
- https://github.com/search?q=org%3ANethServer+ejabber&type=Code

My PRs have not been merged in master for 7.8.

Base:
- https://github.com/NethServer/nethserver-base/pulls?q=is%3Apr+author%3A%40Neustradamus

1/ https://github.com/NethServer/nethserver-base/pull/165

Ejabberd:
- https://github.com/NethServer/nethserver-ejabberd/pulls?q=is%3Apr+author%3A%40Neustradamus

1/ https://github.com/NethServer/nethserver-ejabberd/pull/23
2/ https://github.com/NethServer/nethserver-ejabberd/pull/25
3/ https://github.com/NethServer/nethserver-ejabberd/pull/26
4/ https://github.com/NethServer/nethserver-ejabberd/pull/27

Fail2ban:
- https://github.com/NethServer/nethserver-fail2ban/pulls?q=is%3Apr+author%3A%40Neustradamus

1/ https://github.com/NethServer/nethserver-fail2ban/pull/74
2/ https://github.com/NethServer/nethserver-fail2ban/pull/75

Docs:
- https://github.com/NethServer/docs/pulls?q=is%3Apr+author%3A%40Neustradamus

1/ https://github.com/NethServer/docs/pull/460

comps:
- https://github.com/NethServer/comps/pulls?q=is%3Apr+author%3A%40Neustradamus

1/ https://github.com/NethServer/comps/pull/36

Lang:
- https://github.com/NethServer/nethserver-lang/pulls?q=is%3Apr+author%3A%40Neustradamus

1/ https://github.com/NethServer/nethserver-lang/pull/27
2/ https://github.com/NethServer/nethserver-lang/pull/28
