### ISSUE TITLE
Update ns6upgrade repo for NS 7.8

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#6143]
The ns6upgrade repo is required for the in-place upgrade procedure from version 6 to 7.

Update the repository with the new kernel release. By now just a temporary copy of the 7.7/ns6upgrade repo has been done for 7.8.

http://mirror.nethserver.org/nethserver/7.8.2003/ns6upgrade/x86_64/

See also https://github.com/NethServer/dev/issues/5867

**Comment by Neustradamus** [comment]
Please wait, I will do ejabberd PR that you have missing :)

**Comment by DavidePrincipi** [comment]
- The new kernel works as expected during the upgrade
- Published here http://mirror.nethserver.org/nethserver/7.8.2003/ns6upgrade/
