### ISSUE TITLE
Backup Data Restic

### ISSUE THREAD

**Issue by khuyenht** [NethServer/dev#6149]
Hi experts,
I create backup data using command following https://docs.nethserver.org/projects/nethserver-devel/en/latest/nethserver-backup-data.html 
But job backup failed.
Could you please support me resolve this issue.
Thank you so much
**Steps to reproduce**

db backups set backup2 restic BackupTime '30 19 * * *' CleanupOlderThan 56D Notify always NotifyTo abc@gmail.com Type full VFSType usb USBLabel backup VolSize 200 status enable  

echo -e "123456" > /root/backup2-password; signal-event nethserver-backup-data-save backup2  /root/backup2-password

**Expected behavior**

Backup Successfully

**Actual behavior**
Backup: backup2
Backup started at 2020-04-30 23:29:19
Pre backup scripts status: SUCCESS
Fatal: create repository at /mnt/backup-backup2 failed: config file already exists

Fatal: wrong password or no key found
Backup failed
Action 'backup-data-restic backup2': FAIL Backup status: FAIL

Log file: /var/log/backup/backup-backup2-202004302329.log

**Components**

rpm -qa | grep -F .ns7. | sort

dante-0.3.0-1.ns7.x86_64
dovecot-deleted-to-trash-0.6-4.ns7.x86_64
duc-1.4.2-1.ns7.x86_64
libopenr2-1.3.3-1.ns7.x86_64
libss7-2.0.0-1.ns7.x86_64
nethserver-antivirus-1.5.0-1.ns7.noarch
nethserver-backup-config-2.5.0-1.ns7.noarch
nethserver-backup-data-1.7.1-1.ns7.noarch
nethserver-base-3.7.6-1.ns7.noarch
nethserver-cockpit-1.6.3-1.ns7.noarch
nethserver-cockpit-lib-1.6.3-1.ns7.noarch
nethserver-collectd-3.1.0-1.ns7.noarch
nethserver-dante-1.0.2-1.ns7.noarch
nethserver-dc-1.8.1-1.ns7.x86_64
nethserver-diagtools-1.0.3-1.ns7.noarch
nethserver-dnsmasq-1.7.2-1.ns7.noarch
nethserver-duc-1.7.0-1.ns7.noarch
nethserver-firewall-base-3.8.9-1.ns7.noarch
nethserver-hosts-1.2.2-1.ns7.noarch
nethserver-httpd-3.8.1-1.ns7.noarch
nethserver-httpd-admin-2.4.0-1.ns7.noarch
nethserver-httpd-virtualhosts-3.8.1-1.ns7.noarch
nethserver-lang-cockpit-1.4.4-3.ns7.noarch
nethserver-lang-en-1.4.4-3.ns7.noarch
nethserver-letsencrypt-1.1.6-1.ns7.noarch
nethserver-lib-2.2.11-1.ns7.noarch
nethserver-lsm-1.2.3-1.ns7.noarch
nethserver-mail-common-2.12.4-1.ns7.noarch
nethserver-mail-filter-2.12.4-1.ns7.noarch
nethserver-mail-getmail-2.12.4-1.ns7.noarch
nethserver-mail-server-2.12.4-1.ns7.noarch
nethserver-mail-smarthost-2.12.4-1.ns7.noarch
nethserver-memcached-1.1.0-1.ns7.noarch
nethserver-mysql-1.1.4-1.ns7.noarch
nethserver-netdata-1.1.0-1.ns7.noarch
nethserver-nethforge-release-7-3.ns7.noarch
nethserver-nextcloud-1.9.2-1.ns7.noarch
nethserver-ntp-1.1.3-1.ns7.noarch
nethserver-openssh-1.5.2-1.ns7.noarch
nethserver-phonehome-1.4.0-1.ns7.noarch
nethserver-php-1.2.1-1.ns7.noarch
nethserver-release-7-16.ns7.noarch
nethserver-restore-data-2.0.6-1.ns7.noarch
nethserver-rh-php72-php-fpm-1.1.1-1.ns7.noarch
nethserver-samba-4.5.3-1.ns7.noarch
nethserver-samba-audit-1.3.1-1.ns7.noarch
nethserver-smartd-1.1.0-1.ns7.noarch
nethserver-sssd-1.6.0-1.ns7.noarch
nethserver-subscription-3.5.4-1.ns7.noarch
nethserver-subscription-inventory-3.5.4-1.ns7.x86_64
nethserver-subscription-ui-3.5.4-1.ns7.noarch
nethserver-unbound-1.1.0-1.ns7.noarch
nethserver-vsftpd-1.1.1-1.ns7.noarch
nethserver-yum-1.4.1-1.ns7.noarch
olefy-1.1.0-1.ns7.x86_64
perl-Mail-RFC822-Address-0.3-1.ns7.noarch
perl-Net-DBus-1.1.0-4.ns7.x86_64
restic-0.9.6-1.ns7.x86_64
sogo-4.3.0-1.ns7.x86_64
sogo-activesync-4.3.0-1.ns7.x86_64
sogo-ealarms-notify-4.3.0-1.ns7.x86_64
sogo-tool-4.3.0-1.ns7.x86_64
sope49-appserver-4.9-20191218_1900.ns7.x86_64
sope49-cards-4.3.0-1.ns7.x86_64
sope49-core-4.9-20191218_1900.ns7.x86_64
sope49-gdl1-4.9-20191218_1900.ns7.x86_64
sope49-gdl1-contentstore-4.3.0-1.ns7.x86_64
sope49-gdl1-mysql-4.9-20191218_1900.ns7.x86_64
sope49-ldap-4.9-20191218_1900.ns7.x86_64
sope49-mime-4.9-20191218_1900.ns7.x86_64
sope49-sbjson-2.3.1-20191218_1900.ns7.x86_64
sope49-xml-4.9-20191218_1900.ns7.x86_64

**Comment by filippocarletti** [comment]
Please, use the new Cockpit server-manager interface to configure the backup, it will protect you from errors.
And I suggest reporting issues in the forum (https://community.nethserver.org/) where you will find some help.

**Comment by khuyenht** [comment]
Hi filippocarletti,
Thank for your quick reply, 3 weeks ago i used Cockpit server-manager to create backup data restic job name: backup-daily-restic, backup job was working well in 2 weeks.
backup job failed on 23/Apr/2020 with 
below is log file.
Backup: daily-backup-restic
Backup started at 2020-04-23 23:13:26
Pre backup scripts status: SUCCESS
Fatal: create repository at /mnt/backup-daily-backup-restic failed: config file already exists

Fatal: wrong password or no key found
Backup failed
Action 'backup-data-restic daily-backup-restic': FAIL
Backup status: FAIL
I am learning Nethserver, cloud you please explain why backup failed.
Thank you so much

**Comment by filippocarletti** [comment]
So this is not a bug, but a problem on your side, maybe a disk failure.
Please, again, write to our [community forum](https://community.nethserver.org/) where the support team could help you discover the problem.
Thank you.
