### ISSUE TITLE
Backport security fix for Squid

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#6179]
Rebase NethServer Squid package on latest from upstream.

Security advisory: https://access.redhat.com/errata/RHSA-2020:2040

**Comment by gsanchietti** [comment]
In nethserver-testing:
- squid-3.5.20-9991.ns7.x86_64.rpm
- squid-debuginfo-3.5.20-9991.ns7.x86_64.rpm
- squid-migration-script-3.5.20-9991.ns7.x86_64.rpm
- squid-sysvinit-3.5.20-9991.ns7.x86_64.rpm

**Comment by gsanchietti** [comment]
**Test case 1**
- On a clean machine, install `nethserver-squid` package
- Configure the proxy (manual and authenticated)
- Check the proxy is started and it's worling

**Test case 2**
- Update an existing machine where the proxy has been already configured
- Check the proxy is still working after the update

**Comment by mamengoni** [comment]
Test Case 1

Tested and verified

Test case 2

Tested and verified

**Comment by gsanchietti** [comment]
Released in nethserver-updates:
- squid-3.5.20-9991.ns7.x86_64.rpm
- squid-debuginfo-3.5.20-9991.ns7.x86_64.rpm
- squid-migration-script-3.5.20-9991.ns7.x86_64.rpm
- squid-sysvinit-3.5.20-9991.ns7.x86_64.rpm
