### ISSUE TITLE
Missing ejabberd DH (Diffie-Hellman) 2048 bit

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#6216]
@DavidePrincipi, @stephdl: /!\ It is missing for ejabberd (C2Sx2/S2S/HTTPSx2)

- https://github.com/NethServer/nethserver-ejabberd/blob/master/root/etc/e-smith/templates/etc/ejabberd/ejabberd.yml/30MacrosXXXXX

define_macro:
```
  'CERTFILE': "/etc/ejabberd/ejabberd.pem"
  'TLSOPTS': XXX
  'CIPHERS': XXX
  'DHFILE': "/etc/ejabberd/dhparams.pem"
```

- https://github.com/NethServer/nethserver-ejabberd/blob/master/root/etc/e-smith/templates/etc/ejabberd/ejabberd.yml/40Listen
-> 5222
```
    protocol_options: 'TLSOPTS'
    ciphers: 'CIPHERS'
    dhfile: 'DHFILE'
```

-> 5223
```
    protocol_options: 'TLSOPTS'
    ciphers: 'CIPHERS'
    dhfile: 'DHFILE'
```
-> 5280
```
    protocol_options: 'TLSOPTS'
    ciphers: 'CIPHERS'
    dhfile: 'DHFILE'
```

-> 5269
```
    protocol_options: 'TLSOPTS'
    ciphers: 'CIPHERS'
    dhfile: 'DHFILE'
```

-> 5443
```
    protocol_options: 'TLSOPTS'
    ciphers: 'CIPHERS'
    dhfile: 'DHFILE'
```

**Comment by gsanchietti** [comment]
Thank you for reporting, but, as we already stated many times, we are not going to change nor upgrade ejabberd unless security flaws have been found.

Also, the right place to raise feature requests is https://community.nethserver.org. After discussion, a new feature request can be opened here.
So please, open a feature request inside the community forum. If more users are requesting such feature we will further evaluating it.

**Comment by Neustradamus** [comment]
@gsanchietti, @stephdl: I am sorry but it is not a new request, it is only linked to:
- https://github.com/NethServer/nethserver-mail/pull/203

**Comment by stephdl** [comment]
testing the port 5223 we can see that we use a DH group of 2048 bits, the reason for postfix is that we used a default group of 1024

```
 Testing robust forward secrecy (FS) -- omitting Null Authentication/Encryption, 3DES, RC4 

 FS is offered (OK)           ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-SHA256
                              ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-SHA256 
 Elliptic curves offered:     prime256v1 
 DH group offered:            RFC5114/2048-bit DSA group with 256-bit prime order subgroup (2048 bits)
```
Long story short but @gsanchietti got reason to close it

**Comment by Neustradamus** [comment]
@stephdl: All specified ports are ok?

**Comment by stephdl** [comment]
please test and report 

https://wiki.nethserver.org/doku.php?id=testing_tls_ssl_encryption&s[]=testssl#testsslsh
