### ISSUE TITLE
Asterisk 13.36.0 (2020-09-03)

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#6292]
After 13.35.0: https://github.com/NethServer/dev/issues/6260

Version 13.36.0 since 2020-09-03:
- https://downloads.asterisk.org/pub/telephony/asterisk/ChangeLog-13-current

Source:
- https://www.asterisk.org/downloads/asterisk/all-asterisk-versions/

Plan to update.

Thanks in advance.

**Comment by gsanchietti** [comment]
Version 13.35 was released few days ago, and in 13.36 there are no relevant changes.

Since the validation process can lasts several days, we are going to stick to 13.35 for a little while.
