### ISSUE TITLE
Upgrade to Rspamd 2.5

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#6322]
We are currently running Rspamd 2.2 and 2.6 is out.

**Proposed solution**

As we already tested 2.5 in depth, let's roll out it with NS 7.9.

**Alternative solutions**

Start testing 2.6 now

**Comment by stephdl** [comment]
> Start testing 2.6 now

I think we could have several changes, lets go to 2.5 which works pretty well

https://rspamd.com/announce/2020/09/30/rspamd-2.6.html

**Comment by DavidePrincipi** [comment]
In nethserver-updates 7.9.2009

http://packages.nethserver.org/nethserver/7.9.2009/updates/x86_64/Packages/rspamd-2.5-156.x86_64.rpm

**Comment by stephdl** [comment]
QA

On a 7.9 system, the rspamd is up with all the associated services (olefy, clamd@rspamd,redis-rspamd).

The email are filtered inside the email logs

set verified

**Comment by DavidePrincipi** [comment]
Released: the RPM is already under 7.9.2009 updates
