### ISSUE TITLE
PHP SCL: include_path uses the default path

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6371]
**Steps to reproduce**

- Install nethserver-horde
- install nethserver-rh-php73-php-fpm
- enable horde to use rh-php73 in the apache configuration `/etc/httpd/conf.d/php-horde-horde.conf`

      <FilesMatch .php$>
         SetHandler "proxy:fcgi://127.0.0.1:9003"
      </FilesMatch>
- restart httpd
- you have a blank web page at https://url/horde
- you can find in log ` /var/opt/rh/rh-php73/log/php-fpm/www-error.log`

```
[18-Dec-2020 15:14:00 UTC] PHP Warning:  require_once(Horde/Autoloader/Default.php): failed to open stream: No such file or directory in /usr/share/horde/lib/core.php on line 49
[18-Dec-2020 15:14:00 UTC] PHP Fatal error:  require_once(): Failed opening required 'Horde/Autoloader/Default.php' (include_path='/usr/share/horde/lib:.:/opt/rh/rh-php73/root/usr/share/pear:/opt/rh/rh-php73/root/usr/share/php') in /usr/share/horde/lib/core.php on line 49
```
- as a side not if I install my module nethserver-php-scl it works out of the box with php73, just by adjusting the port to `9073`

**Expected behavior**

I expect that horde uses rh-PHP73 without errors, it is not an incompatibility but a pear library not find in the path of the software collection `/opt/rh/rh-php73/root/usr/share/pear:/opt/rh/rh-php73/root/usr/share/php`. The pear Horde is in the path `/usr/share /pear` and obviously it cannot be found.

**Actual behavior**

The web page of horde is blank, to fix it we have to set the path of the pear library to the original path 
- /usr/share/pear

Inside my original module nethserver-php-scl I add a custom path inside the php.ini, here we have to create a file `/etc/opt/rh/rh-php73/php.d/10-php.ini` that we could set at a noreplace file in the rpm spec 

`include_path                           = ".:/opt/remi/php73/root/usr/share/pear:/opt/remi/php73/root/usr/share/php:/usr/share/pear"`

in some reading I can see that other add also the path `/usr/share/php` also, I did not know if it is needed, I honestly do not use it.

I would like to add to all php SCL version the `/etc/opt/r*/*php*/php.d/10-php.ini` to modify the path, as a side note this file could help us to add in the future other values to the php.ini
**Components**

nethserver-rh-php7{2,3}-php-fpm
nethserver-remi-php80-php-fpm

**See also**

https://community.nethserver.org/t/horde-issues-before-to-release/17141/11

----

thank @mrmarkuz

**Comment by gsanchietti** [comment]
It seems we agreed on soft approach: https://community.nethserver.org/t/horde-issues-before-to-release/17141/17?u=giacomo

I'm willing to close this issue as invalid.

**Comment by stephdl** [comment]
yes we decided to not fix at the core level, at least until another bug is coming or blocking. For those who want to  fix the bug itself it is trivial to drop a configuration file themselve 

Just as a side note I fixed it in my SCL module

> Inside my original module nethserver-php-scl I add a custom path inside the php.ini, here we have to create a file /etc/opt/rh/rh-php73/php.d/10-php.ini that we could set at a noreplace file in the rpm spec

For now won't fix

**Comment by gsanchietti** [comment]
WONTFIX
