### ISSUE TITLE
Fail2Ban, unable to unban IPs - IPs are not listed

### ISSUE THREAD

**Issue by Flying--Dutchman** [NethServer/dev#6381]
**Steps to reproduce**

- Install and activate Fail2Ban

**Expected behavior**

List banned IPs on "unban" page.

**Actual behavior**

IPs are not listed., only a message appears "You have no banned IPs".
On the Dashboard it says that there are 15 banned ips.

Also forced a ban with my mobile phone, got banned but it was not listed.

**Components**
- NethServer 7.9.2009
- Fail2Ban 1.5.7
- Antivirus 1.5.1
- Bandwidth monitor 3.1.1
- Firewall 3.13.1
- IPS 2.3.2
- Report 1.0.2
- Threat shield 1.1.4

**See also**
Dashboard:
![image](https://user-images.githubusercontent.com/9158539/103560549-3b410d00-4eb8-11eb-903b-03481fb7da79.png)

Unban page:
![image](https://user-images.githubusercontent.com/9158539/103560582-46943880-4eb8-11eb-8473-9cc1d26ea206.png)

**Comment by gsanchietti** [comment]
The dashboard displays the total number of banned IP, it contains historical data.

From command line, you can see the list of banned IPs using: `fail2ban-listban`.
If such command reports banned IPs which are not present inside the "Unban" page, it's a bug.

On my firewall, this is an extract of the above command:
```
...
List of all banned IP: 
81.161.63.100
81.161.63.253
205.185.115.183
```

The same IP's are visible also inside the UI.

I'm going to close this issue as invalid.
Please open a thread inside https://community.nethserver.org/ for further discussion.
