### ISSUE TITLE
ejabberd: 5223 port must be optional but enabled by default to keep compatibility with old machines

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#6410]
A long time ago, I have done PRs, already talked.

Like S2S 5269 port is optional.

5223 port must be same but enabled by default to keep compatibility with old machines.

**Comment by stephdl** [comment]
How a port/protocol  must be optional but enabled by default, for now `invalid`

**Comment by Neustradamus** [comment]
like S2S, the option is in Cockpit.

5223 is optionnal, but fir compatibility with old NethServer, keep enable.
one click to disable it in Cockpit.

Already talked on community.
