### ISSUE TITLE
ejabberd: Option to enable/disable MQTT (disabled by default)

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#6411]
This MQTT option is missing.

Can you add the option to enable/disable MQTT (disabled by default).

Source:
- https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L71

**Comment by stephdl** [comment]
This is a new feature request we use to talk on it on the forum community.nethserver.org before to raise a github issue, for now let close it

**Comment by Neustradamus** [comment]
Already talked on community some months ago

**Comment by stephdl** [comment]
in a perfect world we should have no rules, but we are just humans and we need rules.
