### ISSUE TITLE
ejabberd: Audio/Video calls

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#6412]
It is possible to add option for Audio/Video calls:
- https://www.process-one.net/blog/how-to-set-up-ejabberd-video-voice-calling/
- https://docs.ejabberd.im/admin/configuration/modules/#mod-stun-disco
- https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L61

**Comment by stephdl** [comment]
This is a new feature request we use to talk on it on the forum community.nethserver.org before to raise a github issue, for now let close it

**Comment by Neustradamus** [comment]
Already talked on community some months ago
