### ISSUE TITLE
ejabberd: disable broken "digest-md5" hash in configuration to be more secure

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#6413]
In ejabberd, to be more secure, it is needed to add:
`disable_sasl_mechanisms: "digest-md5"`
- https://docs.ejabberd.im/admin/configuration/toplevel/#disable-sasl-mechanisms

**Comment by stephdl** [comment]
This is a new feature request we use to talk on it on the forum community.nethserver.org before to raise a github issue, for now let close it
