### ISSUE TITLE
ejabberd: Add options to select/change different ports than default 5280/5443 + feature links

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#6414]
Add options to select/change the default 5280 and 5443 ports + feature links

Examples:
- People want to have /upload feature with XXXXX port instead of the default 5443
- People want to have /api feature with XXXXX port instead of the default 5280 (in NethServer) | 5443 (by default in ejabberd.yml.example)
- People want to have "web" /admin feature with XXXXX port instead of the default 5280 (in NethServer) | 5280 (by default in ejabberd.yml.example) and 5443 (by default in ejabberd.yml.example)
- People want to have /bosh feature with XXXXX port instead of the default 5280 (in NethServer) | 5443 (by default in ejabberd.yml.example)
- People want to have /websocket (ws in ejabberd.yml.example) feature with XXXXX port instead of the default 5280 (in NethServer) | 5443 (by default in ejabberd.yml.example)

The CAPTCHA feature is missing, can be used by MUC Rooms.
- /captcha: ejabberd_captcha

ejabberd.yml parts from NethServer: https://github.com/NethServer/nethserver-ejabberd/tree/master/root/etc/e-smith/templates/etc/ejabberd/ejabberd.yml

ejabberd.yml.example:
- https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L42

**Comment by stephdl** [comment]
This is a new feature request we use to talk on it on the forum community.nethserver.org before to raise a github issue, for now let close it
