### ISSUE TITLE
Improvements for Nethserver-collabora

### ISSUE THREAD

**Issue by markVnl** [NethServer/dev#6437]
During the fix for #6426 a few other issues where disclosed and users experienced breakages on updates.
Nethserver's user experience of one-click installation installation is not provided by the packages as is..

Hence this community effort to give nethserver-collabora a bit of care.

**The objective are:**

- Improve stability on updates in non interactive shells.
- If the NS-server you install nethserver-collabora on has nethserver-nextcloud installed and is the DNS-server: it should work out-off the box on virtual/wopi host `collabora.server-domain`.
- If a loolwsd VirtualHost prop is set (custom virtual host) it respects this.
- Redirect `http > https` on virtualhost except for `acme http-01 challenge` 
- If the virtual/wopi host does not have a valid cert and nethserver-nextcloud is installed on the same server disable certificate verification
- Enable certificate verification on certifate-update event if the cert is valid.
- Update documentation in README/documentation/wiki :
  -  Reflect the changes made about what the package does.
  -  Provide documentation to include exception in web-browser if cert is invalid.
  -  Provide documentation to set `AllowWopiHost` if Nextcloud runs on an other instance.
- Update CODE-brand, loolwsd, collaboraoffice6.x

**See also**

https://community.nethserver.org/t/improvements-for-nethserver-collabora/17725

tk @syntaxerrormmm , @mrmarkuz , @mmccarn and @stephdl

**Comment by stephdl** [comment]
Still waiting this, please ping me for help

**Comment by gsanchietti** [comment]
This is issue is stale.
Can we do a release with what has been currently implemented?

**Comment by stephdl** [comment]
Will check....I hope you are safe @markVnl

**Comment by stephdl** [comment]
Closed waiting the Input of the developer
