### ISSUE TITLE
Janus-Gateway: upgrade to 0.11.2 (2789365)

### ISSUE THREAD

**Issue by alepolidori** [NethServer/dev#6504]
**Description**

Current version to be released is 0.11.2 (meetecho commit 2789365)

**Additional context**

https://github.com/meetecho/janus-gateway

**Involved packages**

- `janus-gateway`
- `nethserver-janus`

**Comment by gsanchietti** [comment]
This issue is stale.
If we are not going to this release, we can close it.

**Comment by gsanchietti** [comment]
Delayed for now.
