### ISSUE TITLE
ldapservice account has not "isCriticalSystemObject=TRUE"

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#6547]
The ldapservice account has not "isCriticalSystemObject=TRUE", can you add it at account creation and to solve this bug in current state?

Thanks in advance.

Forum: https://community.nethserver.org/t/how-to-add-at-ldapservice-account-at-creation-iscriticalsystemobject-true/18653

**Comment by gsanchietti** [comment]
There is no need to add such option.
See community thread for more info.

**Comment by Neustradamus** [comment]
@gsanchietti: Solution, can you create a test system?

Add here:
- https://github.com/NethServer/nethserver-dc/blob/5b65852a5835527a976566d5be0d55f63225ef27/root/etc/e-smith/events/actions/nethserver-dc-createldapservice#L72 1

```
-
replace: "isCriticalSystemObject"
isCriticalSystemObject: TRUE
-
replace: "showInAdvancedViewOnly"
showInAdvancedViewOnly: TRUE
```

OR
```
-
add: "isCriticalSystemObject"
isCriticalSystemObject: TRUE
-
add: "showInAdvancedViewOnly"
showInAdvancedViewOnly: TRUE
```
