### ISSUE TITLE
Not all Let's encrypt certificates are renewed automatically

### ISSUE THREAD

**Issue by chaerle** [NethServer/dev#6548]
**Problem**:
Currently NS only updates certificates for domains listed in “config getprop pki LetsEncryptDomains”. However it seems the domains listed there will be automatically updated to the lasted Let's encryt certificate, so that only the last one will be automatically updated. 

**Expected**:
All Lets' encrypt certificates should be prolonged. 
Remove the 
https://docs.nethserver.org/projects/nethserver-devel/en/latest/nethserver-letsencrypt.html

**Solution**:
1) Replace the whoe code by a run:
certbot renew --post-hook “/sbin/e-smith/signal-event certificate-update”

2) Remove unused config values form code and documentaiton:
LetsEncryptRenewDays: not used currently but documented
LetsEncryptDomains: not used any more after change

**Diskussion**:
https://community.nethserver.org/t/lets-encrypt-renewal-the-105th/18197/11
https://community.nethserver.org/t/lets-encrypt-did-not-update-automatically/18669/7

**Comment by chaerle** [comment]
The problem ist NOT solved by just removing the documenation!

**Comment by gsanchietti** [comment]
I removed the obsolete documentation: the implementation has been moved from `nethserver-letsencrypt` package to `nethserver-base` one. 
Sorry, I forgot to merge the old doc with the new one: https://github.com/NethServer/dev/commit/ffa4c8a9a4cb4a00fc63c77a3e15961601b516e2

The updated do is available here: https://docs.nethserver.org/projects/nethserver-devel/en/latest/certificate_management.html#let-s-encrypt
