### ISSUE TITLE
Email: warn the user before  his email box is full 

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6615]
When you set quota to a email box, the email are refused by the server when the mailbox is full, the user is not warned before the sender receive that his email cannot be delivery.

**Proposed solution**

I propose to warn the user by delivering an email before the email box is full, with a body like :  you email box is full at x%
 
**Alternative solutions**

do nothing

----

thank @lucagasparini

**Comment by gsanchietti** [comment]
Proposed implementation lacks some features:
- the notification should not be enabled by default
- the notification mail should support internationalization, not all users are English speakers
- the notification could create a loop (see Dovecot doc: https://doc.dovecot.org/configuration_manual/quota/#quota-warning-scripts)

We are going to close this implementation and create new widget for the report which displays the list of users with high quota usage.
