### ISSUE TITLE
Openvpn RW: wrong label "Valid" even though the user certificate is expired

### ISSUE THREAD

**Issue by cotosso** [NethServer/dev#6688]
In the OpenVPN RW section if a user account is expired but the certificate has not been revoked, the label near the expiration date show always the "Valid" state, this could lead a sysadmin to think that the account is still working (but it's not).
The expiration date is always correctly showed.

**Steps to reproduce**

- configure openvpn rw server with certificate autentication and enable it
- create an account that will expire very soon 
You can create an acccount that expire in 1 day pasting this code in the terminal (user:  test-xuser, validity 1 day)  

```
echo '{"action":"create-account","type":"vpn","name":"test-xuser","certEOL":1,"OpenVpnIp":"","VPNRemoteNetmask":"","VPNRemoteNetwork":""}' | /usr/bin/setsid /usr/bin/sudo /usr/libexec/nethserver/api/nethserver-vpn-ui/openvpn-rw/create | jq
```
it is also possible to change the server date and create an account in the past.

**Expected behavior**

After the expiration date it isn't possible  to connect and the label shows "expired" value

**Actual behavior**
After the expiration date it isn't possible  to connect and the label still shows "Valid" value

![image](https://user-images.githubusercontent.com/7226896/179998824-91368111-9a3e-4d37-9e69-58e4cbb6c336.png)

The label's value in the UI seems to be taken from certindex, there is a line for every account and its value is always "V"  if not revoked

```
[root@srv ~]# cat /var/lib/nethserver/certs/certindex
.
.
.
V	220711161121Z		08	unknown	/C=--/ST=SomeState/L=XXX/O=YYY/OU=ZZZ/CN=test-expiration/emailAddress=admin@srv
```
 

**Components**

NethServer release 7.9.2009 (final)
openvpn-2.4.12-1.el7.x86_64
nethserver-openvpn-1.15.0-1.ns7.noarch

**Comment by gsanchietti** [comment]
I agree the UI is not clear on this. Still, we have to relay on flags inside the CRL.
As an alternative we could try to parse each certificate, match it against the CA and see if the whole chain is valid.
I think rewriting this part can take a long time and it's prone to error.

Also bear in mind that even the certificate is valid, the connection could fail for many other reasons.

In the end, I'd keep the current implementation.
Eventually we could extend the current documentation with a note.

**Comment by gsanchietti** [comment]
I'm closing this for now.
We will evaluate a better UI for the next release.
