### ISSUE TITLE
FreePBX 14 EOL

### ISSUE THREAD

**Issue by pcxlan** [NethServer/dev#6723]
EOL Notice for FreePBX 13 and 14

**Proposed solution**

Upgrade to 15 or 16

**Alternative solutions**

Do nothing

**See also**

- https://community.nethserver.org/t/eol-of-freepbx-13-and-14/20945

- https://www.freepbx.org/eol-notice-for-freepbx-13-and-14/

**Comment by Stell0** [comment]
We are evaluating if it's feasible to update current version or it is better to just focus on Nethserver 8 version.
Any comment/opinion/help is appreciated.

**Comment by Stell0** [comment]
Updating to FreePBX 15 following the instructions on the [FreePBX wiki](https://wiki.freepbx.org/display/FOP/Upgrade+to+FreePBX+15) works almost fine, you just need to install two modules missing by default (filestore and backup). Therefore, we are not updating packages nor provide any automatic updates right now, focusing on NethServer 8 development.
