### ISSUE TITLE
nextcloud 26.0.1

### ISSUE THREAD

**Issue by jgelauff** [NethServer/dev#6743]
https://github.com/NethServer/nethserver-nextcloud/pull/154

nextcloud 25.0.6 and 26.0.1 are available maybe it is time to swith to 26
https://help.nextcloud.com/t/patch-releases-26-0-1-25-0-6-and-last-24-release-24-0-12/160569

**Comment by gsanchietti** [comment]
I'm not sure.
Theu usually breaks things for a couple of minors.
Maybe is it better to wait 26.0.2 or 26.0.3?

What do you think?
/cc @DavidePrincipi @nrauso

**Comment by nrauso** [comment]
It's a good idea to wait for the release of a couple of minors

**Comment by jgelauff** [comment]
i understand to wait, but i think then we have to go for 25.0.6 to be secure

**Comment by gsanchietti** [comment]
Let's wait a bit more!
