### ISSUE TITLE
Upgrade nextcloud to 26.0.2

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6751]
as per the topic, I upgrade nextcloud to 26.0.1like in NS8 , the version 26.0.2 is not yet available in the dockerhub

https://github.com/NethServer/nethserver-nextcloud/pull/157

- test case 1
first install

- test case 2
upgrade from nc25

**Comment by stephdl** [comment]
we need to test http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/nethserver-nextcloud-1.21.4-1.4.g138b7d2.ns7.noarch.rpm

**Comment by gsanchietti** [comment]
We can prepare it for the release.
I'm going to wait one or two days if someone else what to try it (maybe @jgelauff?).

**Comment by jgelauff** [comment]
i already did some testing today with upgrade from 25, my testmachine went well, my production machine has problems, serving blank pages due to php fatal error (i'm investigation the error)

**Comment by gsanchietti** [comment]
Try to disable extra application, usually the error is there

**Comment by jgelauff** [comment]
> Try to disable extra application, usually the error is there

yes i have done that, i'm litte bit lost. i have create a new vrtual host where i managed to install nextcloud 26.0.2 and it is working so the webserver, mysql and php are oke. but i can't get the same directory tree get working in de /usr/share/nextcloud dir. i can you nextcloud for the moment .
