### ISSUE TITLE
Roundcube 1.6.5 and 1.5.6

### ISSUE THREAD

**Issue by Neustradamus** [NethServer/dev#6770]
https://roundcube.net/news/2023/11/05/security-updates-1.6.5-and-1.5.6

**Comment by stephdl** [comment]
Please when you request for a bug, could fill the bug template, your issue could not help us to understand what is occuring.

**Comment by Neustradamus** [comment]
Done :)

**Comment by Neustradamus** [comment]
Dear @NethServer team,

An important information about Roundcube and NextCloud:
- https://nextcloud.com/blog/open-source-email-pioneer-roundcube-comes-aboard-nextcloud/
- https://nextcloud.com/blog/roundcubes-future-at-nextcloud-an-interview-with-the-founders/
