### ISSUE TITLE
Upgrade nethserver-roundcubemail-next to  1.6.5

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6771]
**Steps to reproduce**

- We have a security update in the branch 1.6.x
- upgrade to 1.6.5 breaks the smtp
- from an upgrade with larry skin that is the default since ages to 1.6.5 breaks the template because larry is not bundled (default is elastic with 1.6.x) 

**Expected behavior**

- I expect to have the last version
- I expect to be able to send email with 1.6.5
- I expect to have larry without doing anything but with the choice to switch to elastic

```
config setprop roundcubemail skin elastic
signal-event nethserver-roundcubemail-next-update

```
**Actual behavior**
I am stick at the version 1.5.5

install nethserver-roundcubemail-next
upgrade to testing version : 
`yum install http://packages.nethserver.org/nethserver/7.9.2009/autobuild/x86_64/Packages/nethserver-roundcubemail-next-1.5.6-1.2.pr9.g4c454e5.ns7.noarch.rpm`

verify the version is fully workable just after the installation

sent email
receive email
create addressbooks

**Components**

nethserver-roundcubemail-next

**See also**

https://community.nethserver.org/t/when-are-we-going-to-see-about-updating-for-this-roundcube-0-day/22350

----

thank fasttech

**Comment by mrmarkuz** [comment]
The upgrade worked as expected in a test VM.

Mail send/receive OK
Create groups OK
Create contacts OK

**Comment by stephdl** [comment]
closed released as http://packages.nethserver.org/nethserver/7.9.2009/updates/x86_64/Packages/nethserver-roundcubemail-next-1.5.7-1.ns7.noarch.rpm
