### ISSUE TITLE
Nextcloud 27.1.3

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6772]
Update Nextcloud release to 27.1.3

[Requirements](https://docs.nextcloud.com/server/27/admin_manual/installation/system_requirements.html) are satisfied.

Nextcloud 27 should be the latest major release for NS7 since it's [EOL on June 2024](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule#currently-maintained-versions).
Also Nextcloud 28 will require PHP 8.1 which is not currently available on NS7.

Changelog:
https://nextcloud.com/it/changelog/#latest27

**Comment by stephdl** [comment]
Test case 1

- Install on a clean machine with OpenLDAP or AD
Check everything works as expected
Test case 2

- Update an existing machine with OpenLDAP or AD
Check everything works as expected

**Comment by stephdl** [comment]
the rpm to test : http://packages.nethserver.org/nethserver/7/testing/x86_64/Packages/nethserver-nextcloud-1.22.1-1.2.g119ba14.ns7.noarch.rpm

**Comment by lucagasparini** [comment]
**Test case 1: OK**
Nextcloud installs and works as expected with both OpenLDAP and AD

**Test case 2: OK**
Nextcloud upgrades from the previous version (27.0.1) and works as expected with both OpenLDAP and AD

**Comment by stephdl** [comment]
released as nethserver-nextcloud-1.22.2-1.ns7.noarch.rpm

http://packages.nethserver.org/nethserver/7.9.2009/updates/x86_64/Packages/nethserver-nextcloud-1.22.2-1.ns7.noarch.rpm
