### ISSUE TITLE
Webtop cannot connect to chat server (ejabberd)

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6780]
**Steps to reproduce**

- Install ["webtop","ejabberd","mail"]
- set and configure ejabberd with connected client
- set and configure email
- set and configure webtop
- enable chat client for all users 

**Expected behavior**

I expect webtop can connect to ejabberd

**Actual behavior**

Webtop cannot connect to ejabberd, we have a an error displayed after the login

if we manually set the host and the port inside the pgsql of webtop we could have it workable 

```
Pannello admin di WebTop -> Properties (system) -> aggiunta di queste due chiavi:
Add -> com.sonicle.webtop.core -> Key=xmpp.host -> Value= <server chat> (il default è localhost)

Add -> com.sonicle.webtop.core -> Key=xmpp.port  -> Value= <porta server chat> (il default è 5222)
```

however to make it workable the mail domain used by webtop for  instance domain.com (`mail: foo@domain.com`) must match the virtualhost of ejabberd domain.com (`xmpp: foo@domain.com`)

**Components**

ns8-mail
ns8-webtop
ns8-ejabberd

**Comment by stephdl** [comment]
test case 1 

we need to install first ejabberd latest 
- install : add-module ghcr.io/nethserver/ejabberd:latest
- configure ejabberd with a domain name : `foo.com`

- install user account provider
- install ns8-mail and configure the first domain as `foo.com`

then we need to install webtop
- install latest : add-module ghcr.io/nethserver/webtop:latest

- you need to configure webtop with a FQDN domain name of your choice
- you need to configure the LDAP domain of your choice
- you need to configure the MAIL domain : `foo.com`

once the MAIL domain is set you can see that an ejabberd instance is available if the `ejabberd domain === webtop mail domain` : `foo.com === foo.com` 
- set the ejabberd instance

in webtop
- enable chat for user in webtop admin user page
- go to a webtop user you must be able to use the chat

to make it workable we have a limitation, the ejabberd login must be the email address so `webtop MAIL domain === First MAIL domain === FQDN Ejabberd === foo.com`

inside the admin page you can see that the xmpp.port=5222 and xmpp.host=local.ip.ejabberd.node

test case 2

once the ejabberd instance is linked to the webtop instance, a saved change inside Ejabberd must configure and restart ejabberd

**Comment by lucagasparini** [comment]
Test case 1: **OK**
Test case 2: **OK**

**Comment by Amygos** [comment]
Released: https://github.com/NethServer/ns8-webtop/releases/tag/1.0.9
