### ISSUE TITLE
Ejabberd: The button of the web admin page could have DNS issue

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6787]
**Steps to reproduce**

- Install NS8-ejabberd stable
- configure it
- open advanced menu 
- Enable the web administration page
- You have a Button page to use the Administration page

**Expected behavior**

I expect that the button can be used to use the Administration page

**Actual behavior**

The button takes the URL from the `hostname` property , and it can be wrong from a DNS point of view

**Components**

NS8-ejabberd

**Comment by lucagasparini** [comment]
QA is successfully passed :+1:
Just a note: the HTTP route must be created by configuring the mandatory path `/admin`

**Comment by stephdl** [comment]
QA
The button of webadmin page  is back, we want to test it workable

- Install the version add-module ghcr.io/nethserver/ejabberd:1.0.4-dev.4
- install an account provider
- configure ejabberd
- enable the switch of web admin page
- save and start ejaberd
- check the button is workable, you need to reach the admin page of ejabberd https://FQDN:5280/admin of the server

**Comment by lucagasparini** [comment]
QA test: **OK**
