### ISSUE TITLE
Understand Nextcloud internal user domain selection

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6806]
Nextcloud configuration form has a selector for the User domain. If no domain is selected (item `-`), the NC internal user database is used.

The UI is not clear enough: add a label, or the "ℹ tooltip" to better explain what's going on.

![Image](https://github.com/NethServer/dev/assets/2920838/cac2dbc0-704e-4cf4-a8d0-4efcef12d5c8)

----

[ns8 crash course]

**Comment by stephdl** [comment]
QA

We tried in that release to forbid  empty input strings, add better translation  to help the users

- install nextcloud and an account provider
add-module ghcr.io/nethserver/nextcloud:1.1.2-dev.2
- once installed press save, you must hit a validator against empty string for hostname and LDAP domain
- translations should help you better for the LDAP user domain (placeholder an tooltips) and for the hostname (translation)
- install ns8-collabora, configure ns8-collabora and save the form 
- go back to nextcloud settings and verify the tooltips and the placeholder of collabora can guide you to link the nextcloud session to collabora or not. 
- Choose the collabora server available and save the form, no errors

**Comment by nrauso** [comment]
Labels, tooltips and placeholders are clear and accurate.
Validators worked as expected.
The reference to Collabora into the Nextcloud settings page eased the configuration.

**Comment by stephdl** [comment]
can we release @DavidePrincipi

**Comment by stephdl** [comment]
released as 1.1.2
