### ISSUE TITLE
Spam emails are not deleted automatically

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6831]
**Steps to reproduce**

- install a NS8 mail server and spread the world with your personal email
- set to remove the spam automatically each X days
- wait to receive email tagged as spam by rspamd
 
**Expected behavior**

I expect that emails tagged as spam are deleted 

**Actual behavior**

The spam messages are not removed automatically, they stay in their mailbox

**Components**

ns8-mail

----

thank @lucagasparini alessio fattorini

**Comment by stephdl** [comment]
QA

on a real server with spam, upgrade mail to ghcr.io/nethserver/mail:1.3.2-dev.1 
- set in the mail > settings to expunge spam xDays
- wait xDays
- the spam must be expunged

**Comment by lucagasparini** [comment]
Test OK :+1:
Set automatic spam deletion after 7 days and waited the next day: old spam emails successfully deleted !!

**Comment by stephdl** [comment]
released as ghcr.io/nethserver/mail:1.3.2
