### ISSUE TITLE
The user domain count is zero in the restore cluster

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6834]
**Steps to reproduce**
- Install a ns8 server
- Install the ldap account provider and configure it 
- install mail server and configure it 
- configure the backup to a repository
- do the backup to the repository
- download the cluster backup tar.gz in the backup menu

on another server
- initiate the cluster
- do not transform as  leader but select the disaster recovery
- restore from the  cluster backup tar.gz 

**Expected behavior**

After we have loaded the cluster backup a new panel enumerate of what you are ready to restore in terms of domains, custom routes, custom certificate and backup repository

**Actual behavior**

The counter is missing the number of user domain, we should list the a number > than 0

![image](https://github.com/NethServer/dev/assets/3164851/da8e9de5-1817-4ca4-9826-e7e2cde461ce)

**Components**

core 2.3.0 https://github.com/NethServer/ns8-core/releases/tag/2.3.0

**Comment by stephdl** [comment]
QA

the test is to verify that the translation reflect that `Domains` gets a new translation `External user domains`

to verify you neext to test with ghcr.io/nethserver/core:2.5.0-dev.3

install a NS8 and backup it to a repo
download the cluster backup to make a disaster recovery
install a new NS8 and do a recover with the cluster backup
the translation `Domains` must be explicit to `External user domains`

**Comment by nrauso** [comment]
test case: **VERIFIED**

Now the label `External user domains`:
![steph](https://github.com/NethServer/dev/assets/16102909/dd26f8d0-f1d8-4d24-bfa3-b1c428cdeaff)

**Comment by stephdl** [comment]
issue verified, to be released with https://github.com/NethServer/dev/issues/6835
