### ISSUE TITLE
Mail clients error with empty domain list

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6837]
**Steps to reproduce**

on NS8
- Install an account provider
- Install a mail server
- configure mail server
- install webtop or sogo, or roundcubemail
- configure them to use the mail server

everything is OK

- in the mail server delete all domains

**Expected behavior**

I expect no errors in the get-configuration or get-defaults actions

**Actual behavior**

I have an error because the case where there is no domains in the mail server is not handled

```
api-cli run module/webtop2/get-defaults | jq
Warning: using user “cluster” credentials from the environment
Traceback (most recent call last):
File “/home/webtop2/.config/actions/get-defaults/20readconfig”, line 25, in
if kd[‘addusers’]:
~~^^^^^^^^^^^^
```
**Components**

ns8-webtop:1.0.11
ns8-roundcubemail:1.0.5
ns8-sogo:1.0.2

**See also**
https://community.nethserver.org/t/ns8-rc1-webtop-could-not-see-mailservers/22477/20?u=stephdl

----

thank savetec

**Comment by stephdl** [comment]
QA

We need to test ns8-roundcubemail and ns8-webtop to see if they have a warning when the mail server is misconfigured.

- install an account provider
- install a mail server
- configure it
- in the mail server got to `domains` and remove all domains

- install ns8-roundcubemail `add-module  ghcr.io/nethserver/roundcubemail:1.0.6-dev.2`
- install ns8-webtop add-module ghcr.io/nethserver/webtop/1.0.12-dev.1

When you go to the settings page of each module you must have a banner to explain that the mail server is misconfigured, the NScomBoBox must be empty and you cannot save the form

If you go back to the domains settings page of the mail server and you create again a new domain (you must add at least user from the user domain), then you must be able to configure each module

**Comment by stephdl** [comment]
QA

install an account provider
install maisl server from add-module ghcr.io/nethserver/mail:1.3.3-dev.2
Configure mail server
create several mail domain
create a backup repository 
backup the mail server to the repository (do not backup the account provider)
download the cluster backup

install a NS8 and do a disaster recovery (do not initiate the cluster)
give the cluster-backup
restore only the mail module

at the end we must have a mail server restoration fully workable without issues, check the mail domains of mail server

**Comment by nrauso** [comment]
test case: **VERIFIED**

Now both Webtop and Roundcube do not allow to save the config if there is no e-mail domain configured:
![webtop_no_domain](https://github.com/NethServer/dev/assets/16102909/3bca5fbe-bfea-41f3-9c70-9ed7f6ef802f)
![roundcubemail_no_domain](https://github.com/NethServer/dev/assets/16102909/9498341a-8fbd-4289-af7f-001644800467)

**Comment by stephdl** [comment]
released as 

docker pull ghcr.io/nethserver/webtop:1.0.12
docker pull ghcr.io/nethserver/roundcubemail:2.0.0
docker pull ghcr.io/nethserver/sogo:1.0.3
