### ISSUE TITLE
Traefik route with a space cannot be removed

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6839]
**Steps to reproduce**

 - on NS8 go to settings > http route
 - create a route with a space inside the `name` (the `instance` javascript object)
 - save the form
 - the route is well created 
 
**Expected behavior**

I expect the route can be removed

**Actual behavior**

The route cannot be removed anymore or edited, the options are grayed inside the user interface

We can see the route has been well created but with a space inside the file name

```
[root@R1-pve ~]# tree /home/traefik1/.config/state/configs/
/home/traefik1/.config/state/configs/
├── _api.yml
├── _api_server.yml
├── _default_cert.yml
├── _http2https.yml
├── certificate-R1-pve.rocky9-pve.org.yml
├── tooto 2.yml

```

inside the traefik route we can see that the route has been well created 

```
http:
  services:
    tooto 2:
      loadBalancer:
        servers:
        - url: http://1.2.3.4
  routers:
    tooto 2-http:
      rule: Host(`tytu.ot`)
      priority: '2'
      entryPoints: http,https
      service: tooto 2
    tooto 2-https:
      rule: Host(`tytu.ot`)
      priority: '2'
      entryPoints: http,https
      service: tooto 2
      tls:
        domains:
        - main: tytu.ot
```

**Components**

```
ghcr.io/nethserver/traefik:2.1.0
ghcr.io/nethserver/core:2.4.0
```

**Comment by stephdl** [comment]
QA

install `ghcr.io/nethserver/core:2.5.0-dev.5` and `ghcr.io/nethserver/traefik:2.1.1-dev.1`

Try to create an http route name  with non allowed characters (allowed characters are : `A-Za-z0-9 - _` 
you must have an error validation

**Comment by lucagasparini** [comment]
VERIFIED :+1:
The validator does not allow illegal characters in the route name:
![HTTP-routes](https://github.com/NethServer/dev/assets/11161326/c0a1b78e-3591-4f8b-9a3b-ba710533b936)

**Comment by stephdl** [comment]
released ghcr.io/nethserver/traefik:2.1.1
