### ISSUE TITLE
Add Imapsync configuration to backup

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6840]
**Proposed solution**

With ns8-imapsync we use two volumes that needs to be backuped, a documentation should be added to do custom scripts 

**Alternative solutions**

no backups at all, even if we do not store data, we could store configuration

**Components**

ghcr.io/nethserver/imapsync:1.0.0

**Comment by stephdl** [comment]
QA

test1 
- we want to test the backup of  of imapsync
- Install imapsync from dev `ghcr.io/nethserver/imapsync:1.0.1-dev.1`
- configure a repository backup
- drop files in /home/imapsync1/.config/state/{cron,imapsync}
- do the backup
- restore the backup by removing imasync1
- in the home folder of imapsync2 you have to find your files


test2

in /home/imapsync1/.config/state/{cron,imapsync} we need to test custom script
read the readme of imapsync
made imapsync custom cron script 
or a simple script cron.custom  (in /home/imapsync1/.config/state/cron) 
`* * * * * root /etc/imapsync/script.custom`
in do a script.custom (/home/imapsync1/.config/state/imapsync)
`echo "foo" >> /tmp/foo`

**Comment by lucagasparini** [comment]
test1: **OK**
test2: **OK**
test3: **OK**

**Comment by stephdl** [comment]
released as 1.0.1
