### ISSUE TITLE
Store MM relation of Ejabberd and user domains

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6842]
Proposed solution

With https://github.com/NethServer/dev/issues/6814 we have provided a way to show to the user inside the user-portal to what application his account can authenticate.

Now we are working on the ejabberd

Alternative solutions

do nothing

**Comment by stephdl** [comment]
QA

Install and configure two account provider (LDAP and SAMBA_AD)
Install ghcr.io/nethserver/ejabberd:1.0.5-dev.1
Configure ejabberd to use openldap
Go to the user-portal of LDAP and check that the user can see the Ejabberd in the applications list
Configure the ejabberd server to use samba AD
Go to the user-portal of LDAP and check that the user can see the Ejabberd in the applications list

**Comment by lucagasparini** [comment]
VERIFIED :+1:

**Comment by stephdl** [comment]
released ghcr.io/nethserver/ejabberd:1.0.5
