### ISSUE TITLE
Nextcloud does not create the route when moved to another node

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6843]
**Steps to reproduce**

- Install nextcloud and configure it
- move nextcloud to another node

**Expected behavior**

I expect a fully configured instance with its route created inside traefik

**Actual behavior**

the module is up but the route inside traefik is not created

**Components**

ghcr.io/nethserver/nextcloud:1.1.4

**Comment by stephdl** [comment]
QA

on NS8 you need two nodes in a cluster

- Install nextcloud and configure it from ghcr.io/nethserver/nextcloud:1.1.5-dev.1
- to be sure the the good version will be respected do 
` redis-cli hset cluster/override/modules nextcloud ghcr.io/nethserver/nextcloud:1.1.5-dev.1`
- move nextcloud to another node belong the cluster
- go to cluster-admin > settings > http routes 
- the route from the previous nextcloud module has been removed and you can see the new route to the new module

**Comment by nrauso** [comment]
Tested: **VERIFIED**
HTTP route is now correctly managed.

**Comment by stephdl** [comment]
released as ghcr.io/nethserver/nextcloud:1.1.5
