### ISSUE TITLE
Ejabberd restoration is broken

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6844]
**Steps to reproduce**
On NS8
- install and configure account provider
- install and configure ejabberd
- configure a backup recovery
- do a backup of ejabberd
- download the cluster-backup

On  a new machine, install NS8 but do a recover cluster and restore ejabberd

**Expected behavior**

I expect the restoration is well done

**Actual behavior**

The restoration is broken, it doesn't pass the json validation schema and the volume upload has not been backuped

**Components**

ghcr.io/nethserver/ejabberd:1.0.4

**Comment by nrauso** [comment]
test case: **VERIFIED**

**Comment by stephdl** [comment]
released ghcr.io/nethserver/ejabberd:1.0.5
