### ISSUE TITLE
Upgrade ns8-nextcloud to nextcloud 27.1.6

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6864]
**Steps to reproduce**

- try to migrate nextcloud from NS7 to NS8

**Expected behavior**

I expect a migration without issue

**Actual behavior**

Nextcloud cannot be migrated, the process hangs inside nethserver-ns7-migration and we can fin inside the log of NS8 

`/lib/base.php\"],\"function\":\"require_once\"}],\"File\":\"/var/www/html/lib/private/legacy/OC_Util.php\",\"Line\":1202,\"Hint\":\"Downgrading is not supported and is likely to cause unpredictable issues (from 27.1.6.2 to 27.1.3.2)\",\"CustomMessage\":\"--\"}","userAgent":"--","version":"27.1.6.2"}
`
The two versions differs, 27.1.6 on NS7 and 27.1.3 on NS8

**Components**

NS8-NEXTCLOUD 1.1.4

**Comment by stephdl** [comment]
QA

- Install NS8 from ghcr.io/nethserver/nextcloud:1.1.5-dev.2
- nextcloud must be UP and workable

Migrate nextcloud from ns7 to ns8 with issue

**Comment by nrauso** [comment]
test case 1: **VERIFIED**
upgrade worked smooth

test case 2: **VERIFIED**
module migration from NS7 to NS8 was successfully completed

**Comment by stephdl** [comment]
released as ghcr.io/nethserver/nextcloud:1.1.5
