### ISSUE TITLE
Roundcubemail: add LDAP addressbook

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6914]
When you configure roundcubemail, it is linked to a mail server bound to an LDAP, we could use this LDAP to populate a LDAP address book for roundcubemail

**Proposed solution**

Create the code to add a LDAP address book to roundcubemail 

**Alternative solutions**

do nothing

**See also**

https://community.nethserver.org/t/ns8-roundcube-e-mail-address-autocompletion-not-working/23427

----

thank mrmarkus

**Comment by stephdl** [comment]
QA

install two account providers (openldap & samba ad) and create users
install mail and configure to it 
create several domains inside mail (`foo.org` and `foo.com`)
Install ghcr.io/nethserver/roundcubemail:2.0.2-dev.1

1. configure roundcubemail to use the mail server with `foo.org` and go the LDAP address book to see user, the mail address must be with `user@foo.org`
2. configure roundcubemail to use the mail server with `foo.com` and go the LDAP address book to see user, the mail address must be with `user@foo.com`

3. change the user domain of the mail server (test the two userèdomain, ad and openldap) , once configured the user-panel must have the change propagated, roundcubemail must be listed as an application in the user-domain of the mail server. You will see roundcubemail restarted by the event

**Comment by mrmarkuz** [comment]
1. Works!
2. Works!
3. Works!

I tested internal Samba, OpenLDAP and external Samba that worked too.

**Comment by stephdl** [comment]
thanks a lot mate

**Comment by stephdl** [comment]
released as ghcr.io/nethserver/roundcubemail:2.0.2
