### ISSUE TITLE
DokuWiki admin user has no admin permissions when username is not admin/administrator

### ISSUE THREAD

**Issue by mrmarkuz** [NethServer/dev#6919]
**Steps to reproduce**

- Set internal authentication or LDAP
- Setup an admin username to something else than admin/administrator like localadmin

**Expected behavior**

localadmin has full admin permissions after login to DokuWiki

**Actual behavior**

localadmin just has common user permissions

**Components**

NS8 DokuWiki 1.0.3

**See also**

https://community.nethserver.org/t/dokuwiki-admin-user-has-no-admin-permissions-when-username-is-not-admin-administrator/23628

**Proposed fix**

Set `\$conf['superuser'] = '@admin,@domain\ admins';` in DokuWiki config to allow internal admins and domain admins by group

----

Thanks to Denis Pollini for finding the bug.

**Comment by stephdl** [comment]
QA

test case 1
test the admin from LDAP can access to administrative page 

test case 2
without ldap, test the admin can access to administrative page

**Comment by stephdl** [comment]
test 1 and test 2 verified
