### ISSUE TITLE
Incomplete display name in WebTop on NS8

### ISSUE THREAD

**Issue by lucagasparini** [NethServer/dev#6923]
**Steps to reproduce**

- on NS8 with OpenLDAP account provider create a user with 3 words separated by space in the display name:
![Domain-users-and-groups](https://github.com/NethServer/dev/assets/11161326/9040dc0a-dc7b-4ca3-aecf-11e6b4e10901)

- log in to webtop for the first time with this new user

**Expected behavior**

- the display name is imported completely into the webtop profile

**Actual behavior**

- the display name is imported incomplete, the first part is missing:
![WebTop-5-two-three-](https://github.com/NethServer/dev/assets/11161326/bead92a5-0691-4d8a-8928-f849a6f904cd)

I think the problem is caused by this value set with our provisioning:
![WebTop-5-Administrator-](https://github.com/NethServer/dev/assets/11161326/02b2cb21-fb5e-4d45-a835-2a0dd834d2d6)

which on NS8 should become: `displayName`

**Components**

ns8-webtop

**Comment by stephdl** [comment]
it is reproducible

**Comment by stephdl** [comment]
QA

test the case it not reproducible for openldap and samba AD, however it is true for first installation and only for users that have never login

**Comment by lucagasparini** [comment]
@stephdl trying to install returns this error:
```
 ~]# add-module ghcr.io/nethserver/webtop:1.0.17-testing.2
<7>podman-pull-missing ghcr.io/nethserver/webtop:1.0.17-testing.2
Trying to pull ghcr.io/nethserver/webtop:1.0.17-testing.2...
Error: initializing source docker://ghcr.io/nethserver/webtop:1.0.17-testing.2: reading manifest 1.0.17-testing.2 in ghcr.io/nethserver/webtop: manifest unknown
```

**Comment by stephdl** [comment]
it seems the build failed, I start it again
