### ISSUE TITLE
Allow LDAP access for Webserver app

### ISSUE THREAD

**Issue by mrmarkuz** [NethServer/dev#6928]
When installing a site using LDAP on the Webserver app, the ldapproxy isn't reachable. As a lot of web apps use LDAP we should allow it.

**Proposed solution**

Add `--network=slirp4netns:allow_host_loopback=true` to the webserver service to allow LDAP access.

**Alternative solutions**

Use the custom configuration as explained in the [community](https://community.nethserver.org/t/customize-container-systemd-service-file/23687/4?u=mrmarkuz)

**See also**

https://community.nethserver.org/t/customize-container-systemd-service-file/23687

----

Thanks to kovand for proposing this feature.

**Comment by stephdl** [comment]
won't fix for now, we can add it manually by a systemd service
