### ISSUE TITLE
Upgrade ejabberd to 24.02

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6931]
**Proposed solution**

Actually ejabberd is built with 23.10 I propose to upgrade to the latest version 24.02

**Alternative solutions**

do nothing

**Additional context**

we need to consider to test the migration from NS7 to NS8
first installation NS8 to 24.02
upgrade NS8 from 23.10 to 24.02

**Comment by stephdl** [comment]
QA


- test case 1 first install

install account provider, mail, webtop, ejabberd from  ghcr.io/nethserver/ejabberd:1.0.6-dev.1
enable in webtop to use ejabberd
send message with the chat of webtop to users
test you still can connect a xmpp client (gagim, pidgin...)

- test case 2 upgrade

install account provider, mail, webtop, ejabberd 
enable in webtop to use ejabberd
send message with the chat of webtop to users
upgrade ejabberd to ghcr.io/nethserver/ejabberd:1.0.6-dev.1
test the upgrade is not broken
test you still can connect a xmpp client (gagim, pidgin...)



- test case 3 migration

install nethserver-ejabberd with an account provider
create some messages with  xmpp clients
migrate the stack to NS8

**Comment by stephdl** [comment]
test case 1 OK
message are sent, no error in logs

test case OK
upgrade good, messages are sent from webtop and xmpp client 

test case 3 OK
migration is good, message sent from NS7 are available with NS8, we can continue to use ejabberd in NS8

**Comment by stephdl** [comment]
released pull ghcr.io/nethserver/ejabberd:1.0.6

**Comment by Neustradamus** [comment]
@stephdl: Good job!
