### ISSUE TITLE
nethsecurity-controller: invalid `config.env` after "Save" on cluster interface

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#6952]
**Steps to reproduce**

- install ns8-nethsecurity-controller
- go to cluster admin page to configure the module
- configure it
- press "Save"
- check `config.env` is valid, under `/home/nethsecurity-controller<MODULE_ID>/.config/state/config.env`
- press "Save" again

**Expected behavior**
- the file `config.env` under `/home/nethsecurity-controller<MODULE_ID>/.config/state/config.env` should be valid like the first configuration

**Actual behavior**

- the file `config.env` is corrupted. only `ADMIN_USER` env is set and the others variables is missing

**Components**

ns8-nethsecurity-controller:0.0.21

**Comment by edospadoni** [comment]
It seems like this action: https://github.com/NethServer/ns8-nethsecurity-controller/blob/main/imageroot/actions/configure-module/20configure#L109 always accepts `api_password` field from the UI request.

If the field does not exists in the request, the action leads to unexpected behavior and does not correctly create the `config.env` file.

On the second "Save", the field `api_password` is missing in the request.

**Comment by stephdl** [comment]
evidence

```
Jun 18 15:28:15 R3.rocky9-3.org agent@nethsecurity-controller1[1745]: Traceback (most recent call last):
Jun 18 15:28:15 R3.rocky9-3.org agent@nethsecurity-controller1[1745]:   File "/home/nethsecurity-controller1/.config/actions/configure-module/20configure", line 109, in <module>
Jun 18 15:28:15 R3.rocky9-3.org agent@nethsecurity-controller1[1745]:     env.write(f'ADMIN_PASSWORD={request["api_password"]}\n')
Jun 18 15:28:15 R3.rocky9-3.org agent@nethsecurity-controller1[1745]:                                 ~~~~~~~^^^^^^^^^^^^^^^^
Jun 18 15:28:15 R3.rocky9-3.org agent@nethsecurity-controller1[1745]: KeyError: 'api_password'
```

**Comment by stephdl** [comment]
QA

install ghcr.io/nethserver/nethsecurity-controller:0.0.22-dev.1

no expected errors when you configure the module several times

**Comment by edospadoni** [comment]
Verified. With `ghcr.io/nethserver/nethsecurity-controller:0.0.22-dev.2` no errors occurs after multiple saves. The `config.env` file is always valid

**Comment by stephdl** [comment]
released as ghcr.io/nethserver/nethsecurity-controller:0.0.22
