### ISSUE TITLE
nethsecurity-controller: improve configuration form

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#6953]
Improve the current form with these changes:

- make sure the user understands that the password can't be changed later from the main UI
- move retention options and controller name under an advanced section 

**See also**

Community discussion: https://community.nethserver.org/t/nethserver-controller-nethsecurity-glitch/23814

**Comment by stephdl** [comment]
QA

install ghcr.io/nethserver/nethsecurity-controller:0.0.22-dev.1

verify some steps 

- the information banner warn you to save the password
- the advanced menu is here to hide not important settings
- no expected errors when you configure the module

**Comment by gsanchietti** [comment]
Verified: the UI is now clear and works good

**Comment by stephdl** [comment]
released as ghcr.io/nethserver/nethsecurity-controller:0.0.22
