### ISSUE TITLE
Collabora: the password is saved in redis

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6969]
**Steps to reproduce**

- install collabora
- configure collabora
- the admin password is saved in redis due to the set_env

**Expected behavior**

I expect the password is not saved in redis that is public and can been read by any module

```
127.0.0.1:6379> hgetall module/collabora3/environment
 1) "TRAEFIK_HOST"
 2) "collabora3.rocky9-pve3.org"
 3) "CODE_IMAGE"
 4) "docker.io/collabora/code:24.04.2.1.1"
 5) "TCP_PORTS"
 6) "20012"
 7) "IMAGE_URL"
 8) "ghcr.io/nethserver/collabora:1.0.5"
 9) "MODULE_UUID"
10) "6827a18a-d9ea-4e85-8394-37adb0582614"
11) "IMAGE_ID"
12) "94d1dbe8c93bb55dac2213568c40dcbf6593e37b42691c4e904ab2f4f4df0f58"
13) "IMAGE_DIGEST"
14) "sha256:2152a2729aab5568820cc8264568b454945c6e1d81a798038429846899b346f9"
15) "MODULE_ID"
16) "collabora3"
17) "ADMIN_PASSWORD"
18) "Nethesis,1234"
19) "TCP_PORT"
20) "20012"
21) "NODE_ID"
22) "1"
23) "TRAEFIK_LETS_ENCRYPT"
24) "False"
25) "TRAEFIK_HTTP2HTTPS"
26) "False"
27) "IMAGE_REOPODIGEST"
28) "ghcr.io/nethserver/collabora@sha256:2152a2729aab5568820cc8264568b454945c6e1d81a798038429846899b346f9"
```

**Actual behavior**

the password is saved in redis with set_env

**Components**

collabora:1.0.5

**See also**

https://mattermost.nethesis.it/nethesis/pl/kttrwb6xdibt8mwznb611ehdfo

----

thank  @NethNick

**Comment by stephdl** [comment]
test direct install and upgrade, the password of the webadmin page must not  be visible anymore in the `~/.config/state/environment` but in a `~/.config/state/password.env`

1. first install
install collabora:1.0.6-dev.1
configure
verify the service is up and admin page is reachable
verify the password of the webadmin page is  inside `~/.config/state/password.env`

2. upgrade
install collabora:1.0.5
configure
verify the service is up and admin page is reachable
upgrade to collabora:1.0.6-dev.1
verify the service is up and admin page is reachable
verify the password of the webadmin page is  inside `~/.config/state/password.env` and not anymore in `~/.config/state/environment`

**Comment by nrauso** [comment]
test case 1: **VERIFIED**
test case 2: **VERIFIED**

**Comment by stephdl** [comment]
released as ghcr.io/nethserver/collabora:1.0.6
