### ISSUE TITLE
DNSMasq silently stops when dns toggle is enabled

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#6982]
The installation of dnsmasq if a module previously installed with a requirement on the tcp/53 or udp/53 is not possible, when you enable the dns feature of dnsmasq, the service stops silently, there is no check that the port 53 is already bound to another container.

**Steps to reproduce**

- install an account provider active directory
- configure the active directory
- install dnsmasq
- configure dnsmasq to an interface
- no issue so far
- enable the dns toggle to use the dns server feature of dnsmasq
- save, the service restart and fall in a failure state without warning, with this error in log

```
Aug 02 14:46:49 R1-pve.rocky9-pve.org systemd[1]: Started DNSmasq podman container.
Aug 02 14:46:49 R1-pve.rocky9-pve.org dnsmasq[14344]: 
Aug 02 14:46:49 R1-pve.rocky9-pve.org dnsmasq[14344]: dnsmasq: failed to create listening socket for port 53: Address already in use
Aug 02 14:46:49 R1-pve.rocky9-pve.org systemd[1]: libpod-fce765239026cc76c7574a45217720b14c2a4124025202ea32b55c094dc6f054.scope: Deactivated successfully.

```

**Expected behavior**

I expect the dns feature of dnsmasq is usable or at least we have an error if the dnsmasq fails to restart

**Actual behavior**

dnsmasq stop to work immediately because the port 53 is already used by another process (i.e. Samba DC) dnsmasq silently fails to start and remains stopped. 

The solution could be Implement a validator to see if port 53 is already used by another process: a validation error message explaining why it failed is required. 

As alternative, the UI could disable the DNS switch completely with a message that explains why.

Discussion: @nrauso (PVT) https://mattermost.nethesis.it/nethesis/pl/n77fixar37897eez8xximujj1r

**Components**

dnsmasq:1.0.2

----

thank @nrauso

**Comment by stephdl** [comment]
QA

install an account provider first like samba4
install ns8-dnsmasq version ghcr.io/nethserver/dnsmasq:1.0.3-dev.1
a validator should set to disabled the toggle of the DNS feature with a warning to explain

**Comment by nrauso** [comment]
test case: **VERIFIED**

Now a warning appears if the port 53 is already in use:
![dnsmasq](https://github.com/user-attachments/assets/342d9d60-d2d4-46cf-84fa-df0753f0f0f7)

**Comment by stephdl** [comment]
released ghcr.io/nethserver/dnsmasq:1.0.3
