### ISSUE TITLE
traefik: uploaded custom certificates are not exported into Redis

### ISSUE THREAD

**Issue by Amygos** [NethServer/dev#6986]
**Steps to reproduce**

1. Upload a custom certificate

**Expected behavior**

The certificate is exported into Redis and an event `certificate-updated` is raised.

**Actual behavior**

The certificate is not exported into Redis and the event is not raised.

**Workaround**

Copy the certificates from the Traefik module's state directory `/home/<moduleid>/.config/state/custom_certificates/`

**Components**

https://github.com/NethServer/ns8-traefik

**See also**

Private Mattermost chat: https://mattermost.nethesis.it/nethesis/pl/gto9urptuibndgddbwfieco9ee

**Comment by Amygos** [comment]
Testing release `2.2.5-testing.1`

**Comment by Amygos** [comment]
**Test case 1**
- Install on a clean machine
```
bash install.sh ghcr.io/nethserver/traefik:2.2.5-testing.1
```
- Upload a custom certificate for a domain
- Install a module that requires a certificate, but not for HTTPS, like `ns8-mail or `ns8-nethvoice-proxy`
- Configure the module with the domain of the custom certificate
- Check if the module correctly uses the domain's certificate

**Test case 2**
- Upgrade an existing installation
```
 api-cli run update-module --data '{"module_url":"ghcr.io/nethserver/traefik:2.2.5-testing.1","instances":["traefik1"]}'
```
- Upload a custom certificate for a domain
- Install a module that requires a certificate, but not for HTTPS, like `ns8-mail or `ns8-nethvoice-proxy`
- Configure the module with the domain of the custom certificate
- Check if the module correctly uses the domain's certificate

**Comment by Amygos** [comment]
Testing release `2.2.5-testing.2`

**Comment by nrauso** [comment]
test case 1: **VERIFIED**

test case 2: **VERIFIED**

**Comment by Amygos** [comment]
Released: https://github.com/NethServer/ns8-traefik/releases/tag/2.2.5
