### ISSUE TITLE
Upgrade to Mattermost 9.11

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6997]
Mattermost 8 reached its End of Life (EOL) in May 2024, meaning it no longer receives updates or security patches, posing potential risks. To ensure continued security and support, it's crucial to upgrade to Mattermost 9.11.0, the latest stable version with active maintenance and improvements.

**Proposed solution**
I propose upgrading Mattermost to version 9.11.0, which is an Extended Support Release (ESR) and will be supported until April 2025. For the database, the minimal requirement is PostgreSQL 11, as outlined in the [software requirements](https://docs.mattermost.com/install/software-hardware-requirements.html). Our current setup uses PostgreSQL 13, which remains supported until November 2025, as detailed on the [EOL schedule](https://endoflife.date/postgresql). The migration process will require a minor [SQL adjustment](https://docs.mattermost.com/upgrade/important-upgrade-notes.html) to ensure compatibility.

**Alternative solutions**

Since May 2024, our version of Mattermost is no longer supported, leaving us with no viable options other than upgrading. Continuing to use an unsupported version can expose us to security vulnerabilities and compatibility issues. Therefore, upgrading to a supported version is necessary to ensure ongoing functionality and security.

**Additional context**

- [x] Release 2.0.7, just to fix the app drawer logo https://github.com/NethServer/dev/issues/6954
- [x] Plan for upgrade to 9
- [x] Freeze the version in the migration tool https://github.com/NethServer/nethserver-ns8-migration/pull/77

**Comment by stephdl** [comment]
QA

- test 1 install
install ghcr.io/nethserver/mattermost:2.0.8-dev.1
configure
no errors expected

- test 2 upgrade: 
a postgres fix is done to the database by an upgrade script, you should see some upgrade messages
install ghcr.io/nethserver/mattermost:2.0.7
configure
no errors expected
upgrade ghcr.io/nethserver/mattermost:2.0.8-dev.1
no errors expected

**Comment by stephdl** [comment]
the migration of nethserver-mattermost to mattermost:2.0.7 will be tested [there](https://github.com/NethServer/dev/issues/6994)

**Comment by nrauso** [comment]
test case 1: **VERIFIED**

test case 2: **VERIFIED**
the db upgrade is explicitly traced:
```
Sep 09 08:54:27 myns8.test.net agent@mattermost2[6748]: Running /home/mattermost2/.config/update-module.d/10database_upgrade...
Sep 09 08:54:27 myns8.test.net agent@mattermost2[6748]: Postgres service is active, we start database upgrade to 9.11.0
```
Also tested `mattermost` migration from NS7 to NS8, editing the dedicated migration fragment
```
~]# cat /usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-mattermost/bind.env
# This file is included by ns8-bind-app
MODULE_VOLUMES="mattermost-data"
MODULE_IMAGE_URL="ghcr.io/nethserver/mattermost:2.0.8-dev.2"
```
It worked flawlessly.
