### ISSUE TITLE
Upgrade to Nextcloud 28

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#7002]
Since NC 27.7.11 is available for both NS7 and NS8, and the migration tool is frozen to use that fixed release number for the migration (app version is 1.1.7), we can release NC 28 for NS8.

**Proposed solution**

Bump NC 28 in NS8 app.

**Alternative solutions**

None.

**Additional context**

Upgrade to NC 29 will be possible when core implementation of `org.nethserver.min-from` is released. Refs https://github.com/NethServer/dev/issues/6956.

**See also**

- https://community.nethserver.org/t/nextcloud-28-hub-7-office-productivity-improvements/22587
- https://mattermost.nethesis.it/nethesis/pl/9b557tf7wibdtyx84t77apr61r

**Comment by stephdl** [comment]
The target version is ghcr.io/nethserver/nextcloud:1.1.8-dev.1

**Comment by stephdl** [comment]
QA

The idea is to test the upgrade and the first installation, th emigration points to the version 1.0.7 so we do not need to handle this case

- first installation
install an account provider
add-module `ghcr.io/nethserver/nextcloud:1.1.8-dev.1`
configure nextcloud with the account provider
Nextcloud is up
go the administrative page of Nextcloud with the `admin` user
no red warnings, some yellow warnings relative to the database that could be enhanced

 - upgrade
 install an account provider
add-module ghcr.io/nethserver/nextcloud:1.1.7
configure nextcloud with the account provider
Nextcloud is up 
upgrade nextcloud to `ghcr.io/nethserver/nextcloud:1.1.8-dev.1`
`api-cli run update-module --data '{"module_url":"ghcr.io/nethserver/nextcloud:1.1.8-dev.1","instances":["nextcloud1"],"force":true}'`
go the administrative page of Nextcloud with the `admin` user
no red warnings, some yellow warnings relative to the database that could be enhanced

**Comment by nrauso** [comment]
tested first installation: **VERIFIED**

tested upgrade: **VERIFIED**
