### ISSUE TITLE
Collabora: Restoration broken

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7003]
I'm facing two issues with backup and restoration. The first is a KeyError: 'ADMIN_PASSWORD' due to a missing environment variable. The second issue is that the password.env file isn't included in the backup, causing problems during restoration.

**Steps to reproduce**

- Install collabora and configure it with a FQDN and a password
- configure a backup and do a backup of the collabora module
- do a restoration on the module itself

**Expected behavior**

I expect no errors on the restoration, collabora must be up and configured without  issue

**Actual behavior**

I have two issues relevant to the backup and the restoration

- ` KeyError: 'ADMIN_PASSWORD'`
The environment  variable does not exist , we use a passfile now but I still require a mandatory  environment file
```
Sep 03 05:34:07 R1-pve.rocky9-pve.org agent@collabora2[136856]:   File "/home/collabora2/.config/actions/restore-module/06copyenv", line 36, in <module>
Sep 03 05:34:07 R1-pve.rocky9-pve.org agent@collabora2[136856]:     agent.set_env(evar, original_environment[evar])
Sep 03 05:34:07 R1-pve.rocky9-pve.org agent@collabora2[136856]:                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
Sep 03 05:34:07 R1-pve.rocky9-pve.org agent@collabora2[136856]: KeyError: 'ADMIN_PASSWORD'
```

- the passfile password.env is not inside the backup
```
[root@R1-pve ~]# locate password.env
/home/collabora1/.config/state/password.env
```
**Components**
`ghcr.io/nethserver/collabora:1.0.6`

**Comment by stephdl** [comment]
QA

the purpose of the verification is to verify the restoration but also the new CODE version installed

- install nextcloud
add testing version of nextcloud
- install collabora
add-module ghcr.io/nethserver/collabora:1.0.7-dev.1
- configure nextcloud and collabora
- demonstrate that you can use collabora inside nextcloud to open libre office files. Tthink to accept the custom certificate of collabora
- do a backup of nextcloud and collabora
- restore on the same module of nextcloud and collabora, no error expected
- go to the nextcloud UI, the widget to choose the collabora instance is visible
- go to nextcloud you can still edit libreoffice files, the version has been updated to 
![image](https://github.com/user-attachments/assets/be0717b7-e34a-42a5-b647-1e92b36d9594)

**Comment by nrauso** [comment]
test case: **VERIFIED**
