### ISSUE TITLE
NethVoice: Phone Model Visibility in NethVoice Admin interface

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7006]
When creating a new model by copying an existing one in NethVoice, the model does not appear immediately. 

To make the model appear in NethVoice on NS8, it must first be associated with a phone. 
Only then will it show up in the list of models.

Thus, while the model is indeed created and can be selected for association with a phone, it does not appear under Devices -> Models.

![image](https://github.com/user-attachments/assets/899fa027-0091-4fe8-b184-cc38fcbf016b)
![image](https://github.com/user-attachments/assets/ad1b5c68-5a9b-4efe-a3f6-8a0cb5eb4842)
![image](https://github.com/user-attachments/assets/8e15ff62-54b2-4fd7-9cb0-844f673d3cce)

This seems to be a graphical bug.

**Comment by edospadoni** [comment]
Testing release: https://github.com/nethesis/ns8-nethvoice/tree/1.0.1-testing.4

**Comment by andrea-marchionni** [comment]
Verified.
