### ISSUE TITLE
NethVoice CTI: inverted titles in audio settings

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7007]
In the Settings menu -> Devices if I configure the audio settings of the web phone I get the drawer.
In the drawer where there is the section titled "Speakers", the selection box says "Select audio input" but instead the output devices are shown.
Vice versa for the section titled "Microphone" and the selection box "Select audio output" the input devices are shown.

![image](https://github.com/user-attachments/assets/dd750d04-f265-4dc4-96f0-b6fc8c6b22ca)

**Comment by edospadoni** [comment]
Test case:
- check the bug is not reproducible

**Comment by edospadoni** [comment]
Testing release: https://github.com/nethesis/ns8-nethvoice/tree/1.0.1-testing.4

**Comment by andrea-marchionni** [comment]
Verified
