### ISSUE TITLE
Nethvoice, Nethvoice-proxy: Don't use NS8's default environment for sensitive data

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7011]
Environment variables written using agent.set_env() are stored in NS8 Redis and are readable by everyone. We need to avoid to use agent.set_env() for sensitive variables.

One Proposed solution is to write configuration to a json file, backup it, and write configuration to environment on module configure.
Another solution is to use core functions [read_envfile](https://github.com/NethServer/ns8-core/blob/ce3ffde4377c7663cf8fb703404fe4c919c67d40/core/imageroot/usr/local/agent/pypkg/agent/__init__.py#L87)/[write_envfile](https://github.com/NethServer/ns8-core/blob/ce3ffde4377c7663cf8fb703404fe4c919c67d40/core/imageroot/usr/local/agent/pypkg/agent/__init__.py#L108), to store sensitive variables.

Implementing this will probably cause regressions in installation, backup and restore, migration from 7 and move/clone from node to node.

Actions to modify:
 - [x] create-module
 - [x] configure-module
 - [x]  update-module
 - [x] import-module
 - [x] transfert-state (seems nothing to do, we just stop services)
 - [x] clone-module
 - [x]  restore-module
 - [x] bin

**Comment by Amygos** [comment]
NethVoice testing release: [1.0.3-testing.3](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.3-testing.3)

**Comment by Amygos** [comment]
Nethvoice Proxy testing release: [1.0.2-testing.2](https://github.com/nethesis/ns8-nethvoice-proxy/releases/tag/1.0.2-testing.2)

**Comment by Amygos** [comment]
## Test Case 1: Verify that a new installation of NethVoice testing version works correctly

**Description**: Ensure that NethVoice functions correctly after a fresh installation in the testing version.  
**Pre-conditions**:  
- A fresh installation of the NethVoice testing version is available.  
- The installation is performed on a compatible system.

**Steps**:
1. Install the NethVoice testing version.
2. Follow the standard installation steps for the module.
3. Open NethVoice after installation.
4. Verify that all basic features (login, main page, settings) function correctly.

**Expected Result**: NethVoice testing version should work without any errors after installation.  
**Post-conditions**: None.

---

## Test Case 2: Verify that an update to NethVoice testing version functions correctly

**Description**: Ensure that updating NethVoice from a previous version to the testing version works without issues.  
**Pre-conditions**:  
- The previous version of NethVoice is installed.  
- The update module for the new testing version of NethVoice is available.

**Steps**:
1. Perform the update from the previous version to the NethVoice testing version.
2. Open NethVoice after the update.
3. Verify that existing data and settings are retained.
4. Test core features (login, user data, settings) to ensure functionality.

**Expected Result**: The update to the NethVoice testing version should be successful, and all features should work as expected.  
**Post-conditions**: None.

---

## Test Case 3: Verify the migration of NethVoice to another node in testing version

**Description**: Ensure that NethVoice can be migrated to another node without issues in the testing version and that it is reconfigured correctly.  
**Pre-conditions**:  
- NethVoice is installed and running on the current node in the testing version.  
- The target node is ready for migration.

**Steps**:
1. Prepare the target node for migration.
2. Initiate the migration process from the current node to the target node.
3. Verify that all data and settings are transferred correctly.
4. Reconfigure NethVoice on the target node to ensure proper functionality.
5. Open NethVoice on the target node and verify that all features function correctly.

**Expected Result**: NethVoice testing version should function correctly on the target node with all data and settings intact after migration and reconfiguration.  
**Post-conditions**: None.

---

## Test Case 4: Verify the backup/restore procedure of NethVoice testing version

**Description**: Ensure that the backup and restore procedures for NethVoice work correctly in the testing version.  
**Pre-conditions**:  
- NethVoice testing version is installed and running.  
- A backup of NethVoice is available.

**Steps**:
1. Perform a backup of the current NethVoice configuration and data.
2. Verify that the backup is created successfully.
3. Restore NethVoice from the backup.
4. Open NethVoice after the restore and verify that all data and settings are intact.

**Expected Result**: The backup and restore procedures should work correctly in the testing version, with no data loss or errors.  
**Post-conditions**: None.

---

## Test Case 5: Verify migration from NetServer 7 to NethVoice testing version

**Description**: Ensure that migrating from NetServer 7 to NethVoice testing version is successful and functional.  
**Pre-conditions**:  
- A working installation of NetServer 7 is available.  
- The migration module for NethVoice testing version is ready.

**Steps**:
1. Prepare for migration from NetServer 7 to NethVoice testing version.
2. Initiate the migration process.
3. Verify that all relevant data and configurations are transferred to NethVoice.
4. Open NethVoice after migration and check that all features function as expected.

**Expected Result**: Migration from NetServer 7 to NethVoice testing version should be successful, with all features working properly.  
**Post-conditions**: None.

**Comment by andrea-marchionni** [comment]
Execute the Test Case: 1,2,3 for NethVoice

**Comment by andrea-marchionni** [comment]
Test case 4 for NethVoice ok

**Comment by Amygos** [comment]
Nethvoice released https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.3

**Comment by Amygos** [comment]
Nethvoice Proxy released https://github.com/nethesis/ns8-nethvoice-proxy/releases/tag/1.0.2

**Comment by Amygos** [comment]
Testing release `nethesis/ns8-nethvoice` [1.1.2-testing.6](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.2-testing.6)

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.2)
