### ISSUE TITLE
NethVoice CTI: Mobile App settings are not hidden

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7014]
If a user does not have the mobile app option active, in the Nethvoice CTI settings menu he should not see the mobile app section like now.

![Schermata 2024-09-12 alle 10 46 24](https://github.com/user-attachments/assets/b80b22b8-4f96-4e36-b55c-1de9c566816b)

**Comment by edospadoni** [comment]
Test case:
- check the bug is not reproducible

**Comment by edospadoni** [comment]
Testing release: https://github.com/nethesis/ns8-nethvoice/tree/1.0.1-testing.4
