### ISSUE TITLE
NethVoice CTI rebranding

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7020]
A NethVoice reseller must be able to customize the admin interfaces by changing these characteristics to create a different and personal brand:

NethVoice CTI:
- [x] favicon
- [x] background image of the login page 
- [x] brand images of the login page (light/dark)
- [x] choose if hide or display the action_voice-cti image
- [x] brand images of CTI interface (light/dark)

**Comment by edospadoni** [comment]
Test case 1:
- install the ns8-nethvoice module from testing release
- leave cluster a community without subscription
- go to the cluster administration interface to configure the module
- check if rebranding inputs are hidden

Test case 2:
- install the ns8-nethvoice module from testing release
- enroll the cluster in a community subscription (trial on my.nethserver.com)
- go to the cluster administration interface to configure the module
- check if rebranding inputs are hidden

Test case 3:
- install the ns8-nethvoice module from testing release
- register the cluster with an enterprise subscription (reseller on my.nethesis.it)
- go to the cluster administration interface to configure the module
- check if rebranding inputs are displayed
- add logos and background urls
- check rebranding preview changes with new logos and background
- save the configuration
- check that the nethvoice CTI instance has rebranding 

Test case 4:
- install the ns8-nethvoice module from the test version
- register the cluster with an enterprise subscription (reseller on my.nethesis.it)
- go to the cluster administration interface to configure the module
- check if rebranding inputs are displayed
- add logos and background
- check rebranding preview changes with new logos and background
- save the configuration
- check that the nethvoice CTI instance has rebranding
- go to the cluster administration interface to configure the module again
- remove rebranding inputs (or click "Clear Rebranding" in the preview image)
- save the configuration
- check that the Nethvoice CTI instance is not rebranded

**Comment by andrea-marchionni** [comment]
Test case 3 and test case 4 OK

**Comment by andrea-marchionni** [comment]
Test case 1 OK

**Comment by andrea-marchionni** [comment]
Test case 2 OK
