### ISSUE TITLE
Miss link to report in CTI history

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7021]
It is necessary to add a link to the NethVoice reports page in the NethVoice CTI report.

This is to help the user who is looking for advanced reporting features.

![Image](https://github.com/user-attachments/assets/56333842-925b-4c68-8e11-ffe58a92cccf)

This feature has already been added to the QManager section

![Image](https://github.com/user-attachments/assets/71ab486e-3f88-478a-85fe-bac6df1e0e83)

**Comment by edospadoni** [comment]
Test case:
- check the bug is not reproducible

**Comment by edospadoni** [comment]
Testing release: https://github.com/nethesis/ns8-nethvoice/tree/1.0.1-testing.4

**Comment by andrea-marchionni** [comment]
Verified
