### ISSUE TITLE
Wrong URL on NethVoice Admin page

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7022]
There are two wrong link on NethVoice admin page footer, they refer to the old version:

![Image](https://github.com/user-attachments/assets/ce6bd194-37ad-4c05-8e9a-30b586856f41)

![Image](https://github.com/user-attachments/assets/cbbf172f-f9fb-4263-bdb4-72097a0a44fb)

**Comment by Amygos** [comment]
Testing release: [1.0.1-testing.3](https://github.com/nethesis/ns8-nethvoice/tree/1.0.1-testing.3)

**Comment by edospadoni** [comment]
Test case:
- check the links are valid

**Comment by andrea-marchionni** [comment]
The test failed on already configured installation.

**Comment by andrea-marchionni** [comment]
Test case 1 (fresh install):

- install NethVoice Proxy and configure it
- install NethVoice and configure it
- check that the links are correct by logging into  the NethVoice interface

Test case 2 (update):

- update NethVoice app 
- check that the links are correct by logging into  the NethVoice interface

**Comment by edospadoni** [comment]
Testing release: [1.0.1-testing.7](https://github.com/nethesis/ns8-nethvoice/tree/1.0.1-testing.7)
