### ISSUE TITLE
NethVoice CTI: default filter is wrong on Queues and QManager customers management

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7028]
The default filter is with all enabled queues selected in the customer's management tabs of the Queue and QManager section.

This when a user has many queues enabled creates overload on the page and difficulty in disabling most of them, given that the most used view is the one with only some queues enabled.

![image](https://github.com/user-attachments/assets/7c2c8f1a-fbdb-4f8d-8c7f-a2316acd3723)

It would be more useful to have the default filter with no queues enabled.

**Comment by edospadoni** [comment]
Test case:
- check the bug is not reproducible

**Comment by edospadoni** [comment]
Testing release: [1.0.1-testing.6](https://github.com/nethesis/ns8-nethvoice/tree/1.0.1-testing.6)
