### ISSUE TITLE
NethVoice CTI: Phone island should not give error without audio device

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7030]
If I connect to NethVoice CTI from a PC that is not equipped with audio input and/or output devices or a video camera I get an error.

![image](https://github.com/user-attachments/assets/f27558f2-1387-40a3-acbe-e63bc4f12909)

Phone Island should not show error in this situation.

NethVoice CTI can also be used without an audio and/or video device for consultation or in support of a physical telephone

**Comment by edospadoni** [comment]
Testing release [1.1.1-testing.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1-testing.1)

**Comment by edospadoni** [comment]
Test case:
- make sure the bug is not reproducible

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1)
