### ISSUE TITLE
Add NethVoice Phonebook on NethVoice App

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7034]
NethVoice App user needs to use NethVoice CTI address book also inside the app.

The app supports connection to an external source of contacts, here is the documentation:

https://doc.acrobits.net/api/client/web_contacts.html

**Comment by edospadoni** [comment]
Test case 1:
- open NethVoice app
- go to Contacts tab
- check if contacts are present

Test case 2:
- open NethVoice app
- go to Contacts tab
- check if contacts are present
- pull down the page and start refresh
- check if contacts are still present

Test case 3:
- open NethVoice app
- go to Contacts tab
- check if contacts are present
- go to NethVoice CTI
- create a contact
- go back to NethVoice app
- pull down the page and start refresh
- check the newly created contact is present

Test case 4:
- open NethVoice app
- go to Contacts tab
- check if contacts are present
- go to NethVoice CTI
- create a contact
- go back to NethVoice app
- wait at least 1 hour to auto-sync
- check the newly created contact is present

**Comment by andrea-marchionni** [comment]
Released [1.0.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.2)
