### ISSUE TITLE
NethSecurity Controller: add monitoring feature

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#7035]
Update the NethSecurity Controller application to add the monitoring feature.

Required changes:

- [x] update to latest controller release
- [x] add Timescale database to store report data:
   - [x] the database dump must be added to the backup
   - the database is accessed in write mode only from the API server
   - the database is access in read only mode from Grafana
- [x] add MaxMind license for the API server: the license should be configurable using the UI
- [x] apply retention also to Timescale database
- [x] update Grafana to 11.2.0 (required to make work the [render plugin](https://github.com/orgs/NethServer/projects/10/views/2?pane=issue&itemId=79945439) on a subpath)
- [x] update existing module installations to include a new port for Timescale, requires: https://github.com/NethServer/ns8-core/pull/699
- [x] expand documentation page

See related issues:
- implements https://github.com/NethServer/nethsecurity/issues/754
- requires https://github.com/NethServer/dev/issues/6974

**Comment by gsanchietti** [comment]
**Test case 1**
- Install a new instance of the controller: `add-module ghcr.io/nethserver/nethsecurity-controller:latest`
- Access the module UI and configure it , including the new Max Mind license field
- Save the configuration
- Verify the controller is accessible and units can be registered
- Follow the [unit test case](https://github.com/NethServer/nethsecurity/issues/754#issuecomment-2378706529)

**Test case 2 (ON HOLD)**
- Update an existing instance where there is at least one unit connected: `api-cli run update-module --data '{"module_url":"ghcr.io/nethserver/nethsecurity-controller:latest","instances":["nethsecurity-controller1"],"force":true}'` 
- Verify the units still reconnect after the upgrade
- Check the timescale database is running: `runagent -m nethsecurity-controller8 podman ps`

**Comment by Tbaile** [comment]
Case 2 verified.

**Comment by stephdl** [comment]
test 1 verified

once the controller up and the nethsecurity unit up with registration on the both side, the data is  visible in grafana without action of the sysadmin after few minutes
the page of the  controller in the nethsecurity web page show us that the data is well sent to grafana

![image](https://github.com/user-attachments/assets/6dc9be39-fa30-4e15-895d-5a40e83ab557)

**Comment by gsanchietti** [comment]
Released version 1.1.0
