### ISSUE TITLE
Show user status on NethVoice App

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7039]
Nethvoice App must be able to show the status of other users.
it is possible to do this by adding an extension number and name to favorites and checking the BLF function (section named Favorites in the NethVoice App)

![Image](https://github.com/user-attachments/assets/b5fbe8ea-23a5-4382-8271-c7fd91d4300d)

![Image](https://github.com/user-attachments/assets/3dc331b7-db89-4edd-9ac8-42693ac554f3)

The app user would like to automatically find configured the users to monitor.

On the NethVoice CTI side, we can take this data from:
- users set as favorites in the operator panel (NethVoice CTI's favorite users are stored locally, if they will be necessary, before they must be saved server side) 
- speed dials ( they are saved in the NethVoice CTI Phonebook)

it is therefore a question of evaluating the feasibility of the 2 possibilities (my preference goes to favorites).

On the app side, it is possible to pass the favorites via provisioning.

https://doc.acrobits.net/cloudsoftphone/account.html#busy-lamp-field

**Comment by edospadoni** [comment]
Test case:
- update NethVoice CTI to 0.1.14 (included in testing release below)
- go to NethVoice CTI app and check that your favorites are still there
- open the NethVoice App and check, under Quick Dial tab, that there are the same favourites as you have on NethVoice CTI
- Add/Remove favourites from NethVoice CTI and check that they are also added/removed on NethVoice App (wait at least 30/60 seconds before check)

**Comment by edospadoni** [comment]
Testing release: https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.2-testing.2

**Comment by andrea-marchionni** [comment]
Released [1.0.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.2)
