### ISSUE TITLE
NethVoice CTI: after container restart QManager is not present

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7041]
After restarting the FreePBX container in an enterprise installation, access to the NethVoice CTI QManager is unavailable, despite having a profile with the permission enabled.

To reproduce the issue, restart the FreePBX container and log in to NethVoice CTI with a user who has the QManager permission enabled in their profile.

Check  that QManager is not present

![image](https://github.com/user-attachments/assets/210ac28e-1450-4a39-b4fd-f27540ce4a2c)

Make any change to the configuration, even if it's not related to the QManager permission, in order to trigger a regeneration of the configuration files.

Check that QManager is now present.

![image](https://github.com/user-attachments/assets/bac50727-1d23-487e-951a-9392549f71df)

**Comment by Amygos** [comment]
Released [1.0.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.2)
