### ISSUE TITLE
Tancredi: Snom expansion module are not configured well

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7044]
Tancredi does not configure the expansion modules of Snom phones well for two reasons:
- in the template, the number of keys of each module is forced to 18, but there are also other sizes
- in the scopes of the phones the variables (cap_expkey_count, cap_expkey_type_blacklist) are duplicated

The problem occurs by not being able to configure all the available keys because only 18x3 keys of the expansion modules are configured

**Comment by Stell0** [comment]
Testing packages:
ns7 http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-testing/x86_64/Packages/nethserver-tancredi-1.17.0-1.3.gd8f7fbd.ns7.noarch.rpm
ns8 [1.0.2-testing.8](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.2-testing.8)

**Comment by andrea-marchionni** [comment]
ns7 Verified
ns8 Verified

**Comment by Stell0** [comment]
in `7.9.2009/nethesis-updates`:
- nethserver-tancredi-1.18.0-1.ns7.noarch.rpm [x86_64](http://packages.nethesis.it/nethserver/enterprise/7.9.2009/nethesis-updates/x86_64/Packages/nethserver-tancredi-1.18.0-1.ns7.noarch.rpm)
