### ISSUE TITLE
NethVoice: check user sync

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7045]
The synchronization of users within FreePBX occurs in two moments:
- when the FreePBX container is started
- when the NethVoice user interface is opened

These modes cause these problems:

- at the end of the installation and configuration of the NethVoice module on NS8, if the administrator enters the user interface of NethVoice before the user synchronization is finished, he does not see any available users
- if a user is added on the account provider, it is necessary to open the NethVoice interface to start the synchronization, in this access the user will not be available but will be available only in the next

Possible solution:

- show in the NethVoice interface if the synchronization is in progress checking with a polling, update the users view when synchronization is complete and if there isn't an active synchronization, give the user the possibility to launch a new synchronization

also launch the synchronization using a systemd timer

**Comment by edospadoni** [comment]
Test case:
- go to the Extensions page
- check that a message is shown saying that users are syncing
- check that at the end of the synchronization the message disappears and that the user list is updated
- check that the same thing also happens under the Configurations/Users page

**Comment by edospadoni** [comment]
Testing release: Testing release: [1.0.2-testing.3](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.2-testing.3)

**Comment by Amygos** [comment]
Released [1.0.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.2)
