### ISSUE TITLE
NethVoice CTI: the conversation time shown by Phone Island is wrong

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7049]
Phone Island receives the conversation time from the server.
In the case of a call from a queue, the time it receives also includes the time the caller spent waiting, thus giving the user incorrect information.

Check if the correct conversation time also arrives from the server (there should be one for the user's extension channel) or otherwise calculate it on the client side.

How to reproduce the problem:

- Get a call that has been waiting in a queue for a few seconds
- The talk time after answering does not start at zero

**Comment by Amygos** [comment]
Release Nethesis/ns8-nethvoice  [1.1.0](https://github.com/Nethesis/ns8-nethvoice/releases/tag/1.1.0)

**Comment by edospadoni** [comment]
Testing release [1.1.1-testing.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1-testing.1)

**Comment by edospadoni** [comment]
Test case:
- make sure the bug is not reproducible

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1)
