### ISSUE TITLE
Check NethVoice CTI security issues

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7051]
There are several node dependencies that are behind the release and expose critical vulnerabilities. 

Let's upgrade to node version 18 and update critical dependencies

**Comment by edospadoni** [comment]
Test case:
- there are no usage changes. the test case consists of opening the CTI and verifying that the login and various API calls work.

**Comment by edospadoni** [comment]
Testing release [1.0.3-testing.5](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.3-testing.5)

**Comment by Amygos** [comment]
NethVoice released https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.3
