### ISSUE TITLE
NethVoice: LDAPS phonebook (dedicated to IP phone) doesn't work

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7053]
The LDAPS address book created to allow IP phones to consult contacts is not working.

The provisioning of Tancredi does not configure the various phone models in the same way, it seems that the configuration data is not passed to Tancredi.

In older installations, I note that on the NethServer 8 firewall, the port dedicated to the address book is not managed.

The current behavior is that phones configured by NethVoice cannot get the contact list and the address book remains loading until timeout.

**Comment by andrea-marchionni** [comment]
Testing release: [1.0.3-testing.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.3-testing.2)

**Comment by Amygos** [comment]
NethVoice released https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.3
