### ISSUE TITLE
Mattermost: minor upgrade to 9.11.2

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7055]
Mattermost gets a docker upgrade image to 9.11.2

**Proposed solution**

upgrade mattermost to use 9.11.2

**Alternative solutions**

do nothing

**Additional context**

The target is to upgrade ns8-mattermost: 2.0.8

**Comment by nrauso** [comment]
test case 1: **VERIFIED**
test case 2: **VERIFIED**

**Comment by stephdl** [comment]
released as https://github.com/NethServer/ns8-mattermost/releases/tag/2.1.0
