### ISSUE TITLE
NethVoice: errors creating configuration for Patton gateways

### ISSUE THREAD

**Issue by andrea-marchionni** [NethServer/dev#7056]
1) Trying to create the configuration for an analog Patton gateway I get a configuration file where not all the fields have been filled in.

`
    map TRUNKNUMBER1(.%) to \1
`
`
    map TRUNKNUMBER2(.%) to \1
`

`
address-translation outgoing-call from-header user-part fix TRUNKUSERNAME1 host-part fix voice2.demo-heron.sf.nethserver.net 5060
`
`
 address-translation outgoing-call from-header user-part fix TRUNKUSERNAME2 host-part fix voice2.demo-heron.sf.nethserver.net 5060
`

`username TRUNKUSERNAME1 password TRUNKSECRET1`

`
username TRUNKUSERNAME2 password TRUNKSECRET2
`

Step to reproduce:

- In the NethVoice Admin interface go to trunk->Physycal add a gateway (Patton TRINITY ANalog) and compile all the fields
- Download the configuration and note that some fields are not filled in.

---------------------

2) Trying to create the configuration for a primary Patton gateway when saving I get an error in the network in the browser and the interface remains on the same screen, but I find the configuration in the interface if I reload the page.

![Schermata 2024-10-08 alle 11 18 10](https://github.com/user-attachments/assets/954fab1d-c290-429f-b65a-1ce0110ac4fb)
![Schermata 2024-10-08 alle 11 18 22](https://github.com/user-attachments/assets/5a18b2d0-3802-4c0a-a2c9-503095d06488)
![Schermata 2024-10-08 alle 11 18 29](https://github.com/user-attachments/assets/37ac086c-20de-40c1-804f-79dd1535362d)

Step to reproduce:

- In the NethVoice Admin interface go to trunk->Physycal add a gateway (Patton TRINITY Primary) and compile all the fields
- Check the browser tools

**Comment by Amygos** [comment]
NethVoice released https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.3
