### ISSUE TITLE
Nethvoice UI: Ensure Proxy Installation Check

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7057]
When installing Nethvoice, the initial step is to navigate to the application settings, configure the necessary hostnames, and press the Save button. However, Nethvoice cannot function without the proxy, and during the "Configure Module" action, the system checks if the proxy is installed. If the proxy is not present, the UI throws an unclear error.

**Proposed solution**

The UI should check if the proxy is installed and configured before allowing the user to begin the configuration process. This would prevent confusion and ensure a smoother setup experience.

**Alternative solutions**

do nothing

**Additional context**

nethvoice:1.0.2

**See also**

see https://mattermost.nethesis.it/nethesis/pl/rwbc11p34tdz8q36cqugeqo83c

**Comment by stephdl** [comment]
QA

The target version  is :  `ghcr.io/nethesis/nethvoice:1.0.4-testing.1`

- install nethvoice first without the nethvoice proxy, all fields should be disabled, you cannot save the form. A banner is visible to inform you that there is no proxy installed on the node and you must install first.
- install  the nethvoice proxy first and netvoice after, you should be able to configure nethvoice by pressing the button save.

**Comment by Amygos** [comment]
Testing release https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.4-testing.1

**Comment by Amygos** [comment]
Released: https://github.com/nethesis/ns8-nethvoice/releases/tag/1.0.4
