### ISSUE TITLE
Controller: show OpenVPN port in the app Status section

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7059]
Sometimes we need to know what port is using the OpenVPN server in order to forward it in the perimeter firewall.
This information is not clearly exposed in the NS8 UI.
Showing it in the app Status page could be a good idea.

**Proposed solution**

add the port of vpn in the status page 

![image](https://github.com/user-attachments/assets/41d95421-eaf4-43d4-8538-dc9578ed83b9)

**Alternative solutions**

Go to CLI to find the port

**Additional context**

ns8-nethsecurity-controller:1.0.1

**See also**

https://github.com/orgs/NethServer/projects/10/views/2?pane=issue&itemId=81229281

----

thank @cotosso

**Comment by stephdl** [comment]
QA

install the version ghcr.io/nethserver/nethsecurity-controller:1.1.0-dev.1
- the port is displayed in a new card in the `status` page
- the port is displayed in the banner of the `settings` page

**Comment by gsanchietti** [comment]
Verified: the port is visible both on configure and status page

**Comment by stephdl** [comment]
released by https://github.com/NethServer/ns8-nethsecurity-controller/releases/tag/1.1.0
