### ISSUE TITLE
First configuration aborted for DB init timeout exceeded

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#7067]
NethVoice first configuration fails after few minutes for a Systemd service timeout.

**Steps to reproduce**

- Install NethVoice
- Go to Settings page, fill the form and Save

**Expected behavior**

First configuration succeeds.

**Actual behavior**

The first configuration fails with the following messages in stderr.

```text
<4>agent.ldapproxy: domain studioetti.net should not be used by nethvoice1. Invoke agent.bind_user_domains(["studioetti.net"]) to fix this warning.
Job for mariadb.service failed because a timeout was exceeded.
See "systemctl --user status mariadb.service" and "journalctl --user -xeu mariadb.service" for details.
```

Full application journal: [nethvoice1.log](https://github.com/user-attachments/files/17434617/nethvoice1.log)

**Components**

- nethvoice 1.0.4 
- nethvoice-proxy 1.0.2
- core 3.1.1

Discussion: https://mattermost.nethesis.it/nethesis/pl/hwfuijzce38r9gc1cfeyo9ur6o

---

Thanks to @nrauso

**Comment by Stell0** [comment]
- MariaDB doesn't initialize because systemd timeput is reached
- FreePBX fails to start because PostExec control hits the 30 seconds timeout

**Comment by Amygos** [comment]
[1.1.0-testing.3](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.0-testing.3)

**Comment by nrauso** [comment]
The module provisioning completes successfully now

**Comment by Amygos** [comment]
Released [1.1.0](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.0)

**Comment by Amygos** [comment]
Testing release `nethesis/ns8-nethvoice` [1.1.2-testing.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.2-testing.1)

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.2)
