### ISSUE TITLE
Update Netdata to v1.47.5 for Improved Performance and Bug Fixes

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7076]
Description:
Updating Netdata to version 1.47.5 addresses critical bug fixes and performance improvements. This update enhances monitoring stability and introduces minor feature updates, improving overall system observability.

Proposed solution:
Upgrade Netdata to v1.47.5 in the current environment to take advantage of these improvements. A quick version check and compatibility test will ensure smooth integration.

Alternative solutions:
Consider remaining on the current version if backward compatibility with dependencies is a concern or if the new features are not immediately necessary.

Additional context:
Upgrading to v1.47.5 is expected to resolve issues reported in the prior version and reduce resource consumption, especially beneficial for high-load environments.

See also:
Refer to [Netdata’s release notes](https://github.com/netdata/netdata/releases/tag/v1.47.5) for detailed change logs and community discussions.

**Comment by stephdl** [comment]
QA

- first install 
add-module ghcr.io/nethserver/netdata:1.1.2-dev.1
no error expected, netdata is up and running 

- upgrade
add-module netdata
then upgrade to ghcr.io/nethserver/netdata:1.1.2-dev.1
no error expected, netdata is up and running

**Comment by nrauso** [comment]
test case 1: **VERIFIED**
test case 2: **VERIFIED**

**Comment by stephdl** [comment]
QA

install ghcr.io/nethserver/netdata:1.1.2-dev.2
once  the service is started, stop it and check the status
this message must not be printed, the service must be stopped gracefully

`Oct 28 08:43:57 R4-pve.rocky9-pve4.org netdata3[400715]: time="2024-10-28T08:43:57+01:00" level=warning msg="StopSignal SIGTERM failed to stop container netdata3 in 10 seconds, resorting to SIGKILL"
`

**Comment by nrauso** [comment]
test case: **VERIFIED**

These logs were captured during the module shutdown:
```
Oct 29 14:54:43 rl10.nr.nethserver.net netdata1[5455]: time=2024-10-29T14:54:43.856+01:00 level=info msg="received terminated signal (15). Terminating..." plugin=go.d component=agent
Oct 29 14:54:43 rl10.nr.nethserver.net netdata1[5455]: time=2024-10-29T14:54:43.856+01:00 level=info msg="instance is stopped" plugin=go.d component="filestatus manager"
Oct 29 14:54:43 rl10.nr.nethserver.net netdata1[5455]: time=2024-10-29T14:54:43.856+01:00 level=info msg="instance is stopped" plugin=go.d component="functions manager"
Oct 29 14:54:43 rl10.nr.nethserver.net netdata1[5455]: time=2024-10-29T14:54:43.856+01:00 level=info msg=stopped plugin=go.d collector=wireguard job=wireguard
Oct 29 14:54:43 rl10.nr.nethserver.net netdata1[5455]: time=2024-10-29T14:54:43.856+01:00 level=info msg=stopped plugin=go.d collector=chrony job=local
Oct 29 14:54:43 rl10.nr.nethserver.net netdata1[5455]: time=2024-10-29T14:54:43.856+01:00 level=info msg="instance is stopped" plugin=go.d component="job manager"
Oct 29 14:54:43 rl10.nr.nethserver.net netdata1[5455]: time=2024-10-29T14:54:43.856+01:00 level=info msg="instance is stopped" plugin=go.d component="discovery manager"
Oct 29 14:54:43 rl10.nr.nethserver.net netdata1[5455]: time=2024-10-29T14:54:43.856+01:00 level=info msg="instance is stopped" plugin=go.d component=agent
Oct 29 14:54:45 rl10.nr.nethserver.net netdata1[6576]: 2469d940a8e30d64de2e0103e75bb463a2bc88a1536d8d14ba9c21069069910a
Oct 29 14:54:45 rl10.nr.nethserver.net netdata1[6592]: 2469d940a8e30d64de2e0103e75bb463a2bc88a1536d8d14ba9c21069069910a
```

**Comment by stephdl** [comment]
released https://github.com/NethServer/ns8-netdata/releases/tag/1.1.2
