### ISSUE TITLE
Single File/Folder Restore Tool for File and Mail Servers

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#7077]
**Description**:  
Develop a general-purpose restore tool that allows users to recover accidentally deleted or modified files and folders from both File Server and Mail Server data. The tool should provide an option to select specific files/folders and the corresponding snapshot for restoration.

**Requirements**:
- Ability to browse and select files/folders from File Server and Mail Server storage.
- Option to restore from a list of available snapshots.
- Integration with existing backup systems.
- User-friendly interface for non-technical users.
- Support for various file types and large file sizes.
- Support for restoring on the original path or inside a new path to avoid file replace

**Comment by AmaLuci** [comment]
Mockups ready in [Figma](https://www.figma.com/design/aOjWm9CUWM99zn1gnH1ONi/NS8-design?node-id=767-146879&node-type=frame&t=hI3f7FGwkv1YodJN-0)
