### ISSUE TITLE
Upgrade SOGo to 5.11.2

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7080]
Description:
Upgrading SOGo from version 5.11.0 to 5.11.2 will bring important security patches and performance improvements that enhance user experience. The update addresses bug fixes reported in the previous release, ensuring a more stable environment.

Proposed solution:
Adopt SOGo 5.11.2 in place of 5.11.0 to leverage these enhancements. This upgrade will require testing in our environment to confirm compatibility and ensure a smooth transition.

Alternative solutions:
Continue using version 5.11.0, though this may expose users to known issues already addressed in 5.11.2.

Additional context:
SOGo 5.11.2 includes optimizations and bug fixes. Release notes detail these improvements for reference.

**Comment by stephdl** [comment]
QA

you must be able to configure sogo with a mail server, no expected error

case 1 (upgrade): no errors expected
upgrade to ghcr.io/nethserver/sogo:2.0.2-dev.1
`api-cli run update-module --data "{"module_url":"docker pull ghcr.io/nethserver/sogo:2.0.2-dev.1","instances":["sogo1"],"force":true}"`

case 2 (direct install) : no errors expected
docker pull ghcr.io/nethserver/sogo:2.0.2-dev.1

**Comment by stephdl** [comment]
community verification asked to https://community.nethserver.org/t/sogo-5-11-2-needs-testers/24834

**Comment by epetersen-lab** [comment]
Hi, 
The command for upgrade did not work for me. No docker pull and incorrect quoting.
Guess it sholud be similar to (worked for me)
`sudo api-cli run update-module --data '{"module_url":"ghcr.io/nethserver/sogo:2.0.2-dev.1","instances":["sogo1"],"force":true}'`

Upgrade did not complain and the service seems to run as expected.
Thanks.

**Comment by stephdl** [comment]
thank @epetersen-lab 

released as https://github.com/NethServer/ns8-sogo/releases/tag/2.0.2
