### ISSUE TITLE
NethVoice CTI: SpeedDial bad behavior and missing translations

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7084]
When you add a SpeedDial make sure is created as `speeddial-basic` to to prevent it from being duplicated.
Also add issing translations.

**Comment by edospadoni** [comment]
Test case:
- make sure the bug is not reproducible

**Comment by edospadoni** [comment]
Testing release [1.1.1-testing.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1-testing.1)

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1)
