### ISSUE TITLE
NethVoice CTI: Missing call info and NethLink click to call

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7087]
1. If the user quickly close the call, the store and the info of the call is missing. Try to avoid this, by updating react store earlier.
2. If NethLink is open, cli2call on the web starts call on the NethLink
3. Add phone_urls on Entrypoint.sh to supports physical phones (under `/etc/nethcti/phone_urls.json`)

**Comment by edospadoni** [comment]
Test case:
- check the described bugs is no more reproducible

**Comment by Amygos** [comment]
Testing release `nethesis/ns8-nethvoice` [1.1.1-testing.5](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1-testing.5)

**Comment by viktec** [comment]
test verified

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1)

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1)
