### ISSUE TITLE
Click2Call: Add mute to physical phone URI actions

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7088]
NethVoice CTI via phone island can invoke the supported landline APIs to perform these actions:
- call
- answer
- hold_unhold
- dtmf

Add mute/unmute action.

Yealink
http://$PHONE_USER:$PHONE_PASS@$PHONE_IP/servlet?key=MUTE

Snom

http://$PHONE_USER:$PHONE_PASS@$PHONE_IP/command.htm?key=MUTE

Fanvil

http://$PHONE_USER:$PHONE_PASS@$PHONE_IP/cgi-bin/ConfigManApp.com?key=F_MUTE

**Comment by tonyco97** [comment]
** Test case **

Check if  `/etc/nethcti/phone_urls.json` contains supported phones url

**Comment by edospadoni** [comment]
Testing release: https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1-testing.6

**Comment by edospadoni** [comment]
**Test case**:
Perform these actions:

- call
- answer
- hold_hold
-dtmf
- disable_enable audio

with supported physical phones via Phone-Island and make sure it works.

Supported physical phones are listed in the issue description

**Comment by andrea-marchionni** [comment]
Missing NethLink as TEL protocol client

**Comment by edospadoni** [comment]
Testing release: https://github.com/NethServer/nethlink/pull/38#issuecomment-2498065170

**Comment by viktec** [comment]
test verified

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1)

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1)
