### ISSUE TITLE
Improve NethVoice remote support

### ISSUE THREAD

**Issue by Amygos** [NethServer/dev#7094]
On NethServer 7, when a remote support session was initiated, a FreePBX `nethsupport` user with admin privileges was created, using the session ID as the password.

To replicate this behavior in NethVoice on NethServer 8, the following steps are required:

* Create two new events to signal the start and end of a remote support session.
* Upon interception of these events, create or remove the `nethsupport` user in FreePBX.

**Comment by andrea-marchionni** [comment]
Testing release [1.1.1-testing.3](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1-testing.3)

**Comment by Amygos** [comment]
Testing release `nethesis/ns8-nethvoice` [1.1.1-testing.3](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1-testing.3)
