### ISSUE TITLE
User Creation and Removal for Remote Support Session

### ISSUE THREAD

**Issue by Amygos** [NethServer/dev#7096]
Upon interception of the `remote-support-started` and `remote-support-stopped` events, create or remove the `nethsupport` user in FreePBX on NethVoice for NethServer 8. The user should have admin privileges and use the session ID as the password.

**Comment by Stell0** [comment]
**Test case:**
- Start the remote support session.
- Verify that it is possible to log in to the NethVoice interface and FreePBX interface with the username `nethsupport` and the password as the session ID.
- Stop the remote support session.
- Logging in with the same credentials should no longer be possible.

**Comment by Amygos** [comment]
Testing release `nethesis/ns8-nethvoice` [1.1.1-testing.3](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1-testing.3)

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.1](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.1)
