### ISSUE TITLE
SNGREP TLS support

### ISSUE THREAD

**Issue by Amygos** [NethServer/dev#7098]
Simplify and speed up the process of enabling TLS connection viewing in SNGREP, and, if possible, link it to the activation of remote support.

 Deactivation should also be easy, and ideally, automated when remote support is turned off

Sngrep with TLS doesn't permit to save on file pcap of conversation.

**Comment by Stell0** [comment]
https://evoseed.atlassian.net/servicedesk/customer/portal/5/EA-38

**Comment by Amygos** [comment]
#### Prequisites

An example of sngrep configuration and usage:

```bash
[root@mv ~]# cat ~/.sngrephep2rc
set capture.device lo
set eep.listen on
set eep.listen.version 2
set eep.listen.address 127.0.0.1
set eep.listen.port 5065
[root@nv ~]# sngrep -f ~/.sngrephep2rc -d any
```
#### Test Case 1: Enable SIP Tracing During Active Support Sessions
- **Objective**: Verify that SIP tracing can be enabled specifically during active support sessions to capture necessary TLS debug information.
- **Preconditions**:
  - Nethserver 8 is installed with the Nethvoice Proxy module (testing version).
  - The cluster is activated with a subscription.
  - An active support session is initiated.
- **Steps**:
  1. Initiate an active support session on the Nethserver 8 system.
  2. Enable SIP tracing during the active support session.
  3. Verify that SIP tracing is capturing TLS debug information.
  4. Check the system performance to ensure it is not overloaded with traces outside of the active support session.
- **Expected Results**:
  - SIP tracing is successfully enabled during the active support session.
  - System performance is maintained, and tracing is limited to the active support session period.

#### Test Case 2: Limit SIP Tracing to Active Support Sessions
- **Objective**: Verify that SIP tracing is limited to active support sessions and does not capture data outside of these sessions.
- **Preconditions**:
  - Nethserver 8 is installed with the Nethvoice Proxy module (testing version).
  - The cluster is activated with a subscription.
  - SIP tracing is enabled during an active support session.
- **Steps**:
  1. End the active support session.
  2. Verify that SIP tracing is automatically disabled.
  3. Check the system logs to ensure that no unnecessary trace data is captured outside of the active support session.
- **Expected Results**:
  - SIP tracing is automatically disabled when the active support session ends.
  - No unnecessary trace data is captured outside of the active support session.

#### Test Case 3: Update Procedure
- **Objective**: Verify that the Nethvoice Proxy module can be updated from the stable version to the testing version without affecting the SIP tracing functionality.
- **Preconditions**:
  - Nethserver 8 is installed with the Nethvoice Proxy module (stable version).
  - The cluster is activated with a subscription.
- **Steps**:
  1. Update the Nethvoice Proxy module from the stable version to the testing version.
  2. Verify that the SIP tracing functionality is still working as expected.
  3. Test the SIP tracing feature during an active support session.
- **Expected Results**:
  - The Nethvoice Proxy module is successfully updated to the testing version.
  - The SIP tracing functionality is still working as expected after the update.
  - SIP tracing can be enabled and disabled as expected during active support sessions.

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.2)
