### ISSUE TITLE
NethLink: Device Does Not Switch Automatically Between CTI and NethLink

### ISSUE THREAD

**Issue by viktec** [NethServer/dev#7114]
When switching between CTI and NethLink, the device in use is not updated automatically. For instance, if a user closes NethLink and opens CTI, the device does not switch from "device phone" to "WebRTC" as expected.

Steps to Reproduce:

1) Open NethLink and connect a device.
2) Close NethLink and open CTI.
3) Observe that the device does not switch to WebRTC.

Expected Behavior:
The device should switch to the appropriate setting automatically based on whether CTI or NethLink is in use.

**Comment by edospadoni** [comment]
Testing release: https://github.com/NethServer/nethlink/pull/39#issuecomment-2527308077

**Comment by viktec** [comment]
verified

**Comment by edospadoni** [comment]
Released in https://github.com/NethServer/nethlink/releases/tag/v0.3.4
