### ISSUE TITLE
NethLink: Phone Island Temporarily Closes and Reopens with NethLink

### ISSUE THREAD

**Issue by viktec** [NethServer/dev#7116]
When using NethLink, the phone island appears with an incoming call, briefly closes for about a second, and then reopens. This may be related to the "ghost call" issue, which is expected to be resolved but hasn’t been implemented for NethLink yet.

Steps to Reproduce:

1) Receive an incoming call via NethLink.
2) Observe the phone island as it briefly closes and then reopens after displaying the ringing status.

Expected Behavior:
The phone island should remain open consistently during an incoming call without any interruptions.

**Comment by edospadoni** [comment]
Released in https://github.com/NethServer/nethlink/releases/tag/v0.3.4
