### ISSUE TITLE
NethLink: Notifications Title Displays "electron.app" Instead of App Name

### ISSUE THREAD

**Issue by viktec** [NethServer/dev#7117]
On Windows, notification titles display as "electron.app" instead of showing the app's actual name, resulting in a lack of clear identification in notifications.

Steps to Reproduce:

1) Trigger a notification from the application on a Windows system.
2) Observe that the notification title is incorrectly displayed as "electron.app".

Expected Behavior:
The notification title should display the application’s name, not "electron.app".

**Comment by edospadoni** [comment]
Testing release: https://github.com/NethServer/nethlink/pull/39#issuecomment-2527308077

**Comment by viktec** [comment]
verified

**Comment by edospadoni** [comment]
Released in https://github.com/NethServer/nethlink/releases/tag/v0.3.4
