### ISSUE TITLE
Nextcloud: Migration and change of base DN, LDAP auto discovery 

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7174]
We need to test the migration of an openldap directory.nh to another base DN set by the sysadmin with the use of nextcloud. Alternatively the LDAP settings discovery is not automatic, it is done when the sysadmin configure the settings panel

For this purpose the test the platform we need to install on NS7 and migrate the whole stack to NS8

nethserver-openldap
nethserver-nextcloud

**Comment by stephdl** [comment]
QA

nextcloud version to test with new event user-domain-changed : `ghcr.io/nethserver/nextcloud:1.2.0-dev.1`

- test case 1
install an account provider 
install the testing version of nextcloud
configure it
you can login to nextcloud with the user of ldap

- test case 2
install an account provider 
install the testing version of nextcloud
configure it
you can login to nextcloud with the user of ldap
trigger the event user-domain-changed ([by a python script](https://github.com/NethServer/ns8-ldapproxy/blob/1d94a88c20db0f8d070df05b0afb0910294d71d5/imageroot/bin/allocate-ports#L71)
the service must be restarted and the ldap settings must be discovered

**Comment by stephdl** [comment]
test case 2 written @gsanchietti

**Comment by gsanchietti** [comment]
Test case 2 verified: after the migration, the LDAP configuration of Nextcloud reports the correct user domain.
Please bear in mind that Nextcloud could take a couple of minutes before being fully reconfigured.

**Comment by stephdl** [comment]
https://github.com/NethServer/ns8-nextcloud/releases/tag/1.1.9
https://github.com/NethServer/ns8-nextcloud/releases/tag/1.2.0
