### ISSUE TITLE
Mail stack (mail,SOGo, roundcubemail): Migrate a mail stack and  change the base DN

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7175]
We need to test the migration of an openldap directory.nh to another base DN set by the sysadmin

For this purpose the test the platform we need to install on NS7 and migrate the whole stack to NS8

nethserver-openldap
nethserver-mail-server
nethserver-roundcubemail
nethserver-sogo

**Comment by gsanchietti** [comment]
All test cases passed except for Sogo: if the nethforge is not enabled on the cluster, the migration of Sogo will silently fail.

**Comment by stephdl** [comment]
https://github.com/NethServer/ns8-sogo/releases/tag/2.0.4

**Comment by stephdl** [comment]
mail released as https://github.com/NethServer/ns8-mail/releases/tag/1.4.10
