### ISSUE TITLE
Mockup for NethLink Click to call

### ISSUE THREAD

**Issue by edospadoni** [NethServer/dev#7177]
Create a mockup for the parent issue: #7118

- Devices management
- Error management

**Comment by AmaLuci** [comment]
Mockups for device managment on [Figma file](https://www.figma.com/design/N4QkxZKUY4wPfMeAtvteRL/NethLink---Shared-file?node-id=1011-26216&node-type=frame&t=mUyuAbyfP0TNcdgE-0)
The implementation involves a general interface change. We'll remove the "gear" icon and also move the theme color settings to the avatar menu.

The menu should have a fixed size and interaction through pages moves in right to left and moves out left to right. (Iphone navigation for example)

Example mockup
![Image](https://github.com/user-attachments/assets/43c2b9ee-cca8-4559-a8bc-b3db56a824bf)

**Comment by AmaLuci** [comment]
Device error, mockups in [Figma](https://www.figma.com/design/N4QkxZKUY4wPfMeAtvteRL/NethLink---Shared-file?node-id=1018-6214&node-type=frame&t=cUTUR3lJFTBAoepU-0)

![Image](https://github.com/user-attachments/assets/76a72dd7-e8ac-4f38-8ded-2c9fbf6f0575)
![Image](https://github.com/user-attachments/assets/9eb1cfa5-79c9-43d7-bcb9-e7577cc39298)
