### ISSUE TITLE
NethVoice: Migration and change of base DN

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#7178]
The parent issue #7103 implements the logic that allow to migrate multiple NethVoice installations on NS7 to a single NS8 cluster.

The NethVoice module must:
- listen to `user-domain-changed` event
- reconfigure all NethVoice applications when the event is fired

The event is fired once at the end of the migration when the OpenLDAP account provider is finally migrated to NS8.

Things to check before the end of the migration, when the NethVoice running on NS8 is attached to the LDAP running on NS7:
- list of users inside FreePBX
- login of users inside the CTI application

Things to check after the end of the migration, when NethVoice running on NS8 is attached to the LDAP running also on NS8:
- list of users inside FreePBX
- login of users inside the CTI application

**Comment by Amygos** [comment]
Testing release `nethesis/ns8-nethvoice` [1.1.2-testing.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.2-testing.2)

**Comment by stephdl** [comment]
Version to test 
ns8-nethvoice: ghcr.io/nethesis/nethvoice:1.1.2-testing.2
nethserver-ns8-migration: http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/nethserver-ns8-migration-1.0.18-1.6.ga6b0914.ns7.x86_64.rpm

To test the event user-domain-changed and the migration of the base DN to another DN, you have to write to the /usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-nethvoice14/bind.env the version above and migrate the mail stack to a NS8

- install NS7 with an openldap account provider and nethvoice
- create some data like users in LDAP, configure nethvoice as needed to be functional
- install the testing version of nethserver-ns8-migration: `yum install http://packages.nethserver.org/nethserver/7.9.2009/testing/x86_64/Packages/nethserver-ns8-migration-1.0.18-1.6.ga6b0914.ns7.x86_64.rpm`
- modify the bind.env to set the version of nethvoice
this is an example :
`vim /usr/share/nethesis/nethserver-ns8-migration/apps/nethserver-nethvoice14/bind.env`
change `MODULE_IMAGE_URL="nethvoice"`
to `MODULE_IMAGE_URL="ghcr.io/nethesis/nethvoice:1.1.2-testing.2"`
- before to proceed the migration install the nethvoice proxy on the node you want to migrate nethvoice14
- migrate nethvoice  by the UI of the nethserver-ns8-migration
- once the stack is migrated, using the remote LDAP account provider you can use nethvoice, the users of ldap should be displayed in the first wizard screen.
- once the test before is good, migrate the account provider
- at the end of the account provider migration, the event user-domain-changed is triggered and all the service netvoice  will restart (you can see it in journald of NS8)
- once the stack is migrated,do not reconfigure something, just test, you can continue to login to nethvoice, the users of ldap should be displayed in the first wizard screen . In any case do not configure the settings panel of nethvoice NS8 panel, the event should autodiscover the new ldap settings


As a side note, the product must be tested, the change inside nethvoice are only related to the event user-domain-changed,

**Comment by gsanchietti** [comment]
Test cases seems verified but I've found some errors inside the logs:
```
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]: 2024-12-02T12:06:35+00:00 - error: [proxy_logic_13] TypeError: Cannot read property 'toJSON' of undefined
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at Object.getJSONExtension (/app/node_modules/@nethesis/astproxy/lib/proxy_logic_13/proxy_logic_13.js:2526:30)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at Object.extensions (/app/plugins/com_astproxy_rest/plugins_rest/astproxy.js:1825:44)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at Server.execute (/app/plugins/com_astproxy_rest/server_com_astproxy_rest.js:131:22)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at next (/app/node_modules/restify/lib/server.js:912:30)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at f (/app/node_modules/once/once.js:25:25)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at Server.restifyCORSSimple (/app/node_modules/restify/lib/plugins/cors.js:104:13)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at next (/app/node_modules/restify/lib/server.js:912:30)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at f (/app/node_modules/once/once.js:25:25)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at Server.parseBody (/app/node_modules/restify/lib/plugins/body_parser.js:52:17)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at next (/app/node_modules/restify/lib/server.js:912:30)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at f (/app/node_modules/once/once.js:25:25)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at IncomingMessage.done (/app/node_modules/restify/lib/plugins/body_reader.js:111:17)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at Object.onceWrapper (events.js:519:28)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at IncomingMessage.emit (events.js:412:35)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at IncomingMessage.emit (domain.js:537:15)
Dec 02 12:06:35 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]:     at endReadableNT (internal/streams/readable.js:1333:12)

```

Also:
```
Dec 02 12:07:06 rl1.leader.cluster0.gs.nethserver.net nethvoice2[101010]: 2024-12-02T12:07:06+00:00 - warn: [arch_astproxy] problem logging in to nethvoice report with request: self signed certificate
```

And also:
```
Dec 02 12:09:42 rl1.leader.cluster0.gs.nethserver.net agent@nethvoice2[90966]: Handler of module/openldap4/event/service-users-admin-changed is starting step 30traefik
Dec 02 12:09:42 rl1.leader.cluster0.gs.nethserver.net agent@nethvoice2[102490]:   File "/home/nethvoice2/.config/events/service-users-admin-changed/30traefik", line 18
Dec 02 12:09:42 rl1.leader.cluster0.gs.nethserver.net agent@nethvoice2[102490]:     ksrv = agent.list_service_providers(agent.redis_connect(use_replica=True), "users-admin", "http", {"domain": os.environ["USER_DOMAIN"]]})
Dec 02 12:09:42 rl1.leader.cluster0.gs.nethserver.net agent@nethvoice2[102490]:                                                                                                                                           ^
Dec 02 12:09:42 rl1.leader.cluster0.gs.nethserver.net agent@nethvoice2[102490]: SyntaxError: closing parenthesis ']' does not match opening parenthesis '{'
Dec 02 12:09:42 rl1.leader.cluster0.gs.nethserver.net agent@nethvoice2[90966]: exit status 1
```
This issue should be fixed in https://github.com/nethesis/ns8-nethvoice/pull/342

**Comment by Amygos** [comment]
Testing release `nethesis/ns8-nethvoice` [1.1.2-testing.3](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.2-testing.3)

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.2)
