### ISSUE TITLE
Backup restore doesn't set correct transport ports

### ISSUE THREAD

**Issue by Stell0** [NethServer/dev#7196]
**Steps to reproduce**

- Migrate a NethVoice instance from a cluster to another one
- Make sure that the 2nd cluster has different number of instances installed (for example if you are migrating 3rd nethvoice on cluster 1, on cluster 2 the bug appears if you are installing 1st, 2nd, 4th... but not the third!
- check where asterisk transport is listening

**Expected behavior**

- transport should listen at the port defined in ASTERISK_SIP_PORT envrionment variable

**Actual behavior**

- transport listens at old instance port

**Components**

ns8-nethvoice

**Comment by Stell0** [comment]
Also test module clone, looking at the code, same issue should be present

**Comment by Stell0** [comment]
Workaround: in FreePBX interface -> Asterisk sip settings -> chan_pjsip set transport ports to the ones defined in ASTERISK_SIP_PORT and ASTERIS_SIPS_PORT environment variables

**Comment by Amygos** [comment]
Testing release `nethesis/ns8-nethvoice` [1.1.2-testing.4](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.2-testing.4)

**Comment by Amygos** [comment]
Release `nethesis/ns8-nethvoice`  [1.1.2](https://github.com/nethesis/ns8-nethvoice/releases/tag/1.1.2)
