### ISSUE TITLE
Collabora can't open documents after upgrading to Podman 5.2

### ISSUE THREAD

**Issue by mrmarkuz** [NethServer/dev#7197]
In Podman 5 the local interface IP is also used in the container and therefore not routed to the outside anymore so Collabora can't open a document on Rocky that recently updated to Podman 5.2.

**Steps to reproduce**

- Check Podman version, should be >= 5
- Open a document in Collabora

**Expected behavior**

The document is opened.

**Actual behavior**

An error is displayed:

Document loading failed
Unauthorized WOPI host. Please try again later and report to your administrator if the issue persists.

This can be solved by adding `--network=slirp4netns:allow_host_loopback=true` to the `pod create` command in the service file.

**Components**

- Collabora 1.0.7

**See also**

https://community.nethserver.org/t/collabora-and-onlyoffice-in-conjunction-with-nextcloud-no-longer-work-since-the-last-update-dnf-update-from-rocky/24972

https://blog.podman.io/2024/03/podman-5-0-breaking-changes-in-detail/

----

Thanks to Transocean

**Comment by stephdl** [comment]
Version to test : ghcr.io/nethserver/collabora:1.0.8-dev.1

@mrmarkuz could you please write the verification cases, I suppose we need to handle the upgrade and the first installation

**Comment by mrmarkuz** [comment]
It should be possible to open an office document without errors when Collabora and Nextcloud are installed on the same node.

Test Case 1 (fresh install)

- Install Nextcloud and ghcr.io/nethserver/collabora:1.0.8-dev.1
- Configure Collabora
- Configure Nextcloud and add Collabora
- Open an Office Document

Test Case 2 (upgrade)

- Update Collabora to ghcr.io/nethserver/collabora:1.0.8-dev.1
- Open an Office Document

**Comment by stephdl** [comment]
case 1 Fresh install  : OK
case 2 upgrade :  OK

**Comment by stephdl** [comment]
released as https://github.com/NethServer/ns8-collabora/releases/tag/1.0.8
