### ISSUE TITLE
Nextcloud: upgrade to 28.0.14

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7206]
New available version of nextcloud, we need to upgrade the full stack or each dependencies one by one, I mean nginx and mariadb

**Proposed solution**

upgrade the minor version of nextcloud to 28.0.14
Optionnal
upgrade mariadb to 10.6.20 [see the changelog](https://mariadb.com/kb/en/mariadb-10-6-20-release-notes/)
upgrade nginx to 1.27.3 [see the changelog ](https://mariadb.com/kb/en/mariadb-10-6-20-release-notes/)

remove the warning in logs

```
Dec 10 18:24:28 R1.rocky9.org nextcloud-nginx[35832]: 2024/12/10 17:24:28 [warn] 1#1: duplicate extension "wasm", content type: "application/wasm", previous content type: "application/wasm" in /etc/nginx/nginx.conf:16
Dec 10 18:24:28 R1.rocky9.org nextcloud-nginx[35832]: nginx: [warn] duplicate extension "wasm", content type: "application/wasm", previous content type: "application/wasm" in /etc/nginx/nginx.conf:16
```

**Alternative solutions**

do nothing

**Additional context**

ghcr.io/nethserver/nextcloud:1.1.9

**See also**

our [brilliant community ](https://community.nethserver.org/t/nextcloud-28-needs-an-update/25009)is waiting the best of us

----

thank transocean

**Comment by stephdl** [comment]
QA

case 1 direct install
- direct install from ghcr.io/nethserver/nextcloud:1.2.1-dev.3
`add-module ghcr.io/nethserver/nextcloud:1.2.1-dev.3`
- configure nextcloud with a FQDN and a user account and with internal database
- Nextcloud is up and workable
- we have updated Nginx to 1.27.3 (minor version) and mariadb to 10.6.20 (minor version), verify in log that we have no issue
- the log trace in log about wasm is not found
```
Dec 10 18:24:28 R1.rocky9.org nextcloud-nginx[35832]: 2024/12/10 17:24:28 [warn] 1#1: duplicate extension "wasm", content type: "application/wasm", previous content type: "application/wasm" in /etc/nginx/nginx.conf:16
Dec 10 18:24:28 R1.rocky9.org nextcloud-nginx[35832]: nginx: [warn] duplicate extension "wasm", content type: "application/wasm", previous content type: "application/wasm" in /etc/nginx/nginx.conf:16
```

case 2 update
- install and configure nextcloud from 1.2.0 (stable in NS8) with a FQDN and a user account or with internal database
- upgrade from ghcr.io/nethserver/nextcloud:1.2.1-dev.3
`api-cli run update-module --data '{"module_url":"ghcr.io/nethserver/nextcloud:1.2.1-dev.3","instances":["nextcloud1"],"force":true}'`
- Nextcloud is up and workable
- we have updated Nginx to 1.27.3 (minor version) and mariadb to 10.6.20 (minor version), verify in log that we have no issue
- the log trace in log about wasm is not found
```
Dec 10 18:24:28 R1.rocky9.org nextcloud-nginx[35832]: 2024/12/10 17:24:28 [warn] 1#1: duplicate extension "wasm", content type: "application/wasm", previous content type: "application/wasm" in /etc/nginx/nginx.conf:16
Dec 10 18:24:28 R1.rocky9.org nextcloud-nginx[35832]: nginx: [warn] duplicate extension "wasm", content type: "application/wasm", previous content type: "application/wasm" in /etc/nginx/nginx.conf:16
```

**Comment by nrauso** [comment]
test case 1: **VERIFIED**
test case 2: **VERIFIED**

**Comment by stephdl** [comment]
are you concerned by this @nrauso 

https://help.nextcloud.com/t/28-0-13-and-30-0-3-withdrawn/211672

**Comment by stephdl** [comment]
@nrauso back to testing, we go to 28.0.14, 28.0.13 gets an issue and has been patched by upstream

**Comment by nrauso** [comment]
test case 1: **VERIFIED**
test case 2: **VERIFIED**

**Comment by stephdl** [comment]
released https://github.com/NethServer/ns8-nextcloud/releases/tag/1.2.1
