### ISSUE TITLE
Mattermost: upgrade to 9.11.6

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#7212]
I propose to upgrade mattermost to the version 9.11.6

**Proposed solution**

We have some minor version to fill the gap, [this is the changelog](https://docs.mattermost.com/about/mattermost-v9-changelog.html)

**Alternative solutions**

do nothing

**Additional context**

docker pull ghcr.io/nethserver/mattermost:2.1.0

**Comment by stephdl** [comment]
QA

case 1
- direct install ghcr.io/nethserver/mattermost:2.1.1-dev.1
- Install and configure
- mattermost muts be up and workable

case 2
- Install and configure a stable version
- upgrade to ghcr.io/nethserver/mattermost:2.1.1-dev.1
- mattermost must be up and workable
- the changelog states that we have  [no database or functional changes.](https://docs.mattermost.com/about/mattermost-v9-changelog.html) between 9.11.2 to 9.11.6

**Comment by lucagasparini** [comment]
Test case 1: **VERIFIED**
Test case 2: **VERIFIED**

**Comment by stephdl** [comment]
released https://github.com/NethServer/ns8-mattermost/releases/tag/2.1.1
